<?php
defined('BASEPATH') OR exit('No direct script access allowed');
// Website page copy (English + Arabic source text and SEO) written from the brand narrative.
// Installed once per COPY_VERSION by: php index.php ha_cli seed copy
return array (
  'en' => 
  array (
    'home' => 
    array (
      'title' => 'Hospitality Academy: Hotel Staff Training in Saudi Arabia',
      'subtitle' => 'Role-based training, practical assessment and verifiable certification for hotel teams, from Altus Advisory in Riyadh. In Arabic, English and the languages your staff speak.',
      'body' => '<h2>What is Hospitality Academy?</h2><p>Hospitality Academy is the public training academy of Altus Advisory, a hospitality and business strategy firm based in Riyadh, Saudi Arabia. It runs on the altus Hospitality Knowledge &amp; Performance platform, which delivers hotel staff training by job role and then checks whether each person can actually do the work.</p><h2>How is it different from an ordinary online course?</h2><p>Completion is not treated as proof. Each learner moves from role-based learning to theory and practical assessment, and the result is recorded against defined competencies. Where a gap appears, an action plan and a reassessment follow, so managers see evidence of capability rather than a list of finished videos.</p><ol><li>Learning assigned from the requirements of the job role</li><li>Theory assessment and a practical assessment on the same standard</li><li>A competency record, identified gaps and a corrective action plan</li><li>Reassessment, a readiness status and a verifiable certificate</li></ol><h2>Which hotel departments does the academy cover?</h2><p>The master curriculum is organised into ten core professional domains: hotel fundamentals, front office, housekeeping, food and beverage, kitchen, sales and marketing, revenue and reservations, guest experience, quality and audit, and security and safety. Browse the <a href="/en/courses">course catalogue</a> or follow a structured <a href="/en/learning-paths">learning path</a> for a specific role.</p><h2>Which languages can hotel staff learn in?</h2><p>Arabic and English are built in as one experience, with Arabic laid out right to left. The staff workspace also supports Hindi, Urdu, Filipino, Bengali, Nepali and Malayalam, so the standard is understood by the people who deliver it on every shift.</p><h2>Can an employer check a certificate?</h2><p>Yes. Every certificate carries a unique number and a verification code, and anyone can confirm whether it is valid, expired or revoked on the <a href="/en/verify">certificate verification page</a>.</p><h2>How does the academy support Vision 2030?</h2><p>Vision 2030 targets 150 million annual visits to the Kingdom by 2030 and places Saudi human capital at the centre of that growth. Altus Advisory aligns the academy with those goals through bilingual learning paths, assessed competence and certification that hotels in Saudi Arabia and the GCC can rely on.</p><p>Hotel owners and operators can <a href="/en/hotels">set up training for their properties</a> or <a href="/en/contact">speak with the academy team in Riyadh</a>.</p>',
      'cta_label' => 'Browse the course catalogue',
      'meta_title' => 'Hotel Staff Training Saudi Arabia | Hospitality Academy',
      'meta_description' => 'Hotel staff training in Saudi Arabia from Altus Advisory: role-based learning, practical assessment and verifiable certificates in Arabic and English.',
      'focus_keyword' => 'hotel staff training Saudi Arabia',
    ),
    'about' => 
    array (
      'title' => 'About Hospitality Academy',
      'subtitle' => 'The public training academy of Altus Advisory in Riyadh: who stands behind the content, how it is approved, and what we will and will not claim.',
      'body' => '<h2>Who runs Hospitality Academy?</h2><p>Hospitality Academy is operated by Altus Advisory, a boutique strategy firm headquartered in Riyadh, Kingdom of Saudi Arabia, serving clients across the GCC and MENA. Altus works through two integrated divisions, Hospitality Solutions and Business Growth Solutions, and the academy is how its operating standards reach hotel teams directly.</p><h2>What experience is the training content based on?</h2><p>The content draws on the operating standards of the Altus founders, whose combined leadership experience exceeds 60 years, gained inside Marriott, IHG, Starwood and Accor systems and in independent hotels. Training starts from standard operating procedures as they are performed on shift, not from a generic course library.</p><h2>How does the academy relate to the altus platform?</h2><p>The academy is the public entry point to the altus Hospitality Knowledge &amp; Performance platform. Inside the platform, hotels assign learning by role, run theory and practical assessments, track competency gaps and action plans, and see each employee\'s readiness. A governed AI assistant answers staff questions only from approved content and says so when that content does not cover a question.</p><h2>How is training content approved?</h2><p>Every lesson, procedure and assessment passes a governed review before learners see it.</p><ol><li>The author prepares a draft.</li><li>The draft receives internal approval.</li><li>The draft receives quality approval.</li><li>The content is published and its version is recorded.</li></ol><p>Authors cannot approve their own work, and earlier versions remain on record so an auditor can see which standard applied on any date.</p><h2>What principles guide the academy?</h2><p>The academy follows the principles Altus Advisory applies to every mandate.</p><ul><li>Evidence over intuition: capability is shown through assessment, not assumed from attendance.</li><li>Standards that hold on every shift, in Arabic, English and the workforce languages hotel staff use.</li><li>Partnership beyond the mandate: knowledge stays inside the client organisation after the engagement ends.</li><li>Support for Saudi human capital, in line with the Vision 2030 goals for Saudization and youth empowerment.</li></ul><h2>What does the academy not claim?</h2><p>This site publishes no pass rates, client endorsements or accreditation claims. A certificate states exactly what it records: who completed which course or programme, on what date, with what result, and whether it is still valid. Read <a href="/en/certificates">how certification works</a>, or learn more about <a href="/en/altus">Altus Advisory and its services</a>.</p>',
      'cta_label' => 'See how certification works',
      'meta_title' => 'Hospitality Training Academy Riyadh | Altus Advisory',
      'meta_description' => 'Hospitality Academy is the Riyadh-based hospitality training academy of Altus Advisory, built on operator-grade standards and governed review.',
      'focus_keyword' => 'hospitality training academy Riyadh',
    ),
    'for-hotels' => 
    array (
      'title' => 'Hotel Training Platform for Properties in Saudi Arabia',
      'subtitle' => 'Assign learning by role, assess theory and practice, close competency gaps and see readiness for every property, in one bilingual workspace.',
      'body' => '<h2>Why do hotels need proof of capability, not just course completion?</h2><p>Most hotels already know what their teams should do. The difficulty is proving that each person can do it to the current standard, and finding the gaps before a guest, an audit or an inspection does. Altus Advisory built the altus Hospitality Knowledge &amp; Performance platform to close that gap for hotels in Riyadh and across Saudi Arabia.</p><h2>What does a hotel get from the platform?</h2><p>A single workspace where training, assessment and evidence sit together for every property.</p><ul><li>Learning assigned to people, job roles, departments or cohorts, with due dates and exemptions</li><li>Theory assessments and practical assessments scored on weighted rubrics, where a critical criterion caps the result</li><li>Competency profiles, a gap heatmap, action plans with evidence upload and reassessment</li><li>A readiness status for each employee, including opening readiness for pre-opening teams</li><li>Quality audits, KPIs and reports exported to CSV and XLSX</li><li>A governed AI assistant that answers only from your approved SOPs and policies, with citations</li><li>Property branding: your logo, colours and name</li></ul><h2>Who sees what inside the platform?</h2><p>Access follows your organisation. A department head sees their team, a general manager sees the property, and an executive sees the portfolio overview and a printable board report. Every step is scoped to your organisation and recorded in an audit log, and no organisation can see another organisation\'s data.</p><h2>Which properties is the platform designed for?</h2><p>According to the Altus Advisory corporate profile, the platform is purpose-built for independent hotels, serviced apartments and SME establishments across Saudi Arabia and the Arab region that need practical, standards-based training without the cost and complexity of global-chain systems. The need is growing: Saudi Ministry of Tourism preliminary data records 122 million domestic and international visits in 2025, and Vision 2030 targets 150 million annual visits by 2030.</p><h2>How do we get started?</h2><p>Setup starts from your structure, not from an empty catalogue.</p><ol><li>Share your properties, departments and approximate headcount per department.</li><li>Altus sets up the organisation and links job roles to the competencies they require.</li><li>Mandatory training is assigned, so staff open their own list on their first login.</li><li>Managers follow completion, assessment results and readiness from their dashboard.</li></ol><p>See the <a href="/en/hotels/training">training programmes by department</a>, browse <a href="/en/programs">certification programmes</a>, or <a href="/en/contact">talk to the academy team</a>.</p>',
      'cta_label' => 'Talk to the academy',
      'meta_title' => 'Hotel Training Platform Saudi Arabia | Altus Advisory',
      'meta_description' => 'A hotel training platform for Saudi Arabia: assign learning by role, run practical assessments, close competency gaps and track readiness per property.',
      'focus_keyword' => 'hotel training platform Saudi Arabia',
    ),
    'hotels-training' => 
    array (
      'title' => 'Hotel Staff Training Programmes by Department',
      'subtitle' => 'What each hotel department is trained on, the order it is delivered in, and how capability is confirmed before an employee works unsupervised.',
      'body' => '<h2>What training does each hotel department need?</h2><p>Each department follows its own track within the master curriculum that Altus Advisory developed in Riyadh from field-tested operating standards. Content is structured as professional domain, track, module and lesson, followed by assessment and certification, so every role has a defined path.</p><ul><li><strong>Front office:</strong> arrival and departure, guest registration and privacy, room assignment, complaint handling, upselling and the night audit.</li><li><strong>Housekeeping:</strong> room cleaning sequence, bed and bathroom standards, chemical safety, lost and found, laundry, public areas and inspection.</li><li><strong>Food and beverage:</strong> service sequence, greeting and seating, table and beverage service, banquets and point of sale procedure.</li><li><strong>Kitchen:</strong> food safety, temperature control, storage and receiving, allergen handling, knife safety and waste control.</li><li><strong>Sales, revenue and reservations:</strong> sales and marketing, reservations procedure, distribution and revenue fundamentals.</li><li><strong>Guest experience, quality and audit:</strong> service recovery, brand and SOP compliance, and quality inspection.</li><li><strong>Security and safety:</strong> fire safety, emergency response and security procedure for every employee.</li></ul><h2>In what order is hotel staff training delivered?</h2><p>Safety and foundations come first, then role skills, then assessment of the same standard.</p><ol><li>Hotel fundamentals, the property induction and safety for every employee</li><li>Role prerequisites, such as chemical safety in housekeeping or food safety and allergen handling in the kitchen</li><li>Role modules with short applied lessons in video, PDF, slides or audio</li><li>A theory assessment, then a practical assessment by a supervisor</li><li>A certificate, or an action plan and reassessment where a gap is found</li></ol><h2>Can the training follow our own hotel standards?</h2><p>Yes. The platform is white-label per property, and your approved SOPs, policies and checklists sit alongside the curriculum, with staff acknowledgement recorded against each version. The AI assistant answers staff questions only from that approved content.</p><h2>Is the training available for staff who do not read Arabic or English?</h2><p>Lessons are bilingual in Arabic and English, and the staff workspace also supports Hindi, Urdu, Filipino, Bengali, Nepali and Malayalam for the multinational teams that work in hotels across Saudi Arabia.</p><p>Explore the <a href="/en/courses">full course catalogue</a>, follow a <a href="/en/learning-paths">learning path by role</a>, or read <a href="/en/hotels">how hotels deploy the platform</a>.</p>',
      'cta_label' => 'See the full catalogue',
      'meta_title' => 'Hotel Staff Training Programmes by Department | KSA',
      'meta_description' => 'Hotel staff training programmes by department, from front office to kitchen, with practical assessment and certification for teams in Saudi Arabia.',
      'focus_keyword' => 'hotel staff training programmes',
    ),
    'certificates-info' => 
    array (
      'title' => 'Hotel Training Certificates and Verification',
      'subtitle' => 'What a Hospitality Academy certificate records, when it is issued, and how an employer can check in seconds whether it is genuine and current.',
      'body' => '<h2>When is a Hospitality Academy certificate issued?</h2><p>A certificate is issued when a learner completes every mandatory lesson in a course and passes its assessment at or above the pass mark set for that course. A programme certificate is issued when every course in the programme is complete. Certification is designed to reflect assessed capability, not attendance.</p><h2>What does a hotel training certificate record?</h2><p>Each certificate records the facts an employer needs and nothing more.</p><ul><li>The learner name</li><li>The course or programme completed</li><li>The completion date and the final score</li><li>A unique certificate number, a verification code and a QR code</li><li>An expiry date where the subject needs periodic refreshing, such as safety and food safety</li></ul><h2>How do I verify a hotel training certificate?</h2><p>Use the public verification page. No account is needed.</p><ol><li>Open the <a href="/en/verify">certificate verification page</a>.</li><li>Enter the verification code printed on the certificate, or scan its QR code.</li><li>Read the status returned: valid, expired, revoked or not found.</li></ol><p>A valid result shows the learner name, the subject and the issue date, and nothing else about the person.</p><h2>Why might a certificate show as revoked?</h2><p>A certificate is revoked if it was issued in error, if the assessment result behind it is found to be invalid, or at the request of the issuing organisation. A revoked certificate stays verifiable and keeps returning a revoked status rather than disappearing, so an earlier copy cannot be presented as current.</p><h2>Who issues the certificates?</h2><p>Certificates are issued through the altus Hospitality Knowledge &amp; Performance platform, operated by Altus Advisory in Riyadh, Saudi Arabia. A certificate records completion of a specific course or programme by a specific person on a specific date. It is not a licence, a regulatory approval or a statement that the holder is qualified for any particular role.</p><p>Browse the available <a href="/en/programs">certification programmes</a> or <a href="/en/contact">ask the academy team</a> about certifying your hotel staff.</p>',
      'cta_label' => 'Verify a certificate',
      'meta_title' => 'Verify a Hotel Training Certificate | Hospitality Academy',
      'meta_description' => 'Verify a hotel training certificate from Hospitality Academy by code or QR, and see what each certificate records, when it expires and why it may be revoked.',
      'focus_keyword' => 'verify a hotel training certificate',
    ),
    'contact' => 
    array (
      'title' => 'Contact Hospitality Academy',
      'subtitle' => 'Tell us about your properties and your team, and we will come back with a structure rather than a brochure.',
      'body' => '<h2>How do I request hotel training for my property?</h2><p>Send your enquiry about hotel training in Riyadh or elsewhere in the Kingdom through the form on this page. A member of the Hospitality Academy team at Altus Advisory in Riyadh, Kingdom of Saudi Arabia, replies to arrange a call. There is no automated email sequence, and your details are not passed to any third party.</p><h2>What should I include in my enquiry?</h2><p>A few facts let us reply with a working structure instead of a general presentation.</p><ul><li>The properties and cities involved</li><li>The departments you want to start with</li><li>The approximate number of employees in each department</li><li>The languages your staff need: Arabic, English, or workforce languages such as Hindi, Urdu, Filipino, Bengali, Nepali or Malayalam</li><li>Any deadline, such as a pre-opening or an inspection</li></ul><h2>What happens after I get in touch?</h2><p>The process is short and handled by people, not automation.</p><ol><li>We reply to arrange an introductory call.</li><li>We discuss your properties, job roles and current standards.</li><li>We propose a structure of departments, roles and mandatory training for your team.</li></ol><h2>Can I contact Altus Advisory about something other than training?</h2><p>Yes. Altus Advisory also advises hotel owners and investors in Saudi Arabia and the GCC on hotel development and owner representation, pre-opening support, operations, guest experience, commercial performance and wider business growth. Read about <a href="/en/altus">Altus Advisory and its services</a>.</p><h2>Where do I go with a certificate question?</h2><p>To confirm whether a certificate is genuine, use the <a href="/en/verify">certificate verification page</a> directly; no enquiry is needed. To request a copy of your own learning record or a correction to it, contact your employer\'s administrator or write to us through this page.</p><p>Before you write, you may find it useful to see <a href="/en/hotels">how the platform works for hotels</a> or browse the <a href="/en/courses">course catalogue</a>.</p>',
      'cta_label' => 'Send your enquiry',
      'meta_title' => 'Contact Us: Hotel Training in Riyadh | Altus Advisory',
      'meta_description' => 'Contact Hospitality Academy at Altus Advisory about hotel training in Riyadh and across Saudi Arabia. Tell us your properties, departments and deadlines.',
      'focus_keyword' => 'hotel training in Riyadh',
    ),
    'privacy' => 
    array (
      'title' => 'Privacy Policy',
      'subtitle' => 'What the academy stores, why it is stored, who can see it and how long it is kept.',
      'body' => '<h2>Who this policy covers</h2><p>This policy applies to Hospitality Academy, the training academy operated by Altus Advisory in Riyadh, Kingdom of Saudi Arabia, and to learners who use it through their employer or directly.</p><h2>What is collected</h2><p>For a learner, the academy stores:</p><ul><li>Name, work email and mobile number where provided</li><li>Employer, property, department and job role</li><li>The learning record: enrolments, lesson progress, assessment attempts and scores, certificates and procedure acknowledgements</li></ul><h2>Why it is collected</h2><p>The information is used to:</p><ul><li>Deliver training</li><li>Record whether training was completed</li><li>Issue and verify certificates</li><li>Let an employer see the compliance position of its own workforce</li></ul><p>Nothing is sold, and nothing is used for advertising.</p><h2>Procedure acknowledgements</h2><p>An acknowledgement records the user, the exact procedure version, the timestamp and the originating network address. This is deliberate: an acknowledgement that cannot be tied to a person, a version and a moment is not evidence of anything.</p><h2>Who can see a learning record</h2><p>A learning record can be seen by:</p><ul><li>The learner</li><li>The learner\'s line manager</li><li>Department, property and organisation administrators within the same organisation</li><li>An academy administrator</li></ul><p>No organisation can see another organisation\'s data.</p><h2>Retention</h2><p>Learning records and certificates are retained while the account is active, and afterwards for as long as the issuing organisation requires them for audit. A certificate record is retained indefinitely so that verification keeps working.</p><h2>Your requests</h2><p>A learner may request a copy of their record, or a correction to it, through their employer\'s administrator or by contacting the academy directly through the <a href="/en/contact">contact page</a>. The <a href="/en/terms">terms of use</a> set out the rules for accounts and certificates.</p>',
      'cta_label' => 'Contact the academy',
      'meta_title' => 'Privacy Policy | Hospitality Academy by Altus Advisory',
      'meta_description' => 'Hospitality Academy privacy policy: what learner data is collected, why, who can see a learning record, and how long records and certificates are kept.',
      'focus_keyword' => 'Privacy Policy',
    ),
    'terms' => 
    array (
      'title' => 'Terms of Use',
      'subtitle' => 'The terms that apply to using the academy and to the certificates it issues.',
      'body' => '<h2>Scope</h2><p>These terms apply to Hospitality Academy, operated by Altus Advisory in Riyadh, Kingdom of Saudi Arabia, and to the certificates issued through it.</p><h2>Accounts</h2><p>An account belongs to one named person.</p><ul><li>Sharing an account is not permitted.</li><li>Completing training on behalf of another person is not permitted.</li></ul><p>Either practice invalidates any certificate resulting from it and is grounds for the account to be suspended.</p><h2>Assessments</h2><p>Assessment attempts are recorded with a timestamp and an attempt number. Attempt limits, time limits and question randomisation are applied as configured for each assessment. A result obtained by circumventing those controls is void.</p><h2>Certificates</h2><p>A certificate records completion of a specific course or programme by a specific person on a specific date. It is not a licence, a regulatory approval, or a statement that the holder is qualified for any particular role. Any such use is outside these terms. Certificate status can be checked on the <a href="/en/verify">verification page</a>.</p><h2>Content</h2><p>Course material and procedures published by the academy remain the property of the academy or of the organisation that authored them. Procedures uploaded by an organisation remain that organisation\'s property and are not shared with any other organisation.</p><h2>Availability</h2><p>The academy aims to keep the service available continuously but does not guarantee uninterrupted access. Planned maintenance is announced in advance where it is expected to interrupt access.</p><h2>Related policies</h2><p>How personal data is handled is described in the <a href="/en/privacy">privacy policy</a>.</p>',
      'cta_label' => 'Read the privacy policy',
      'meta_title' => 'Terms of Use | Hospitality Academy by Altus Advisory',
      'meta_description' => 'Hospitality Academy terms of use: rules for accounts and assessments, what a certificate does and does not state, content ownership and availability.',
      'focus_keyword' => 'Terms of Use',
    ),
  ),
  'ar' => 
  array (
    'home' => 
    array (
      'title' => 'أكاديمية الضيافة: تدريب موظفي الفنادق في السعودية',
      'subtitle' => 'تدريب قائم على الدور الوظيفي، وتقييم عملي، وشهادات قابلة للتحقق لفرق الفنادق، من ألتوس للاستشارات في الرياض، بالعربية والإنجليزية وبلغات موظفيك.',
      'body' => '<h2>ما هي أكاديمية الضيافة؟</h2><p>أكاديمية الضيافة هي الأكاديمية التدريبية العامة التابعة لشركة ألتوس للاستشارات، وهي دار استشارات متخصصة في الضيافة واستراتيجية الأعمال مقرها الرياض في المملكة العربية السعودية. تعمل الأكاديمية على منصة ألتوس للمعرفة والأداء الفندقي، التي تدرّب فرق الفنادق وفق الدور الوظيفي ثم تتحقق من قدرة كل موظف على أداء العمل فعلياً.</p><h2>بماذا تختلف عن الدورات الإلكترونية المعتادة؟</h2><p>لا يُعدّ إكمال الدورة دليلاً كافياً. ينتقل كل متدرب من التعلم المرتبط بدوره إلى التقييم النظري والعملي، وتُسجَّل النتيجة مقابل كفاءات محددة. وحين تظهر فجوة تُعدّ خطة عمل تصحيحية ثم يُعاد التقييم، فيرى المدير دليلاً على القدرة لا قائمة بمقاطع فيديو مكتملة.</p><ol><li>تعلّم يُسند وفق متطلبات الدور الوظيفي</li><li>تقييم نظري وتقييم عملي على المعيار نفسه</li><li>سجل كفاءات وفجوات محددة وخطة عمل تصحيحية</li><li>إعادة تقييم وحالة جاهزية وشهادة قابلة للتحقق</li></ol><h2>ما أقسام الفندق التي تغطيها الأكاديمية؟</h2><p>يتوزع المنهج الرئيسي على عشرة مجالات مهنية أساسية: أساسيات الفندقة، ومكتب الاستقبال، والتدبير الفندقي، والأغذية والمشروبات، والمطبخ، والمبيعات والتسويق، والإيرادات والحجوزات، وتجربة الضيف، والجودة والتدقيق، والأمن والسلامة. تصفّح <a href="/ar/courses">كتالوج الدورات</a> أو اتبع <a href="/ar/learning-paths">مساراً تعليمياً</a> مصمماً لدور بعينه.</p><h2>ما اللغات التي يتعلم بها موظفو الفندق؟</h2><p>العربية والإنجليزية مدمجتان في تجربة واحدة، والواجهة العربية مصممة من اليمين إلى اليسار. وتدعم مساحة عمل الموظفين كذلك الهندية والأردية والفلبينية والبنغالية والنيبالية والمالايالامية، ليفهم المعيارَ من ينفذه في كل وردية.</p><h2>هل يستطيع صاحب العمل التحقق من الشهادة؟</h2><p>نعم. تحمل كل شهادة رقماً فريداً ورمز تحقق، ويستطيع أي شخص معرفة ما إذا كانت سارية أو منتهية أو ملغاة عبر <a href="/ar/verify">صفحة التحقق من الشهادات</a>.</p><h2>كيف تدعم الأكاديمية رؤية 2030؟</h2><p>تستهدف رؤية 2030 استقبال 150 مليون زيارة سنوياً إلى المملكة بحلول عام 2030، وتضع رأس المال البشري السعودي في قلب هذا النمو. وتوائم ألتوس للاستشارات الأكاديمية مع هذه الأهداف عبر مسارات تعليمية ثنائية اللغة، وكفاءة مُقيَّمة، وشهادات يمكن للفنادق في السعودية ودول الخليج الاعتماد عليها.</p><p>يمكن لملاك الفنادق ومشغليها <a href="/ar/hotels">إعداد التدريب لمنشآتهم</a> أو <a href="/ar/contact">التواصل مع فريق الأكاديمية في الرياض</a>.</p>',
      'cta_label' => 'تصفّح كتالوج الدورات',
      'meta_title' => 'تدريب موظفي الفنادق في السعودية | أكاديمية الضيافة',
      'meta_description' => 'تدريب موظفي الفنادق في السعودية من ألتوس للاستشارات: تعلّم حسب الدور الوظيفي، وتقييم عملي، وشهادات قابلة للتحقق بالعربية والإنجليزية.',
      'focus_keyword' => 'تدريب موظفي الفنادق في السعودية',
    ),
    'about' => 
    array (
      'title' => 'عن أكاديمية الضيافة',
      'subtitle' => 'الأكاديمية التدريبية العامة لشركة ألتوس للاستشارات في الرياض: من يقف خلف المحتوى، وكيف يُعتمد، وما الذي ندّعيه وما لا ندّعيه.',
      'body' => '<h2>من يدير أكاديمية الضيافة؟</h2><p>تتولى إدارة أكاديمية الضيافة شركة ألتوس للاستشارات، وهي دار استشارات استراتيجية متخصصة مقرها الرياض في المملكة العربية السعودية، وتخدم عملاءها في دول الخليج والشرق الأوسط وشمال أفريقيا. تعمل ألتوس عبر قطاعين متكاملين هما حلول الضيافة وحلول نمو الأعمال، والأكاديمية هي القناة التي تصل بها معاييرها التشغيلية إلى فرق الفنادق مباشرة.</p><h2>على أي خبرة يستند المحتوى التدريبي؟</h2><p>يستند المحتوى إلى المعايير التشغيلية لمؤسسي ألتوس، الذين تتجاوز خبرتهم القيادية مجتمعة 60 عاماً اكتسبوها داخل أنظمة ماريوت وIHG وستاروود وأكور وفي فنادق مستقلة. ويبدأ التدريب من إجراءات التشغيل القياسية كما تُنفَّذ في الوردية، لا من مكتبة دورات عامة.</p><h2>ما علاقة الأكاديمية بمنصة ألتوس؟</h2><p>الأكاديمية هي البوابة العامة إلى منصة ألتوس للمعرفة والأداء الفندقي. وداخل المنصة تُسند الفنادق التعلم حسب الدور الوظيفي، وتجري التقييمات النظرية والعملية، وتتابع فجوات الكفاءة وخطط العمل، وترى جاهزية كل موظف. ويجيب مساعد ذكاء اصطناعي خاضع للحوكمة عن أسئلة الموظفين من المحتوى المعتمد وحده، ويصرّح بذلك حين لا يغطي المحتوى السؤال.</p><h2>كيف يُعتمد المحتوى التدريبي؟</h2><p>يمر كل درس وإجراء وتقييم بمراجعة محكومة قبل أن يصل إلى المتدربين.</p><ol><li>يُعدّ المؤلف المسودة.</li><li>تحصل المسودة على الاعتماد الداخلي.</li><li>تحصل المسودة على اعتماد الجودة.</li><li>يُنشر المحتوى ويُسجَّل إصداره.</li></ol><p>لا يحق للمؤلف اعتماد عمله بنفسه، وتبقى الإصدارات السابقة محفوظة ليعرف المدقق المعيار الذي كان سارياً في أي تاريخ.</p><h2>ما المبادئ التي توجّه عمل الأكاديمية؟</h2><p>تلتزم الأكاديمية بالمبادئ التي تطبقها ألتوس للاستشارات في كل تكليف.</p><ul><li>الدليل قبل الحدس: تُثبت القدرة بالتقييم، ولا تُفترض من الحضور.</li><li>معايير ثابتة في كل وردية، بالعربية والإنجليزية وبلغات العمالة التي يستخدمها موظفو الفنادق.</li><li>شراكة تتجاوز حدود التكليف: تبقى المعرفة داخل منشأة العميل بعد انتهاء المهمة.</li><li>دعم رأس المال البشري السعودي، انسجاماً مع أهداف رؤية 2030 في التوطين وتمكين الشباب.</li></ul><h2>ما الذي لا تدّعيه الأكاديمية؟</h2><p>لا ينشر هذا الموقع نسب اجتياز أو شهادات عملاء أو ادعاءات اعتماد. وتذكر الشهادة بدقة ما توثقه: من أكمل أي دورة أو برنامج، وفي أي تاريخ، وبأي نتيجة، وهل ما زالت سارية. اطّلع على <a href="/ar/certificates">آلية إصدار الشهادات</a>، أو تعرّف أكثر على <a href="/ar/altus">ألتوس للاستشارات وخدماتها</a>.</p>',
      'cta_label' => 'اطّلع على آلية الاعتماد',
      'meta_title' => 'أكاديمية تدريب ضيافة في الرياض | ألتوس للاستشارات',
      'meta_description' => 'أكاديمية الضيافة هي أكاديمية تدريب ضيافة في الرياض تابعة لألتوس للاستشارات، مبنية على معايير تشغيلية ميدانية ومراجعة محكومة للمحتوى.',
      'focus_keyword' => 'أكاديمية تدريب ضيافة في الرياض',
    ),
    'for-hotels' => 
    array (
      'title' => 'منصة تدريب للفنادق والمنشآت في السعودية',
      'subtitle' => 'أسند التعلم حسب الدور الوظيفي، وقيّم الجانبين النظري والعملي، وعالج فجوات الكفاءة، وتابع جاهزية كل منشأة في مساحة عمل واحدة ثنائية اللغة.',
      'body' => '<h2>لماذا تحتاج الفنادق إلى إثبات القدرة لا مجرد إكمال الدورات؟</h2><p>تعرف معظم الفنادق مسبقاً ما ينبغي أن تؤديه فرقها. أما الصعوبة فهي إثبات أن كل موظف قادر على أدائه وفق المعيار الحالي، واكتشاف الفجوات قبل أن يكشفها ضيف أو تدقيق أو جولة تفتيش. ولهذا بنت ألتوس للاستشارات منصة ألتوس للمعرفة والأداء الفندقي لسد هذه الفجوة لدى الفنادق في الرياض وسائر مناطق السعودية.</p><h2>ماذا يحصل الفندق من المنصة؟</h2><p>مساحة عمل واحدة يجتمع فيها التدريب والتقييم والأدلة لكل منشأة.</p><ul><li>إسناد التعلم للأفراد أو المسميات الوظيفية أو الأقسام أو المجموعات، مع تواريخ استحقاق واستثناءات</li><li>تقييمات نظرية وتقييمات عملية تُصحَّح بمعايير موزونة، ويحدّ المعيار الحرج من النتيجة النهائية</li><li>ملفات كفاءة، وخريطة حرارية للفجوات، وخطط عمل مع رفع الأدلة، وإعادة تقييم</li><li>حالة جاهزية لكل موظف، تشمل جاهزية الافتتاح لفرق ما قبل التشغيل</li><li>تدقيقات جودة ومؤشرات أداء وتقارير قابلة للتصدير بصيغتي CSV وXLSX</li><li>مساعد ذكاء اصطناعي خاضع للحوكمة يجيب من إجراءاتك وسياساتك المعتمدة وحدها مع ذكر المصادر</li><li>هوية المنشأة: شعارك وألوانك واسمك</li></ul><h2>من يرى ماذا داخل المنصة؟</h2><p>تتبع الصلاحيات هيكل منشأتك. فرئيس القسم يرى فريقه، والمدير العام يرى الفندق، والتنفيذي يرى نظرة عامة على المحفظة وتقريراً قابلاً للطباعة لمجلس الإدارة. وكل خطوة محصورة في نطاق منشأتك ومسجلة في سجل التدقيق، ولا تستطيع أي منشأة الاطلاع على بيانات منشأة أخرى.</p><h2>لأي منشآت صُممت المنصة؟</h2><p>وفقاً للملف التعريفي لشركة ألتوس للاستشارات، صُممت المنصة خصيصاً للفنادق المستقلة والشقق المخدومة والمنشآت الصغيرة والمتوسطة في السعودية والمنطقة العربية، التي تحتاج إلى تدريب عملي قائم على المعايير دون تكلفة أنظمة السلاسل العالمية وتعقيدها. والحاجة في تزايد، إذ تسجل البيانات الأولية لوزارة السياحة 122 مليون زيارة محلية ودولية في عام 2025، وتستهدف رؤية 2030 استقبال 150 مليون زيارة سنوياً بحلول عام 2030.</p><h2>كيف نبدأ؟</h2><p>يبدأ الإعداد من هيكل منشأتك، لا من كتالوج فارغ.</p><ol><li>شاركنا الفنادق والأقسام وعدد الموظفين التقريبي في كل قسم.</li><li>تُعدّ ألتوس هيكل المنشأة وتربط كل مسمى وظيفي بالكفاءات التي يتطلبها.</li><li>يُسند التدريب الإلزامي، فيجد كل موظف قائمته الخاصة عند أول تسجيل دخول.</li><li>يتابع المديرون الإكمال ونتائج التقييم والجاهزية من لوحة المتابعة.</li></ol><p>اطّلع على <a href="/ar/hotels/training">برامج التدريب حسب القسم</a>، أو تصفّح <a href="/ar/programs">برامج الشهادات</a>، أو <a href="/ar/contact">تحدّث مع فريق الأكاديمية</a>.</p>',
      'cta_label' => 'تواصل مع الأكاديمية',
      'meta_title' => 'منصة تدريب الفنادق في السعودية | ألتوس للاستشارات',
      'meta_description' => 'منصة تدريب الفنادق في السعودية: إسناد التعلم حسب الدور، وتقييم عملي، ومعالجة فجوات الكفاءة، ومتابعة جاهزية كل منشأة.',
      'focus_keyword' => 'منصة تدريب الفنادق في السعودية',
    ),
    'hotels-training' => 
    array (
      'title' => 'برامج تدريب موظفي الفنادق حسب القسم',
      'subtitle' => 'ما الذي يتدرب عليه كل قسم فندقي، وبأي ترتيب يُقدَّم التدريب، وكيف تُثبت القدرة قبل أن يعمل الموظف دون إشراف.',
      'body' => '<h2>ما التدريب الذي يحتاجه كل قسم في الفندق؟</h2><p>لكل قسم مساره الخاص ضمن المنهج الرئيسي الذي طورته ألتوس للاستشارات في الرياض انطلاقاً من معايير تشغيلية مجرّبة ميدانياً. ويتدرج المحتوى من المجال المهني إلى المسار ثم الوحدة ثم الدرس، يليها التقييم والاعتماد، فيكون لكل دور طريق واضح.</p><ul><li><strong>مكتب الاستقبال:</strong> إجراءات الوصول والمغادرة، وتسجيل الضيف وخصوصيته، وتوزيع الغرف، ومعالجة الشكاوى، والبيع الإضافي، والتدقيق الليلي.</li><li><strong>التدبير الفندقي:</strong> تسلسل تنظيف الغرفة، ومعايير السرير ودورة المياه، وسلامة المواد الكيميائية، والمفقودات، والمغسلة، والمناطق العامة، والتفتيش.</li><li><strong>الأغذية والمشروبات:</strong> تسلسل الخدمة، والاستقبال والإجلاس، وخدمة الطاولة والمشروبات، والولائم، وإجراءات نقاط البيع.</li><li><strong>المطبخ:</strong> سلامة الغذاء، وضبط درجات الحرارة، والتخزين والاستلام، والتعامل مع مسببات الحساسية، وسلامة السكاكين، وضبط الهدر.</li><li><strong>المبيعات والإيرادات والحجوزات:</strong> المبيعات والتسويق، وإجراءات الحجز، والتوزيع، وأساسيات إدارة الإيرادات.</li><li><strong>تجربة الضيف والجودة والتدقيق:</strong> معالجة إخفاقات الخدمة، والالتزام بمعايير العلامة والإجراءات، وتفتيش الجودة.</li><li><strong>الأمن والسلامة:</strong> السلامة من الحريق، والاستجابة للطوارئ، وإجراءات الأمن لكل موظف.</li></ul><h2>بأي ترتيب يُقدَّم تدريب موظفي الفنادق؟</h2><p>تأتي السلامة والأساسيات أولاً، ثم مهارات الدور، ثم تقييم المعيار نفسه.</p><ol><li>أساسيات الفندقة والتعريف بالمنشأة والسلامة لكل موظف</li><li>المتطلبات المسبقة للدور، مثل سلامة المواد الكيميائية في التدبير الفندقي أو سلامة الغذاء ومسببات الحساسية في المطبخ</li><li>وحدات الدور بدروس تطبيقية قصيرة بالفيديو أو ملفات PDF أو العروض أو الصوت</li><li>تقييم نظري، ثم تقييم عملي يجريه المشرف</li><li>شهادة، أو خطة عمل وإعادة تقييم عند ظهور فجوة</li></ol><h2>هل يمكن أن يتبع التدريب معايير فندقنا الخاصة؟</h2><p>نعم. المنصة قابلة للتخصيص بهوية كل منشأة، وتُضاف إجراءاتك وسياساتك وقوائم التحقق المعتمدة لديك إلى جانب المنهج، مع تسجيل إقرار الموظفين بكل إصدار. ويجيب مساعد الذكاء الاصطناعي عن أسئلة الموظفين من هذا المحتوى المعتمد وحده.</p><h2>هل يتوفر التدريب للموظفين الذين لا يقرؤون العربية أو الإنجليزية؟</h2><p>الدروس ثنائية اللغة بالعربية والإنجليزية، وتدعم مساحة عمل الموظفين كذلك الهندية والأردية والفلبينية والبنغالية والنيبالية والمالايالامية، لتلائم الفرق متعددة الجنسيات العاملة في فنادق السعودية.</p><p>استكشف <a href="/ar/courses">كتالوج الدورات الكامل</a>، أو اتبع <a href="/ar/learning-paths">مساراً تعليمياً حسب الدور</a>، أو اقرأ <a href="/ar/hotels">كيف تعتمد الفنادق المنصة</a>.</p>',
      'cta_label' => 'اطّلع على الكتالوج الكامل',
      'meta_title' => 'برامج تدريب موظفي الفنادق حسب القسم في السعودية',
      'meta_description' => 'برامج تدريب موظفي الفنادق حسب القسم، من الاستقبال إلى المطبخ، مع تقييم عملي وشهادات قابلة للتحقق للفرق العاملة في السعودية.',
      'focus_keyword' => 'برامج تدريب موظفي الفنادق',
    ),
    'certificates-info' => 
    array (
      'title' => 'شهادات التدريب الفندقي والتحقق منها',
      'subtitle' => 'ما الذي توثقه شهادة أكاديمية الضيافة، ومتى تُصدر، وكيف يتحقق صاحب العمل خلال ثوانٍ من صحتها وسريانها.',
      'body' => '<h2>متى تُصدر شهادة أكاديمية الضيافة؟</h2><p>تُصدر الشهادة عندما يكمل المتدرب كل درس إلزامي في الدورة ويجتاز تقييمها بدرجة النجاح المحددة لتلك الدورة أو أعلى منها. وتُصدر شهادة البرنامج عند إكمال جميع دوراته. والغاية من الاعتماد أن يعكس قدرة مُقيَّمة، لا مجرد حضور.</p><h2>ما الذي توثقه شهادة التدريب الفندقي؟</h2><p>توثق كل شهادة ما يحتاجه صاحب العمل من معلومات فقط.</p><ul><li>اسم المتدرب</li><li>الدورة أو البرنامج المكتمل</li><li>تاريخ الإكمال والدرجة النهائية</li><li>رقم شهادة فريد ورمز تحقق ورمز استجابة سريعة (QR)</li><li>تاريخ انتهاء حين يتطلب الموضوع تجديداً دورياً، مثل السلامة وسلامة الغذاء</li></ul><h2>كيف أتحقق من شهادة تدريب فندقي؟</h2><p>استخدم صفحة التحقق العامة، ولا حاجة إلى حساب.</p><ol><li>افتح <a href="/ar/verify">صفحة التحقق من الشهادات</a>.</li><li>أدخل رمز التحقق المطبوع على الشهادة، أو امسح رمز QR الخاص بها.</li><li>اقرأ الحالة الظاهرة: سارية أو منتهية أو ملغاة أو غير موجودة.</li></ol><p>تعرض النتيجة السارية اسم المتدرب والموضوع وتاريخ الإصدار، ولا شيء آخر عن الشخص.</p><h2>لماذا قد تظهر الشهادة ملغاة؟</h2><p>تُلغى الشهادة إذا صدرت بالخطأ، أو إذا تبيّن أن نتيجة التقييم التي بُنيت عليها غير صحيحة، أو بطلب من الجهة المُصدِرة. وتبقى الشهادة الملغاة قابلة للتحقق وتظهر بحالة «ملغاة» بدلاً من أن تختفي، حتى لا تُقدَّم نسخة سابقة على أنها سارية.</p><h2>من يُصدر الشهادات؟</h2><p>تُصدر الشهادات عبر منصة ألتوس للمعرفة والأداء الفندقي التي تشغّلها ألتوس للاستشارات في الرياض بالمملكة العربية السعودية. وتوثق الشهادة إكمال شخص محدد لدورة أو برنامج محدد في تاريخ محدد، وهي ليست رخصة ولا موافقة تنظيمية ولا إفادة بأن حاملها مؤهل لدور بعينه.</p><p>تصفّح <a href="/ar/programs">برامج الشهادات</a> المتاحة، أو <a href="/ar/contact">اسأل فريق الأكاديمية</a> عن اعتماد موظفي فندقك.</p>',
      'cta_label' => 'تحقق من شهادة',
      'meta_title' => 'التحقق من شهادة تدريب فندقي | أكاديمية الضيافة',
      'meta_description' => 'التحقق من شهادة تدريب فندقي صادرة عن أكاديمية الضيافة برمز التحقق أو رمز QR، وما الذي توثقه الشهادة ومتى تنتهي ولماذا قد تُلغى.',
      'focus_keyword' => 'التحقق من شهادة تدريب فندقي',
    ),
    'contact' => 
    array (
      'title' => 'تواصل مع أكاديمية الضيافة',
      'subtitle' => 'أخبرنا عن منشآتك وفريقك، وسنعود إليك بهيكل عمل لا بكتيّب تعريفي.',
      'body' => '<h2>كيف أطلب تدريباً فندقياً لمنشأتي؟</h2><p>أرسل طلبك بشأن تدريب الفنادق في الرياض أو في أي منطقة أخرى من المملكة عبر النموذج في هذه الصفحة، وسيتواصل معك أحد أعضاء فريق أكاديمية الضيافة في ألتوس للاستشارات بالرياض، المملكة العربية السعودية، لترتيب مكالمة. لا توجد رسائل بريد آلية متسلسلة، ولا تُمرَّر بياناتك إلى أي طرف ثالث.</p><h2>ما المعلومات التي أذكرها في طلبي؟</h2><p>تتيح لنا بعض المعلومات الأساسية أن نرد بهيكل عمل واضح بدلاً من عرض تقديمي عام.</p><ul><li>الفنادق والمدن المعنية</li><li>الأقسام التي تريد البدء بها</li><li>العدد التقريبي للموظفين في كل قسم</li><li>اللغات التي يحتاجها موظفوك: العربية أو الإنجليزية أو لغات العمالة مثل الهندية والأردية والفلبينية والبنغالية والنيبالية والمالايالامية</li><li>أي موعد نهائي، مثل افتتاح منشأة أو جولة تفتيش</li></ul><h2>ماذا يحدث بعد التواصل؟</h2><p>الإجراء قصير ويتولاه أشخاص لا أنظمة آلية.</p><ol><li>نرد عليك لترتيب مكالمة تعريفية.</li><li>نناقش منشآتك ومسمياتها الوظيفية ومعاييرها الحالية.</li><li>نقترح هيكلاً للأقسام والأدوار والتدريب الإلزامي لفريقك.</li></ol><h2>هل يمكنني التواصل مع ألتوس للاستشارات في موضوع غير التدريب؟</h2><p>نعم. تقدم ألتوس للاستشارات أيضاً خدماتها لملاك الفنادق والمستثمرين في السعودية ودول الخليج في تطوير الفنادق وتمثيل الملاك، ودعم ما قبل الافتتاح، والتشغيل، وتجربة الضيف، والأداء التجاري، ونمو الأعمال بوجه عام. تعرّف على <a href="/ar/altus">ألتوس للاستشارات وخدماتها</a>.</p><h2>إلى أين أتوجه باستفسار عن شهادة؟</h2><p>للتأكد من صحة شهادة، استخدم <a href="/ar/verify">صفحة التحقق من الشهادات</a> مباشرة دون الحاجة إلى تقديم طلب. ولطلب نسخة من سجلك التدريبي أو تصحيحه، تواصل مع مسؤول النظام لدى جهة عملك أو راسلنا عبر هذه الصفحة.</p><p>قبل أن تراسلنا، قد يفيدك الاطلاع على <a href="/ar/hotels">كيف تعمل المنصة للفنادق</a> أو تصفّح <a href="/ar/courses">كتالوج الدورات</a>.</p>',
      'cta_label' => 'أرسل طلبك',
      'meta_title' => 'تواصل معنا: تدريب الفنادق في الرياض | ألتوس',
      'meta_description' => 'تواصل مع أكاديمية الضيافة في ألتوس للاستشارات بشأن تدريب الفنادق في الرياض وسائر مناطق السعودية. أخبرنا بمنشآتك وأقسامك ومواعيدك.',
      'focus_keyword' => 'تدريب الفنادق في الرياض',
    ),
    'privacy' => 
    array (
      'title' => 'سياسة الخصوصية',
      'subtitle' => 'ما الذي تحفظه الأكاديمية، ولماذا تحفظه، ومن يطّلع عليه، وإلى متى يُحفظ.',
      'body' => '<h2>نطاق هذه السياسة</h2><p>تسري هذه السياسة على أكاديمية الضيافة، الأكاديمية التدريبية التي تشغّلها ألتوس للاستشارات في الرياض بالمملكة العربية السعودية، وعلى المتدربين الذين يستخدمونها عبر جهة عملهم أو مباشرة.</p><h2>ما الذي يُجمع</h2><p>تحفظ الأكاديمية للمتدرب ما يلي:</p><ul><li>الاسم والبريد الإلكتروني الوظيفي ورقم الجوال إن قُدِّم</li><li>جهة العمل والفندق والقسم والمسمى الوظيفي</li><li>السجل التدريبي: التسجيلات وتقدم الدروس ومحاولات التقييم والدرجات والشهادات والإقرارات بالإجراءات</li></ul><h2>لماذا يُجمع</h2><p>تُستخدم هذه المعلومات من أجل:</p><ul><li>تقديم التدريب</li><li>توثيق إكمال التدريب</li><li>إصدار الشهادات والتحقق منها</li><li>تمكين جهة العمل من الاطلاع على وضع الالتزام لدى كوادرها</li></ul><p>لا يُباع شيء من هذه البيانات، ولا يُستخدم شيء منها لأغراض إعلانية.</p><h2>الإقرار بالإجراءات</h2><p>يسجل الإقرار المستخدم وإصدار الإجراء بدقة والتوقيت وعنوان الشبكة الذي صدر منه. وهذا مقصود، فالإقرار الذي لا يمكن ربطه بشخص وإصدار ولحظة محددة لا يُعد دليلاً على شيء.</p><h2>من يستطيع الاطلاع على السجل التدريبي</h2><p>يطّلع على السجل التدريبي كل من:</p><ul><li>المتدرب نفسه</li><li>مديره المباشر</li><li>مسؤولو القسم والفندق والمنشأة داخل المنشأة نفسها</li><li>مسؤول الأكاديمية</li></ul><p>ولا تستطيع أي منشأة الاطلاع على بيانات منشأة أخرى.</p><h2>مدة الحفظ</h2><p>تُحفظ السجلات التدريبية والشهادات ما دام الحساب فعالاً، ثم للمدة التي تطلبها الجهة المُصدِرة لأغراض التدقيق. ويُحفظ سجل الشهادة دون حد زمني ليبقى التحقق منها ممكناً.</p><h2>طلباتك</h2><p>يستطيع المتدرب طلب نسخة من سجله أو تصحيحه عبر مسؤول النظام لدى جهة عمله، أو بالتواصل مع الأكاديمية مباشرة من خلال <a href="/ar/contact">صفحة التواصل</a>. وتحدد <a href="/ar/terms">شروط الاستخدام</a> القواعد المتعلقة بالحسابات والشهادات.</p>',
      'cta_label' => 'تواصل مع الأكاديمية',
      'meta_title' => 'سياسة الخصوصية | أكاديمية الضيافة من ألتوس للاستشارات',
      'meta_description' => 'سياسة الخصوصية لأكاديمية الضيافة: البيانات التي تُجمع عن المتدرب، وسبب جمعها، ومن يطّلع على السجل التدريبي، ومدة حفظ السجلات والشهادات.',
      'focus_keyword' => 'سياسة الخصوصية',
    ),
    'terms' => 
    array (
      'title' => 'شروط الاستخدام',
      'subtitle' => 'الشروط المطبقة على استخدام الأكاديمية وعلى الشهادات التي تصدرها.',
      'body' => '<h2>النطاق</h2><p>تسري هذه الشروط على أكاديمية الضيافة التي تشغّلها ألتوس للاستشارات في الرياض بالمملكة العربية السعودية، وعلى الشهادات الصادرة من خلالها.</p><h2>الحسابات</h2><p>يخص الحساب شخصاً واحداً محدداً بالاسم.</p><ul><li>لا يُسمح بمشاركة الحساب.</li><li>لا يُسمح بإكمال التدريب نيابة عن شخص آخر.</li></ul><p>وأي من هاتين الممارستين يُبطل كل شهادة تنتج عنها، ويُعد سبباً لتعليق الحساب.</p><h2>التقييمات</h2><p>تُسجَّل محاولات التقييم مع توقيتها ورقم المحاولة. وتُطبَّق حدود المحاولات وحدود الوقت والترتيب العشوائي للأسئلة وفق إعدادات كل تقييم. وتُعد لاغية أي نتيجة يُحصل عليها بالالتفاف على هذه الضوابط.</p><h2>الشهادات</h2><p>توثق الشهادة إكمال شخص محدد لدورة أو برنامج محدد في تاريخ محدد. وهي ليست رخصة ولا موافقة تنظيمية ولا إفادة بأن حاملها مؤهل لدور بعينه، وأي استخدام لها بهذا المعنى يقع خارج نطاق هذه الشروط. ويمكن التحقق من حالة الشهادة عبر <a href="/ar/verify">صفحة التحقق</a>.</p><h2>المحتوى</h2><p>تبقى المواد التدريبية والإجراءات التي تنشرها الأكاديمية ملكاً للأكاديمية أو للجهة التي ألّفتها. وتبقى الإجراءات التي ترفعها أي منشأة ملكاً لتلك المنشأة، ولا تُشارَك مع أي منشأة أخرى.</p><h2>الإتاحة</h2><p>تسعى الأكاديمية إلى إبقاء الخدمة متاحة باستمرار، لكنها لا تضمن وصولاً دون انقطاع. ويُعلَن مسبقاً عن الصيانة المخططة حين يُتوقع أن تعطّل الوصول.</p><h2>سياسات ذات صلة</h2><p>توضح <a href="/ar/privacy">سياسة الخصوصية</a> كيفية التعامل مع البيانات الشخصية.</p>',
      'cta_label' => 'اقرأ سياسة الخصوصية',
      'meta_title' => 'شروط الاستخدام | أكاديمية الضيافة من ألتوس للاستشارات',
      'meta_description' => 'شروط استخدام أكاديمية الضيافة: قواعد الحسابات والتقييمات، وما تثبته الشهادة وما لا تثبته، وملكية المحتوى، وإتاحة الخدمة.',
      'focus_keyword' => 'شروط الاستخدام',
    ),
  ),
);
