<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/**
 * The end-of-course question bank.
 *
 * One entry per course code, each a list of questions shaped as:
 *
 *     array('question text', array('option', 'option', ...), 1-based correct)
 *
 * Written per course rather than generated from a template. A template
 * produces questions that could belong to any course ("What is the main goal
 * of this procedure?"), which tests whether the learner can read the question
 * rather than whether they learned the work. Every question here is about
 * something that is actually done on shift, and the wrong options are wrong
 * in ways a learner who skimmed would plausibly choose.
 *
 * Where a question touches safety or law (food temperatures, chemical
 * handling, fire response, guest data) the correct answer follows the
 * published standard rather than local habit: HACCP for food, Saudi PDPL for
 * guest data, manufacturer instructions for chemicals.
 */
class Ha_quizbank {

    public function questions() {
        return array_merge(
            $this->front_office(),
            $this->housekeeping(),
            $this->food_and_beverage(),
            $this->kitchen(),
            $this->engineering(),
            $this->commercial_and_management()
        );
    }

    private function front_office() {
        return array(
        'fo-fundamentals' => array(
            array('A guest arrives at 11:00 and the room is not ready. What does the agent do first?',
                array('Tell the guest to come back at check-in time', 'Acknowledge it, offer luggage storage and give a specific time the room will be ready', 'Upgrade the guest to a suite at no charge', 'Check the guest in anyway and let them wait in the corridor'), 2),
            array('What does the front office hand over at shift change?',
                array('Only the cash float', 'Pending arrivals, guest requests still open, out-of-order rooms and anything unresolved', 'Nothing, the system holds all of it', 'Only complaints'), 2),
            array('Which department does the front desk depend on most to sell a clean room?',
                array('Engineering', 'Housekeeping', 'Finance', 'Sales'), 2),
            array('A guest asks a question the agent cannot answer. The correct response is to',
                array('Guess, so the guest is not kept waiting', 'Say it is not your department', 'Say you will find out, give a time, and come back with the answer', 'Refer them to the website'), 3),
        ),
        'fo-check-in' => array(
            array('What must be verified before a room key is issued?',
                array('The guest\'s identity against the reservation', 'The guest\'s social media', 'Nothing, the booking is enough', 'Only the payment card'), 1),
            array('A guest booked a twin room and arrives expecting a double. What is the correct step?',
                array('Insist the booking is correct and move on', 'Check availability for a double, explain the options and confirm before moving them', 'Move them without telling them', 'Charge a change fee first'), 2),
            array('Rooming a guest means',
                array('Leaving them to find the room themselves', 'Escorting them and showing how the room works, then confirming they have what they need', 'Sending a bellman with the luggage only', 'Calling the room after ten minutes'), 2),
            array('When should the guest be told the checkout time?',
                array('Never, it is on the door', 'At check-in, along with breakfast times and Wi-Fi', 'Only if they ask', 'On the morning of departure'), 2),
        ),
        'fo-check-out' => array(
            array('A guest disputes a minibar charge at checkout. What is the first step?',
                array('Remove it immediately without checking', 'Insist the charge stands', 'Check the posting with housekeeping before deciding, and keep the guest informed', 'Ask the guest to email the hotel later'), 3),
            array('What should be offered at the end of every checkout?',
                array('A discount voucher', 'An itemised folio and help with onward travel or luggage', 'A review request only', 'Nothing'), 2),
            array('A late checkout request should be answered by',
                array('Refusing automatically', 'Checking the arrivals for that room type before committing', 'Always agreeing', 'Charging a full extra night in every case'), 2),
            array('Why does the folio need to be accurate before the guest leaves?',
                array('It is easier to correct in person than after departure', 'It is a legal requirement in every country', 'It changes the room rate', 'It is not important'), 1),
        ),
        'fo-complaints' => array(
            array('A guest is angry about noise from the room above. What comes first?',
                array('Explain the hotel policy', 'Listen without interrupting, acknowledge the problem and apologise for the effect on them', 'Offer a free night', 'Ask them to put it in writing'), 2),
            array('What does LEARN stand for in complaint handling?',
                array('Listen, Empathise, Apologise, React, Notify', 'Leave, Escalate, Argue, Refuse, Note', 'Log, Email, Assign, Review, Notify', 'Listen, Explain, Argue, Refund, Note'), 1),
            array('When a complaint cannot be resolved by the agent, the correct action is',
                array('Tell the guest nothing can be done', 'Escalate to the duty manager with the facts, and tell the guest who will contact them and when', 'Give the guest the manager\'s mobile number', 'Wait until the next shift'), 2),
            array('Why is every complaint logged, even one resolved on the spot?',
                array('To justify refusing a refund later', 'So repeat causes can be found and fixed', 'It is not logged if resolved', 'To record which staff member was at fault'), 2),
        ),
        'fo-guest-registration' => array(
            array('The guest folio is',
                array('The room key record', 'The running account of every charge and payment for that stay', 'The housekeeping report', 'The reservation confirmation'), 2),
            array('Which details must be captured at registration in Saudi Arabia?',
                array('Name only', 'Identity document details as required by law, plus contact and payment', 'Nothing, the booking suffices', 'Social media handle'), 2),
            array('A registration card signed by the guest establishes',
                array('The guest\'s agreement to the rate and the hotel\'s terms', 'The housekeeping schedule', 'The loyalty tier', 'Nothing legally'), 1),
            array('Where a guest declines to give required identity details, the agent should',
                array('Check them in anyway', 'Explain that it is a legal requirement and involve the duty manager if it is refused', 'Refuse service without explanation', 'Copy details from a previous stay'), 2),
        ),
        'fo-guest-privacy' => array(
            array('A caller asks whether a named guest is staying at the hotel. The correct answer is',
                array('Confirm and put the call through', 'Neither confirm nor deny that the guest is in house', 'Confirm but refuse to connect', 'Give the room number only'), 2),
            array('Under the Saudi Personal Data Protection Law, guest data may be used',
                array('For any purpose the hotel chooses', 'Only for the purpose it was collected for, unless the guest consents to more', 'Freely once the guest has checked out', 'For marketing by default'), 2),
            array('A printed arrivals list left on the desk is a problem because',
                array('It wastes paper', 'It exposes guest names and room numbers to anyone passing', 'It is out of date quickly', 'It is not a problem'), 2),
            array('A guest asks what data the hotel holds about them. The correct response is',
                array('Refuse, it is internal', 'Follow the hotel\'s data request procedure, which gives the guest a right to know', 'Read it out from the screen immediately', 'Tell them no data is held'), 2),
        ),
        'fo-room-assignment' => array(
            array('Which guest should be prioritised when assigning the best available room?',
                array('The latest booker', 'Guests with an accessibility requirement, then VIP and repeat guests', 'Whoever complains most', 'The cheapest rate'), 2),
            array('An accessible room should be held for',
                array('Anyone, it is a normal room', 'A guest who has requested one, until it is clear none is needed', 'Staff use', 'Group bookings'), 2),
            array('A room marked out of order should be',
                array('Sold at a discount', 'Kept out of inventory until engineering releases it', 'Assigned to a late arrival', 'Cleaned and sold'), 2),
            array('Why are connecting rooms held back during a family-heavy arrival day?',
                array('They are harder to clean', 'They are the only option for families travelling with children and are quickly exhausted', 'They cost more', 'They are not held back'), 2),
        ),
        'fo-telephone' => array(
            array('Within how many rings should an internal call be answered as a standard?',
                array('Three', 'Eight', 'Fifteen', 'It does not matter'), 1),
            array('The correct greeting on answering an external call includes',
                array('Just "hello"', 'The hotel name, the department, your name and an offer of help', 'Only your name', 'The room number'), 2),
            array('Before placing a caller on hold you should',
                array('Put them on hold immediately', 'Ask permission, explain why, and thank them when you return', 'Transfer them instead', 'Tell them to call back'), 2),
            array('A caller asks to be put through to a guest room. The agent should',
                array('Connect without confirming anything', 'Ask for the guest name, and connect without revealing the room number', 'Give the room number so the caller can dial direct', 'Refuse all such calls'), 2),
        ),
        'fo-concierge' => array(
            array('A guest asks for a restaurant recommendation. The best answer',
                array('Names the hotel restaurant only', 'Asks what they are in the mood for, then gives two or three options with reasons', 'Hands them a directory', 'Names the most expensive option'), 2),
            array('The bell desk is responsible for',
                array('Room cleaning', 'Luggage handling, storage and delivery, and assisting arrivals and departures', 'Billing', 'Reservations'), 2),
            array('When storing luggage, the item must be',
                array('Left in the lobby', 'Tagged with a receipt given to the guest, and stored securely', 'Kept behind the desk untagged', 'Taken to the guest room'), 2),
            array('A concierge who cannot arrange a request should',
                array('Say it is impossible', 'Offer the nearest alternative and be clear about what can and cannot be done', 'Promise and then not deliver', 'Refer the guest to reception'), 2),
        ),
        'fo-night-audit' => array(
            array('The night audit exists to',
                array('Clean the lobby', 'Close the financial day, post room and tax charges and reconcile the day\'s revenue', 'Prepare breakfast', 'Reset the key system'), 2),
            array('A discrepancy found during the audit should be',
                array('Corrected silently', 'Documented with the correction and passed to the accounts team', 'Left for the morning shift', 'Ignored if it is small'), 2),
            array('Rooms still showing as occupied after the expected departure should be',
                array('Charged automatically', 'Checked against housekeeping status before any charge is raised', 'Released without checking', 'Reported to the police'), 2),
            array('Why is the audit run at night?',
                array('Staff are cheaper', 'It is the quietest point of the trading day, so the books can be closed against a stable position', 'It is a legal requirement', 'The system is faster'), 2),
        ),
        'fo-reception-operations' => array(
            array('A walk-in guest arrives when the hotel is full. The agent should',
                array('Turn them away', 'Check for cancellations, then help them find a room nearby if there is genuinely nothing', 'Put them in an out-of-order room', 'Ask them to wait indefinitely'), 2),
            array('The arrivals list is checked at the start of a shift to',
                array('Count staff', 'Know who is coming, what they have asked for and which rooms are committed', 'Set room rates', 'Order breakfast'), 2),
            array('A reservation taken by phone must be read back because',
                array('It is polite', 'It catches errors in dates, room type and spelling before they become a problem at arrival', 'The system requires it', 'It is not read back'), 2),
            array('Which of these is a front desk responsibility at every shift?',
                array('Counting and signing for the cash float', 'Cleaning guest rooms', 'Cooking breakfast', 'Fixing air conditioning'), 1),
        ),
        'fo-upselling' => array(
            array('The best moment to offer a room upgrade is',
                array('After the guest has paid and left the desk', 'At check-in, once you know what the guest is here for', 'By email a week later', 'At checkout'), 2),
            array('An effective upsell is based on',
                array('The highest priced room', 'A benefit that matches what the guest said they need', 'Pressure', 'A script read word for word'), 2),
            array('A guest declines the upgrade. The agent should',
                array('Ask again immediately', 'Accept it gracefully and continue the check-in normally', 'Note them as difficult', 'Offer a discount on the same room'), 2),
            array('Why does upselling fail when the guest is tired and late?',
                array('It does not fail', 'The guest wants the room, not a decision, and pressing reads as an obstacle', 'The system blocks it', 'Rates change at night'), 2),
        ),
        'fo-vip' => array(
            array('A returning guest\'s preferences should be',
                array('Asked again every stay as if new', 'Held on the profile and acted on before arrival', 'Guessed', 'Ignored'), 2),
            array('A VIP arrival is prepared by',
                array('Doing nothing different', 'Checking the room personally, confirming amenities are placed and briefing the team who will meet them', 'Assigning any available room', 'Upgrading automatically'), 2),
            array('Recognising a repeat guest by name at arrival matters because',
                array('It is required by law', 'It is the clearest signal that the hotel remembers them, and it costs nothing', 'It speeds up check-in', 'It does not matter'), 2),
            array('A VIP complaint should be handled',
                array('The same as any other, with the duty manager informed early', 'By giving whatever is asked for', 'By ignoring the normal process', 'By the general manager only'), 1),
        ),
        'dig-pms' => array(
            array('A property management system holds',
                array('Only room rates', 'Reservations, guest profiles, room status, folios and the night audit', 'Only housekeeping schedules', 'Only the booking engine'), 2),
            array('Room status in the PMS should be updated by housekeeping because',
                array('The front desk cannot sell a room it believes is dirty', 'It is a legal requirement', 'It changes the rate', 'It is not updated'), 1),
            array('A guest profile merged in error causes',
                array('No problem', 'Charges and preferences attached to the wrong person, which is both a service and a data protection failure', 'Faster check-in', 'A rate change'), 2),
            array('Before overriding a PMS rate, an agent should',
                array('Override freely', 'Follow the authorisation rule, because rate overrides are auditable', 'Ask the guest', 'Change it back afterwards'), 2),
        ),
        );
    }

    private function housekeeping() {
        return array(
        'hk-fundamentals' => array(
            array('What does a room attendant do before entering a guest room?',
                array('Enter using the key immediately', 'Knock, announce "housekeeping", wait, repeat, then enter announcing again', 'Call the guest from reception', 'Wait for the guest to leave the floor'), 2),
            array('The housekeeping control desk is responsible for',
                array('Cooking', 'Coordinating room status, assignments, keys and guest requests across the floors', 'Billing guests', 'Checking guests in'), 2),
            array('A room reported as "clean" but not inspected should be',
                array('Sold immediately', 'Held until inspected, if the standard requires inspection before release', 'Reported as out of order', 'Cleaned again'), 2),
            array('Why is the cleaning sequence fixed rather than left to preference?',
                array('It is faster to supervise', 'A fixed order prevents steps being missed and stops clean surfaces being recontaminated', 'It is not fixed', 'It saves chemicals'), 2),
        ),
        'hk-room-cleaning' => array(
            array('In what order should a guest room be cleaned?',
                array('Bathroom first, then bedroom, then floor', 'Top to bottom and clean to dirty, finishing with the floor', 'Floor first', 'Whatever is quickest'), 2),
            array('Cloths are colour coded so that',
                array('They look tidy', 'A cloth used in the toilet is never used on a surface a guest touches', 'They match the uniform', 'They are easier to count'), 2),
            array('A guest\'s personal belongings found during cleaning should be',
                array('Moved to a drawer', 'Left where they are, tidied around but not handled or moved unnecessarily', 'Put in lost and found', 'Photographed'), 2),
            array('A departure room differs from a stayover room mainly because',
                array('It takes less time', 'Everything is stripped and replaced, and the room is reset to a sellable standard', 'Only the bed is made', 'It needs no inspection'), 2),
        ),
        'hk-bed-making' => array(
            array('Linen should be changed on a stayover',
                array('Never', 'According to the hotel standard, and always on request or when soiled', 'Only at departure', 'Every third day regardless'), 2),
            array('Stripped linen should be',
                array('Placed on the floor', 'Placed directly into the linen bag on the trolley, never on the floor or furniture', 'Left on the chair', 'Shaken out in the room'), 2),
            array('Why is bed linen not shaken out in a guest room?',
                array('It creases', 'It disperses dust and any contamination into the air the guest will breathe', 'It takes longer', 'It is allowed'), 2),
            array('A mattress protector is checked at every departure because',
                array('It is decorative', 'A soiled protector means the mattress may be affected and must be dealt with before the room is sold', 'It is not checked', 'Guests ask about it'), 2),
        ),
        'hk-bathroom' => array(
            array('Which is cleaned last in a bathroom?',
                array('The mirror', 'The toilet', 'The basin', 'The shower'), 2),
            array('A cloth used on the toilet may then be used on',
                array('The basin', 'The mirror', 'Nothing else, it is removed from service', 'The bath'), 3),
            array('Contact time for a disinfectant means',
                array('How long it takes to apply', 'The time the surface must stay wet for the product to work', 'How long the bottle lasts', 'The drying time'), 2),
            array('Bathroom amenities are replenished',
                array('Only at departure', 'To the standard set for the room type, at every service', 'When the guest asks', 'Never'), 2),
        ),
        'hk-chemical-safety' => array(
            array('Two cleaning chemicals should never be mixed because',
                array('It wastes product', 'Some combinations, such as bleach and acid cleaners, release toxic gas', 'It changes the colour', 'It is allowed if diluted'), 2),
            array('Dilution rates are taken from',
                array('Experience', 'The manufacturer\'s instructions and the product data sheet', 'The strongest that works', 'The supervisor\'s preference'), 2),
            array('A chemical decanted into a second container must be',
                array('Left unlabelled', 'Labelled with the product name and its hazards', 'Marked only with a colour', 'Used the same day'), 2),
            array('The safety data sheet for a product tells you',
                array('The price', 'The hazards, the protective equipment needed and what to do in an exposure', 'The supplier address only', 'Nothing useful'), 2),
        ),
        'hk-deep-cleaning' => array(
            array('Deep cleaning differs from daily cleaning because it',
                array('Is faster', 'Addresses what daily cleaning cannot reach, on a planned cycle', 'Uses no chemicals', 'Is done by the front desk'), 2),
            array('A room scheduled for deep cleaning should be',
                array('Sold as normal', 'Blocked from sale for the time the work needs', 'Cleaned around the guest', 'Left until it is quiet'), 2),
            array('Deep cleaning is planned on a cycle because',
                array('It is cheaper', 'Condition declines predictably, and planned work is cheaper than replacement', 'Guests request it', 'It is not planned'), 2),
            array('Which is a deep cleaning task rather than a daily one?',
                array('Making the bed', 'Shampooing carpet and cleaning behind and under furniture', 'Emptying the bin', 'Replacing towels'), 2),
        ),
        'hk-inspection' => array(
            array('Room inspection exists to',
                array('Catch staff out', 'Confirm the room meets the standard before it is sold, and find what training is needed', 'Slow the release of rooms', 'Satisfy the guest'), 2),
            array('An inspector finding a repeated fault across several rooms should',
                array('Fix it quietly', 'Record it and raise it as a training or process issue, not just a room issue', 'Ignore it', 'Report the attendant'), 2),
            array('A room failing inspection is',
                array('Sold anyway', 'Returned for correction and re-inspected before release', 'Marked out of order', 'Released with a note'), 2),
            array('Which is checked in an inspection but easily missed in cleaning?',
                array('The bed', 'High and low surfaces, behind doors, and the underside of fittings', 'The floor', 'The towels'), 2),
        ),
        'hk-public-areas' => array(
            array('A wet floor in a public area requires',
                array('No action if it is small', 'A warning sign in place for as long as the floor is wet', 'Closing the area', 'Only a verbal warning'), 2),
            array('Public areas are cleaned on a frequency based on',
                array('Convenience', 'Traffic and visibility, with high-touch points done most often', 'Cost', 'Guest complaints only'), 2),
            array('High-touch points in a lobby include',
                array('The ceiling', 'Door handles, lift buttons, handrails and counter edges', 'The carpet centre', 'Artwork'), 2),
            array('Cleaning a public area during peak hours should',
                array('Proceed as normal', 'Be limited to what can be done without obstructing guests, with the rest rescheduled', 'Be skipped entirely', 'Close the area'), 2),
        ),
        'hk-turnaround' => array(
            array('Room turnaround time is measured from',
                array('The guest\'s departure to the room being sellable again', 'Check-in to checkout', 'The start to the end of a shift', 'The booking to the arrival'), 1),
            array('The biggest cause of slow turnaround on a busy departure day is usually',
                array('Slow attendants', 'Rooms not being reported as vacant promptly, so cleaning starts late', 'Too much linen', 'Guests checking out early'), 2),
            array('Priority rooms in the turnaround queue are',
                array('The nearest to the linen room', 'Those with a confirmed early arrival or a guest waiting', 'The largest rooms', 'The cheapest rooms'), 2),
            array('Rushing a turnaround typically costs the hotel more because',
                array('It uses more chemicals', 'A room released below standard generates a complaint, a move and a refund', 'It does not cost more', 'Staff work overtime'), 2),
        ),
        'hk-productivity' => array(
            array('A trolley is stocked before the shift so that',
                array('It looks tidy', 'The attendant does not lose time returning to the store mid-room', 'It is easier to push', 'The supervisor can check it'), 2),
            array('Productivity in housekeeping is measured against',
                array('Rooms per hour alone', 'Rooms cleaned to standard per hour, since a fast room that fails inspection is not done', 'Chemicals used', 'Hours worked'), 2),
            array('Which change most reliably improves productivity?',
                array('Working faster', 'Removing interruptions and having the right supplies to hand', 'Shorter breaks', 'More staff'), 2),
            array('A room attendant consistently over time should first be',
                array('Disciplined', 'Observed, to find whether the cause is method, supplies or the rooms assigned', 'Reassigned', 'Given fewer rooms'), 2),
        ),
        'hk-lost-found' => array(
            array('An item found in a departed room must be',
                array('Kept by the finder', 'Logged with the room, date and finder, and stored securely', 'Left in the room', 'Thrown away'), 2),
            array('A guest calls about an item left behind. The correct step is',
                array('Say nothing was found', 'Check the log, and arrange return at the guest\'s cost if it is there', 'Post it immediately without checking', 'Ask them to return'), 2),
            array('High-value items such as passports and jewellery should be',
                array('Stored with everything else', 'Stored in the safe and reported to the duty manager the same day', 'Returned to the room', 'Held by the attendant'), 2),
            array('Unclaimed items are disposed of',
                array('Immediately', 'After the retention period set by hotel policy, with the disposal recorded', 'Never', 'By the finder'), 2),
        ),
        'hk-laundry' => array(
            array('Clean and soiled linen must be',
                array('Transported together to save time', 'Kept separate at every stage, including transport and storage', 'Stored in the same room', 'Sorted by the guest'), 2),
            array('Linen stained with blood or bodily fluid is',
                array('Washed with the normal load', 'Handled as infectious, bagged separately and washed to the required temperature', 'Discarded', 'Soaked in the room'), 2),
            array('Par stock for linen means',
                array('The cheapest supplier', 'The quantity needed to keep every bed supplied while other sets are in circulation', 'The stock in the laundry', 'One set per bed'), 2),
            array('Overloading a washing machine results in',
                array('Faster cycles', 'Linen that is not properly cleaned or rinsed, and more rewashing', 'Lower cost', 'No effect'), 2),
        ),
        );
    }

    private function food_and_beverage() {
        return array(
        'fb-restaurant-service' => array(
            array('From which side is a plated dish normally served?',
                array('The guest\'s left, and cleared from the right', 'The guest\'s right always', 'Whichever is convenient', 'Over the guest\'s shoulder'), 1),
            array('A guest at the table has not received their dish while others are eating. The server should',
                array('Say nothing', 'Acknowledge it at once, check with the kitchen and give the guest a time', 'Offer a free dessert', 'Remove the other plates'), 2),
            array('Plates are cleared when',
                array('The first guest finishes', 'Everyone at the table has finished', 'The kitchen asks', 'After thirty minutes'), 2),
            array('Carrying a tray, the server should',
                array('Hold it at chest height across the body', 'Balance it on the flat palm and forearm, away from the body, loaded heaviest in the centre', 'Carry it with both hands in front', 'Rest it on the hip'), 2),
        ),
        'fb-table-service' => array(
            array('In American style service, the food is',
                array('Carved at the table', 'Plated in the kitchen and brought to the guest', 'Served from a platter to the guest\'s plate', 'Placed in the centre to share'), 2),
            array('Silver service differs in that the server',
                array('Plates in the kitchen', 'Transfers food from a platter to the guest\'s plate at the table', 'Leaves the platter with the guest', 'Does not serve at all'), 2),
            array('Cutlery is laid',
                array('In any order', 'From the outside in, in the order the courses will be eaten', 'All on the right', 'After the guest sits'), 2),
            array('The cover is checked before service to confirm',
                array('The bill is ready', 'Everything is clean, matched, correctly spaced and free of marks', 'The guest has arrived', 'The menu is printed'), 2),
        ),
        'fb-guest-greeting' => array(
            array('A guest arriving without a reservation at a full restaurant should be',
                array('Turned away', 'Given a realistic wait time and the option to wait or book another time', 'Seated at a reserved table', 'Asked to come back'), 2),
            array('Within how long should an arriving guest be acknowledged?',
                array('Thirty seconds, even if the host cannot seat them yet', 'Five minutes', 'When a table is free', 'It does not matter'), 1),
            array('Seating a guest includes',
                array('Pointing to a table', 'Escorting them, presenting the menu and telling them who will serve them', 'Nothing more than showing the table', 'Taking the order'), 2),
            array('A guest with a mobility aid should be seated',
                array('Wherever is free', 'Where they can reach the table without obstruction, asked rather than assumed', 'Near the door always', 'At the back'), 2),
        ),
        'fb-beverage' => array(
            array('Beverages are served',
                array('Before the guest orders', 'From the guest\'s right, without reaching across', 'From the left always', 'By placing the tray on the table'), 2),
            array('A guest orders an alcoholic drink in a venue that does not serve alcohol. The server should',
                array('Argue', 'Explain politely that it is not served and offer the alternatives available', 'Ignore the request', 'Send them elsewhere'), 2),
            array('Glassware is handled',
                array('By the rim', 'By the stem or the base, never the rim', 'With a cloth over the top', 'However is fastest'), 2),
            array('A drink is checked before it leaves the bar for',
                array('Price', 'Correct glass, correct garnish, correct level and a clean exterior', 'Temperature only', 'Nothing'), 2),
        ),
        'fb-banquet' => array(
            array('The banquet event order exists to',
                array('Price the event', 'Tell every department exactly what is required, when and where', 'Record complaints', 'Book the room'), 2),
            array('A last-minute increase in guest numbers should be',
                array('Refused', 'Confirmed in writing and communicated to kitchen, service and stewarding at once', 'Handled on the day', 'Accepted verbally only'), 2),
            array('In buffet service, food safety depends most on',
                array('Presentation', 'Holding temperature and the time food has been on display', 'The number of dishes', 'Staff numbers'), 2),
            array('Room set-up should be completed',
                array('As guests arrive', 'Before the agreed time, allowing for a final check', 'Whenever the room is free', 'By the client'), 2),
        ),
        'fb-food-safety' => array(
            array('Hot food held for service must be kept at or above',
                array('50°C', '60°C', '45°C', '37°C'), 2),
            array('A server notices a dish has been on the pass for twenty minutes. They should',
                array('Serve it quickly', 'Not serve it, and tell the kitchen so it is replaced', 'Reheat it under the lamp', 'Serve it with an apology'), 2),
            array('A guest declares a nut allergy. The server must',
                array('Suggest dishes they think are safe', 'Inform the kitchen, confirm with them, and not guess about any ingredient', 'Say all food is safe', 'Ask the guest to choose carefully'), 2),
            array('Cross-contamination in the service area most often happens through',
                array('The menu', 'Hands, cloths and shared utensils moving between raw and ready-to-eat items', 'The floor', 'The till'), 2),
        ),
        'fb-hygiene' => array(
            array('Hands must be washed',
                array('At the start of the shift only', 'After any task that could contaminate them, and between handling different foods', 'Once an hour', 'Only after the toilet'), 2),
            array('A server with vomiting or diarrhoea must',
                array('Work with gloves', 'Report it and stay away from food handling until clear for the required period', 'Work away from the kitchen', 'Take medication and continue'), 2),
            array('A cut on the hand must be',
                array('Left uncovered', 'Covered with a coloured waterproof dressing, and a glove worn over it', 'Covered with any plaster', 'Reason to go home'), 2),
            array('Jewellery is restricted in food areas because',
                array('It looks unprofessional', 'It harbours bacteria and can fall into food', 'It is expensive', 'It is not restricted'), 2),
        ),
        'fb-haccp' => array(
            array('HACCP stands for',
                array('Hotel and Catering Cleaning Procedure', 'Hazard Analysis and Critical Control Points', 'Health and Catering Control Plan', 'Hygiene Assessment of Cooking and Chilling Practice'), 2),
            array('A critical control point is',
                array('Any step in the process', 'A step where control is essential to prevent or eliminate a hazard', 'The final inspection', 'The delivery point'), 2),
            array('A critical limit is',
                array('The maximum number of guests', 'The measurable boundary, such as a temperature, that separates safe from unsafe', 'The budget', 'The shelf life'), 2),
            array('When monitoring shows a critical limit has been breached,',
                array('Note it and continue', 'Take the corrective action set out in the plan and record what was done', 'Discard the record', 'Inform the guest'), 2),
        ),
        'fb-pos' => array(
            array('An order entered incorrectly into the point of sale should be',
                array('Left and corrected on the bill', 'Voided following the authorisation rule, with the reason recorded', 'Deleted quietly', 'Ignored if small'), 2),
            array('Voids and discounts are authorised because',
                array('It slows service', 'They are the most common route for revenue loss and must be traceable', 'The system requires it', 'Guests expect it'), 2),
            array('Splitting a bill should be offered',
                array('Never', 'When the table asks, and handled before payment begins', 'Only for large groups', 'After payment'), 2),
            array('The till is reconciled at the end of a shift to',
                array('Count staff', 'Match takings against recorded sales and find differences while they can still be traced', 'Set prices', 'Order stock'), 2),
        ),
        'fb-upselling' => array(
            array('An effective suggestion at the table is',
                array('The most expensive item', 'A specific item that fits what the guest has already chosen', 'Everything on the menu', 'A discount'), 2),
            array('Order taking should begin with',
                array('The nearest guest', 'A logical order the table can follow, noting seat positions so dishes reach the right person', 'Whoever speaks first', 'The host only'), 2),
            array('Repeating the order back to the table',
                array('Wastes time', 'Catches errors before they reach the kitchen', 'Is only for large tables', 'Is unnecessary with a handheld device'), 2),
            array('Suggesting a dessert works best',
                array('With the main course order', 'When the main plates are cleared and the guest is deciding whether to stay', 'At arrival', 'With the bill'), 2),
        ),
        );
    }

    private function kitchen() {
        return array(
        'kit-fundamentals' => array(
            array('Mise en place means',
                array('Cleaning down', 'Everything prepared and in position before service begins', 'The menu order', 'The kitchen brigade'), 2),
            array('The brigade system exists to',
                array('Create hierarchy', 'Divide the kitchen into sections with clear responsibility so service flows', 'Reduce staff', 'Set pay grades'), 2),
            array('A recipe specification is followed exactly because',
                array('The chef says so', 'It controls cost, portion and consistency, which the guest and the margin both depend on', 'It is faster', 'It is not followed exactly'), 2),
            array('The pass is where',
                array('Deliveries arrive', 'Finished dishes are checked before they leave the kitchen', 'Waste is sorted', 'Staff eat'), 2),
        ),
        'kit-food-safety' => array(
            array('The temperature danger zone is',
                array('0°C to 4°C', '5°C to 63°C', '63°C to 100°C', 'Below 0°C'), 2),
            array('Cooked food to be cooled must pass through the danger zone',
                array('Slowly, at room temperature', 'As quickly as possible, within the time the standard allows', 'Overnight', 'It does not matter'), 2),
            array('Raw meat is stored',
                array('Above ready-to-eat food', 'Below ready-to-eat food, to prevent drips contaminating it', 'Anywhere in the fridge', 'At room temperature'), 2),
            array('Reheated food must reach a core temperature of at least',
                array('63°C', '75°C', '50°C', '100°C'), 2),
        ),
        'kit-temperature' => array(
            array('A fridge should run at',
                array('0°C to 5°C', '8°C to 12°C', '−18°C', '10°C'), 1),
            array('A freezer should run at or below',
                array('0°C', '−18°C', '−5°C', '4°C'), 2),
            array('Temperature checks are recorded because',
                array('It is a habit', 'The record is the evidence that control was maintained, and shows trends before a failure', 'The supplier asks', 'They are not recorded'), 2),
            array('A probe thermometer is sanitised',
                array('Once a day', 'Before and after every use, and between different foods', 'Weekly', 'Never'), 2),
        ),
        'kit-storage' => array(
            array('FIFO means',
                array('Fresh In, Frozen Out', 'First In, First Out, so older stock is used first', 'Food Inspection For Operations', 'Fast In, Fast Out'), 2),
            array('Dry goods are stored',
                array('On the floor', 'Off the floor on shelving, in sealed containers, away from damp', 'In the walkway', 'Next to chemicals'), 2),
            array('An opened product must be',
                array('Used the same day', 'Labelled with the date it was opened and its use-by date', 'Returned to the supplier', 'Left as delivered'), 2),
            array('Chemicals are stored',
                array('With the food', 'In a separate, marked area away from all food', 'Above the preparation surface', 'In the fridge'), 2),
        ),
        'kit-hygiene' => array(
            array('A chef changes their apron',
                array('Once a week', 'Whenever it is soiled, and between raw and ready-to-eat work', 'At the end of the shift', 'Never'), 2),
            array('Colour-coded boards are used so that',
                array('They look organised', 'Raw and ready-to-eat foods never share a preparation surface', 'They are easier to replace', 'Chefs can find them'), 2),
            array('Hand contact with ready-to-eat food should be',
                array('Normal practice', 'Minimised by using tongs, utensils or single-use gloves', 'Avoided by washing hands only', 'Unrestricted with gloves'), 2),
            array('A damaged chopping board must be',
                array('Cleaned more often', 'Taken out of service, because cuts and cracks hold bacteria that cannot be cleaned out', 'Turned over', 'Sanded down'), 2),
        ),
        'kit-cleaning' => array(
            array('A cleaning schedule sets out',
                array('Who is on shift', 'What is cleaned, how, how often, with what, and by whom', 'The menu', 'Delivery times'), 2),
            array('Clean as you go matters because',
                array('It looks better', 'It stops contamination building up and keeps the workspace safe during service', 'It saves chemicals', 'It is not required'), 2),
            array('Equipment is dismantled for cleaning when',
                array('It is broken', 'The manufacturer\'s instructions require it to reach food contact surfaces', 'Once a year', 'Never'), 2),
            array('Cleaning is signed off so that',
                array('Staff can be blamed', 'There is a record that the task was done, by whom and when', 'It takes longer', 'The schedule is met'), 2),
        ),
        'kit-allergens' => array(
            array('A guest asks whether a dish contains sesame. The correct response is',
                array('Say you think not', 'Check the recipe specification and allergen record, and answer from that', 'Say all dishes are safe', 'Suggest they avoid it'), 2),
            array('The safest way to prepare an allergen-free dish is',
                array('Remove the ingredient at the end', 'Prepare it separately with clean equipment and clean hands', 'Cook it hotter', 'Serve it first'), 2),
            array('Allergen information must be',
                array('Given only if asked', 'Available and accurate for every dish served', 'Kept in the office', 'Estimated'), 2),
            array('A recipe change affecting allergens must be',
                array('Made quietly', 'Recorded and communicated to service before the dish is sold', 'Made only by the head chef', 'Tested on staff first'), 2),
        ),
        'kit-knife-safety' => array(
            array('A sharp knife is safer than a blunt one because',
                array('It cuts less deeply', 'It needs less force, so it is less likely to slip', 'It is lighter', 'It is not safer'), 2),
            array('A knife should be carried',
                array('Point up', 'Point down, close to the body, blade turned away', 'On a tray', 'In a pocket'), 2),
            array('A falling knife should be',
                array('Caught', 'Allowed to fall, with feet moved clear', 'Kicked aside', 'Caught by the handle'), 2),
            array('Knives are cleaned',
                array('In the dishwasher', 'By hand, immediately, and never left in a sink of water', 'At the end of service', 'With the pans'), 2),
        ),
        'kit-waste' => array(
            array('Food waste is separated because',
                array('It is required by the landlord', 'It can be measured and reduced, and it must be disposed of correctly', 'It smells', 'It is not separated'), 2),
            array('The largest avoidable source of kitchen waste is usually',
                array('Trimmings', 'Over-production and spoilage from poor stock rotation', 'Packaging', 'Guest plates'), 2),
            array('Waste oil must be',
                array('Poured down the drain', 'Collected and removed by an approved contractor', 'Mixed with food waste', 'Reused indefinitely'), 2),
            array('Recording waste is useful because',
                array('It satisfies the auditor', 'It shows where product and money are actually being lost, so it can be fixed', 'It is not useful', 'It reduces cost directly'), 2),
        ),
        'kit-receiving' => array(
            array('A chilled delivery should be checked for temperature',
                array('After it is put away', 'On arrival, before it is accepted', 'The next day', 'Only if it looks warm'), 2),
            array('A delivery that fails the check should be',
                array('Accepted and used quickly', 'Rejected and recorded, with the supplier informed', 'Accepted and frozen', 'Accepted at a discount'), 2),
            array('Goods are checked against',
                array('Memory', 'The purchase order and the delivery note, for quantity, quality and price', 'The invoice only', 'Nothing'), 2),
            array('Damaged packaging matters because',
                array('It looks poor', 'The contents may be contaminated and the seal can no longer be relied on', 'It is harder to store', 'It does not matter'), 2),
        ),
        );
    }

    private function engineering() {
        return array(
        'eng-fundamentals' => array(
            array('Engineering\'s main contribution to revenue is',
                array('Reducing the electricity bill', 'Keeping rooms sellable, because an out-of-order room earns nothing', 'Buying equipment cheaply', 'Staffing levels'), 2),
            array('A fault reported by housekeeping should be',
                array('Fixed when convenient', 'Logged as a work order, prioritised and tracked to completion', 'Reported to the guest', 'Fixed without record'), 2),
            array('Planned maintenance is preferred to reactive repair because',
                array('It is more interesting', 'It is cheaper, and it fails at a time you choose rather than during a full house', 'It uses fewer parts', 'It is required by law'), 2),
            array('Which record tells you whether a recurring fault is really fixed?',
                array('The invoice', 'The work order history for that asset', 'The guest comment', 'The duty log'), 2),
        ),
        'eng-fire-safety' => array(
            array('On discovering a fire, the first action is',
                array('Fight the fire', 'Raise the alarm', 'Open windows to clear smoke', 'Find the fire marshal'), 2),
            array('A fire door must never be',
                array('Closed', 'Wedged or propped open', 'Signed', 'Painted'), 2),
            array('A CO2 extinguisher is used on',
                array('Cooking oil fires', 'Electrical fires', 'Paper and wood', 'Metal fires'), 2),
            array('The assembly point is where',
                array('Staff wait for instructions to return', 'Everyone is accounted for after evacuation', 'The fire panel is', 'Guests collect belongings'), 2),
        ),
        'eng-electrical' => array(
            array('Work on live electrical equipment is',
                array('Normal for small jobs', 'Done only by a competent person, with the circuit isolated wherever possible', 'Allowed with gloves', 'Done by any technician'), 2),
            array('Lock-out tag-out exists to',
                array('Record who did the work', 'Make sure isolated equipment cannot be re-energised while someone is working on it', 'Prevent theft', 'Satisfy the insurer'), 2),
            array('A damaged power cable in a guest room should be',
                array('Taped up', 'Taken out of service immediately and the item replaced or repaired', 'Left if it still works', 'Reported next week'), 2),
            array('Portable appliance testing is done to',
                array('Extend warranty', 'Confirm equipment is still electrically safe to use, on a set frequency', 'Increase efficiency', 'Track assets'), 2),
        ),
        'eng-hvac' => array(
            array('A guest reports the room will not cool. The first check is',
                array('Replace the unit', 'The set point, the filter and whether a window or balcony door is open', 'The chiller plant', 'The thermostat wiring'), 2),
            array('Dirty air filters cause',
                array('Better filtration', 'Reduced airflow, higher energy use and poorer cooling', 'No change', 'Lower running cost'), 2),
            array('Legionella risk in a building system is managed mainly by',
                array('Cleaning the ducts', 'Controlling water temperature and avoiding stagnation', 'Changing filters', 'Running the system harder'), 2),
            array('Condensate drains are checked because',
                array('They are noisy', 'A blocked drain causes water damage to ceilings and rooms below', 'They affect temperature', 'They do not need checking'), 2),
        ),
        'eng-plumbing' => array(
            array('The first action on a burst pipe in an occupied floor is',
                array('Call a contractor', 'Isolate the water supply to that section', 'Mop the floor', 'Move the guest'), 2),
            array('A slow draining shower is most often caused by',
                array('Low water pressure', 'A blockage of hair and soap in the trap', 'A faulty valve', 'Air in the system'), 2),
            array('Backflow prevention protects',
                array('The drains', 'The drinking water supply from contamination', 'The boiler', 'The pump'), 2),
            array('Hot water delivered to a guest outlet must be',
                array('As hot as the system allows', 'Controlled to prevent scalding, while stored hot enough to control bacteria', 'Below 40°C in storage', 'Unregulated'), 2),
        ),
        'eng-preventive' => array(
            array('Preventive maintenance is scheduled by',
                array('When something breaks', 'Time or usage intervals set for each asset', 'Guest complaints', 'Budget availability'), 2),
            array('The cost of preventive maintenance is justified by',
                array('Longer asset life and fewer out-of-order rooms', 'A lower headcount', 'Cheaper parts', 'Insurance discounts'), 1),
            array('A preventive task that is repeatedly skipped should be',
                array('Removed from the schedule', 'Investigated, since either the interval is wrong or the resource is not there', 'Done twice next time', 'Ignored'), 2),
            array('Asset history is kept so that',
                array('The auditor is satisfied', 'Replace-or-repair decisions are made on evidence rather than impression', 'Staff can be assessed', 'Warranty is valid'), 2),
        ),
        'eng-work-orders' => array(
            array('A work order should record',
                array('Only the fault', 'The asset, the fault, the priority, who did what and when it was closed', 'The cost only', 'The reporter\'s name'), 2),
            array('Priority on a work order is set by',
                array('Who reported it', 'Impact on guest safety and on sellable rooms', 'Ease of repair', 'Age of the asset'), 2),
            array('A work order is closed when',
                array('The technician leaves', 'The fault is fixed and verified, with the work recorded', 'The part is ordered', 'The shift ends'), 2),
            array('Open work orders are reviewed daily because',
                array('It fills the morning meeting', 'Ageing jobs are the ones that become guest complaints and out-of-order rooms', 'The system requires it', 'They are not reviewed'), 2),
        ),
        'eng-asset-inspection' => array(
            array('An asset inspection checks',
                array('Only whether it runs', 'Condition, safety, performance against its standard and what needs planning', 'The purchase price', 'The warranty'), 2),
            array('A defect found during inspection is',
                array('Fixed on the spot if possible, otherwise raised as a work order', 'Noted for the annual review', 'Reported verbally', 'Ignored if minor'), 1),
            array('Inspection frequency is based on',
                array('Convenience', 'Criticality, usage and manufacturer guidance', 'Age alone', 'Budget'), 2),
            array('Photographs on an inspection record help because',
                array('They look professional', 'They show condition at a point in time, which makes deterioration visible', 'They are required', 'They speed up the inspection'), 2),
        ),
        'eng-emergency' => array(
            array('In a power failure, the first priority is',
                array('Restoring the lifts', 'Life safety systems and emergency lighting, and accounting for anyone trapped', 'Restarting the kitchen', 'Informing guests'), 2),
            array('A guest trapped in a lift should be',
                array('Told to wait quietly', 'Kept in contact and reassured while trained release is arranged', 'Released by any available staff member', 'Left until the engineer arrives'), 2),
            array('Emergency contact lists are checked regularly because',
                array('Staff change and an out-of-date number costs time in the one moment it matters', 'It is an audit point', 'The list is long', 'They are not checked'), 1),
            array('After any emergency, the hotel should',
                array('Return to normal quietly', 'Review what happened, record it and change what did not work', 'Report only if a guest was hurt', 'Wait for the insurer'), 2),
        ),
        );
    }

    private function commercial_and_management() {
        return array(
        'mgt-hotel-management' => array(
            array('A hotel general manager\'s first responsibility is',
                array('Occupancy', 'The safety of guests and staff', 'Profit', 'Guest satisfaction scores'), 2),
            array('Departments conflict most often over',
                array('Budget alone', 'Room readiness, where housekeeping, engineering and front office share one deadline', 'Staffing', 'Menus'), 2),
            array('A daily operations meeting exists to',
                array('Review the previous year', 'Align departments on today\'s arrivals, events, issues and constraints', 'Set strategy', 'Discuss payroll'), 2),
            array('Standard operating procedures matter most when',
                array('The hotel is quiet', 'The hotel is busy or short staffed, and judgement alone will not hold the standard', 'An auditor visits', 'New staff join'), 2),
        ),
        'mgt-leadership' => array(
            array('A supervisor who only corrects mistakes will usually',
                array('Raise standards fastest', 'Lose the team\'s willingness to raise problems early', 'Be respected', 'Reduce turnover'), 2),
            array('Delegation means',
                array('Giving away the difficult work', 'Assigning responsibility with the authority and information to carry it out', 'Avoiding accountability', 'Reducing your workload'), 2),
            array('Feedback is most effective when it is',
                array('Given in the annual review', 'Specific, timely and about the work rather than the person', 'Given publicly', 'Written only'), 2),
            array('High turnover in a hospitality team is most often driven by',
                array('Pay alone', 'The immediate supervisor and the daily working conditions', 'Guest behaviour', 'Shift length'), 2),
        ),
        'mgt-team-management' => array(
            array('A rota should be built around',
                array('Staff preference alone', 'Forecast demand, with skill mix covered on every shift', 'Equal hours for everyone', 'Seniority'), 2),
            array('A new starter\'s first week should include',
                array('Full independent shifts', 'Safety, the standards they will be held to, and supervised practice', 'Only paperwork', 'Whatever the shift allows'), 2),
            array('Performance problems should be addressed',
                array('At the annual review', 'Early and directly, with clear expectations and support', 'By reassignment', 'By the HR department only'), 2),
            array('Cross-training helps the operation because',
                array('It reduces pay', 'It covers absence and peaks without adding headcount', 'It simplifies the rota', 'It reduces training cost'), 2),
        ),
        'mgt-quality' => array(
            array('A quality standard is useful only if',
                array('It is written down', 'It is measurable, and someone actually checks against it', 'It is ambitious', 'It matches competitors'), 2),
            array('Root cause analysis asks',
                array('Who was responsible', 'Why the failure was possible, repeatedly, until the underlying cause is reached', 'How much it cost', 'When it happened'), 2),
            array('A mystery guest audit is most valuable when',
                array('The score is high', 'The findings are acted on and re-checked', 'It is announced', 'It is frequent'), 2),
            array('Recurring complaints about the same issue indicate',
                array('Difficult guests', 'A process problem rather than an individual one', 'Bad luck', 'A training need only'), 2),
        ),
        'mgt-guest-experience' => array(
            array('The guest experience is shaped most by',
                array('The building', 'The moments where something goes wrong and how they are handled', 'The rate', 'The location'), 2),
            array('Service recovery done well often results in',
                array('A worse impression than if nothing had gone wrong', 'Loyalty higher than if nothing had gone wrong', 'No change', 'A refund request'), 2),
            array('Guest feedback is most useful when',
                array('It is positive', 'It is specific enough to act on and is routed to the team who can act', 'It is anonymous', 'It is public'), 2),
            array('A guest journey map is used to',
                array('Plan the building layout', 'Find the points where the guest\'s experience is decided, and design those', 'Track room moves', 'Schedule staff'), 2),
        ),
        'mgt-kpis' => array(
            array('RevPAR is',
                array('Revenue per available room', 'Revenue per arriving reservation', 'Rate per available room', 'Rooms per available rate'), 1),
            array('ADR measures',
                array('Total revenue divided by rooms available', 'Room revenue divided by rooms sold', 'Occupancy times rate', 'Revenue per guest'), 2),
            array('A hotel with high occupancy and falling RevPAR is likely',
                array('Performing well', 'Discounting too heavily to fill rooms', 'Losing market share', 'Understaffed'), 2),
            array('GOPPAR is more useful than RevPAR because it',
                array('Is easier to calculate', 'Accounts for the cost of earning the revenue, not just the revenue', 'Excludes departments', 'Is reported daily'), 2),
        ),
        'mgt-crisis' => array(
            array('The first minutes of a crisis should be spent',
                array('Drafting a statement', 'Making people safe and establishing who is in charge', 'Informing the owner', 'Investigating the cause'), 2),
            array('A single spokesperson is nominated so that',
                array('Others can avoid responsibility', 'The hotel speaks with one accurate voice', 'It is faster', 'It is legally required'), 2),
            array('A crisis plan is tested because',
                array('Regulators require it', 'An untested plan fails at the point of use, and the gaps are only visible in rehearsal', 'It reassures staff', 'It is cheap'), 2),
            array('After a crisis, guests and staff should receive',
                array('No further contact', 'Follow-up and, where needed, support, since the effect outlasts the event', 'A discount', 'A survey'), 2),
        ),
        'mgt-finance' => array(
            array('In the uniform system of accounts, departmental profit is',
                array('Revenue less all hotel costs', 'Departmental revenue less the direct costs of that department', 'Revenue less payroll', 'Gross operating profit'), 2),
            array('A flow-through analysis shows',
                array('Cash movement', 'How much of a change in revenue reaches profit', 'Guest numbers', 'Debt cover'), 2),
            array('Fixed costs in a hotel',
                array('Vary with occupancy', 'Continue whether or not rooms are sold', 'Are only payroll', 'Are avoidable'), 2),
            array('A budget variance should be explained by',
                array('The finance team alone', 'The department head who owns the line, with the reason and the action', 'The auditor', 'Nobody, if it is small'), 2),
        ),
        'mgt-cost-control' => array(
            array('Cost control means',
                array('Spending less on everything', 'Spending to a standard, and finding where spend does not produce value', 'Cutting payroll', 'Buying the cheapest option'), 2),
            array('Payroll is best controlled by',
                array('Cutting hours across the board', 'Matching rostered hours to forecast demand', 'Reducing pay rates', 'Using agency staff'), 2),
            array('Purchasing through agreed suppliers helps because',
                array('It is faster', 'It fixes specification and price, which makes variance visible', 'It reduces paperwork', 'It is required'), 2),
            array('A stock take that is consistently over should prompt',
                array('A change of supplier', 'A check of recording, portioning and waste before assuming theft', 'Reduced ordering', 'No action'), 2),
        ),
        'mgt-revenue' => array(
            array('Revenue management is the practice of selling',
                array('The most rooms possible', 'The right room to the right guest at the right time and price', 'Rooms at the highest rate', 'Through the most channels'), 2),
            array('Displacement analysis asks',
                array('How many guests moved rooms', 'Whether accepting a group displaces higher-value transient business', 'Which channel performed best', 'How many cancelled'), 2),
            array('A rate parity failure means',
                array('Rates differ between room types', 'The same room is offered at different rates across channels, undermining direct sales', 'The rate is too low', 'Rates changed overnight'), 2),
            array('Forecasting accuracy matters most because',
                array('It satisfies the owner', 'Staffing, purchasing and pricing decisions are all made from it', 'It sets the budget', 'It is reported weekly'), 2),
        ),
        'dig-analytics' => array(
            array('A useful metric is one that',
                array('Is easy to collect', 'Changes a decision', 'Looks good in a report', 'Is tracked by competitors'), 2),
            array('Comparing this month to last month alone is misleading because',
                array('Months differ in length', 'Hotel demand is seasonal, so the right comparison is the same period last year', 'The data is late', 'It is not misleading'), 2),
            array('Pace reporting shows',
                array('How fast the website loads', 'How bookings for a future date are building compared with the same point last year', 'Staff productivity', 'Channel cost'), 2),
            array('A dashboard with fifty metrics usually',
                array('Gives the fullest picture', 'Hides the few numbers that actually drive action', 'Is best practice', 'Is easier to read'), 2),
        ),
        'dig-booking-engine' => array(
            array('The booking engine\'s main commercial purpose is',
                array('Displaying photographs', 'Converting a visitor into a direct booking without commission', 'Managing inventory', 'Collecting reviews'), 2),
            array('The most common cause of booking abandonment is',
                array('Room photographs', 'Unexpected cost or friction appearing late in the flow', 'Too few room types', 'Slow email'), 2),
            array('Mobile conversion matters because',
                array('It is fashionable', 'A large share of hotel searches happen on a phone, and a poor mobile flow loses them', 'Desktop is declining', 'It affects SEO only'), 2),
            array('Rate parity with OTAs should be maintained so that',
                array('OTAs rank the hotel higher', 'The direct channel is never more expensive than the commissioned one', 'The rate is simple', 'It is legally required everywhere'), 2),
        ),
        'dig-channel' => array(
            array('A channel manager exists to',
                array('Choose which OTAs to use', 'Keep rates and availability consistent across every connected channel', 'Negotiate commission', 'Handle guest messages'), 2),
            array('Overbooking most often results from',
                array('Guest error', 'Inventory not syncing between channels in time', 'Rate changes', 'Cancellations'), 2),
            array('Channel mix should be reviewed because',
                array('Contracts expire', 'Each channel has a different cost of acquisition, and the mix decides net revenue', 'OTAs require it', 'It changes rarely'), 2),
            array('Closing a channel at short notice risks',
                array('Nothing', 'Penalties and loss of ranking, so it is a planned decision rather than a reaction', 'Lower rates', 'Higher commission'), 2),
        ),
        'dig-ota' => array(
            array('OTA commission is best understood as',
                array('A marketing cost with a measurable return', 'An unavoidable tax', 'A fixed fee', 'A discount to the guest'), 1),
            array('Content on an OTA listing should be',
                array('Minimal', 'Complete and accurate, because it drives both ranking and guest expectation', 'Copied from competitors', 'Updated annually'), 2),
            array('A poor OTA review should be',
                array('Ignored', 'Answered publicly, factually and without argument', 'Disputed with the OTA', 'Removed'), 2),
            array('The billboard effect describes',
                array('OTA advertising spend', 'Guests finding a hotel on an OTA and then booking direct', 'Roadside signage', 'Rate parity'), 2),
        ),
        'dig-direct-booking' => array(
            array('The strongest reason a guest books direct is usually',
                array('Loyalty points', 'Confidence that the direct channel gives the best price and terms', 'Website design', 'Email offers'), 2),
            array('A direct booking strategy should begin with',
                array('Discounting below the OTA rate', 'Making the direct channel at least as good, then making that visible', 'Closing OTA channels', 'Paid search only'), 2),
            array('Undercutting OTA rates publicly usually',
                array('Increases direct share safely', 'Breaches parity agreements and can cost ranking or the contract', 'Has no downside', 'Is the standard approach'), 2),
            array('Direct booking value is measured by',
                array('Volume alone', 'Net revenue after acquisition cost, compared with the same booking through an OTA', 'Conversion rate', 'Page views'), 2),
        ),
        'dig-marketing' => array(
            array('Hotel marketing spend should be judged on',
                array('Impressions', 'Revenue generated against cost, by channel', 'Follower growth', 'Click volume'), 2),
            array('The most valuable owned channel for a hotel is usually',
                array('Social media', 'The guest email list, because it is direct and costs nothing per send', 'Paid search', 'Display advertising'), 2),
            array('Photography matters commercially because',
                array('It fills the website', 'It is the single biggest driver of whether a listing converts', 'It is cheap', 'It supports SEO'), 2),
            array('Marketing to past guests works because',
                array('They are easy to reach', 'They convert at a far higher rate and cost less to reach than new prospects', 'They expect discounts', 'It is required'), 2),
        ),
        'dig-seo' => array(
            array('For a hotel, the highest-value organic search terms are usually',
                array('Generic terms like "hotel"', 'Location plus intent, such as "hotel near Riyadh airport"', 'Brand terms only', 'Competitor names'), 2),
            array('A Google Business Profile matters because',
                array('It replaces the website', 'It is often the first and sometimes only result a local searcher sees', 'It improves rankings directly', 'It is required'), 2),
            array('Duplicate descriptions copied from an OTA harm the site because',
                array('The OTA objects', 'Search engines have no reason to rank a page that adds nothing new', 'They are too long', 'They do not harm it'), 2),
            array('Page speed affects hotel SEO mainly through',
                array('Keyword ranking alone', 'Users abandoning a slow page, which search engines observe', 'Image quality', 'Server cost'), 2),
        ),
        'dig-reputation' => array(
            array('The most important thing to do with a negative review is',
                array('Dispute it', 'Respond factually, and fix the cause if it is real', 'Ignore it', 'Ask for its removal'), 2),
            array('Review volume matters alongside score because',
                array('It affects commission', 'A high score on very few reviews is not yet evidence', 'It improves rate', 'It does not matter'), 2),
            array('Asking every guest for a review is',
                array('Against policy everywhere', 'Reasonable, provided it is not selective about who is asked', 'Only for happy guests', 'Ineffective'), 2),
            array('A pattern in reviews is more useful than any single review because',
                array('It is easier to read', 'It points at a process that is repeatedly failing', 'It is more recent', 'It affects ranking more'), 2),
        ),
        'dig-technology' => array(
            array('When choosing hotel technology, integration matters because',
                array('It reduces licence cost', 'Systems that cannot exchange data create manual work and errors', 'It is a vendor requirement', 'It speeds up training'), 2),
            array('Guest data held in a hotel system must be',
                array('Shared freely with partners', 'Protected, with access limited to those who need it for their work', 'Deleted monthly', 'Stored locally only'), 2),
            array('The main risk in replacing a core system is',
                array('Cost', 'Data migration and the period where staff know neither system well', 'Vendor support', 'Hardware'), 2),
            array('A technology decision should be led by',
                array('The IT supplier', 'The operational problem it is meant to solve', 'The lowest price', 'What competitors use'), 2),
        ),
        );
    }
}
