<?php
$labels = Ha_readiness::check_labels();
$pol = $edit_policy;
$prules = $pol ? (json_decode($pol['rules_json'], true) ?: array()) + Ha_readiness::default_rules() : Ha_readiness::default_rules();
$prog = $edit_program;
$gr = $prog ? json_decode($prog['rules_json'], true) : array();
$gr = (is_array($gr) ? $gr : array()) + array('tracks' => array(), 'rubrics' => array(), 'assessments' => array(), 'competencies' => array(), 'require_readiness' => 'ready');
$comp = array(); foreach ($gr['competencies'] as $c) { $comp[$c['skill_id']] = $c['level']; }
$asel = array_map(function ($a) { return (int) (is_array($a) ? $a['id'] : $a); }, $gr['assessments']);
?>
<div class="hkp-head"><div><h1><?php echo hkp_e('Readiness & certification rules'); ?></h1><p><?php echo hkp_e('Every rule is data, not code: change what makes someone Ready, and what a certificate requires, without a release.'); ?></p></div>
<div class="hkp-actions"><a class="hkp-btn" href="<?php echo hkp_url('admin/rules/policy'); ?>"><?php echo hkp_e('New policy'); ?></a><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('admin/rules/program'); ?>"><?php echo hkp_e('New programme'); ?></a></div></div>
<div class="hkp-grid hkp-grid--2" style="margin-bottom:1rem">
  <section class="hkp-card"><h2><?php echo hkp_e('Readiness policies'); ?></h2><ul class="hkp-list"><?php foreach ($policies as $p): ?><li><a href="<?php echo hkp_url('admin/rules/policy/' . $p['id']); ?>"><?php echo hkp_h(hkp_pick($p, 'name')); ?></a><span class="hkp-small"><?php echo $p['job_role_id'] ? hkp_e('Role-specific') : hkp_e('Default'); ?></span></li><?php endforeach; ?></ul></section>
  <section class="hkp-card"><h2><?php echo hkp_e('Certification programmes'); ?></h2><ul class="hkp-list"><?php foreach ($programs as $p): ?><li><a href="<?php echo hkp_url('admin/rules/program/' . $p['id']); ?>"><?php echo hkp_h(hkp_pick($p, 'title')); ?></a><span><?php echo hkp_h($p['number_prefix']); ?> <?php echo hkp_badge($p['status']); ?></span></li><?php endforeach; ?></ul></section>
</div>
<?php if ($new === 'policy'): ?>
<form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('admin/rules/policy_save/' . ($pol ? $pol['id'] : 0)); ?>"><?php echo ha_csrf_field(); ?><h2><?php echo $pol ? hkp_h(hkp_pick($pol, 'name')) : hkp_e('New readiness policy'); ?></h2>
  <div class="hkp-row"><div class="hkp-field"><label for="pn"><?php echo hkp_e('Name (English)'); ?></label><input id="pn" class="hkp-input" name="name_en" value="<?php echo hkp_h($pol ? $pol['name_en'] : ''); ?>" required></div>
    <div class="hkp-field"><label for="pna"><?php echo hkp_e('Name (Arabic)'); ?></label><input id="pna" class="hkp-input" dir="rtl" name="name_ar" value="<?php echo hkp_h($pol ? $pol['name_ar'] : ''); ?>"></div>
    <div class="hkp-field"><label for="pr"><?php echo hkp_e('Role'); ?></label><select id="pr" class="hkp-select" name="job_role_id"><option value=""><?php echo hkp_e('Any role (default)'); ?></option><?php foreach ($roles as $r): ?><option value="<?php echo (int) $r['id']; ?>"<?php echo $pol && (int) $pol['job_role_id'] === (int) $r['id'] ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($r, 'title')); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="pp"><?php echo hkp_e('Property (optional)'); ?></label><select id="pp" class="hkp-select" name="property_id"><option value=""></option><?php foreach ($props as $p): ?><option value="<?php echo (int) $p['id']; ?>"<?php echo $pol && (int) $pol['property_id'] === (int) $p['id'] ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($p, 'name')); ?></option><?php endforeach; ?></select></div></div>
  <div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Check'); ?></th><th><?php echo hkp_e('Enabled'); ?></th><th><?php echo hkp_e('If it fails'); ?></th><th><?php echo hkp_e('Threshold'); ?></th></tr></thead><tbody>
  <?php foreach ($prules as $k => $r): if (!isset($labels[$k])) continue; ?><tr><td><strong><?php echo hkp_e($labels[$k]); ?></strong></td><td><input type="checkbox" name="r[<?php echo $k; ?>][enabled]" value="1"<?php echo !empty($r['enabled']) ? ' checked' : ''; ?> aria-label="<?php echo hkp_e('Enabled'); ?>"></td>
    <td><select class="hkp-select" name="r[<?php echo $k; ?>][on_fail]" aria-label="<?php echo hkp_e('If it fails'); ?>"><option value="not_ready"<?php echo $r['on_fail'] === 'not_ready' ? ' selected' : ''; ?>><?php echo hkp_e('Not ready'); ?></option><option value="conditional"<?php echo $r['on_fail'] === 'conditional' ? ' selected' : ''; ?>><?php echo hkp_e('Conditional'); ?></option></select></td>
    <td><?php if (isset($r['min_pct'])): ?><input class="hkp-input" style="max-width:90px" type="number" name="r[<?php echo $k; ?>][min_pct]" value="<?php echo (float) $r['min_pct']; ?>" aria-label="<?php echo hkp_e('Minimum %'); ?>"> %<?php elseif (isset($r['max'])): ?><?php echo hkp_e('allowed'); ?> <input class="hkp-input" style="max-width:70px" type="number" name="r[<?php echo $k; ?>][max]" value="<?php echo (int) $r['max']; ?>" aria-label="<?php echo hkp_e('Allowed'); ?>"><?php endif; ?></td></tr><?php endforeach; ?>
  </tbody></table></div><div><button class="hkp-btn"><?php echo hkp_e('Save policy'); ?></button></div></form>
<?php elseif ($new === 'program'): ?>
<form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('admin/rules/program_save/' . ($prog ? $prog['id'] : 0)); ?>"><?php echo ha_csrf_field(); ?><h2><?php echo $prog ? hkp_h(hkp_pick($prog, 'title')) : hkp_e('New certification programme'); ?></h2>
  <div class="hkp-row"><div class="hkp-field"><label for="gt"><?php echo hkp_e('Title (English)'); ?></label><input id="gt" class="hkp-input" name="title_en" required value="<?php echo hkp_h($prog ? $prog['title_en'] : ''); ?>"></div>
    <div class="hkp-field"><label for="gta"><?php echo hkp_e('Title (Arabic)'); ?></label><input id="gta" class="hkp-input" dir="rtl" name="title_ar" value="<?php echo hkp_h($prog ? $prog['title_ar'] : ''); ?>"></div>
    <div class="hkp-field"><label for="gp"><?php echo hkp_e('Number prefix'); ?></label><input id="gp" class="hkp-input" name="number_prefix" value="<?php echo hkp_h($prog ? $prog['number_prefix'] : 'ALTUS'); ?>"></div>
    <div class="hkp-field"><label for="gv"><?php echo hkp_e('Valid for (months, 0 = no expiry)'); ?></label><input id="gv" class="hkp-input" type="number" name="validity_months" value="<?php echo $prog ? (int) $prog['validity_months'] : 24; ?>"></div></div>
  <div class="hkp-row"><div class="hkp-field"><label for="gr"><?php echo hkp_e('For role (auto-issue)'); ?></label><select id="gr" class="hkp-select" name="job_role_id"><option value=""></option><?php foreach ($roles as $r): ?><option value="<?php echo (int) $r['id']; ?>"<?php echo $prog && (int) $prog['job_role_id'] === (int) $r['id'] ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($r, 'title')); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="gd"><?php echo hkp_e('Domain'); ?></label><select id="gd" class="hkp-select" name="domain_id"><option value=""></option><?php foreach ($domains as $d): ?><option value="<?php echo (int) $d['id']; ?>"<?php echo $prog && (int) $prog['domain_id'] === (int) $d['id'] ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($d, 'name')); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="gi"><?php echo hkp_e('Issuing authority'); ?></label><input id="gi" class="hkp-input" name="issuing_authority_en" value="<?php echo hkp_h($prog ? $prog['issuing_authority_en'] : 'Altus Advisory'); ?>"></div>
    <div class="hkp-field"><label for="gs"><?php echo hkp_e('Status'); ?></label><select id="gs" class="hkp-select" name="status"><?php foreach (array('draft', 'published', 'archived') as $s): ?><option value="<?php echo $s; ?>"<?php echo $prog && $prog['status'] === $s ? ' selected' : ''; ?>><?php echo hkp_label($s); ?></option><?php endforeach; ?></select></div></div>
  <div class="hkp-grid hkp-grid--3">
    <div class="hkp-field"><label for="gtr"><?php echo hkp_e('Tracks to complete'); ?></label><select id="gtr" class="hkp-select" name="tracks[]" multiple size="7"><?php foreach ($tracks as $t): ?><option value="<?php echo (int) $t['id']; ?>"<?php echo in_array((int) $t['id'], array_map('intval', $gr['tracks']), true) ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($t, 'title')); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="gas"><?php echo hkp_e('Assessments to pass'); ?></label><select id="gas" class="hkp-select" name="assessments[]" multiple size="7"><?php foreach ($assessments as $a): ?><option value="<?php echo (int) $a['id']; ?>"<?php echo in_array((int) $a['id'], $asel, true) ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($a, 'title')); ?></option><?php endforeach; ?></select><input class="hkp-input" type="number" name="min_score" placeholder="<?php echo hkp_e('Minimum score (optional)'); ?>" aria-label="<?php echo hkp_e('Minimum score'); ?>"></div>
    <div class="hkp-field"><label for="gru"><?php echo hkp_e('Practical rubrics to pass'); ?></label><select id="gru" class="hkp-select" name="rubrics[]" multiple size="7"><?php foreach ($rubrics as $r): ?><option value="<?php echo (int) $r['id']; ?>"<?php echo in_array((int) $r['id'], array_map('intval', $gr['rubrics']), true) ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($r, 'title')); ?></option><?php endforeach; ?></select></div></div>
  <h3><?php echo hkp_e('Competency levels required'); ?></h3><div class="hkp-grid hkp-grid--3"><?php foreach ($skills as $s): ?><div class="hkp-actions" style="justify-content:space-between"><span class="hkp-small"><?php echo hkp_h(hkp_pick($s, 'name')); ?></span><select class="hkp-select" style="max-width:80px" name="comp[<?php echo (int) $s['id']; ?>]" aria-label="<?php echo hkp_h(hkp_pick($s, 'name')); ?>"><option value="0">—</option><?php for ($l = 1; $l <= 5; $l++): ?><option value="<?php echo $l; ?>"<?php echo isset($comp[$s['id']]) && (int) $comp[$s['id']] === $l ? ' selected' : ''; ?>><?php echo $l; ?></option><?php endfor; ?></select></div><?php endforeach; ?></div>
  <div class="hkp-field"><label for="grr"><?php echo hkp_e('Readiness required'); ?></label><select id="grr" class="hkp-select" name="require_readiness" style="max-width:260px"><option value=""><?php echo hkp_e('Not required'); ?></option><option value="ready"<?php echo $gr['require_readiness'] === 'ready' ? ' selected' : ''; ?>><?php echo hkp_e('Ready'); ?></option><option value="conditional"<?php echo $gr['require_readiness'] === 'conditional' ? ' selected' : ''; ?>><?php echo hkp_e('Ready or conditional'); ?></option></select></div>
  <div><button class="hkp-btn"><?php echo hkp_e('Save programme'); ?></button></div></form>
<?php endif; ?>
