<div class="hkp-head"><div><h1><?php echo hkp_e('Users & access'); ?></h1><p><?php echo hkp_e('Access comes from role grants. A grant\'s scope (platform, organisation, property, department or self) decides what the person can reach.'); ?></p></div>
<div class="hkp-actions"><?php if ($this->ha_auth->has('users.create')): ?><a class="hkp-btn" href="<?php echo hkp_url('team/new_person'); ?>"><?php echo hkp_e('Add employee'); ?></a><?php endif; ?><?php if ($this->ha_auth->has('imports.run')): ?><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('admin/imports?type=users'); ?>"><?php echo hkp_e('Import users'); ?></a><?php endif; ?></div></div>
<form class="hkp-card hkp-actions" method="get" style="margin-bottom:1rem"><label class="hkp-sr" for="uq"><?php echo hkp_e('Search'); ?></label><input id="uq" class="hkp-input" style="flex:1" name="q" value="<?php echo hkp_h($q); ?>"><button class="hkp-btn"><?php echo hkp_e('Search'); ?></button></form>
<section class="hkp-card"><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('User'); ?></th><th><?php echo hkp_e('Organisation'); ?></th><th><?php echo hkp_e('Role grants'); ?></th><th><?php echo hkp_e('Grant access'); ?></th></tr></thead><tbody>
<?php foreach ($rows as $u): ?><tr>
  <td><?php echo hkp_person_open($u['id']); ?><strong><?php echo hkp_h($u['first_name'] . ' ' . $u['last_name']); ?></strong><?php echo hkp_person_close(); ?><div class="hkp-small hkp-muted"><?php echo hkp_h($u['email']); ?></div><?php echo (int) $u['login_status'] ? '' : hkp_badge('inactive'); ?></td>
  <td class="hkp-small"><?php echo hkp_h($u['org']); ?><div class="hkp-muted"><?php echo hkp_h($u['prop']); ?></div></td>
  <td><?php foreach (isset($grants[$u['id']]) ? $grants[$u['id']] : array() as $g): ?>
    <form method="post" action="<?php echo hkp_url('admin/users/revoke/' . $u['id']); ?>" style="display:inline" data-confirm="<?php echo hkp_e('Remove this role grant?'); ?>"><?php echo ha_csrf_field(); ?><input type="hidden" name="grant_id" value="<?php echo (int) $g['id']; ?>">
      <button class="hkp-badge hkp-badge--neutral" style="border:0;cursor:pointer" title="<?php echo hkp_e('Remove'); ?>"><?php echo hkp_h(hkp_pick($g, 'name')); ?> · <?php echo hkp_label($g['scope']); ?> ✕</button></form>
  <?php endforeach; ?></td>
  <td><form method="post" action="<?php echo hkp_url('admin/users/grant/' . $u['id']); ?>" class="hkp-actions"><?php echo ha_csrf_field(); ?>
    <select class="hkp-select" name="role_id" aria-label="<?php echo hkp_e('Role'); ?>" style="max-width:180px"><?php foreach ($roles as $r): ?><option value="<?php echo (int) $r['id']; ?>"><?php echo hkp_h(hkp_pick($r, 'name')); ?> (<?php echo hkp_label($r['scope']); ?>)</option><?php endforeach; ?></select>
    <select class="hkp-select" name="organization_id" aria-label="<?php echo hkp_e('Organisation'); ?>" style="max-width:150px"><option value=""><?php echo hkp_e('Organisation'); ?></option><?php foreach ($orgs as $o): ?><option value="<?php echo (int) $o['id']; ?>"><?php echo hkp_h($o['name_en']); ?></option><?php endforeach; ?></select>
    <select class="hkp-select" name="property_id" aria-label="<?php echo hkp_e('Property'); ?>" style="max-width:150px"><option value=""><?php echo hkp_e('Property'); ?></option><?php foreach ($props as $p): ?><option value="<?php echo (int) $p['id']; ?>"><?php echo hkp_h($p['name_en']); ?></option><?php endforeach; ?></select>
    <select class="hkp-select" name="department_id" aria-label="<?php echo hkp_e('Department'); ?>" style="max-width:140px"><option value=""><?php echo hkp_e('Department'); ?></option><?php foreach ($depts as $d): ?><option value="<?php echo (int) $d['id']; ?>"><?php echo hkp_h($d['name_en']); ?></option><?php endforeach; ?></select>
    <button class="hkp-btn hkp-btn--sm"><?php echo hkp_e('Grant'); ?></button></form></td></tr><?php endforeach; ?>
</tbody></table></div></section>
