<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_e('What is happening across the portfolio?'); ?></div><h1><?php echo hkp_e('Portfolio dashboard'); ?></h1>
<p><?php echo hkp_e('Clients, properties and the capability evidence chain across every tenant you administer.'); ?></p></div>
<div class="hkp-actions"><?php if ($this->ha_auth->has('organizations.create')): ?><a class="hkp-btn" href="<?php echo hkp_url('admin/crud/organizations/new'); ?>"><?php echo hkp_e('New client'); ?></a><?php endif; ?><?php if ($this->ha_auth->has('properties.create')): ?><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('admin/crud/properties/new'); ?>"><?php echo hkp_e('New property'); ?></a><?php endif; ?></div></div>
<div class="hkp-grid hkp-grid--4" style="margin-bottom:1rem">
<?php foreach (array(array('organisations', 'Organisations', 'admin/crud/organizations', 'organizations.view'), array('properties', 'Properties', 'admin/crud/properties', 'properties.view'), array('users', 'Users', 'admin/users', 'users.view'), array('active', 'Active in 30 days', 'admin/users', 'users.view'),
  array('learners', 'Learners', 'admin/users', 'users.view'), array('managers', 'Managers', 'admin/users', 'users.view'), array('courses', 'Modules', 'admin/curriculum', 'curriculum.view'), array('domains', 'Domains', 'admin/crud/domains', 'curriculum.view'),
  array('tracks', 'Tracks', 'admin/crud/tracks', 'curriculum.view'), array('lessons', 'Lessons', 'admin/curriculum', 'curriculum.view'), array('assessments', 'Assessments', 'admin/assessments', array('assessments.create', 'question_banks.view')), array('competencies', 'Competencies', 'admin/crud/competencies', 'competencies.view'),
  array('gaps', 'Open gaps', 'admin', null), array('actions', 'Open action plans', 'admin', null), array('certificates', 'Certificates', 'admin', null), array('expiring', 'Expiring in 30 days', 'admin', null),
  array('awaiting', 'Content awaiting approval', 'admin/content', array('knowledge.create', 'knowledge.review', 'knowledge.approve', 'knowledge.view')), array('ai_week', 'AI questions this week', 'admin/ai', 'ai.govern')) as $t): ?>
  <?php $open = $t[3] === null || $this->ha_auth->has($t[3]); ?><<?php echo $open ? 'a href="' . hkp_url($t[2]) . '" style="text-decoration:none"' : 'div'; ?> class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e($t[1]); ?></span><span class="hkp-tile__value"><?php echo hkp_number($s[$t[0]]); ?></span></<?php echo $open ? 'a' : 'div'; ?>>
<?php endforeach; ?>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Readiness rate'); ?></span><span class="hkp-tile__value"><?php echo hkp_pct($k['readiness_rate']); ?></span></div>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Competency coverage'); ?></span><span class="hkp-tile__value"><?php echo hkp_pct($k['competency_coverage']); ?></span></div>
</div>
<section class="hkp-card" style="margin-bottom:1rem"><h2><?php echo hkp_e('Cross-property comparison'); ?></h2>
  <div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Property'); ?></th><th><?php echo hkp_e('Status'); ?></th><th class="hkp-num"><?php echo hkp_e('Staff'); ?></th><th><?php echo hkp_e('Learning completion'); ?></th><th class="hkp-num"><?php echo hkp_e('Ready'); ?></th><th class="hkp-num"><?php echo hkp_e('Critical gaps'); ?></th><th class="hkp-num"><?php echo hkp_e('Certificates'); ?></th></tr></thead><tbody>
  <?php foreach ($compare as $c): ?><tr><td><strong><?php echo hkp_h(hkp_pick($c, 'name')); ?></strong></td><td><?php echo hkp_badge($c['operational_status'] === 'operational' ? 'active' : 'warning', hkp_label($c['operational_status'])); ?></td><td class="hkp-num"><?php echo (int) $c['staff']; ?></td>
    <td style="min-width:140px"><?php echo hkp_bar($c['completion']); ?> <span class="hkp-small"><?php echo hkp_pct($c['completion']); ?></span></td><td class="hkp-num"><?php echo hkp_pct($c['ready_pct']); ?></td><td class="hkp-num"><?php echo $c['critical'] ? hkp_badge('critical', $c['critical']) : 0; ?></td><td class="hkp-num"><?php echo (int) $c['certs']; ?></td></tr><?php endforeach; ?>
  </tbody></table></div></section>
<section class="hkp-card"><h2><?php echo hkp_e('Recent activity'); ?></h2><ul class="hkp-list"><?php foreach ($recent as $r): ?><li><span class="hkp-small"><strong><?php echo hkp_h($r['actor_name'] ?: hkp_t('System')); ?></strong> · <?php echo hkp_h($r['action']); ?> · <?php echo hkp_h($r['description']); ?></span><span class="hkp-small hkp-muted"><?php echo hkp_date($r['created_at'], true); ?></span></li><?php endforeach; ?></ul>
  <?php if ($this->ha_auth->has('audit_logs.view')): ?><a href="<?php echo hkp_url('admin/audit'); ?>"><?php echo hkp_e('Full audit log'); ?> →</a><?php endif; ?></section>
