<?php $groups = array(); foreach ($settings as $k => $s) { $groups[$s['meta'][2]][$k] = $s; } ?>
<div class="hkp-head"><div><h1><?php echo hkp_e('System'); ?></h1><p><?php echo hkp_e('Health, global rules, notifications and the product roadmap.'); ?></p></div>
<div class="hkp-actions"><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('admin/crud/roadmap'); ?>"><?php echo hkp_e('Roadmap & feature flags'); ?></a>
<form method="post" action="<?php echo hkp_url('admin/system/run'); ?>"><?php echo ha_csrf_field(); ?><button class="hkp-btn"><?php echo hkp_e('Run daily jobs now'); ?></button></form></div></div>
<div class="hkp-grid hkp-grid--4" style="margin-bottom:1rem"><?php foreach ($health as $k => $h): ?><div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_label($k); ?></span><span><?php echo $h['ok'] ? hkp_badge('success', hkp_t('Healthy')) : hkp_badge('warning', hkp_t('Attention')); ?></span><span class="hkp-tile__foot"><?php echo hkp_h($h['detail']); ?></span></div><?php endforeach; ?></div>
<div class="hkp-grid hkp-grid--main">
<form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('admin/system/settings'); ?>"><?php echo ha_csrf_field(); ?><h2><?php echo hkp_e('Global rules'); ?></h2><p class="hkp-small hkp-muted"><?php echo hkp_e('Organisations and properties may override these where authorised.'); ?></p>
<?php foreach ($groups as $g => $items): ?><h3><?php echo hkp_label($g); ?></h3><div class="hkp-table-wrap"><table class="hkp-table"><tbody>
  <?php foreach ($items as $k => $s): ?><tr><td><strong class="hkp-small"><?php echo hkp_e($s['meta'][3]); ?></strong><div class="hkp-small hkp-muted"><?php echo hkp_h($k); ?></div></td><td style="width:220px"><?php if ($s['meta'][1] === 'text'): ?><textarea class="hkp-input" name="s[<?php echo hkp_h($k); ?>]" rows="2" aria-label="<?php echo hkp_h($k); ?>"><?php echo hkp_h($s['value']); ?></textarea><?php else: ?><input class="hkp-input" name="s[<?php echo hkp_h($k); ?>]" value="<?php echo hkp_h(is_bool($s['value']) ? (int) $s['value'] : $s['value']); ?>" aria-label="<?php echo hkp_h($k); ?>"><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php endforeach; ?>
<div><button class="hkp-btn"><?php echo hkp_e('Save rules'); ?></button></div></form>
<div class="hkp-grid">
  <section class="hkp-card"><h2><?php echo hkp_e('Scheduler'); ?></h2><p class="hkp-small"><?php echo hkp_e('Run once a day (reminders, overdue, certificate expiry, knowledge review, readiness, alerts, email):'); ?></p>
    <pre class="hkp-small" style="white-space:pre-wrap;background:#f4f4f2;padding:.6rem;border-radius:8px">cd <?php echo hkp_h(rtrim(FCPATH, '/\\')); ?> &amp;&amp; php index.php hkp_cli daily</pre>
    <p class="hkp-small"><?php echo hkp_e('Every 5 minutes (email and background queue):'); ?></p><pre class="hkp-small" style="white-space:pre-wrap;background:#f4f4f2;padding:.6rem;border-radius:8px">cd <?php echo hkp_h(rtrim(FCPATH, '/\\')); ?> &amp;&amp; php index.php hkp_cli work</pre></section>
  <section class="hkp-card"><h2><?php echo hkp_e('Recent errors'); ?></h2><?php if (!$errors): ?><p class="hkp-muted"><?php echo hkp_e('No recent errors.'); ?></p><?php endif; ?><ul class="hkp-list"><?php foreach ($errors as $e): ?><li class="hkp-small" style="word-break:break-word"><?php echo hkp_h($e); ?></li><?php endforeach; ?></ul></section>
</div></div>
<form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('admin/system/rules'); ?>" style="margin-top:1rem"><?php echo ha_csrf_field(); ?><h2><?php echo hkp_e('Notification rules and templates'); ?></h2>
  <p class="hkp-small hkp-muted"><?php echo hkp_e('Variables: {{employee_name}}, {{property_name}}, {{course_name}}, {{due_date}}, {{certificate_number}} and more. SMS and WhatsApp are recorded as skipped until a provider is connected.'); ?></p>
  <div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Event'); ?></th><th><?php echo hkp_e('On'); ?></th><th><?php echo hkp_e('Channels'); ?></th><th><?php echo hkp_e('Copy manager'); ?></th></tr></thead><tbody>
  <?php foreach ($rules as $r): $ch = explode(',', $r['channels']); ?><tr><td class="hkp-small"><?php echo hkp_h($r['event_code']); ?></td><td><input type="checkbox" name="rule[<?php echo hkp_h($r['event_code']); ?>][enabled]" value="1"<?php echo (int) $r['enabled'] ? ' checked' : ''; ?> aria-label="<?php echo hkp_e('On'); ?>"></td>
    <td class="hkp-small"><?php foreach (array('in_app', 'email', 'sms', 'whatsapp') as $c): ?><label class="hkp-check" style="display:inline-flex;margin-inline-end:.6rem"><input type="checkbox" name="rule[<?php echo hkp_h($r['event_code']); ?>][ch][]" value="<?php echo $c; ?>"<?php echo in_array($c, $ch, true) ? ' checked' : ''; ?>> <?php echo hkp_label($c); ?></label><?php endforeach; ?></td>
    <td><input type="checkbox" name="rule[<?php echo hkp_h($r['event_code']); ?>][mgr]" value="1"<?php echo (int) $r['notify_manager'] ? ' checked' : ''; ?> aria-label="<?php echo hkp_e('Copy manager'); ?>"></td></tr><?php endforeach; ?></tbody></table></div>
  <details><summary><?php echo hkp_e('Edit templates'); ?></summary><div class="hkp-grid hkp-grid--2" style="margin-top:.8rem"><?php foreach ($templates as $t): ?><div class="hkp-field"><label for="tp<?php echo $t['id']; ?>"><?php echo hkp_h($t['event_code'] . ' · ' . strtoupper($t['locale'])); ?></label><input id="tp<?php echo $t['id']; ?>" class="hkp-input" name="tpl[<?php echo (int) $t['id']; ?>][subject]" value="<?php echo hkp_h($t['subject']); ?>"<?php echo $t['locale'] === 'ar' ? ' dir="rtl"' : ''; ?>><textarea class="hkp-input" name="tpl[<?php echo (int) $t['id']; ?>][body]" rows="2" aria-label="<?php echo hkp_e('Body'); ?>"<?php echo $t['locale'] === 'ar' ? ' dir="rtl"' : ''; ?>><?php echo hkp_h($t['body']); ?></textarea></div><?php endforeach; ?></div></details>
  <div><button class="hkp-btn"><?php echo hkp_e('Save notifications'); ?></button></div></form>
