<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_h($e['org_en']); ?><?php echo $e['prop_en'] ? ' · ' . hkp_h($e['prop_en']) : ''; ?> · <?php echo hkp_label($e['engagement_type']); ?></div><h1><?php echo hkp_h($e['name']); ?></h1>
<p><?php echo hkp_h($e['objectives']); ?></p></div><?php echo hkp_badge($e['status']); ?></div>
<ol class="hkp-steps" style="margin-bottom:1rem"><?php foreach ($e['stages'] as $s): ?><li class="<?php echo $s['status'] === 'signed_off' ? 'is-done' : (in_array($s['status'], array('in_progress', 'awaiting_signoff'), true) ? 'is-now' : ''); ?>"><?php echo strtoupper(hkp_label($s['stage'])); ?></li><?php endforeach; ?></ol>
<?php foreach ($e['stages'] as $s): $can = $this->ha_auth->has('engagements.update'); ?>
<details class="hkp-card" style="margin-bottom:.8rem"<?php echo in_array($s['status'], array('in_progress', 'awaiting_signoff'), true) ? ' open' : ''; ?>><summary><strong><?php echo strtoupper(hkp_label($s['stage'])); ?></strong> <?php echo hkp_badge($s['status']); ?><?php if ($s['signed_off_by']): ?> <span class="hkp-small hkp-muted"><?php echo hkp_e('Signed off by {n} on {d}', array('n' => $s['signed_off_by'], 'd' => hkp_date($s['signed_off_at']))); ?></span><?php endif; ?></summary>
  <div class="hkp-grid hkp-grid--2" style="margin-top:.8rem">
    <div><ul class="hkp-list"><?php foreach ($s['tasks'] as $t): ?><li><span><?php echo hkp_badge('neutral', hkp_label($t['task_type'])); ?> <?php echo hkp_h($t['title']); ?> <span class="hkp-small hkp-muted"><?php echo hkp_date($t['due_date']); ?></span><?php if ($t['token']): ?> <a class="hkp-small" href="<?php echo hkp_url('file/' . $t['token']); ?>"><?php echo hkp_icon('download'); ?> <?php echo hkp_h($t['original_name']); ?></a><?php endif; ?></span>
      <?php if ($can): ?><form method="post" action="<?php echo hkp_url('admin/engagements/task_status/' . $t['id']); ?>"><?php echo ha_csrf_field(); ?><select class="hkp-select" name="status" onchange="this.form.submit()" aria-label="<?php echo hkp_e('Status'); ?>"><?php foreach (array('open', 'in_progress', 'done', 'blocked') as $st): ?><option value="<?php echo $st; ?>"<?php echo $t['status'] === $st ? ' selected' : ''; ?>><?php echo hkp_label($st); ?></option><?php endforeach; ?></select></form><?php else: ?><?php echo hkp_badge($t['status']); ?><?php endif; ?></li><?php endforeach; ?></ul>
      <?php if (!$s['tasks']): ?><p class="hkp-muted hkp-small"><?php echo hkp_e('No tasks yet.'); ?></p><?php endif; ?>
      <?php if ($can): ?><form class="hkp-form" method="post" enctype="multipart/form-data" action="<?php echo hkp_url('admin/engagements/task/' . $s['id']); ?>" style="margin-top:.6rem"><?php echo ha_csrf_field(); ?><div class="hkp-row">
        <input class="hkp-input" name="title" required placeholder="<?php echo hkp_e('Task, deliverable or milestone'); ?>" aria-label="<?php echo hkp_e('Title'); ?>">
        <select class="hkp-select" name="task_type" aria-label="<?php echo hkp_e('Type'); ?>"><?php foreach (array('task', 'deliverable', 'milestone', 'evidence') as $tt): ?><option value="<?php echo $tt; ?>"><?php echo hkp_label($tt); ?></option><?php endforeach; ?></select>
        <input class="hkp-input" type="date" name="due_date" aria-label="<?php echo hkp_e('Due'); ?>"><input class="hkp-input" type="file" name="file" aria-label="<?php echo hkp_e('File'); ?>"></div><div><button class="hkp-btn hkp-btn--sm"><?php echo hkp_e('Add'); ?></button></div></form><?php endif; ?></div>
    <?php if ($can): ?><form class="hkp-form" method="post" action="<?php echo hkp_url('admin/engagements/stage/' . $s['id']); ?>"><?php echo ha_csrf_field(); ?>
      <div class="hkp-field"><label for="so<?php echo $s['id']; ?>"><?php echo hkp_e('Objectives'); ?></label><textarea id="so<?php echo $s['id']; ?>" class="hkp-input" name="objectives" rows="3"><?php echo hkp_h($s['objectives']); ?></textarea></div>
      <div class="hkp-row"><div class="hkp-field"><label for="sd<?php echo $s['id']; ?>"><?php echo hkp_e('Due'); ?></label><input id="sd<?php echo $s['id']; ?>" class="hkp-input" type="date" name="due_date" value="<?php echo hkp_h($s['due_date']); ?>"></div>
        <div class="hkp-field"><label for="ss<?php echo $s['id']; ?>"><?php echo hkp_e('Status'); ?></label><select id="ss<?php echo $s['id']; ?>" class="hkp-select" name="status"><?php foreach (array('not_started', 'in_progress', 'awaiting_signoff', 'signed_off') as $st): ?><option value="<?php echo $st; ?>"<?php echo $s['status'] === $st ? ' selected' : ''; ?>><?php echo hkp_label($st); ?></option><?php endforeach; ?></select></div>
        <div class="hkp-field"><label for="sb<?php echo $s['id']; ?>"><?php echo hkp_e('Client sign-off by'); ?></label><input id="sb<?php echo $s['id']; ?>" class="hkp-input" name="signed_off_by" value="<?php echo hkp_h($s['signed_off_by']); ?>"></div></div>
      <div><button class="hkp-btn hkp-btn--sm"><?php echo hkp_e('Save stage'); ?></button></div></form><?php endif; ?>
  </div></details>
<?php endforeach; ?>
<section class="hkp-card"><h2><?php echo hkp_e('Framework assessments'); ?></h2>
  <ul class="hkp-list"><?php foreach ($e['assessments'] as $a): ?><li><a href="<?php echo hkp_url('admin/frameworks/assess/' . $a['id']); ?>"><?php echo hkp_h($a['title']); ?></a><span><?php echo hkp_h(hkp_pick($a, 'fw')); ?> <?php echo $a['result_label'] ? hkp_badge('neutral', hkp_label($a['result_label'])) : hkp_badge($a['status']); ?></span></li><?php endforeach; ?></ul>
  <?php if ($this->ha_auth->has('frameworks.assess')): ?><form class="hkp-actions" method="post" action="<?php echo hkp_url('admin/frameworks/start'); ?>"><?php echo ha_csrf_field(); ?><input type="hidden" name="organization_id" value="<?php echo (int) $e['organization_id']; ?>"><input type="hidden" name="property_id" value="<?php echo (int) $e['property_id']; ?>"><input type="hidden" name="engagement_id" value="<?php echo (int) $e['id']; ?>">
    <select class="hkp-select" name="framework_id" style="max-width:280px" aria-label="<?php echo hkp_e('Framework'); ?>"><?php foreach ($frameworks as $f): ?><option value="<?php echo (int) $f['id']; ?>"><?php echo hkp_h(hkp_pick($f, 'name')); ?></option><?php endforeach; ?></select><input class="hkp-input" name="title" placeholder="<?php echo hkp_e('Title'); ?>" aria-label="<?php echo hkp_e('Title'); ?>" style="max-width:220px"><button class="hkp-btn hkp-btn--sm"><?php echo hkp_e('Start assessment'); ?></button></form><?php endif; ?></section>
