<?php $st = array(); foreach ($stats as $s) { $st[$s['id']] = $s; } ?>
<div class="hkp-head"><div><div class="hkp-eyebrow"><a href="<?php echo hkp_url('admin/assessments'); ?>"><?php echo hkp_e('Assessments'); ?></a> · <?php echo hkp_h($a['code']); ?></div><h1><?php echo hkp_h(hkp_pick($a, 'title')); ?></h1></div><?php echo hkp_badge($a['status']); ?></div>
<div class="hkp-grid hkp-grid--main">
<div class="hkp-grid">
<section class="hkp-card"><h2><?php echo hkp_e('Questions and analytics'); ?></h2>
  <p class="hkp-small hkp-muted"><?php echo hkp_e('Statistics support a reviewer\'s judgement; no question is labelled bad automatically.'); ?></p>
  <?php foreach ($qs as $i => $q): $s = isset($st[$q['id']]) ? $st[$q['id']] : null; ?>
  <div class="hkp-q"><p><strong><?php echo ($i + 1) . '. ' . hkp_h($q['body_en']); ?></strong> <span class="hkp-small hkp-muted">· <?php echo hkp_label($q['question_type']); ?> · <?php echo (float) $q['marks']; ?></span>
    <?php if (trim((string) $q['body_ar']) === ''): ?><?php echo hkp_badge('warning', hkp_t('No Arabic')); ?><?php endif; ?></p>
    <?php if ($q['body_ar']): ?><p dir="rtl" class="hkp-small"><?php echo hkp_h($q['body_ar']); ?></p><?php endif; ?>
    <ul class="hkp-small"><?php foreach ($q['options'] as $o): $chosen = 0; if ($s) { foreach ($s['distractors'] as $d) { if ($d['body'] === $o['body_en']) { $chosen = $d['chosen']; } } } ?><li><?php echo (int) $o['is_correct'] ? '✓ ' : ''; ?><?php echo hkp_h($o['body_en']); ?><?php if ($o['match_key_en']): ?> → <?php echo hkp_h($o['match_key_en']); ?><?php endif; ?><?php if ($s): ?> <span class="hkp-muted">(<?php echo (int) $chosen; ?>)</span><?php endif; ?></li><?php endforeach; ?></ul>
    <?php if ($s): ?><p class="hkp-small"><?php echo hkp_e('{n} answers · {c}% correct · average {ms} ms', array('n' => $s['attempts'], 'c' => $s['correct_pct'], 'ms' => $s['avg_ms'] ?: '—')); ?></p><?php endif; ?></div>
  <?php endforeach; ?></section>
<form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('admin/assessments/question/' . $a['id']); ?>"><?php echo ha_csrf_field(); ?><h2><?php echo hkp_e('Add a question'); ?></h2>
  <div class="hkp-row"><div class="hkp-field"><label for="qt"><?php echo hkp_e('Type'); ?></label><select id="qt" class="hkp-select" name="question_type"><?php foreach (array('multiple_choice', 'multiple_response', 'true_false', 'matching', 'ordering', 'scenario', 'short_answer', 'essay') as $t): ?><option value="<?php echo $t; ?>"><?php echo hkp_label($t); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="qm"><?php echo hkp_e('Marks'); ?></label><input id="qm" class="hkp-input" type="number" step="0.5" name="marks" value="1"></div>
    <div class="hkp-field"><label for="qd"><?php echo hkp_e('Difficulty'); ?></label><select id="qd" class="hkp-select" name="difficulty"><option value="easy"><?php echo hkp_e('Easy'); ?></option><option value="medium" selected><?php echo hkp_e('Medium'); ?></option><option value="hard"><?php echo hkp_e('Hard'); ?></option></select></div>
    <div class="hkp-field"><label for="qs"><?php echo hkp_e('Competency'); ?></label><select id="qs" class="hkp-select" name="skill_id"><option value=""></option><?php foreach ($skills as $s): ?><option value="<?php echo (int) $s['id']; ?>"><?php echo hkp_h(hkp_pick($s, 'name')); ?></option><?php endforeach; ?></select></div></div>
  <div class="hkp-grid hkp-grid--2"><div class="hkp-field"><label for="qe"><?php echo hkp_e('Question (English)'); ?></label><textarea id="qe" class="hkp-input" name="body_en" rows="2" required></textarea></div><div class="hkp-field"><label for="qa"><?php echo hkp_e('Question (Arabic)'); ?></label><textarea id="qa" class="hkp-input" name="body_ar" rows="2" dir="rtl"></textarea></div></div>
  <p class="hkp-small hkp-muted"><?php echo hkp_e('Options: tick the correct ones. For ordering, enter them in the correct order. For matching, give each item its match. For short answer, list accepted answers and tick them.'); ?></p>
  <?php for ($i = 0; $i < 6; $i++): ?><div class="hkp-actions"><input type="checkbox" name="correct[]" value="<?php echo $i; ?>" aria-label="<?php echo hkp_e('Correct'); ?>"><input class="hkp-input" style="flex:2" name="opt[<?php echo $i; ?>][en]" placeholder="<?php echo hkp_e('Option (English)'); ?>" aria-label="<?php echo hkp_e('Option (English)'); ?>"><input class="hkp-input" style="flex:2" dir="rtl" name="opt[<?php echo $i; ?>][ar]" placeholder="<?php echo hkp_e('Option (Arabic)'); ?>" aria-label="<?php echo hkp_e('Option (Arabic)'); ?>"><input class="hkp-input" style="flex:1" name="opt[<?php echo $i; ?>][match]" placeholder="<?php echo hkp_e('Match'); ?>" aria-label="<?php echo hkp_e('Match'); ?>"></div><?php endfor; ?>
  <div class="hkp-grid hkp-grid--2"><div class="hkp-field"><label for="xe"><?php echo hkp_e('Explanation (English)'); ?></label><input id="xe" class="hkp-input" name="explanation_en"></div><div class="hkp-field"><label for="xa"><?php echo hkp_e('Explanation (Arabic)'); ?></label><input id="xa" class="hkp-input" dir="rtl" name="explanation_ar"></div></div>
  <div><button class="hkp-btn"><?php echo hkp_e('Add question'); ?></button></div></form>
</div>
<form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('admin/assessments/settings/' . $a['id']); ?>"><?php echo ha_csrf_field(); ?><h2><?php echo hkp_e('Settings'); ?></h2>
  <div class="hkp-field"><label for="sp"><?php echo hkp_e('Pass mark (%)'); ?></label><input id="sp" class="hkp-input" type="number" name="pass_percentage" value="<?php echo (int) $a['pass_percentage']; ?>"></div>
  <div class="hkp-field"><label for="sa"><?php echo hkp_e('Maximum attempts'); ?></label><input id="sa" class="hkp-input" type="number" name="max_attempts" value="<?php echo (int) $a['max_attempts']; ?>"></div>
  <div class="hkp-field"><label for="stl"><?php echo hkp_e('Time limit (minutes, 0 = none)'); ?></label><input id="stl" class="hkp-input" type="number" name="time_limit_minutes" value="<?php echo (int) $a['time_limit_minutes']; ?>"></div>
  <div class="hkp-field"><label for="ssel"><?php echo hkp_e('Question selection'); ?></label><select id="ssel" class="hkp-select" name="question_selection"><option value="fixed"<?php echo $a['question_selection'] === 'fixed' ? ' selected' : ''; ?>><?php echo hkp_e('Fixed set'); ?></option><option value="random"<?php echo $a['question_selection'] === 'random' ? ' selected' : ''; ?>><?php echo hkp_e('Random from the bank'); ?></option></select></div>
  <div class="hkp-field"><label for="srn"><?php echo hkp_e('Random question count'); ?></label><input id="srn" class="hkp-input" type="number" name="random_question_count" value="<?php echo (int) $a['random_question_count']; ?>"></div>
  <label class="hkp-check"><input type="checkbox" name="shuffle_questions" value="1"<?php echo (int) $a['shuffle_questions'] ? ' checked' : ''; ?>> <?php echo hkp_e('Shuffle questions'); ?></label>
  <label class="hkp-check"><input type="checkbox" name="shuffle_options" value="1"<?php echo (int) $a['shuffle_options'] ? ' checked' : ''; ?>> <?php echo hkp_e('Shuffle options'); ?></label>
  <label class="hkp-check"><input type="checkbox" name="show_correct_answers" value="1"<?php echo (int) $a['show_correct_answers'] ? ' checked' : ''; ?>> <?php echo hkp_e('Show correct answers after submitting'); ?></label>
  <div class="hkp-field"><label for="sst"><?php echo hkp_e('Status'); ?></label><select id="sst" class="hkp-select" name="status"><?php foreach (array('draft', 'published', 'archived') as $s): ?><option value="<?php echo $s; ?>"<?php echo $a['status'] === $s ? ' selected' : ''; ?>><?php echo hkp_label($s); ?></option><?php endforeach; ?></select></div>
  <h3><?php echo hkp_e('Competency awarded on pass'); ?></h3><p class="hkp-small hkp-muted"><?php echo hkp_e('A pass proves knowledge. Set the level it may lift a competency to; practical levels are set by supervisors.'); ?></p>
  <div style="max-height:320px;overflow:auto"><?php foreach ($skills as $s): ?><div class="hkp-actions" style="justify-content:space-between"><span class="hkp-small"><?php echo hkp_h(hkp_pick($s, 'name')); ?></span><select class="hkp-select" style="max-width:80px" name="map[<?php echo (int) $s['id']; ?>]" aria-label="<?php echo hkp_h(hkp_pick($s, 'name')); ?>"><option value="0">—</option><?php for ($l = 1; $l <= 5; $l++): ?><option value="<?php echo $l; ?>"<?php echo isset($map[$s['id']]) && (int) $map[$s['id']] === $l ? ' selected' : ''; ?>><?php echo $l; ?></option><?php endfor; ?></select></div><?php endforeach; ?></div>
  <div><button class="hkp-btn"><?php echo hkp_e('Save settings'); ?></button></div></form>
</div>
