<div class="hkp-head"><div><h1><?php echo hkp_e('Imports'); ?></h1><p><?php echo hkp_e('Upload a CSV, check the preview, then commit. Every row is validated, duplicates are detected, and a commit writes all valid rows or none.'); ?></p></div></div>
<?php if ($run): $errs = json_decode((string) $run['errors_json'], true) ?: array(); ?>
<section class="hkp-card" style="margin-bottom:1rem"><h2><?php echo hkp_h($run['file_name']); ?> · <?php echo hkp_label($run['import_type']); ?> <?php echo hkp_badge($run['status']); ?></h2>
  <p><?php echo hkp_e('{t} rows · {v} valid · {e} with errors', array('t' => $run['rows_total'], 'v' => $run['rows_valid'], 'e' => $run['rows_error'])); ?></p>
  <?php if ($errs): ?><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Line'); ?></th><th><?php echo hkp_e('Problems'); ?></th></tr></thead><tbody><?php foreach (array_slice($errs, 0, 200) as $er): ?><tr><td class="hkp-num"><?php echo (int) $er['line']; ?></td><td class="hkp-small"><?php echo hkp_h(implode('; ', $er['errors'])); ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
  <div class="hkp-actions" style="margin-top:1rem">
    <?php if ($run['status'] === 'previewed' && $run['rows_valid']): ?><form method="post" action="<?php echo hkp_url('admin/imports/commit/' . $run['id']); ?>" data-confirm="<?php echo hkp_e('Write {n} rows?', array('n' => $run['rows_valid'])); ?>"><?php echo ha_csrf_field(); ?><button class="hkp-btn"><?php echo hkp_e('Commit {n} valid rows', array('n' => $run['rows_valid'])); ?></button></form><?php endif; ?>
    <?php if ($run['status'] === 'committed'): ?><form method="post" action="<?php echo hkp_url('admin/imports/rollback/' . $run['id']); ?>" data-confirm="<?php echo hkp_e('Roll back this import?'); ?>"><?php echo ha_csrf_field(); ?><button class="hkp-btn hkp-btn--danger"><?php echo hkp_e('Roll back'); ?></button></form><?php endif; ?></div></section>
<?php endif; ?>
<div class="hkp-grid hkp-grid--main">
<form class="hkp-card hkp-form" method="post" enctype="multipart/form-data" action="<?php echo hkp_url('admin/imports/preview'); ?>"><?php echo ha_csrf_field(); ?><h2><?php echo hkp_e('New import'); ?></h2>
  <div class="hkp-row"><div class="hkp-field"><label for="it"><?php echo hkp_e('What are you importing?'); ?></label><select id="it" class="hkp-select" name="type"><?php foreach ($types as $t => $cols): ?><option value="<?php echo $t; ?>"<?php echo $type === $t ? ' selected' : ''; ?>><?php echo hkp_label($t); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="io"><?php echo hkp_e('Organisation'); ?></label><select id="io" class="hkp-select" name="organization_id"><?php foreach ($orgs as $o): if (!$this->ha_auth->can_organization($o['id'])) continue; ?><option value="<?php echo (int) $o['id']; ?>"<?php echo (int) $ctx['organization_id'] === (int) $o['id'] ? ' selected' : ''; ?>><?php echo hkp_h($o['name_en']); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="if"><?php echo hkp_e('CSV file (UTF-8)'); ?></label><input id="if" class="hkp-input" type="file" name="file" accept=".csv" required></div></div>
  <div><button class="hkp-btn"><?php echo hkp_icon('upload'); ?> <?php echo hkp_e('Upload and preview'); ?></button></div></form>
<section class="hkp-card"><h2><?php echo hkp_e('Templates'); ?></h2><ul class="hkp-list"><?php foreach ($types as $t => $cols): ?><li><div><strong><?php echo hkp_label($t); ?></strong><div class="hkp-small hkp-muted"><?php echo hkp_h(implode(', ', $cols)); ?></div></div><a class="hkp-btn hkp-btn--sm hkp-btn--ghost" href="<?php echo hkp_url('admin/imports/template?type=' . $t); ?>"><?php echo hkp_icon('download'); ?></a></li><?php endforeach; ?></ul></section>
</div>
<section class="hkp-card" style="margin-top:1rem"><h2><?php echo hkp_e('History'); ?></h2><ul class="hkp-list"><?php foreach ($runs as $r): ?><li><a href="<?php echo hkp_url('admin/imports/view/' . $r['id']); ?>"><?php echo hkp_h($r['file_name']); ?></a><span class="hkp-small"><?php echo hkp_label($r['import_type']); ?> · <?php echo (int) $r['rows_valid']; ?>/<?php echo (int) $r['rows_total']; ?> <?php echo hkp_badge($r['status']); ?> · <?php echo hkp_date($r['created_at'], true); ?></span></li><?php endforeach; ?></ul></section>
