<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_e('Altus Ascent™'); ?></div><h1><?php echo hkp_e('Engagements'); ?></h1><p><?php echo hkp_e('Discover → Assess → Design → Transform → Optimise → Scale, with owners, deliverables, evidence and client sign-off at each stage.'); ?></p></div></div>
<div class="hkp-grid hkp-grid--main">
<section class="hkp-card"><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Engagement'); ?></th><th><?php echo hkp_e('Client'); ?></th><th><?php echo hkp_e('Type'); ?></th><th><?php echo hkp_e('Dates'); ?></th><th><?php echo hkp_e('Status'); ?></th></tr></thead><tbody>
<?php foreach ($rows as $e): ?><tr><td><a href="<?php echo hkp_url('admin/engagements/view/' . $e['id']); ?>"><strong><?php echo hkp_h($e['name']); ?></strong></a><div class="hkp-small hkp-muted"><?php echo hkp_h($e['code']); ?></div></td><td class="hkp-small"><?php echo hkp_h($e['org_en']); ?><div class="hkp-muted"><?php echo hkp_h($e['prop_en']); ?></div></td><td class="hkp-small"><?php echo hkp_label($e['engagement_type']); ?></td><td class="hkp-small"><?php echo hkp_date($e['start_date']); ?> → <?php echo hkp_date($e['end_date']); ?></td><td><?php echo hkp_badge($e['status']); ?></td></tr><?php endforeach; ?>
</tbody></table></div><?php if (!$rows): ?><div class="hkp-empty"><?php echo hkp_e('No engagements yet.'); ?></div><?php endif; ?></section>
<?php if ($this->ha_auth->has('engagements.create')): ?><form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('admin/engagements/create'); ?>"><?php echo ha_csrf_field(); ?><h2><?php echo hkp_e('New engagement'); ?></h2>
  <div class="hkp-field"><label for="en"><?php echo hkp_e('Name'); ?></label><input id="en" class="hkp-input" name="name" required></div>
  <div class="hkp-field"><label for="eo"><?php echo hkp_e('Client'); ?></label><select id="eo" class="hkp-select" name="organization_id" required><?php foreach ($orgs as $o): ?><option value="<?php echo (int) $o['id']; ?>"><?php echo hkp_h($o['name_en']); ?></option><?php endforeach; ?></select></div>
  <div class="hkp-field"><label for="ep"><?php echo hkp_e('Property'); ?></label><select id="ep" class="hkp-select" name="property_id"><option value=""></option><?php foreach ($props as $p): ?><option value="<?php echo (int) $p['id']; ?>"><?php echo hkp_h($p['name_en']); ?></option><?php endforeach; ?></select></div>
  <div class="hkp-field"><label for="et"><?php echo hkp_e('Type'); ?></label><select id="et" class="hkp-select" name="engagement_type"><?php foreach (array('pre_opening', 'operations_optimisation', 'owner_representation', 'feasibility', 'quality_audit', 'commercial_improvement', 'digital_transformation', 'leadership_development', 'strategic_planning', 'other') as $t): ?><option value="<?php echo $t; ?>"><?php echo hkp_label($t); ?></option><?php endforeach; ?></select></div>
  <div class="hkp-row"><div class="hkp-field"><label for="es"><?php echo hkp_e('Start'); ?></label><input id="es" class="hkp-input" type="date" name="start_date"></div><div class="hkp-field"><label for="ee"><?php echo hkp_e('End'); ?></label><input id="ee" class="hkp-input" type="date" name="end_date"></div></div>
  <div class="hkp-field"><label for="eob"><?php echo hkp_e('Objectives'); ?></label><textarea id="eob" class="hkp-input" name="objectives" rows="3"></textarea></div>
  <div><button class="hkp-btn"><?php echo hkp_e('Create'); ?></button></div></form><?php endif; ?>
</div>
