<div class="hkp-head"><div><h1><?php echo hkp_e('Competencies'); ?></h1><p><?php echo hkp_e('Role → required competencies and levels → required learning, assessments and certification. A property can override the master matrix.'); ?></p></div>
<div class="hkp-actions"><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('admin/crud/competencies'); ?>"><?php echo hkp_e('Competency library'); ?></a><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('admin/crud/job_roles'); ?>"><?php echo hkp_e('Job roles'); ?></a><a class="hkp-btn" href="<?php echo hkp_url('admin/competencies/rubric'); ?>"><?php echo hkp_e('New rubric'); ?></a></div></div>
<form class="hkp-card hkp-actions" method="get" style="margin-bottom:1rem"><label for="mr"><?php echo hkp_e('Role'); ?></label><select id="mr" class="hkp-select" name="role" style="max-width:320px" onchange="this.form.submit()"><option value=""><?php echo hkp_e('Choose a role…'); ?></option><?php foreach ($roles as $r): ?><option value="<?php echo (int) $r['id']; ?>"<?php echo $role_id === (int) $r['id'] ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($r, 'title')); ?> (<?php echo hkp_h($r['code']); ?>)</option><?php endforeach; ?></select>
  <label for="mp"><?php echo hkp_e('Applies to'); ?></label><select id="mp" class="hkp-select" name="property" style="max-width:260px" onchange="this.form.submit()"><option value="0"><?php echo hkp_e('All properties (master)'); ?></option><?php foreach ($props as $p): ?><option value="<?php echo (int) $p['id']; ?>"<?php echo $pk === (int) $p['id'] ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($p, 'name')); ?></option><?php endforeach; ?></select></form>
<?php if ($role_id): ?>
<form class="hkp-grid hkp-grid--main" method="post" action="<?php echo hkp_url('admin/competencies/matrix_save/' . $role_id); ?>"><?php echo ha_csrf_field(); ?><input type="hidden" name="property_key" value="<?php echo $pk; ?>">
  <section class="hkp-card"><h2><?php echo hkp_e('Required competencies'); ?></h2><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Competency'); ?></th><th><?php echo hkp_e('Method'); ?></th><th><?php echo hkp_e('Required level'); ?></th><th><?php echo hkp_e('Critical for role'); ?></th></tr></thead><tbody>
  <?php foreach ($skills as $s): $r = isset($req[$s['id']]) ? $req[$s['id']] : null; ?><tr><td><?php echo hkp_h(hkp_pick($s, 'name')); ?> <span class="hkp-small hkp-muted"><?php echo hkp_label($s['criticality']); ?></span></td><td class="hkp-small"><?php echo hkp_label($s['assessment_method']); ?></td>
    <td><select class="hkp-select" style="max-width:90px" name="req[<?php echo (int) $s['id']; ?>]" aria-label="<?php echo hkp_h(hkp_pick($s, 'name')); ?>"><option value="0">—</option><?php for ($l = 1; $l <= 5; $l++): ?><option value="<?php echo $l; ?>"<?php echo $r && (int) $r['required_level'] === $l ? ' selected' : ''; ?>><?php echo $l; ?></option><?php endfor; ?></select></td>
    <td><input type="checkbox" name="crit[<?php echo (int) $s['id']; ?>]" value="1"<?php echo $r && (int) $r['is_critical'] ? ' checked' : ''; ?> aria-label="<?php echo hkp_e('Critical'); ?>"></td></tr><?php endforeach; ?>
  </tbody></table></div></section>
  <section class="hkp-card hkp-form"><h2><?php echo hkp_e('Required learning & certification'); ?></h2>
    <?php foreach (array('track' => array('Tracks', $tracks, 'title'), 'assessment' => array('Assessments', $assessments, 'title'), 'certification' => array('Certification programmes', $programs, 'title')) as $t => $c): $sel = isset($items[$t]) ? $items[$t] : array(); ?>
      <div class="hkp-field"><label for="rq<?php echo $t; ?>"><?php echo hkp_e($c[0]); ?></label><select id="rq<?php echo $t; ?>" class="hkp-select" name="req_<?php echo $t; ?>[]" multiple size="6"><?php foreach ($c[1] as $o): ?><option value="<?php echo (int) $o['id']; ?>"<?php echo in_array((int) $o['id'], $sel, true) ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($o, $c[2])); ?></option><?php endforeach; ?></select></div>
    <?php endforeach; ?>
    <div class="hkp-field"><label for="rdd"><?php echo hkp_e('Days to complete after hire'); ?></label><input id="rdd" class="hkp-input" type="number" name="due_days" value="30"></div>
    <div><button class="hkp-btn"><?php echo hkp_e('Save role requirements'); ?></button></div></section>
</form>
<?php endif; ?>
<section class="hkp-card" style="margin-top:1rem"><h2><?php echo hkp_e('Practical rubrics'); ?></h2><ul class="hkp-list"><?php foreach ($rubrics as $r): ?><li><a href="<?php echo hkp_url('admin/competencies/rubric/' . $r['id']); ?>"><?php echo hkp_h(hkp_pick($r, 'title')); ?></a><span><?php echo hkp_e('v{n}', array('n' => $r['version_no'])); ?> <?php echo hkp_badge($r['status']); ?></span></li><?php endforeach; ?></ul></section>
