<div class="hkp-head"><div><h1><?php echo hkp_e('Audit logs'); ?></h1><p><?php echo hkp_e('Who did what, to which record, when, from where, with the before and after state. Secrets are never recorded.'); ?></p></div>
<?php if ($this->ha_auth->has('audit_logs.export')): $qs = $_GET; $qs['format'] = 'csv'; ?><a class="hkp-btn hkp-btn--ghost" href="?<?php echo hkp_h(http_build_query($qs)); ?>"><?php echo hkp_icon('download'); ?> CSV</a><?php endif; ?></div>
<form class="hkp-card hkp-form" method="get" style="margin-bottom:1rem"><div class="hkp-row">
  <div class="hkp-field"><label for="aa"><?php echo hkp_e('Action'); ?></label><select id="aa" class="hkp-select" name="action"><option value=""><?php echo hkp_e('All'); ?></option><?php foreach (array_merge(Ha_audit::$actions, array('ai_query')) as $x): ?><option<?php echo $f['action'] === $x ? ' selected' : ''; ?>><?php echo $x; ?></option><?php endforeach; ?></select></div>
  <div class="hkp-field"><label for="ae"><?php echo hkp_e('Entity'); ?></label><input id="ae" class="hkp-input" name="entity" value="<?php echo hkp_h($f['entity']); ?>" placeholder="knowledge"></div>
  <div class="hkp-field"><label for="au"><?php echo hkp_e('Actor'); ?></label><input id="au" class="hkp-input" name="user" value="<?php echo hkp_h($f['user']); ?>"></div>
  <div class="hkp-field"><label for="af"><?php echo hkp_e('From'); ?></label><input id="af" class="hkp-input" type="date" name="from" value="<?php echo hkp_h($f['from']); ?>"></div>
  <div class="hkp-field" style="justify-content:flex-end"><button class="hkp-btn"><?php echo hkp_e('Filter'); ?></button></div></div></form>
<section class="hkp-card"><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Time'); ?></th><th><?php echo hkp_e('Actor'); ?></th><th><?php echo hkp_e('Action'); ?></th><th><?php echo hkp_e('Entity'); ?></th><th><?php echo hkp_e('Description'); ?></th><th>IP</th></tr></thead><tbody>
<?php foreach ($rows as $r): ?><tr><td class="hkp-small" style="white-space:nowrap"><?php echo hkp_date($r['created_at'], true); ?></td><td class="hkp-small"><?php echo hkp_h($r['actor_name'] ?: hkp_t('System')); ?></td><td><?php echo hkp_badge('neutral', $r['action']); ?></td><td class="hkp-small"><?php echo hkp_h($r['entity_type']); ?> #<?php echo (int) $r['entity_id']; ?></td>
  <td class="hkp-small"><?php echo hkp_h($r['description']); ?><?php if ($r['before_json'] || $r['after_json']): ?><details><summary><?php echo hkp_e('Changes'); ?></summary><pre style="white-space:pre-wrap;font-size:.72rem"><?php echo hkp_h($r['before_json']); ?>
→ <?php echo hkp_h($r['after_json']); ?></pre></details><?php endif; ?></td><td class="hkp-small"><?php echo hkp_h($r['ip_address']); ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
