<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_e('What is happening across the portfolio?'); ?></div><h1><?php echo hkp_e('Portfolio dashboard'); ?></h1><p><?php echo hkp_e('The people, properties and evidence behind your operational performance.'); ?></p></div><div class="hkp-actions"><?php if ($this->ha_auth->has('organizations.create')): ?><a class="hkp-btn" href="<?php echo hkp_url('admin/crud/organizations/new'); ?>">+ <?php echo hkp_e('New client'); ?></a><?php endif; ?><?php if ($this->ha_auth->has('properties.create')): ?><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('admin/crud/properties/new'); ?>">+ <?php echo hkp_e('New property'); ?></a><?php endif; ?></div></div>
<div class="studio-metrics">
<?php foreach (array(
    array('building', 'Organisations', hkp_number($s['organisations']), 'admin/crud/organizations', 'organizations.view'),
    array('home', 'Properties', hkp_number($s['properties']), 'admin/crud/properties', 'properties.view'),
    array('users', 'Active users · 30 days', hkp_number($s['active']), 'admin/users', 'users.view'),
    array('book', 'Learners', hkp_number($s['learners']), 'admin/users', 'users.view'),
    array('check', 'Learning completion', hkp_pct($k['learning_completion']), 'team/reports', 'reports.view'),
    array('gauge', 'Readiness', hkp_pct($k['readiness_rate']), 'team/readiness', 'readiness.view'),
    array('alert', 'Critical gaps', hkp_number($k['critical_gaps']), 'team/gaps', 'gaps.view'),
    array('award', 'Certificates', hkp_number($s['certificates']), 'team/certifications', 'certificates.export')
) as $metric): $allowed = $this->ha_auth->has($metric[4]); ?>
<<?php echo $allowed ? 'a href="' . hkp_url($metric[3]) . '"' : 'div'; ?> class="hkp-card studio-metric"><span class="studio-metric-icon"><?php echo hkp_icon($metric[0]); ?></span><div><span class="studio-metric-label"><?php echo hkp_e($metric[1]); ?></span><strong class="studio-metric-value"><?php echo $metric[2]; ?></strong></div></<?php echo $allowed ? 'a' : 'div'; ?>>
<?php endforeach; ?></div>
<p class="studio-comparison-note"><?php echo hkp_e('No comparison period available'); ?> · <?php echo hkp_e('Figures reflect your permitted portfolio.'); ?></p>
<div class="studio-insights"><div><strong><?php echo hkp_number($s['awaiting']); ?></strong><span><?php echo hkp_e('Content awaiting approval'); ?></span></div><div><strong><?php echo hkp_number($s['expiring']); ?></strong><span><?php echo hkp_e('Certificates expiring in 30 days'); ?></span></div><div><strong><?php echo hkp_number($s['actions']); ?></strong><span><?php echo hkp_e('Open action plans'); ?></span></div><div><strong><?php echo hkp_pct($k['competency_coverage']); ?></strong><span><?php echo hkp_e('Competency coverage'); ?></span></div></div>
<section class="hkp-card" style="margin-bottom:20px"><div class="studio-section-head"><div><h2><?php echo hkp_e('Cross-property comparison'); ?></h2><p class="hkp-small hkp-muted" style="margin:4px 0 0"><?php echo hkp_e('Focus your attention where learning and readiness need support.'); ?></p></div><?php if ($this->ha_auth->has('properties.view')): ?><a class="hkp-btn hkp-btn--ghost hkp-btn--sm" href="<?php echo hkp_url('admin/crud/properties'); ?>"><?php echo hkp_e('View properties'); ?> →</a><?php endif; ?></div><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Property'); ?></th><th><?php echo hkp_e('Status'); ?></th><th class="hkp-num"><?php echo hkp_e('Staff'); ?></th><th><?php echo hkp_e('Learning completion'); ?></th><th class="hkp-num"><?php echo hkp_e('Ready'); ?></th><th class="hkp-num"><?php echo hkp_e('Critical gaps'); ?></th><th class="hkp-num"><?php echo hkp_e('Certificates'); ?></th></tr></thead><tbody>
<?php foreach ($compare as $c): ?><tr><td><strong><?php echo hkp_h(hkp_pick($c, 'name')); ?></strong></td><td><?php echo hkp_badge($c['operational_status'] === 'operational' ? 'active' : 'warning', hkp_label($c['operational_status'])); ?></td><td class="hkp-num"><?php echo (int) $c['staff']; ?></td><td style="min-width:130px"><?php echo hkp_bar($c['completion']); ?> <span class="hkp-small"><?php echo hkp_pct($c['completion']); ?></span></td><td class="hkp-num"><?php echo hkp_pct($c['ready_pct']); ?></td><td class="hkp-num"><?php echo $c['critical'] ? hkp_badge('critical', $c['critical']) : 0; ?></td><td class="hkp-num"><?php echo (int) $c['certs']; ?></td></tr><?php endforeach; ?>
<?php if (!$compare): ?><tr><td colspan="7"><p class="hkp-muted"><?php echo hkp_e('No properties in your current scope. Add a property to start tracking performance.'); ?></p></td></tr><?php endif; ?></tbody></table></div></section>
<div class="hkp-grid hkp-grid--2"><section class="hkp-card"><div class="studio-section-head"><h2><?php echo hkp_e('Recent activity'); ?></h2><?php if ($this->ha_auth->has('audit_logs.view')): ?><a class="hkp-btn hkp-btn--ghost hkp-btn--sm" href="<?php echo hkp_url('admin/audit'); ?>"><?php echo hkp_e('View audit'); ?> →</a><?php endif; ?></div><ul class="hkp-list"><?php foreach ($recent as $r): ?><li><span class="hkp-small"><strong><?php echo hkp_h($r['actor_name'] ?: hkp_t('System')); ?></strong><br><?php echo hkp_h($r['description'] ?: $r['action']); ?></span><span class="hkp-small hkp-muted"><?php echo hkp_date($r['created_at'], true); ?></span></li><?php endforeach; ?><?php if (!$recent): ?><li><?php echo hkp_e('Your team’s activity will appear here.'); ?></li><?php endif; ?></ul></section>
<section class="hkp-card"><span class="studio-tag"><?php echo hkp_icon('spark'); ?> <?php echo hkp_e('Content Studio'); ?></span><h2 style="margin-top:18px"><?php echo hkp_e('Make your standards teachable'); ?></h2><p class="hkp-small hkp-muted"><?php echo hkp_e('Convert a PDF into editable learning content, or improve your website beside a live preview.'); ?></p><div class="hkp-actions"><?php if ($this->ha_auth->has_all(array('ai.generate', 'courses.create'))): ?><a class="hkp-btn" href="<?php echo hkp_url('cms/publisher'); ?>"><?php echo hkp_e('Upload a document'); ?></a><?php endif; ?><?php if ($this->ha_auth->has('cms_pages.view')): ?><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('cms'); ?>"><?php echo hkp_e('Edit website'); ?></a><?php endif; ?></div><hr style="border:0;border-top:1px solid var(--line);margin:22px 0"><div class="hkp-small hkp-muted"><?php echo hkp_number($s['courses']); ?> <?php echo hkp_e('published modules'); ?> · <?php echo hkp_number($s['lessons']); ?> <?php echo hkp_e('lessons'); ?> · <?php echo hkp_number($s['assessments']); ?> <?php echo hkp_e('assessments'); ?></div></section></div>
