<?php $crit = $r ? $r['criteria'] : array(); $total = array_sum(array_column($crit, 'weight')); ?>
<div class="hkp-head"><div><div class="hkp-eyebrow"><a href="<?php echo hkp_url('admin/competencies'); ?>"><?php echo hkp_e('Competencies'); ?></a></div><h1><?php echo $r ? hkp_h(hkp_pick($r, 'title')) : hkp_e('New rubric'); ?></h1>
<p><?php echo hkp_e('Weights are relative; the score is the weighted share earned. Changing a rubric that already has results creates a new version.'); ?></p></div></div>
<form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('admin/competencies/rubric_save/' . ($r ? $r['id'] : 0)); ?>"><?php echo ha_csrf_field(); ?>
  <div class="hkp-row"><div class="hkp-field"><label for="rt"><?php echo hkp_e('Title (English)'); ?></label><input id="rt" class="hkp-input" name="title_en" required value="<?php echo hkp_h($r ? $r['title_en'] : ''); ?>"></div>
    <div class="hkp-field"><label for="rta"><?php echo hkp_e('Title (Arabic)'); ?></label><input id="rta" class="hkp-input" dir="rtl" name="title_ar" value="<?php echo hkp_h($r ? $r['title_ar'] : ''); ?>"></div>
    <div class="hkp-field"><label for="rs"><?php echo hkp_e('Competency measured'); ?></label><select id="rs" class="hkp-select" name="skill_id"><option value=""></option><?php foreach ($skills as $s): ?><option value="<?php echo (int) $s['id']; ?>"<?php echo $r && (int) $r['skill_id'] === (int) $s['id'] ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($s, 'name')); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="rst"><?php echo hkp_e('Status'); ?></label><select id="rst" class="hkp-select" name="status"><?php foreach (array('draft', 'published', 'archived') as $s): ?><option value="<?php echo $s; ?>"<?php echo $r && $r['status'] === $s ? ' selected' : ''; ?>><?php echo hkp_label($s); ?></option><?php endforeach; ?></select></div></div>
  <div class="hkp-row"><div class="hkp-field"><label for="rd"><?php echo hkp_e('Developing from (%)'); ?></label><input id="rd" class="hkp-input" type="number" step="0.1" name="developing_threshold" value="<?php echo $r ? (float) $r['developing_threshold'] : 50; ?>"></div>
    <div class="hkp-field"><label for="rc"><?php echo hkp_e('Competent from (%)'); ?></label><input id="rc" class="hkp-input" type="number" step="0.1" name="pass_threshold" value="<?php echo $r ? (float) $r['pass_threshold'] : 75; ?>"></div>
    <div class="hkp-field"><label for="re"><?php echo hkp_e('Exceeds from (%)'); ?></label><input id="re" class="hkp-input" type="number" step="0.1" name="exceeds_threshold" value="<?php echo $r ? (float) $r['exceeds_threshold'] : 90; ?>"></div></div>
  <div class="hkp-field"><label for="rdesc"><?php echo hkp_e('Description'); ?></label><textarea id="rdesc" class="hkp-input" name="description_en" rows="2"><?php echo hkp_h($r ? $r['description_en'] : ''); ?></textarea></div>
  <h2><?php echo hkp_e('Criteria'); ?> <span class="hkp-small hkp-muted"><?php echo hkp_e('total weight {w}', array('w' => $total)); ?></span></h2>
  <?php $rows = $crit; $n = count($rows); for ($i = $n; $i < $n + 4; $i++) { $rows[$i] = array('id' => '', 'label_en' => '', 'label_ar' => '', 'weight' => 10, 'is_critical' => 0); } ?>
  <?php foreach ($rows as $i => $c): ?><div class="hkp-actions"><input type="hidden" name="crit[<?php echo $i; ?>][id]" value="<?php echo hkp_h($c['id']); ?>">
    <input class="hkp-input" style="flex:3" name="crit[<?php echo $i; ?>][label_en]" value="<?php echo hkp_h($c['label_en']); ?>" placeholder="<?php echo hkp_e('Criterion (English)'); ?>" aria-label="<?php echo hkp_e('Criterion (English)'); ?>">
    <input class="hkp-input" style="flex:3" dir="rtl" name="crit[<?php echo $i; ?>][label_ar]" value="<?php echo hkp_h($c['label_ar']); ?>" placeholder="<?php echo hkp_e('Criterion (Arabic)'); ?>" aria-label="<?php echo hkp_e('Criterion (Arabic)'); ?>">
    <input class="hkp-input" style="flex:1" type="number" step="0.5" name="crit[<?php echo $i; ?>][weight]" value="<?php echo (float) $c['weight']; ?>" aria-label="<?php echo hkp_e('Weight'); ?>">
    <label class="hkp-check"><input type="checkbox" name="crit[<?php echo $i; ?>][critical]" value="1"<?php echo (int) $c['is_critical'] ? ' checked' : ''; ?>> <?php echo hkp_e('Critical'); ?></label></div><?php endforeach; ?>
  <div><button class="hkp-btn"><?php echo hkp_e('Save rubric'); ?></button></div></form>
