<div class="hkp-head"><div><h1><?php echo hkp_e('Advisory frameworks'); ?></h1><p><?php echo hkp_e('Altus Performance Matrix™, GOPPAR Value Stack™, ESG and institutional capabilities, scored on a 1–5 scale. Scoring thresholds are configuration, not code.'); ?></p></div></div>
<div class="hkp-grid hkp-grid--2" style="margin-bottom:1rem">
<?php foreach ($fw as $f): ?><section class="hkp-card"><h2><?php echo hkp_h(hkp_pick($f, 'name')); ?></h2>
  <p class="hkp-small"><?php foreach ($f['dimensions'] as $d): ?><?php echo hkp_badge('neutral', hkp_pick($d, 'name')); ?> <?php endforeach; ?></p>
  <?php if (!empty($f['config']['note'])): ?><p class="hkp-small hkp-muted"><?php echo hkp_h($f['config']['note']); ?></p><?php endif; ?>
  <?php if ($this->ha_auth->has('frameworks.configure')): ?><details><summary class="hkp-small"><?php echo hkp_e('Scoring configuration'); ?></summary><form method="post" action="<?php echo hkp_url('admin/frameworks/config/' . $f['id']); ?>" class="hkp-form"><?php echo ha_csrf_field(); ?><textarea class="hkp-input" name="config_json" rows="5" aria-label="<?php echo hkp_e('Scoring configuration'); ?>"><?php echo hkp_h(json_encode($f['config'], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE)); ?></textarea><div><button class="hkp-btn hkp-btn--sm"><?php echo hkp_e('Save'); ?></button></div></form></details><?php endif; ?>
  <?php if ($this->ha_auth->has('frameworks.assess')): ?><form class="hkp-actions" method="post" action="<?php echo hkp_url('admin/frameworks/start'); ?>" style="margin-top:.6rem"><?php echo ha_csrf_field(); ?><input type="hidden" name="framework_id" value="<?php echo (int) $f['id']; ?>">
    <select class="hkp-select" name="organization_id" aria-label="<?php echo hkp_e('Client'); ?>" style="max-width:180px"><?php foreach ($orgs as $o): ?><option value="<?php echo (int) $o['id']; ?>"><?php echo hkp_h($o['name_en']); ?></option><?php endforeach; ?></select>
    <select class="hkp-select" name="property_id" aria-label="<?php echo hkp_e('Property'); ?>" style="max-width:180px"><option value=""><?php echo hkp_e('Whole client'); ?></option><?php foreach ($props as $p): ?><option value="<?php echo (int) $p['id']; ?>"><?php echo hkp_h($p['name_en']); ?></option><?php endforeach; ?></select>
    <button class="hkp-btn hkp-btn--sm"><?php echo hkp_e('Assess'); ?></button></form><?php endif; ?></section><?php endforeach; ?>
</div>
<section class="hkp-card"><h2><?php echo hkp_e('Assessments'); ?></h2><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Title'); ?></th><th><?php echo hkp_e('Framework'); ?></th><th><?php echo hkp_e('Client'); ?></th><th><?php echo hkp_e('Result'); ?></th><th><?php echo hkp_e('Date'); ?></th></tr></thead><tbody>
<?php foreach ($rows as $a): ?><tr><td><a href="<?php echo hkp_url('admin/frameworks/assess/' . $a['id']); ?>"><?php echo hkp_h($a['title']); ?></a></td><td class="hkp-small"><?php echo hkp_h(hkp_pick($a, 'fw')); ?></td><td class="hkp-small"><?php echo hkp_h($a['org_en']); ?></td><td><?php echo $a['result_label'] ? hkp_badge('neutral', hkp_label($a['result_label'])) : hkp_badge($a['status']); ?></td><td class="hkp-small"><?php echo hkp_date($a['assessed_at'] ?: $a['created_at']); ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
