<?php $cov = array(); foreach ($coverage as $c) { $cov[$c['coverage']] = (int) $c['n']; } ?>
<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_e('Intelligence & Performance'); ?></div><h1><?php echo hkp_e('AI governance'); ?></h1>
<p><?php echo hkp_e('The assistant answers only from approved, published, current knowledge in the asker\'s scope. Every question, the passages retrieved and the answer are logged.'); ?></p></div>
<form method="post" action="<?php echo hkp_url('admin/ai/reindex'); ?>"><?php echo ha_csrf_field(); ?><button class="hkp-btn hkp-btn--ghost"><?php echo hkp_e('Rebuild index'); ?></button></form></div>
<div class="hkp-grid hkp-grid--4" style="margin-bottom:1rem">
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Knowledge items indexed'); ?></span><span class="hkp-tile__value"><?php echo (int) $status['knowledge_items']; ?></span><span class="hkp-tile__foot"><?php echo hkp_e('of {n} published · {x} excluded', array('n' => $status['published_items'], 'x' => $status['ai_disabled_items'])); ?></span></div>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Lessons indexed'); ?></span><span class="hkp-tile__value"><?php echo (int) $status['lessons']; ?></span><span class="hkp-tile__foot"><?php echo hkp_e('{n} passages · {t}', array('n' => $status['chunks'], 't' => hkp_date($status['last_indexed'], true))); ?></span></div>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Answered (30 days)'); ?></span><span class="hkp-tile__value"><?php echo isset($cov['answered']) ? $cov['answered'] : 0; ?></span><span class="hkp-tile__foot"><?php echo hkp_e('{n} refused for lack of approved knowledge', array('n' => isset($cov['insufficient']) ? $cov['insufficient'] : 0)); ?></span></div>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Model'); ?></span><span class="hkp-tile__value" style="font-size:1rem"><?php echo $route ? hkp_h($route['provider_slug'] . ' / ' . $route['model_id']) : hkp_e('Not connected'); ?></span>
    <a href="<?php echo site_url('ha_ai/routes'); ?>"><?php echo $route ? hkp_e('Change in task routing') : hkp_e('Connect a model (task: knowledge_answer)'); ?> →</a></div>
</div>
<div class="hkp-grid hkp-grid--main">
<form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('admin/ai/save'); ?>"><?php echo ha_csrf_field(); ?><h2><?php echo hkp_e('Controls'); ?></h2>
  <label class="hkp-check"><input type="checkbox" name="ai_enabled" value="1"<?php echo $this->ha_tenant->get('ai.enabled') ? ' checked' : ''; ?>> <?php echo hkp_e('Assistant enabled for the platform'); ?></label>
  <div class="hkp-row"><div class="hkp-field"><label for="ams"><?php echo hkp_e('Sources per answer'); ?></label><input id="ams" class="hkp-input" type="number" name="ai_max_sources" value="<?php echo (int) $this->ha_tenant->get('ai.max_sources'); ?>"></div>
    <div class="hkp-field"><label for="amr"><?php echo hkp_e('Minimum relevance (0–1)'); ?></label><input id="amr" class="hkp-input" type="number" step="0.01" name="ai_min_relevance" value="<?php echo (float) $this->ha_tenant->get('ai.min_relevance'); ?>"></div>
    <div class="hkp-field"><label for="amt"><?php echo hkp_e('Maximum answer tokens'); ?></label><input id="amt" class="hkp-input" type="number" name="ai_max_answer_tokens" value="<?php echo (int) $this->ha_tenant->get('ai.max_answer_tokens'); ?>"></div>
    <div class="hkp-field"><label for="aml"><?php echo hkp_e('Questions per person per day'); ?></label><input id="aml" class="hkp-input" type="number" name="ai_daily_limit_per_user" value="<?php echo (int) $this->ha_tenant->get('ai.daily_limit_per_user'); ?>"></div></div>
  <div class="hkp-field"><label for="asi"><?php echo hkp_e('Additional system instructions'); ?></label><textarea id="asi" class="hkp-input" name="ai_system_instructions" rows="3"><?php echo hkp_h($this->ha_tenant->get('ai.system_instructions')); ?></textarea><span class="hkp-help"><?php echo hkp_e('Appended to the governed prompt. They cannot relax the governance rules.'); ?></span></div>
  <h3><?php echo hkp_e('Per client'); ?></h3><?php foreach ($orgs as $o): ?><input type="hidden" name="org_enabled[<?php echo (int) $o['id']; ?>]" value="0"><label class="hkp-check"><input type="checkbox" name="org_enabled[<?php echo (int) $o['id']; ?>]" value="1"<?php echo $o['ai_enabled'] ? ' checked' : ''; ?>> <?php echo hkp_h($o['name_en']); ?></label><?php endforeach; ?>
  <div><button class="hkp-btn"><?php echo hkp_e('Save'); ?></button></div>
  <details><summary class="hkp-small"><?php echo hkp_e('The governed system prompt'); ?></summary><pre class="hkp-small" style="white-space:pre-wrap"><?php echo hkp_h($prompt); ?></pre></details></form>
<section class="hkp-card"><h2><?php echo hkp_e('Approved sources'); ?></h2><p class="hkp-small hkp-muted"><?php echo hkp_e('Only published items can be sources. Exclude any item from the assistant without unpublishing it.'); ?></p>
  <ul class="hkp-list" style="max-height:520px;overflow:auto"><?php foreach ($sources as $s): ?><li><span class="hkp-small"><?php echo hkp_h($s['title'] ?: $s['code']); ?></span>
    <form method="post" action="<?php echo hkp_url('admin/content/ai_toggle/' . $s['id']); ?>"><?php echo ha_csrf_field(); ?><button class="hkp-btn hkp-btn--sm <?php echo (int) $s['ai_enabled'] ? '' : 'hkp-btn--ghost'; ?>"><?php echo (int) $s['ai_enabled'] ? hkp_e('Included') : hkp_e('Excluded'); ?></button></form></li><?php endforeach; ?></ul></section>
</div>
<section class="hkp-card" style="margin-top:1rem"><h2><?php echo hkp_e('Query log'); ?></h2><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Time'); ?></th><th><?php echo hkp_e('User'); ?></th><th><?php echo hkp_e('Question'); ?></th><th><?php echo hkp_e('Coverage'); ?></th><th><?php echo hkp_e('Sources'); ?></th><th class="hkp-num"><?php echo hkp_e('Tokens'); ?></th></tr></thead><tbody>
<?php foreach ($queries as $q): $src = json_decode((string) $q['sources_json'], true) ?: array(); ?><tr><td class="hkp-small"><?php echo hkp_date($q['created_at'], true); ?></td><td class="hkp-small"><?php echo hkp_h(trim($q['first_name'] . ' ' . $q['last_name'])); ?></td><td class="hkp-small" dir="auto"><?php echo hkp_h(mb_substr($q['question'], 0, 120)); ?></td><td><?php echo hkp_badge($q['coverage']); ?></td><td class="hkp-small"><?php echo hkp_h(implode(', ', array_column($src, 'title'))); ?></td><td class="hkp-num"><?php echo (int) $q['input_tokens'] + (int) $q['output_tokens']; ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
