<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_e('Learning content'); ?></div><h1><?php echo hkp_e('Modules & lessons'); ?></h1>
<p><?php echo hkp_e('Create and edit modules and lessons: text, YouTube or Vimeo links, uploaded video, PDF, PowerPoint and audio, with drip release. Published modules appear in the LMS automatically.'); ?></p></div>
<div class="hkp-actions"><?php if ($this->ha_auth->has('courses.create')): ?><a class="hkp-btn" href="<?php echo hkp_url('cms/module'); ?>"><?php echo hkp_e('New module'); ?></a><?php endif; ?><a class="hkp-btn hkp-btn--ghost" href="<?php echo site_url('ha_ai/studio'); ?>"><?php echo hkp_icon('spark'); ?> <?php echo hkp_e('Generate a whole course with AI'); ?></a></div></div>
<form class="hkp-card hkp-actions" method="get" style="margin-bottom:1rem"><label class="hkp-sr" for="mq"><?php echo hkp_e('Search'); ?></label><input id="mq" class="hkp-input" style="flex:1" name="q" value="<?php echo hkp_h($q); ?>"><button class="hkp-btn"><?php echo hkp_e('Search'); ?></button></form>
<section class="hkp-card"><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Module'); ?></th><th><?php echo hkp_e('Domain'); ?></th><th class="hkp-num"><?php echo hkp_e('Lessons'); ?></th><th><?php echo hkp_e('Scope'); ?></th><th><?php echo hkp_e('Status'); ?></th><th></th></tr></thead><tbody>
<?php foreach ($rows as $c): ?><tr><td><a href="<?php echo hkp_url('cms/module/' . $c['id']); ?>"><strong><?php echo hkp_h(hkp_pick($c, 'title') ?: $c['code']); ?></strong></a><div class="hkp-small hkp-muted"><?php echo hkp_h($c['code']); ?></div></td>
  <td class="hkp-small"><?php echo hkp_h(hkp_pick($c, 'domain')); ?></td><td class="hkp-num"><?php echo (int) $c['lessons']; ?></td><td class="hkp-small"><?php echo $c['organization_id'] ? hkp_e('Client') : hkp_e('Altus global'); ?></td><td><?php echo hkp_badge($c['status']); ?></td>
  <td><a class="hkp-btn hkp-btn--sm" href="<?php echo hkp_url('cms/module/' . $c['id']); ?>"><?php echo hkp_e('Edit'); ?></a></td></tr><?php endforeach; ?>
</tbody></table></div></section>
