<?php $k = $b['kpis']; ?>
<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_h(hkp_pick($brand, 'brand_name')); ?></div><h1><?php echo hkp_e('Board report: capability and readiness'); ?></h1>
<?php foreach ($lines as $l): ?><div class="hkp-small hkp-muted"><?php echo hkp_h($l); ?></div><?php endforeach; ?><div class="hkp-small hkp-muted"><?php echo hkp_e('Data freshness: calculated {t} from live records.', array('t' => hkp_date($k['calculated_at'], true))); ?></div></div>
<button class="hkp-btn hkp-noprint" onclick="window.print()"><?php echo hkp_e('Print / save as PDF'); ?></button></div>
<section class="hkp-card" style="margin-bottom:1rem"><h2><?php echo hkp_e('Executive summary'); ?></h2>
  <p><?php echo hkp_e('{p} people in scope. Learning completion {l}; competency coverage {c}; readiness {r}; certification {x}. {g} critical capability gaps and {o} overdue corrective actions are open.', array('p' => $b['people'], 'l' => hkp_pct($k['learning_completion']), 'c' => hkp_pct($k['competency_coverage']), 'r' => hkp_pct($k['readiness_rate']), 'x' => hkp_pct($k['certification_rate']), 'g' => $k['critical_gaps'], 'o' => $k['overdue_actions'])); ?></p></section>
<div class="hkp-grid hkp-grid--2" style="margin-bottom:1rem">
  <section class="hkp-card"><h2><?php echo hkp_e('Key risks'); ?></h2><ul class="hkp-list"><?php foreach ($b['risks'] as $n => $r): ?><li><span><?php echo hkp_h($n); ?></span><span><?php echo (int) $r['n']; ?> <?php echo $r['critical'] ? hkp_badge('critical', $r['critical'] . ' ' . hkp_t('critical')) : ''; ?></span></li><?php endforeach; ?></ul><?php if (!$b['risks']): ?><p class="hkp-muted"><?php echo hkp_e('No open capability gaps.'); ?></p><?php endif; ?></section>
  <section class="hkp-card"><h2><?php echo hkp_e('Corrective actions'); ?></h2><ul class="hkp-list"><?php foreach ($actions as $a): ?><li><span><?php echo hkp_label($a['status']); ?></span><strong><?php echo (int) $a['n']; ?></strong></li><?php endforeach; ?></ul></section>
  <section class="hkp-card"><h2><?php echo hkp_e('Readiness by property'); ?></h2><ul class="hkp-list"><?php foreach ($b['readiness'] as $pid => $s): $pr = $this->db->select('name_en, name_ar')->get_where('ha_property', array('id' => $pid))->row_array(); ?><li><span><?php echo hkp_h($pr ? hkp_pick($pr, 'name') : '—'); ?></span><span><?php echo hkp_pct($s['ready_pct']); ?> <?php echo hkp_e('ready'); ?> · <?php echo (int) $s['conditional']; ?> <?php echo hkp_e('conditional'); ?> · <?php echo (int) $s['not_ready']; ?> <?php echo hkp_e('not ready'); ?></span></li><?php endforeach; ?></ul></section>
  <section class="hkp-card"><h2><?php echo hkp_e('Advisory engagements'); ?></h2><ul class="hkp-list"><?php foreach ($engagements as $e): ?><li><span><?php echo hkp_h($e['name']); ?></span><?php echo hkp_badge($e['status']); ?></li><?php endforeach; ?></ul><?php if (!$engagements): ?><p class="hkp-muted"><?php echo hkp_e('None active.'); ?></p><?php endif; ?></section>
</div>
<section class="hkp-card"><h2><?php echo hkp_e('Observations'); ?></h2>
  <ul><?php if ($k['critical_gaps']): ?><li><?php echo hkp_e('Close critical gaps first: they block readiness regardless of learning completion.'); ?></li><?php endif; ?>
    <?php if ($k['learning_completion'] !== null && $k['competency_coverage'] !== null && $k['learning_completion'] - $k['competency_coverage'] > 15): ?><li><?php echo hkp_e('Learning completion is well ahead of verified competency: schedule practical assessments.'); ?></li><?php endif; ?>
    <?php if ($k['overdue_actions']): ?><li><?php echo hkp_e('Overdue corrective actions keep people conditional: review them with department heads.'); ?></li><?php endif; ?></ul>
  <p class="hkp-small hkp-muted"><?php echo hkp_e('Sources: {s}.', array('s' => implode(', ', $b['sources']))); ?></p></section>
