<?php $k = $b['kpis']; $pn = array(); foreach ($props as $p) { $pn[$p['id']] = hkp_pick($p, 'name'); } ?>
<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_e('Are capabilities improving and where is risk?'); ?></div><h1><?php echo hkp_e('Executive overview'); ?></h1>
<p><?php echo hkp_e('Aggregated capability, readiness and performance. No individual employee data is shown here.'); ?></p></div><a class="hkp-btn" href="<?php echo hkp_url('exec/board'); ?>"><?php echo hkp_icon('file'); ?> <?php echo hkp_e('Board report'); ?></a></div>
<form class="hkp-card hkp-actions" method="get" style="margin-bottom:1rem"><label for="xp"><?php echo hkp_e('Property'); ?></label><select id="xp" class="hkp-select" name="property_id" style="max-width:260px"><option value=""><?php echo hkp_e('Whole portfolio'); ?></option><?php foreach ($props as $p): ?><option value="<?php echo (int) $p['id']; ?>"<?php echo (int) $f['property_id'] === (int) $p['id'] ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($p, 'name')); ?></option><?php endforeach; ?></select>
  <label for="xd"><?php echo hkp_e('Department'); ?></label><select id="xd" class="hkp-select" name="department_id" style="max-width:200px"><option value=""><?php echo hkp_e('All'); ?></option><?php foreach ($depts as $d): ?><option value="<?php echo (int) $d['id']; ?>"<?php echo (int) $f['department_id'] === (int) $d['id'] ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($d, 'name')); ?></option><?php endforeach; ?></select>
  <label for="xf"><?php echo hkp_e('From'); ?></label><input id="xf" class="hkp-input" type="date" name="from" value="<?php echo hkp_h($f['from']); ?>" style="max-width:170px"><button class="hkp-btn"><?php echo hkp_e('Apply'); ?></button></form>
<div class="hkp-grid hkp-grid--4" style="margin-bottom:1rem">
<?php foreach (array('learning_completion' => 'Training adoption', 'competency_coverage' => 'Competency coverage', 'readiness_rate' => 'Readiness rate', 'certification_rate' => 'Certification rate') as $key => $l): ?>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e($l); ?></span><span class="hkp-tile__value"><?php echo hkp_pct($k[$key]); ?></span><?php echo hkp_bar($k[$key]); ?></div><?php endforeach; ?>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Critical capability gaps'); ?></span><span class="hkp-tile__value"><?php echo (int) $k['critical_gaps']; ?></span></div>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Overdue corrective actions'); ?></span><span class="hkp-tile__value"><?php echo (int) $k['overdue_actions']; ?></span></div>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('People in scope'); ?></span><span class="hkp-tile__value"><?php echo (int) $b['people']; ?></span></div>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Data as of'); ?></span><span class="hkp-tile__value" style="font-size:1rem"><?php echo hkp_date($k['calculated_at'], true); ?></span><span class="hkp-tile__foot"><?php echo hkp_e('live'); ?></span></div>
</div>
<div class="hkp-grid hkp-grid--2" style="margin-bottom:1rem">
  <section class="hkp-card"><h2><?php echo hkp_e('Property readiness'); ?></h2><table class="hkp-table"><tbody><?php foreach ($b['readiness'] as $pid => $s): ?><tr><td><?php echo hkp_h(isset($pn[$pid]) ? $pn[$pid] : '—'); ?></td><td style="min-width:160px"><div class="hkp-stack"><?php foreach (array('ready', 'conditional', 'not_ready', 'not_calculated') as $st): if (!$s[$st]) continue; ?><span class="<?php echo $st; ?>" style="inline-size:<?php echo round(100 * $s[$st] / max(1, $s['total']), 1); ?>%"></span><?php endforeach; ?></div></td><td class="hkp-num"><?php echo hkp_pct($s['ready_pct']); ?></td></tr><?php endforeach; ?></tbody></table>
    <div class="hkp-legend"><span><i style="background:var(--ok)"></i><?php echo hkp_e('Ready'); ?></span><span><i style="background:var(--accent)"></i><?php echo hkp_e('Conditional'); ?></span><span><i style="background:var(--bad)"></i><?php echo hkp_e('Not ready'); ?></span></div></section>
  <section class="hkp-card"><h2><?php echo hkp_e('Where the risk is'); ?></h2><?php if (!$b['risks']): ?><p class="hkp-muted"><?php echo hkp_e('No open capability gaps.'); ?></p><?php endif; ?>
    <table class="hkp-table"><tbody><?php foreach ($b['risks'] as $name => $r): ?><tr><td><?php echo hkp_h($name); ?></td><td class="hkp-num"><?php echo (int) $r['n']; ?> <?php echo hkp_e('open'); ?></td><td class="hkp-num"><?php echo $r['critical'] ? hkp_badge('critical', $r['critical']) : ''; ?></td></tr><?php endforeach; ?></tbody></table></section>
</div>
<section class="hkp-card" style="margin-bottom:1rem"><h2><?php echo hkp_e('Operational KPIs'); ?></h2><p class="hkp-small hkp-muted"><?php echo hkp_e('From PMS, POS, BI or manual entry. Each figure shows its reporting period; properties without data show nothing rather than an estimate.'); ?></p>
  <div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Property'); ?></th><?php foreach (array('revpar' => 'RevPAR', 'goppar' => 'GOPPAR', 'occupancy' => 'Occupancy', 'pickup' => 'Pickup', 'guest_sentiment' => 'Sentiment', 'payroll_productivity' => 'Payroll productivity') as $c => $l): ?><th class="hkp-num"><?php echo hkp_e($l); ?></th><?php endforeach; ?></tr></thead><tbody>
  <?php foreach ($props as $p): ?><tr><td><?php echo hkp_h(hkp_pick($p, 'name')); ?></td><?php foreach (array('revpar', 'goppar', 'occupancy', 'pickup', 'guest_sentiment', 'payroll_productivity') as $c): $v = isset($kpis[$p['id']][$c]) ? $kpis[$p['id']][$c] : null; ?>
    <td class="hkp-num"><?php echo $v ? hkp_number($v['value']['actual'], 1) . ' ' . hkp_badge($v['status'], '') . '<div class="hkp-small hkp-muted">' . hkp_h($v['value']['period_start']) . '</div>' : '<span class="hkp-muted">—</span>'; ?></td><?php endforeach; ?></tr><?php endforeach; ?>
  </tbody></table></div></section>
<section class="hkp-card"><h2><?php echo hkp_e('Completion trend'); ?></h2><?php if (!$b['trend']): ?><p class="hkp-muted"><?php echo hkp_e('No completions in the last six months.'); ?></p><?php else: $mx = max(array_column($b['trend'], 'n')); ?>
  <table class="hkp-table"><tbody><?php foreach ($b['trend'] as $t): ?><tr><td class="hkp-small" style="width:90px"><?php echo hkp_h($t['m']); ?></td><td><?php echo hkp_bar(100 * $t['n'] / max(1, $mx), 'accent'); ?></td><td class="hkp-num"><?php echo (int) $t['n']; ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></section>
