<?php $imported = $draft && $draft['entity_id']; ?>
<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_e('From source to learning'); ?></div><h1><?php echo hkp_e('AI Publisher'); ?></h1><p><?php echo hkp_e('Your operational knowledge. A structured draft. A human decision.'); ?></p></div><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('cms/publisher'); ?>"><?php echo hkp_e('New document'); ?></a></div>
<div class="studio-steps"><span class="<?php echo !$draft ? 'is-current' : ''; ?>"><strong>1</strong><?php echo hkp_e('Upload source'); ?></span><span class="<?php echo $draft && !$draft['payload_json'] ? 'is-current' : ''; ?>"><strong>2</strong><?php echo hkp_e('Analyse & generate'); ?></span><span class="<?php echo $draft && $draft['payload_json'] && !$imported ? 'is-current' : ''; ?>"><strong>3</strong><?php echo hkp_e('Review & edit'); ?></span><span class="<?php echo $imported ? 'is-current' : ''; ?>"><strong>4</strong><?php echo hkp_e('Create draft'); ?></span></div>
<?php if (!$draft): ?>
<div class="studio-review"><form class="hkp-card hkp-form" method="post" enctype="multipart/form-data" action="<?php echo hkp_url('cms/publisher'); ?>"><h2><?php echo hkp_e('Bring your knowledge'); ?></h2><p class="hkp-muted hkp-small"><?php echo hkp_e('Upload a document or paste your source. Extraction happens locally.'); ?></p><?php echo ha_csrf_field(); ?>
<div class="studio-upload"><?php echo hkp_icon('upload'); ?><h3><?php echo hkp_e('A document is all you need'); ?></h3><p class="hkp-small hkp-muted">PDF · DOCX · PPTX · TXT · MD · JSON / 15 MB</p><label class="hkp-sr" for="publisher-file"><?php echo hkp_e('Source document'); ?></label><input id="publisher-file" type="file" name="source_file" accept=".pdf,.docx,.pptx,.txt,.md,.json"></div>
<div class="hkp-field"><label for="publisher-source"><?php echo hkp_e('Or paste source text'); ?></label><textarea class="hkp-input" id="publisher-source" name="source" rows="7" placeholder="<?php echo hkp_e('Paste your SOP, operational standard or training brief…'); ?>"></textarea></div>
<div class="hkp-row"><div class="hkp-field"><label for="publisher-target"><?php echo hkp_e('What would you like to create?'); ?></label><select id="publisher-target" class="hkp-select" name="target"><?php if ($this->ha_auth->has('courses.create')): ?><option value="course"><?php echo hkp_e('Course, modules, lessons & quiz'); ?></option><?php endif; ?><?php if ($this->ha_auth->is_system_scoped() && $this->ha_auth->has('cms_pages.create')): ?><option value="page"><?php echo hkp_e('Website page & sections'); ?></option><?php endif; ?></select></div><div class="hkp-field"><label for="publisher-locale"><?php echo hkp_e('Draft language'); ?></label><select id="publisher-locale" class="hkp-select" name="locale"><option value="en">English</option><option value="ar">العربية</option></select></div></div>
<button class="hkp-btn"><?php echo hkp_e('Analyse document'); ?> <?php echo hkp_icon('arrow'); ?></button></form>
<section class="hkp-card"><span class="studio-tag"><?php echo hkp_icon('shield'); ?> <?php echo hkp_e('Draft first'); ?></span><h2 style="margin-top:20px"><?php echo hkp_e('Make knowledge useful on shift'); ?></h2><p class="hkp-muted hkp-small"><?php echo hkp_e('Turn a housekeeping SOP into ordered modules and practical lessons. Add knowledge checks, adjust the pass mark, and edit every word before creating content.'); ?></p><ul class="hkp-list"><li><?php echo hkp_e('Compare every draft against its source'); ?></li><li><?php echo hkp_e('English and Arabic are independent drafts'); ?></li><li><?php echo hkp_e('Generated content stays unpublished'); ?></li><li><?php echo hkp_e('Scanned PDFs need OCR before upload'); ?></li></ul><p class="hkp-small"><?php echo hkp_e('AI sends the extracted source only when you explicitly choose Generate draft. Configure your approved provider in AI Studio.'); ?></p></section></div>
<?php else: ?>
<div id="publisher-workspace" data-url="<?php echo hkp_url('cms/publisher_action/' . $draft['id']); ?>" data-version="<?php echo (int) $draft['version']; ?>" data-target="<?php echo hkp_h($draft['target']); ?>" data-imported="<?php echo $imported ? '1' : '0'; ?>" data-locale="<?php echo hkp_h($draft['locale']); ?>">
<?php if ($imported): ?><div class="hkp-flash hkp-flash--ok"><?php echo hkp_e('Your draft package is created. Continue editing, review and publish through the existing content workflow.'); ?> <a href="<?php echo hkp_url('cms/' . ($draft['target'] === 'course' ? 'module/' : 'page/') . $draft['entity_id']); ?>"><?php echo hkp_e('Open builder'); ?> →</a></div><?php endif; ?>
<div class="studio-review"><section class="hkp-card"><div class="studio-section-head"><h2><?php echo hkp_e('Source document'); ?></h2><span class="studio-tag"><?php echo strtoupper(hkp_h($draft['locale'])); ?></span></div><p class="hkp-small"><strong><?php echo hkp_h($draft['source_name']); ?></strong> · <?php echo hkp_number(mb_strlen($draft['source_text'])); ?> <?php echo hkp_e('characters'); ?></p><pre class="studio-source"><?php echo hkp_h($draft['source_text']); ?></pre></section>
<section class="hkp-card"><div class="studio-section-head"><h2><?php echo hkp_e('Structured draft'); ?></h2><span class="studio-tag"><?php echo hkp_icon('spark'); ?> <?php echo hkp_e('AI Draft'); ?></span></div>
<?php if (!$imported): ?><details<?php echo !$draft['payload_json'] ? ' open' : ''; ?>><summary><?php echo hkp_e('Generation settings'); ?></summary><div class="hkp-form" style="margin-top:14px"><div class="hkp-row"><div class="hkp-field"><label for="publisher-provider"><?php echo hkp_e('Provider'); ?></label><select class="hkp-select" id="publisher-provider"><option value=""><?php echo hkp_e('Choose provider'); ?></option><?php foreach ($models as $provider): ?><option value="<?php echo hkp_h($provider['slug']); ?>"><?php echo hkp_h($provider['name']); ?></option><?php endforeach; ?></select></div><div class="hkp-field"><label for="publisher-model"><?php echo hkp_e('Model'); ?></label><select id="publisher-model" class="hkp-select"></select></div></div><div class="hkp-field"><label for="publisher-brief"><?php echo hkp_e('Editorial brief'); ?></label><textarea id="publisher-brief" class="hkp-input" rows="3" placeholder="<?php echo hkp_e('Audience, difficulty, number of lessons, quiz questions…'); ?>"></textarea></div><p class="hkp-small hkp-muted"><?php echo hkp_e('Generate sends this extracted source to your chosen provider for drafting. Review all facts and answers before use.'); ?></p><button class="hkp-btn" type="button" data-publisher-action="generate"><?php echo hkp_icon('spark'); ?> <?php echo hkp_e('Generate draft'); ?></button><?php if (!$models): ?><p role="status"><?php echo hkp_e('No enabled provider. Configure AI Studio → Providers and sync its models first.'); ?></p><?php endif; ?></div></details><?php endif; ?>
<p id="publisher-status" role="status" aria-live="polite" class="hkp-small hkp-muted"></p><div id="publisher-visual" class="hkp-form"></div>
<details style="margin:18px 0"><summary><?php echo hkp_e('Advanced: structured JSON / import'); ?></summary><label class="hkp-sr" for="publisher-json"><?php echo hkp_e('Structured JSON draft'); ?></label><textarea id="publisher-json" class="hkp-input studio-json"<?php echo $imported ? ' readonly' : ''; ?>><?php echo hkp_h($draft['payload_json'] ? json_encode(json_decode($draft['payload_json'], true), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) : ''); ?></textarea><button type="button" class="hkp-btn hkp-btn--ghost" id="publisher-use-json"><?php echo hkp_e('Load into editor'); ?></button></details>
<?php if (!$imported): ?><div class="hkp-actions"><button class="hkp-btn hkp-btn--ghost" type="button" data-publisher-action="save"><?php echo hkp_e('Save draft'); ?></button><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('cms/publisher_preview/' . $draft['id']); ?>" target="_blank" rel="noopener"><?php echo hkp_e('Preview saved draft'); ?></a><button class="hkp-btn" type="button" data-publisher-action="import"><?php echo hkp_e('Create content as draft'); ?> <?php echo hkp_icon('arrow'); ?></button></div><?php endif; ?>
</section></div></div>
<script id="publisher-models" type="application/json"><?php echo json_encode($models, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?></script>
<script src="<?php echo hkp_asset('assets/hkp/document-publisher.js'); ?>" defer></script>
<?php endif; ?>
<?php if ($drafts): ?><section class="hkp-card" style="margin-top:24px"><h2><?php echo hkp_e('Recent documents'); ?></h2><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Source'); ?></th><th><?php echo hkp_e('Output'); ?></th><th><?php echo hkp_e('Language'); ?></th><th><?php echo hkp_e('Status'); ?></th><th><?php echo hkp_e('Created'); ?></th></tr></thead><tbody><?php foreach ($drafts as $row): ?><tr><td><a href="<?php echo hkp_url('cms/publisher/' . $row['id']); ?>"><?php echo hkp_h($row['source_name']); ?></a></td><td><?php echo hkp_label($row['target']); ?></td><td><?php echo strtoupper(hkp_h($row['locale'])); ?></td><td><?php echo hkp_badge($row['status']); ?></td><td><?php echo hkp_date($row['created_at'], true); ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
