<?php $imported = $draft && $draft['entity_id']; $pages = $job ? (array) $job['pages'] : array(); $worker = $health['worker']; $failing = array_filter($health['checks'], function ($c) { return !$c['ok']; }); ?>
<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_e('From source to learning'); ?></div><h1><?php echo hkp_e('AI Publisher'); ?></h1><p><?php echo hkp_e('Your operational knowledge. A structured draft. A human decision.'); ?></p></div><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('cms/publisher'); ?>"><?php echo hkp_e('New document'); ?></a></div>
<div class="studio-steps"><span class="<?php echo !$draft ? 'is-current' : ''; ?>"><strong>1</strong><?php echo hkp_e('Upload source'); ?></span><span class="<?php echo $draft && !$draft['payload_json'] ? 'is-current' : ''; ?>"><strong>2</strong><?php echo hkp_e('Analyse & generate'); ?></span><span class="<?php echo $draft && $draft['payload_json'] && !$imported ? 'is-current' : ''; ?>"><strong>3</strong><?php echo hkp_e('Review & edit'); ?></span><span class="<?php echo $imported ? 'is-current' : ''; ?>"><strong>4</strong><?php echo hkp_e('Create draft'); ?></span></div>
<details class="hkp-card" id="publisher-health" style="margin-bottom:18px"<?php echo $failing && !$draft ? ' open' : ''; ?>>
<summary><strong><?php echo hkp_e('Setup & worker health'); ?></strong> · <span data-health-summary><?php echo $failing ? count($failing) . ' ' . hkp_e('item(s) need attention') : hkp_e('All checks passed'); ?></span> · <span id="publisher-worker-status" data-alive="<?php echo $worker['alive'] ? '1' : '0'; ?>"><?php echo $worker['alive'] ? hkp_e('Worker running') : hkp_e('Worker not running'); ?><?php if ($worker['last_heartbeat']): ?> (<?php echo hkp_e('last heartbeat'); ?> <?php echo hkp_h($worker['last_heartbeat']); ?>)<?php endif; ?></span></summary>
<div class="hkp-table-wrap" style="margin-top:12px"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Check'); ?></th><th><?php echo hkp_e('Status'); ?></th><th><?php echo hkp_e('Details'); ?></th><th><?php echo hkp_e('What to do'); ?></th></tr></thead><tbody>
<?php foreach ($health['checks'] as $c): ?><tr data-health-check="<?php echo hkp_h($c['key']); ?>" data-ok="<?php echo $c['ok'] ? '1' : '0'; ?>"><td><?php echo hkp_h($c['label']); ?></td><td><?php echo hkp_badge($c['ok'] ? 'ready' : 'blocked', $c['ok'] ? hkp_t('OK') : hkp_t('Action needed')); ?></td><td class="hkp-small"><?php echo hkp_h($c['detail']); ?></td><td class="hkp-small"><?php echo hkp_h($c['fix']); ?></td></tr><?php endforeach; ?>
</tbody></table></div>
<p class="hkp-small" style="overflow-wrap:anywhere"><?php echo hkp_e('Worker command (run as a service):'); ?> <code><?php echo hkp_h($worker['command']); ?></code> · <?php echo hkp_e('or schedule every minute:'); ?> <code><?php echo hkp_h($worker['batch_command']); ?></code> (<code>tools/publisher-worker-task.ps1</code> / cron <code>* * * * * cd /path/to/app &amp;&amp; php index.php publisher_cli work 25</code>). <?php echo hkp_e('Queued jobs'); ?>: <?php echo (int) $worker['queued']; ?>.</p>
<p class="hkp-small hkp-muted"><?php echo hkp_e('Paths are set in application/config/ha_publisher.php or the ALTUS_PUBLISHER_PYTHON, ALTUS_TESSERACT and ALTUS_TESSDATA environment variables.'); ?> <a href="?refresh_health=1"><?php echo hkp_e('Re-run checks'); ?></a></p></details>
<?php if (!$draft): ?>
<div class="studio-review"><form class="hkp-card hkp-form" method="post" enctype="multipart/form-data" action="<?php echo hkp_url('cms/publisher'); ?>"><h2><?php echo hkp_e('Bring your knowledge'); ?></h2><p class="hkp-muted hkp-small"><?php echo hkp_e('Upload a document or paste your source. Extraction happens locally.'); ?></p><?php echo ha_csrf_field(); ?>
<div class="studio-upload"><?php echo hkp_icon('upload'); ?><h3><?php echo hkp_e('A document is all you need'); ?></h3><p class="hkp-small hkp-muted">PDF · DOCX · PPTX · TXT · MD · JSON / 15 MB</p><label class="hkp-sr" for="publisher-file"><?php echo hkp_e('Source document'); ?></label><input id="publisher-file" type="file" name="source_file" accept=".pdf,.docx,.pptx,.txt,.md,.json"></div>
<div class="hkp-field"><label for="publisher-source"><?php echo hkp_e('Or paste source text'); ?></label><textarea class="hkp-input" id="publisher-source" name="source" rows="7" placeholder="<?php echo hkp_e('Paste your SOP, operational standard or training brief…'); ?>"></textarea></div>
<div class="hkp-row"><div class="hkp-field"><label for="publisher-target"><?php echo hkp_e('What would you like to create?'); ?></label><select id="publisher-target" class="hkp-select" name="target"><?php if ($this->ha_auth->has('courses.create')): ?><option value="course"><?php echo hkp_e('Course, modules, lessons & quiz'); ?></option><?php endif; ?><?php if ($this->ha_auth->is_system_scoped() && $this->ha_auth->has('cms_pages.create')): ?><option value="page"><?php echo hkp_e('Website page & sections'); ?></option><?php endif; ?><?php if ($this->ha_auth->has('knowledge.create')): ?><option value="sop">SOP resource</option><?php endif; ?><?php if ($this->ha_auth->is_system_scoped() && $this->ha_auth->has('articles.create')): ?><option value="article">Article</option><?php endif; ?><?php if ($this->ha_auth->is_system_scoped() && $this->ha_auth->has('cms_pages.create')): ?><option value="topic">Hospitality topic</option><?php endif; ?></select></div><div class="hkp-field"><label for="publisher-locale"><?php echo hkp_e('Draft language'); ?></label><select id="publisher-locale" class="hkp-select" name="locale"><option value="en">English</option><option value="ar">العربية</option></select></div></div>
<button class="hkp-btn"><?php echo hkp_e('Analyse document'); ?> <?php echo hkp_icon('arrow'); ?></button></form>
<section class="hkp-card"><span class="studio-tag"><?php echo hkp_icon('shield'); ?> <?php echo hkp_e('Draft first'); ?></span><h2 style="margin-top:20px"><?php echo hkp_e('Make knowledge useful on shift'); ?></h2><p class="hkp-muted hkp-small"><?php echo hkp_e('Turn a housekeeping SOP into ordered modules and practical lessons. Add knowledge checks, adjust the pass mark, and edit every word before creating content.'); ?></p><ul class="hkp-list"><li><?php echo hkp_e('Compare every draft against its source'); ?></li><li><?php echo hkp_e('English and Arabic are independent drafts'); ?></li><li><?php echo hkp_e('Generated content stays unpublished'); ?></li><li><?php echo hkp_e('Scanned PDFs use local English and Arabic OCR'); ?></li></ul><p class="hkp-small"><?php echo hkp_e('AI sends the extracted source only when you explicitly choose Generate draft. Configure your approved provider in AI Studio.'); ?></p></section></div>
<?php else: ?>
<div id="publisher-workspace" data-url="<?php echo hkp_url('cms/publisher_action/' . $draft['id']); ?>" data-version="<?php echo (int) $draft['version']; ?>" data-target="<?php echo hkp_h($draft['target']); ?>" data-imported="<?php echo $imported ? '1' : '0'; ?>" data-locale="<?php echo hkp_h($draft['locale']); ?>" data-media-url="<?php echo hkp_url('cms/media_picker'); ?>" data-base-url="<?php echo hkp_h(base_url()); ?>">
<?php if ($imported): ?><div class="hkp-flash hkp-flash--ok"><?php echo hkp_e('Your draft package is created. Continue editing, review and publish through the existing content workflow.'); ?> <a href="<?php echo $this->ha_document_publisher->edit_url($draft,$draft['entity_id']); ?>"><?php echo hkp_e('Open builder'); ?> →</a></div><?php endif; ?>
<div class="studio-review"><section class="hkp-card"><div class="studio-section-head"><h2><?php echo hkp_e('Source document'); ?></h2><span class="studio-tag"><?php echo strtoupper(hkp_h($draft['locale'])); ?></span></div><p class="hkp-small"><strong><?php echo hkp_h($draft['source_name']); ?></strong> · <?php echo hkp_number(mb_strlen($draft['source_text'])); ?> <?php echo hkp_e('characters'); ?></p>
<?php if ($draft['status']==='extracting'): ?><div id="document-progress" data-status-url="<?= hkp_url('cms/document_status/'.$draft['id']) ?>"><progress max="100" value="<?php echo $job ? (int) $job['progress'] : 0; ?>"></progress><p role="status"><?php echo $job && $job['error'] ? hkp_h($job['error']) : hkp_e('Queued for local extraction. The document worker must be running.'); ?></p><p class="hkp-small hkp-muted" data-job-attempts><?php if ($job): ?><?php echo hkp_e('Attempts'); ?>: <?php echo (int) $job['attempts']; ?> / <?php echo (int) $job['attempt_limit']; ?><?php endif; ?></p><?php if (!$worker['alive']): ?><p class="hkp-small" data-worker-warning><?php echo hkp_e('No worker heartbeat. Start it with'); ?> <code><?php echo hkp_h($worker['command']); ?></code></p><?php endif; ?><button type="button" class="hkp-btn hkp-btn--ghost" data-document-action="cancel"><?php echo hkp_e('Cancel extraction'); ?></button><button type="button" class="hkp-btn hkp-btn--ghost" data-document-action="retry"><?php echo hkp_e('Retry extraction'); ?></button></div>
<?php else: ?>
<?php if ($pages): ?><details id="publisher-provenance" open style="margin-bottom:12px"><summary><?php echo hkp_e('Page provenance'); ?> · <?php echo count($pages); ?> <?php echo hkp_e('pages'); ?><?php $review = count(array_filter($pages, function ($p) { return !empty($p['review_required']); })); if ($review): ?> · <strong><?php echo (int) $review; ?> <?php echo hkp_e('need review'); ?></strong><?php endif; ?></summary><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Page'); ?></th><th><?php echo hkp_e('Method'); ?></th><th><?php echo hkp_e('Characters'); ?></th><th><?php echo hkp_e('Review'); ?></th></tr></thead><tbody>
<?php foreach ($pages as $pg): $method = ($pg['method'] ?? '') === 'ocr' ? 'ocr' : 'text'; ?><tr data-page="<?php echo (int) $pg['page']; ?>" data-method="<?php echo $method; ?>"><td><button type="button" class="hkp-btn hkp-btn--sm hkp-btn--ghost" data-jump-page="<?php echo (int) $pg['page']; ?>"><?php echo hkp_e('Page'); ?> <?php echo (int) $pg['page']; ?></button></td><td><?php echo $method === 'ocr' ? 'OCR' : hkp_e('Text'); ?></td><td><?php echo hkp_number((int) ($pg['characters'] ?? 0)); ?></td><td><?php echo !empty($pg['review_required']) ? hkp_badge('review') : '—'; ?></td></tr><?php endforeach; ?>
</tbody></table></div><p class="hkp-small hkp-muted"><?php echo hkp_e('OCR and low-text pages need a human check. [Page N] markers in the source are kept so generated sections can cite their pages.'); ?></p></details><?php endif; ?>
<textarea id="publisher-source-correction" class="hkp-input studio-source" rows="18"<?= $imported?' readonly':'' ?>><?= hkp_h($draft['source_text']) ?></textarea><?php if (!$imported): ?><button type="button" class="hkp-btn hkp-btn--ghost" id="publisher-source-save"><?php echo hkp_e('Save corrected source'); ?></button><?php endif; ?><?php endif; ?></section>
<section class="hkp-card"><div class="studio-section-head"><h2><?php echo hkp_e('Structured draft'); ?></h2><span class="studio-tag"><?php echo hkp_icon('spark'); ?> <?php echo hkp_e('AI Draft'); ?></span></div>
<?php if (!$imported): ?><details<?php echo !$draft['payload_json'] ? ' open' : ''; ?>><summary><?php echo hkp_e('Generation settings'); ?></summary><div class="hkp-form" style="margin-top:14px"><div class="hkp-row"><div class="hkp-field"><label for="publisher-provider"><?php echo hkp_e('Provider'); ?></label><select class="hkp-select" id="publisher-provider" disabled><option value=""><?php echo hkp_e('Choose provider'); ?></option><?php foreach ($models as $provider): ?><option value="<?php echo hkp_h($provider['slug']); ?>"><?php echo hkp_h($provider['name']); ?></option><?php endforeach; ?></select></div><div class="hkp-field"><label for="publisher-model"><?php echo hkp_e('Model'); ?></label><select id="publisher-model" class="hkp-select"></select></div></div><div class="hkp-field"><label for="publisher-brief"><?php echo hkp_e('Editorial brief'); ?></label><textarea id="publisher-brief" class="hkp-input" rows="3" placeholder="<?php echo hkp_e('Audience, difficulty, number of lessons, quiz questions…'); ?>"></textarea></div><p class="hkp-small hkp-muted"><?php echo hkp_e('Generate sends this extracted source to your chosen provider for drafting. Review all facts and answers before use.'); ?></p><button class="hkp-btn" type="button" data-publisher-action="generate"><?php echo hkp_icon('spark'); ?> <?php echo hkp_e('Generate draft'); ?></button><button class="hkp-btn hkp-btn--ghost" type="button" data-publisher-action="translate">Translate saved draft to <?= $draft['locale']==='en'?'Arabic':'English' ?></button><?php if (!$models): ?><p role="status"><?php echo hkp_e('No enabled provider. Configure AI Studio → Providers and sync its models first.'); ?></p><?php endif; ?></div></details><?php endif; ?>
<?php if ($draft['target'] !== 'sop' && ($can_media || $media)): ?><div class="hkp-field" id="publisher-media" style="margin:14px 0"><strong><?php echo hkp_e('Featured image'); ?></strong><div data-media-current><?php if ($media): ?><img src="<?php echo hkp_h(base_url($media['file_path'])); ?>" alt="<?php echo hkp_h($media['alt_en'] ?: $media['original_name']); ?>" style="max-width:220px;border-radius:8px;display:block;margin:8px 0"><span class="hkp-small" data-media-name><?php echo hkp_h($media['original_name']); ?></span><?php else: ?><span class="hkp-small hkp-muted" data-media-name><?php echo hkp_e('No image selected. It is applied to the created content.'); ?></span><?php endif; ?></div>
<?php if (!$imported && $can_media): ?><div class="hkp-actions"><button type="button" class="hkp-btn hkp-btn--sm hkp-btn--ghost" id="publisher-media-choose"><?php echo hkp_e('Choose from media library'); ?></button><?php if ($media): ?><button type="button" class="hkp-btn hkp-btn--sm hkp-btn--ghost" id="publisher-media-clear"><?php echo hkp_e('Remove image'); ?></button><?php endif; ?></div><div id="publisher-media-picker" hidden><label class="hkp-sr" for="publisher-media-search"><?php echo hkp_e('Search images'); ?></label><input id="publisher-media-search" class="hkp-input" type="search" placeholder="<?php echo hkp_e('Search images'); ?>"><div data-media-grid style="display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));gap:8px;margin-top:8px"></div></div><?php endif; ?></div><?php endif; ?>
<p id="publisher-status" role="status" aria-live="polite" class="hkp-small hkp-muted"></p><div id="publisher-visual" class="hkp-form"></div>
<details style="margin:18px 0"><summary><?php echo hkp_e('Advanced: structured JSON / import'); ?></summary><label class="hkp-sr" for="publisher-json"><?php echo hkp_e('Structured JSON draft'); ?></label><textarea id="publisher-json" class="hkp-input studio-json"<?php echo $imported ? ' readonly' : ''; ?>><?php echo hkp_h($draft['payload_json'] ? json_encode(json_decode($draft['payload_json'], true), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) : ''); ?></textarea><button type="button" class="hkp-btn hkp-btn--ghost" id="publisher-use-json"><?php echo hkp_e('Load into editor'); ?></button></details>
<?php if (!$imported && $draft['target'] === 'sop'): ?><fieldset class="hkp-card" id="publisher-governance" style="margin:14px 0"><legend><strong><?php echo hkp_e('Knowledge review'); ?></strong></legend><p class="hkp-small hkp-muted"><?php echo hkp_e('The SOP is created as a governed knowledge draft. It is never approved or published automatically.'); ?></p><div class="hkp-row"><div class="hkp-field"><label for="publisher-reviewer"><?php echo hkp_e('Reviewer'); ?></label><select id="publisher-reviewer" class="hkp-select"><option value=""></option><?php foreach ($reviewers as $r): ?><option value="<?php echo (int) $r['id']; ?>"><?php echo hkp_h(trim($r['first_name'] . ' ' . $r['last_name'])); ?></option><?php endforeach; ?></select></div><div class="hkp-field"><label for="publisher-approver"><?php echo hkp_e('Approver'); ?></label><select id="publisher-approver" class="hkp-select"><option value=""></option><?php foreach ($reviewers as $r): ?><option value="<?php echo (int) $r['id']; ?>"><?php echo hkp_h(trim($r['first_name'] . ' ' . $r['last_name'])); ?></option><?php endforeach; ?></select></div></div><label class="hkp-small"><input type="checkbox" id="publisher-submit-review" value="1"> <?php echo hkp_e('Submit for internal review after creating'); ?></label></fieldset><?php endif; ?>
<?php if (!$imported): ?><div class="hkp-actions"><button class="hkp-btn hkp-btn--ghost" type="button" data-publisher-action="save"><?php echo hkp_e('Save draft'); ?></button><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('cms/publisher_preview/' . $draft['id']); ?>" target="_blank" rel="noopener"><?php echo hkp_e('Preview saved draft'); ?></a><button class="hkp-btn" type="button" data-publisher-action="import"><?php echo hkp_e('Create content as draft'); ?> <?php echo hkp_icon('arrow'); ?></button></div><?php endif; ?>
</section></div></div>
<script id="publisher-models" type="application/json"><?php echo json_encode($models, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT); ?></script>
<script src="<?php echo hkp_asset('assets/hkp/document-publisher.js'); ?>" defer></script>
<?php endif; ?>
<?php if ($drafts): ?><section class="hkp-card" style="margin-top:24px"><h2><?php echo hkp_e('Recent documents'); ?></h2><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Source'); ?></th><th><?php echo hkp_e('Output'); ?></th><th><?php echo hkp_e('Language'); ?></th><th><?php echo hkp_e('Status'); ?></th><th><?php echo hkp_e('Created'); ?></th></tr></thead><tbody><?php foreach ($drafts as $row): ?><tr><td><a href="<?php echo hkp_url('cms/publisher/' . $row['id']); ?>"><?php echo hkp_h($row['source_name']); ?></a></td><td><?php echo hkp_label($row['target']); ?></td><td><?php echo strtoupper(hkp_h($row['locale'])); ?></td><td><?php echo hkp_badge($row['status']); ?></td><td><?php echo hkp_date($row['created_at'], true); ?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
