<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_e('Website'); ?></div><h1><?php echo hkp_e('Navigation & footer'); ?></h1><p><?php echo hkp_e('Clear menus in both languages. Drag to reorder, or use Alt + arrow keys. Required page addresses stay protected.'); ?></p></div></div>
<div class="hkp-tabs"><?php foreach ($menus as $menu): ?><a href="<?php echo hkp_url('cms/navigation') . '?menu=' . (int) $menu['id']; ?>" class="<?php echo $selected_menu['id'] === $menu['id'] ? 'is-active' : ''; ?>"><?php echo hkp_h(hkp_pick($menu, 'name')); ?></a><?php endforeach; ?></div>
<?php if ($selected_menu): ?><form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('cms/navigation'); ?>" id="studio-menu-form"><?php echo ha_csrf_field(); ?><input type="hidden" name="menu_id" value="<?php echo (int) $selected_menu['id']; ?>">
<ol class="hkp-sortable" data-sortable="" id="studio-menu-list">
<?php foreach ($items as $i => $item): ?><li data-id="<?php echo $i; ?>" tabindex="0" class="studio-menu-item"><input type="hidden" name="items[<?php echo $i; ?>][id]" value="<?php echo (int) $item['id']; ?>"><span class="hkp-muted">⠿</span><div style="flex:1;min-width:0"><div class="hkp-row"><div class="hkp-field"><label><?php echo hkp_e('English label'); ?><input class="hkp-input" name="items[<?php echo $i; ?>][label_en]" value="<?php echo hkp_h($item['label_en']); ?>" required></label></div><div class="hkp-field"><label><?php echo hkp_e('Arabic label'); ?><input class="hkp-input" name="items[<?php echo $i; ?>][label_ar]" value="<?php echo hkp_h($item['label_ar']); ?>" dir="rtl"></label></div></div><div class="hkp-row"><div class="hkp-field"><label><?php echo hkp_e('English path'); ?><input class="hkp-input" name="items[<?php echo $i; ?>][url_en]" value="<?php echo hkp_h($item['url_en']); ?>"></label></div><div class="hkp-field"><label><?php echo hkp_e('Arabic path'); ?><input class="hkp-input" name="items[<?php echo $i; ?>][url_ar]" value="<?php echo hkp_h($item['url_ar']); ?>"></label></div></div><label><input type="checkbox" name="items[<?php echo $i; ?>][visible]" value="1"<?php echo $item['status'] === 'active' ? ' checked' : ''; ?>> <?php echo hkp_e('Visible'); ?></label></div></li><?php endforeach; ?>
</ol><div class="hkp-actions"><button class="hkp-btn" type="submit"><?php echo hkp_e('Save navigation'); ?></button><button class="hkp-btn hkp-btn--ghost" type="button" id="studio-add-link"><?php echo hkp_e('Add link'); ?></button><a class="hkp-btn hkp-btn--ghost" href="<?php echo base_url('en'); ?>" target="_blank" rel="noopener"><?php echo hkp_e('View website'); ?></a></div></form>
<script>
document.getElementById('studio-add-link').addEventListener('click',function(){var list=document.getElementById('studio-menu-list'),li=document.createElement('li');li.tabIndex=0;li.dataset.id='new-'+Date.now();li.className='studio-menu-item';var content=document.createElement('div');content.style.width='100%';['label_en','label_ar','url_en','url_ar'].forEach(function(k){var label=document.createElement('label');label.className='hkp-field';label.textContent=k.replace('_',' ');var input=document.createElement('input');input.className='hkp-input';input.name='items[new'+Date.now()+']['+k+']';input.dataset.menuField=k;if(k==='label_ar')input.dir='rtl';label.appendChild(input);content.appendChild(label);});var visible=document.createElement('input');visible.type='hidden';visible.value='1';visible.dataset.menuField='visible';content.appendChild(visible);li.appendChild(content);list.appendChild(li);li.querySelector('input').focus();});
document.getElementById('studio-menu-form').addEventListener('submit',function(){Array.from(document.getElementById('studio-menu-list').children).forEach(function(li,i){li.querySelectorAll('[name],[data-menu-field]').forEach(function(el){var key=el.dataset.menuField || el.name.match(/\[([^\]]+)\]$/)[1];el.name='items['+i+']['+key+']';});});});
</script><?php endif; ?>
