<?php
if (!empty($draft_state) && $draft_state['version']) {
    $formdraft = $draft_state['payload'];
    foreach (array('en','ar') as $loc) {
        $record['row']['slug_'.$loc] = $formdraft['slug_'.$loc];
        foreach (array('title','summary','body') as $f) { $col=$f==='summary'?$def['summary']:($f==='body'?$def['body']:'title'); if (!$col) continue; if (isset($def['translation'])) $record['tr'][$loc][$col]=$formdraft[$f.'_'.$loc]; else $record['row'][$col.'_'.$loc]=$formdraft[$f.'_'.$loc]; }
    }
    $record['row'][$def['image']]=$formdraft['image']??'';
    foreach (array('level','duration_hours','department_code','topic_type','city') as $f) if (isset($formdraft[$f])) $record['row'][$f]=$formdraft[$f];
    if ($type==='paths' && isset($formdraft['steps_json'])) $record['steps']=json_decode($formdraft['steps_json'],true);
    if (isset($formdraft['courses'])) $record['courses']=array_map(function($id){ return array('course_id'=>$id); },$formdraft['courses']);
}
?>
<?php $base = hkp_url('cms/catalogue/' . $type); $row = $record['row'] ?? array(); $value = function ($loc, $field) use ($record, $def, $row) { $key = $field === 'summary' ? $def['summary'] : ($field === 'body' ? $def['body'] : 'title'); return isset($def['translation']) ? ($record['tr'][$loc][$key] ?? '') : ($row[$key . '_' . $loc] ?? ''); }; ?>
<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_e('Content Studio'); ?></div><h1><?php echo hkp_e($def['title']); ?></h1><p><?php echo hkp_e('Manage the public catalogue in English and Arabic. Save drafts, review, then publish with the appropriate permission.'); ?></p></div><div class="hkp-actions"><a class="hkp-btn hkp-btn--ghost" href="<?php echo base_url('en/' . $def['route']); ?>" target="_blank" rel="noopener"><?php echo hkp_e('View website'); ?></a><?php if ($this->ha_auth->has($def['perm'] . '.create')): ?><a class="hkp-btn" href="<?php echo $base . '/new'; ?>">+ <?php echo hkp_e('Create content'); ?></a><?php endif; ?></div></div>
<?php if ($editing && $record): ?><div class="hkp-card hkp-actions" style="margin-bottom:1rem"><?php echo hkp_content_view_buttons($type, $row['id'], $row['status']); ?><?php if ($this->ha_auth->has($def['perm'] . '.update')) { echo hkp_content_view_buttons($type, $row['id'], $row['status'], true); } ?><a class="hkp-btn hkp-btn--ghost" href="<?php echo $base; ?>"><?php echo hkp_e('Back to list'); ?></a></div><?php endif; ?>
<?php if ($editing): ?><form class="hkp-card hkp-form" method="post" action="<?php echo ($record ? hkp_url('cms/catalogue_draft/' . $type) : $base) . '/' . (int) ($row['id'] ?? 0); ?>"><?php echo ha_csrf_field(); ?><?php if ($record): ?><input type="hidden" name="draft_version" value="<?php echo (int)$draft_state['version']; ?>"><input type="hidden" name="base_hash" value="<?php echo hkp_h($draft_state['base_hash']); ?>"><p class="hkp-muted">Edits stay in a private draft. Publish the saved draft after review.</p><?php if ($draft_state['version'] && $this->ha_auth->has($def['perm'].'.publish')): ?><button class="hkp-btn" name="action" value="publish" type="submit">Publish saved draft</button><?php endif; ?><?php endif; ?><input type="hidden" name="version" value="<?php echo $record ? hkp_h($this->ha_studio_catalogue->hash($record)) : ''; ?>"><div class="hkp-grid hkp-grid--2"><?php foreach (array('en', 'ar') as $loc): ?><section><h2><?php echo $loc === 'en' ? 'English' : 'العربية'; ?></h2><div class="hkp-field"><label><?php echo hkp_e('Title'); ?><input name="title_<?php echo $loc; ?>" class="hkp-input" value="<?php echo hkp_h($value($loc, 'title')); ?>" required<?php echo $loc === 'ar' ? ' dir="rtl"' : ''; ?>></label></div><div class="hkp-field"><label><?php echo hkp_e('Address'); ?><input name="slug_<?php echo $loc; ?>" class="hkp-input" value="<?php echo hkp_h($row['slug_' . $loc] ?? ''); ?>" required></label></div><?php if ($def['summary']): ?><div class="hkp-field"><label><?php echo hkp_e('Summary'); ?><textarea name="summary_<?php echo $loc; ?>" class="hkp-input" rows="3"<?php echo $loc === 'ar' ? ' dir="rtl"' : ''; ?>><?php echo hkp_h($value($loc, 'summary')); ?></textarea></label></div><?php endif; ?><div class="hkp-field"><label><?php echo hkp_e('Content'); ?><textarea name="body_<?php echo $loc; ?>" class="hkp-input" rows="10"<?php echo $loc === 'ar' ? ' dir="rtl"' : ''; ?>><?php echo hkp_h($value($loc, 'body')); ?></textarea></label></div></section><?php endforeach; ?></div>
<div class="hkp-row"><div class="hkp-field"><label><?php echo hkp_e('Image path'); ?><input class="hkp-input" name="image" value="<?php echo hkp_h($row[$def['image']] ?? ''); ?>"></label></div><div class="hkp-field"><label><?php echo hkp_e('Status'); ?><select class="hkp-select" name="status"><?php foreach (array('draft', 'review', 'published', 'archived') as $s): if ($s === 'published' && !$this->ha_auth->has($def['perm'] . '.publish')) continue; ?><option value="<?php echo $s; ?>"<?php echo ($row['status'] ?? 'draft') === $s ? ' selected' : ''; ?>><?php echo hkp_label($s); ?></option><?php endforeach; ?></select></label></div><?php if ($type === 'programs'): ?><div class="hkp-field"><label><?php echo hkp_e('Level'); ?><select class="hkp-select" name="level"><?php foreach (array('foundation', 'intermediate', 'advanced', 'leadership') as $s): ?><option value="<?php echo $s; ?>"<?php echo ($row['level'] ?? '') === $s ? ' selected' : ''; ?>><?php echo hkp_label($s); ?></option><?php endforeach; ?></select></label></div><div class="hkp-field"><label><?php echo hkp_e('Duration (hours)'); ?><input class="hkp-input" type="number" step="0.5" name="duration_hours" value="<?php echo hkp_h($row['duration_hours'] ?? 0); ?>"></label></div><?php endif; ?></div>
<?php if (in_array($type, array('programs', 'topics'), true)): $selected = array_column($record['courses'] ?? array(), 'course_id'); ?><details><summary><?php echo hkp_e($type === 'programs' ? 'Courses in this program' : 'Related courses'); ?></summary><p class="hkp-small hkp-muted"><?php echo hkp_e('Select global courses. Drag to change their order.'); ?></p><ol class="hkp-sortable" data-sortable=""><?php $ordered = array(); foreach ($selected as $cid) { foreach ($courses as $c) { if ($c['id'] == $cid) $ordered[] = $c; } } foreach ($courses as $c) { if (!in_array($c['id'], $selected)) $ordered[] = $c; } foreach ($ordered as $c): ?><li tabindex="0" data-id="<?php echo (int) $c['id']; ?>"><label><input type="checkbox" name="courses[]" value="<?php echo (int) $c['id']; ?>"<?php echo in_array($c['id'], $selected) ? ' checked' : ''; ?>> <?php echo hkp_h($c['title']); ?></label></li><?php endforeach; ?></ol></details><?php endif; ?>
<?php if ($type === 'topics'): ?><div class="hkp-row"><label class="hkp-field"><?php echo hkp_e('Topic type'); ?><select name="topic_type" class="hkp-select"><?php foreach (array('pillar', 'role', 'city', 'compliance') as $tt): ?><option value="<?php echo $tt; ?>"<?php echo ($row['topic_type'] ?? 'pillar') === $tt ? ' selected' : ''; ?>><?php echo hkp_label($tt); ?></option><?php endforeach; ?></select></label><label class="hkp-field"><?php echo hkp_e('City'); ?><input class="hkp-input" name="city" value="<?php echo hkp_h($row['city'] ?? ''); ?>"></label></div><?php endif; ?>
<?php if ($type === 'paths'): ?><label class="hkp-field"><?php echo hkp_e('Department code'); ?><input class="hkp-input" name="department_code" value="<?php echo hkp_h($row['department_code'] ?? ''); ?>"></label><section id="studio-path"><h2><?php echo hkp_e('Learning sequence'); ?></h2><p class="hkp-muted hkp-small"><?php echo hkp_e('Add bilingual steps and learning items. Existing step IDs are preserved. Steps in enrolled paths cannot be removed.'); ?></p><input type="hidden" name="steps_json" id="studio-path-json"><div id="studio-path-steps"></div><button type="button" id="studio-path-add" class="hkp-btn hkp-btn--ghost"><?php echo hkp_e('Add step'); ?></button></section><script type="application/json" id="studio-path-data"><?php echo json_encode(array('steps' => $record['steps'] ?? array(), 'items' => $path_items), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_UNESCAPED_UNICODE); ?></script><script src="<?php echo hkp_asset('assets/hkp/path-editor.js'); ?>" defer></script><?php endif; ?>
<?php if ($record): ?><a class="hkp-btn hkp-btn--ghost" href="<?php echo hkp_url('cms/catalogue_live/'.$type.'/'.$record['row']['id']); ?>">Open live editor</a><?php endif; ?><div class="hkp-actions"><button class="hkp-btn"><?php echo hkp_e('Save content'); ?></button><button class="hkp-btn hkp-btn--ghost" name="after_save" value="view"><?php echo hkp_e('Save and view'); ?></button><a class="hkp-btn hkp-btn--ghost" href="<?php echo $base; ?>"><?php echo hkp_e('Back to list'); ?></a></div></form>
<?php else: ?><section class="hkp-card"><form method="get" class="hkp-actions" style="margin-bottom:18px"><label class="hkp-sr" for="catalogue-search"><?php echo hkp_e('Search'); ?></label><input id="catalogue-search" name="q" type="search" class="hkp-input" value="<?php echo hkp_h($q); ?>" placeholder="<?php echo hkp_e('Search title or address'); ?>"><button class="hkp-btn hkp-btn--ghost"><?php echo hkp_e('Search'); ?></button></form><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Title'); ?></th><th><?php echo hkp_e('Address'); ?></th><th><?php echo hkp_e('Status'); ?></th><th><?php echo hkp_e('Last updated'); ?></th><th></th></tr></thead><tbody><?php foreach ($list['rows'] as $r): ?><tr><td><strong><?php echo hkp_h($r['title_en'] ?: $r['slug_en']); ?></strong></td><td><?php echo hkp_h($r['slug_en']); ?></td><td><?php echo hkp_badge($r['status']); ?></td><td><?php echo hkp_date($r['updated_at'], true); ?></td><td><div class="hkp-actions"><a class="hkp-btn hkp-btn--sm hkp-btn--ghost" href="<?php echo $base . '/' . (int) $r['id']; ?>"><?php echo hkp_e('Edit'); ?></a><?php echo hkp_content_view_buttons($type, $r['id'], $r['status']); ?></div></td></tr><?php endforeach; ?><?php if (!$list['rows']): ?><tr><td colspan="5"><?php echo hkp_e('No matching content. Create a draft to get started.'); ?></td></tr><?php endif; ?></tbody></table></div><div class="hkp-actions" style="margin-top:16px"><?php for ($i = 1; $i <= $list['pages']; $i++): ?><a class="hkp-btn hkp-btn--sm hkp-btn--ghost" href="<?php echo $base . '?page=' . $i . '&q=' . rawurlencode($q); ?>"<?php echo $i === $page ? ' aria-current="page"' : ''; ?>><?php echo $i; ?></a><?php endfor; ?></div></section><?php endif; ?>
