<div class="hkp-head"><div><h1><?php echo hkp_e('Certifications'); ?></h1><p><?php echo hkp_e('Certificates are issued automatically when every rule is met. Managers can issue a certificate only when the same rules pass.'); ?></p></div></div>
<div class="hkp-grid hkp-grid--4" style="margin-bottom:1rem">
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Issued'); ?></span><span class="hkp-tile__value"><?php echo (int) $d['issued']; ?></span></div>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Certification rate'); ?></span><span class="hkp-tile__value"><?php echo hkp_pct($d['rate']); ?></span></div>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Expiring soon'); ?></span><span class="hkp-tile__value"><?php echo (int) $d['expiring']; ?></span></div>
  <div class="hkp-card hkp-tile"><span class="hkp-tile__label"><?php echo hkp_e('Expired'); ?></span><span class="hkp-tile__value"><?php echo (int) $d['expired']; ?></span></div>
</div>
<div class="hkp-grid hkp-grid--3" style="margin-bottom:1rem">
  <?php foreach (array('by_property' => 'By property', 'by_department' => 'By department', 'by_role' => 'By role') as $k => $l): ?><section class="hkp-card"><h2><?php echo hkp_e($l); ?></h2><ul class="hkp-list"><?php foreach ($d[$k] as $r): ?><li><span><?php echo hkp_h(hkp_pick($r, 'name')) ?: '—'; ?></span><strong><?php echo (int) $r['n']; ?></strong></li><?php endforeach; ?></ul></section><?php endforeach; ?>
</div>
<section class="hkp-card" style="margin-bottom:1rem"><h2><?php echo hkp_e('Progress towards certification'); ?></h2>
  <?php if (!$eligible): ?><p class="hkp-muted"><?php echo hkp_e('Everyone with a certification programme for their role is certified.'); ?></p><?php endif; ?>
  <div class="hkp-table-wrap"><table class="hkp-table"><tbody><?php foreach ($eligible as $e): ?><tr><td><?php echo hkp_person_open($e['person']['user_id']); ?><?php echo hkp_h($e['person']['first_name'] . ' ' . $e['person']['last_name']); ?><?php echo hkp_person_close(); ?></td><td><?php echo hkp_h(hkp_pick($e['program'], 'title')); ?></td>
    <td style="min-width:160px"><?php echo hkp_bar($e['total'] ? 100 * $e['met'] / $e['total'] : 0, 'accent'); ?> <span class="hkp-small"><?php echo (int) $e['met']; ?>/<?php echo (int) $e['total']; ?></span></td>
    <td><?php if ($e['ready'] && $this->ha_auth->has('certificates.issue')): ?><form method="post" action="<?php echo hkp_url('team/certifications/issue'); ?>"><?php echo ha_csrf_field(); ?><input type="hidden" name="user_id" value="<?php echo (int) $e['person']['user_id']; ?>"><input type="hidden" name="program_id" value="<?php echo (int) $e['program']['id']; ?>"><button class="hkp-btn hkp-btn--sm"><?php echo hkp_e('Issue'); ?></button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="hkp-card"><h2><?php echo hkp_e('Register'); ?></h2><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Number'); ?></th><th><?php echo hkp_e('Holder'); ?></th><th><?php echo hkp_e('Certificate'); ?></th><th><?php echo hkp_e('Issued'); ?></th><th><?php echo hkp_e('Expires'); ?></th><th><?php echo hkp_e('Status'); ?></th><th></th></tr></thead><tbody>
<?php foreach ($rows as $c): ?><tr><td class="hkp-small"><a href="<?php echo hkp_url('certificates/view/' . $c['id']); ?>"><?php echo hkp_h($c['certificate_no']); ?></a></td><td><?php echo hkp_h($c['first_name'] . ' ' . $c['last_name']); ?></td><td><?php echo hkp_h(hkp_pick($c, 'subject_title')); ?></td><td class="hkp-small"><?php echo hkp_date($c['issued_at']); ?></td><td class="hkp-small"><?php echo hkp_date($c['expires_at']); ?></td><td><?php echo hkp_badge($c['status']); ?></td>
  <td><?php if ($c['status'] === 'issued' && $this->ha_auth->has('certificates.revoke')): ?><form method="post" action="<?php echo hkp_url('team/certifications/revoke/' . $c['id']); ?>" class="hkp-actions" data-confirm="<?php echo hkp_e('Revoke this certificate?'); ?>"><?php echo ha_csrf_field(); ?><input class="hkp-input" name="reason" required placeholder="<?php echo hkp_e('Reason'); ?>" aria-label="<?php echo hkp_e('Reason'); ?>" style="max-width:140px"><button class="hkp-btn hkp-btn--sm hkp-btn--danger"><?php echo hkp_e('Revoke'); ?></button></form><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
