<div class="hkp-head"><div><h1><?php echo hkp_e('Quality audits'); ?></h1><p><?php echo hkp_e('Brand, SOP, safety and mystery-guest audits. A non-compliant finding opens a corrective action for the responsible person, then a recheck.'); ?></p></div></div>
<div class="hkp-grid hkp-grid--main">
  <section class="hkp-card"><div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Audit'); ?></th><th><?php echo hkp_e('Type'); ?></th><th><?php echo hkp_e('Property'); ?></th><th><?php echo hkp_e('Date'); ?></th><th class="hkp-num"><?php echo hkp_e('Score'); ?></th><th><?php echo hkp_e('Status'); ?></th></tr></thead><tbody>
  <?php foreach ($rows as $a): ?><tr><td><a href="<?php echo hkp_url('team/audits/view/' . $a['id']); ?>"><?php echo hkp_h($a['title']); ?></a></td><td class="hkp-small"><?php echo hkp_label($a['audit_type']); ?></td><td class="hkp-small"><?php echo hkp_h(hkp_pick($a, 'prop')); ?></td><td class="hkp-small"><?php echo hkp_date($a['conducted_at']); ?></td><td class="hkp-num"><?php echo hkp_pct($a['score'], 1); ?></td><td><?php echo hkp_badge($a['status']); ?></td></tr><?php endforeach; ?>
  </tbody></table></div><?php if (!$rows): ?><div class="hkp-empty"><?php echo hkp_e('No audits yet.'); ?></div><?php endif; ?></section>
  <?php if ($this->ha_auth->has('quality_audits.create')): ?><section class="hkp-card"><h2><?php echo hkp_e('New audit'); ?></h2><form class="hkp-form" method="post" action="<?php echo hkp_url('team/audits/create'); ?>"><?php echo ha_csrf_field(); ?>
    <div class="hkp-field"><label for="qt"><?php echo hkp_e('Title'); ?></label><input id="qt" class="hkp-input" name="title" required></div>
    <div class="hkp-field"><label for="qy"><?php echo hkp_e('Type'); ?></label><select id="qy" class="hkp-select" name="audit_type"><?php foreach (array('internal', 'brand_compliance', 'mystery_guest', 'safety', 'sop_compliance') as $t): ?><option value="<?php echo $t; ?>"><?php echo hkp_label($t); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="qs"><?php echo hkp_e('Standard (SOP)'); ?></label><select id="qs" class="hkp-select" name="sop_id"><option value=""></option><?php foreach ($sops as $s): ?><option value="<?php echo (int) $s['id']; ?>"><?php echo hkp_h($s['title']); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="qd"><?php echo hkp_e('Date'); ?></label><input id="qd" class="hkp-input" type="date" name="conducted_at" value="<?php echo date('Y-m-d'); ?>"></div>
    <div><button class="hkp-btn"><?php echo hkp_e('Create'); ?></button></div></form></section><?php endif; ?>
</div>
