<div class="hkp-head"><div><div class="hkp-eyebrow"><?php echo hkp_label($a['audit_type']); ?> · <?php echo hkp_h(hkp_pick($a, 'prop')); ?></div><h1><?php echo hkp_h($a['title']); ?></h1><p><?php echo hkp_date($a['conducted_at']); ?></p></div>
<span class="hkp-tile__value"><?php echo hkp_pct($a['score'], 1); ?></span></div>
<section class="hkp-card" style="margin-bottom:1rem"><h2><?php echo hkp_e('Findings'); ?></h2>
  <div class="hkp-table-wrap"><table class="hkp-table"><thead><tr><th><?php echo hkp_e('Requirement'); ?></th><th><?php echo hkp_e('Compliance'); ?></th><th><?php echo hkp_e('Severity'); ?></th><th><?php echo hkp_e('Responsible'); ?></th><th><?php echo hkp_e('Action'); ?></th><th><?php echo hkp_e('Recheck'); ?></th></tr></thead><tbody>
  <?php foreach ($a['findings'] as $f): ?><tr><td><?php echo hkp_h($f['requirement']); ?><?php if ($f['finding']): ?><div class="hkp-small hkp-muted"><?php echo hkp_h($f['finding']); ?></div><?php endif; ?></td><td><?php echo hkp_badge($f['compliance']); ?></td><td><?php echo hkp_badge($f['severity']); ?></td>
    <td class="hkp-small"><?php echo hkp_h(trim($f['first_name'] . ' ' . $f['last_name'])) ?: '—'; ?></td><td><?php if ($f['action_plan_id']): ?><a href="<?php echo hkp_url('actions/view/' . $f['action_plan_id']); ?>"><?php echo hkp_e('Action plan'); ?></a><?php endif; ?></td>
    <td><?php echo hkp_badge($f['recheck_status']); ?><?php if ($f['recheck_status'] === 'pending' && $this->ha_auth->has('quality_audits.update')): ?><form method="post" action="<?php echo hkp_url('team/audits/recheck/' . $f['id']); ?>" class="hkp-actions" style="margin-top:.3rem"><?php echo ha_csrf_field(); ?><button class="hkp-btn hkp-btn--sm" name="passed" value="1"><?php echo hkp_e('Passed'); ?></button><button class="hkp-btn hkp-btn--sm hkp-btn--ghost" name="passed" value="0"><?php echo hkp_e('Failed'); ?></button></form><?php endif; ?></td></tr><?php endforeach; ?>
  </tbody></table></div></section>
<?php if ($this->ha_auth->has('quality_audits.update')): ?>
<form class="hkp-card hkp-form" method="post" action="<?php echo hkp_url('team/audits/finding/' . $a['id']); ?>"><?php echo ha_csrf_field(); ?><h2><?php echo hkp_e('Add finding'); ?></h2>
  <div class="hkp-row"><div class="hkp-field"><label for="fr"><?php echo hkp_e('Requirement'); ?></label><input id="fr" class="hkp-input" name="requirement" required></div>
    <div class="hkp-field"><label for="fc"><?php echo hkp_e('Compliance'); ?></label><select id="fc" class="hkp-select" name="compliance"><?php foreach (array('compliant', 'partial', 'non_compliant', 'not_applicable') as $c): ?><option value="<?php echo $c; ?>"><?php echo hkp_label($c); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="fs"><?php echo hkp_e('Severity'); ?></label><select id="fs" class="hkp-select" name="severity"><?php foreach (array('low', 'medium', 'high', 'critical') as $s): ?><option value="<?php echo $s; ?>"><?php echo hkp_label($s); ?></option><?php endforeach; ?></select></div>
    <div class="hkp-field"><label for="fu"><?php echo hkp_e('Responsible person'); ?></label><select id="fu" class="hkp-select" name="responsible_user_id"><option value=""></option><?php foreach ($people as $p): ?><option value="<?php echo (int) $p['id']; ?>"><?php echo hkp_h($p['first_name'] . ' ' . $p['last_name']); ?></option><?php endforeach; ?></select></div></div>
  <div class="hkp-field"><label for="ff"><?php echo hkp_e('Finding'); ?></label><textarea id="ff" class="hkp-input" name="finding" rows="2"></textarea></div>
  <div><button class="hkp-btn"><?php echo hkp_e('Record finding'); ?></button></div></form>
<?php endif; ?>
