<div class="hkp-head"><div><h1><?php echo hkp_e('Reports'); ?></h1><p><?php echo hkp_e('Every report contains only people you are allowed to see, and carries the client, property, period, filters, date and author.'); ?></p></div></div>
<form class="hkp-card hkp-form" method="get" id="rf" style="margin-bottom:1rem"><div class="hkp-row">
  <?php if ($props): ?><div class="hkp-field"><label for="rp"><?php echo hkp_e('Property'); ?></label><select id="rp" class="hkp-select" name="property_id"><option value=""><?php echo hkp_e('All'); ?></option><?php foreach ($props as $p): ?><option value="<?php echo (int) $p['id']; ?>"<?php echo (int) $f['property_id'] === (int) $p['id'] ? ' selected' : ''; ?>><?php echo hkp_h(hkp_pick($p, 'name')); ?></option><?php endforeach; ?></select></div><?php endif; ?>
  <div class="hkp-field"><label for="rd"><?php echo hkp_e('Department'); ?></label><select id="rd" class="hkp-select" name="department_id"><option value=""><?php echo hkp_e('All'); ?></option><?php foreach ($depts as $d): ?><option value="<?php echo (int) $d['id']; ?>"><?php echo hkp_h(hkp_pick($d, 'name')); ?></option><?php endforeach; ?></select></div>
  <div class="hkp-field"><label for="rr"><?php echo hkp_e('Role'); ?></label><select id="rr" class="hkp-select" name="job_role_id"><option value=""><?php echo hkp_e('All'); ?></option><?php foreach ($roles as $r): ?><option value="<?php echo (int) $r['id']; ?>"><?php echo hkp_h(hkp_pick($r, 'title')); ?></option><?php endforeach; ?></select></div>
  <div class="hkp-field"><label for="rf1"><?php echo hkp_e('From'); ?></label><input id="rf1" class="hkp-input" type="date" name="from"></div>
  <div class="hkp-field"><label for="rt1"><?php echo hkp_e('To'); ?></label><input id="rt1" class="hkp-input" type="date" name="to"></div></div></form>
<div class="hkp-grid hkp-grid--4">
<?php foreach ($catalogue as $code => $l): ?><section class="hkp-card"><h2><?php echo hkp_h(hkp_locale() === 'ar' ? $l[1] : $l[0]); ?></h2>
  <div class="hkp-actions"><button class="hkp-btn hkp-btn--sm" form="rf" formaction="<?php echo hkp_url('team/reports/' . $code); ?>"><?php echo hkp_e('View'); ?></button>
  <?php if ($this->ha_auth->has('reports.export')): ?><button class="hkp-btn hkp-btn--sm hkp-btn--ghost" form="rf" name="format" value="xlsx" formaction="<?php echo hkp_url('team/reports/' . $code); ?>">Excel</button><button class="hkp-btn hkp-btn--sm hkp-btn--ghost" form="rf" name="format" value="csv" formaction="<?php echo hkp_url('team/reports/' . $code); ?>">CSV</button><button class="hkp-btn hkp-btn--sm hkp-btn--ghost" form="rf" name="format" value="print" formaction="<?php echo hkp_url('team/reports/' . $code); ?>">PDF</button><?php endif; ?></div></section><?php endforeach; ?>
</div>
