<?php
defined('BASEPATH') OR exit('No direct script access allowed');
require_once APPPATH . 'libraries/Ha_seeder.php';

/**
 * SOP knowledge hub content (plan sections 12, 13, 14, 15).
 *
 * Each SOP is seeded with a published v1.0 version in English and Arabic,
 * carrying the full structure the plan requires: purpose, scope,
 * responsibilities, tools, procedure, checklist, safety notes, quality
 * standard, escalation and related documents. Procedures describe the work
 * itself; no regulatory approval or certification claim is made anywhere.
 */
class Seed_sops extends Ha_seeder {

    public static function categories() {
        return array(
            array('sop-front-office',    'Front Office',      'مكتب الاستقبال'),
            array('sop-housekeeping',    'Housekeeping',      'التدبير الفندقي'),
            array('sop-engineering',     'Engineering',       'الهندسة'),
            array('sop-maintenance',     'Maintenance',       'الصيانة'),
            array('sop-food-beverage',   'Food & Beverage',   'الأغذية والمشروبات'),
            array('sop-kitchen',         'Kitchen',           'المطبخ'),
            array('sop-safety',          'Safety',            'السلامة'),
            array('sop-security',        'Security',          'الأمن'),
            array('sop-hr',              'Human Resources',   'الموارد البشرية'),
            array('sop-finance',         'Finance',           'المالية'),
            array('sop-procurement',     'Procurement',       'المشتريات'),
            array('sop-guest-experience','Guest Experience',  'تجربة الضيف'),
            array('sop-emergency',       'Emergency',         'الطوارئ'),
            array('sop-pre-opening',     'Pre-opening',       'ما قبل الافتتاح'),
        );
    }

    /**
     * code, category, department, mandatory, visibility,
     * EN title, AR title, EN body array, AR body array
     *
     * Body arrays are keyed: purpose, scope, responsibilities, tools,
     * procedure (array of steps), checklist (array), safety, quality,
     * escalation.
     */
    public static function documents() {
        return array(

            array('sop-fo-checkin', 'sop-front-office', 'FO', 1, 'organization',
                'Guest Check-in Procedure', 'إجراء تسجيل وصول الضيف',
                array(
                    'purpose' => 'To register an arriving guest accurately, hand over a correct and ready room, and create a complete record of the stay from the first minute.',
                    'scope' => 'Applies to every arrival at the front desk, including walk-ins, group arrivals and late arrivals, at all properties.',
                    'responsibilities' => 'Front Office Associate performs the check-in. Front Office Supervisor resolves exceptions. Duty Manager authorises any rate or room override.',
                    'tools' => 'Property management system, key encoder, registration card, card payment terminal, guest identification scanner.',
                    'procedure' => array(
                        'Greet the guest within ten seconds of them reaching the desk, standing, and confirm the name on the reservation.',
                        'Retrieve the booking in the PMS and confirm departure date, room type, rate and any package inclusions with the guest.',
                        'Verify identification for every adult guest and record the details the registration requires. Return the document immediately after scanning.',
                        'Confirm the guest profile: mobile number, email, company or booking source, and any stated preference.',
                        'Take payment authorisation for the room and an incidental hold. State the held amount aloud before authorising.',
                        'Check the assigned room is in a clean and inspected status before encoding the key. If it is not, assign an alternative of equal or better type.',
                        'Encode the key for the correct departure date and hand it over inside a key folder with the room number written, never said aloud.',
                        'Explain breakfast time and location, wifi access, and the direct number for the desk.',
                        'Offer luggage assistance and direct the guest to the lift.',
                        'Complete the arrival in the PMS so the room shows as occupied, and file the registration record.',
                    ),
                    'checklist' => array('Guest greeted standing', 'Reservation confirmed aloud', 'Identification verified and returned',
                        'Contact details captured', 'Payment authorised and stated', 'Room status confirmed clean',
                        'Key encoded to correct date', 'Room number not spoken aloud', 'Orientation given', 'PMS arrival completed'),
                    'safety' => 'Never state a room number within earshot of another guest. Never leave an identification document unattended on the desk.',
                    'quality' => 'Check-in completed within four minutes for an individual arrival. Registration record complete with no blank mandatory field.',
                    'escalation' => 'Escalate to the Duty Manager for any rate dispute, unavailable room type at arrival, or identification that cannot be verified.',
                ),
                array(
                    'purpose' => 'تسجيل وصول الضيف بدقة، وتسليم غرفة صحيحة وجاهزة، وإنشاء سجل كامل للإقامة منذ الدقيقة الأولى.',
                    'scope' => 'ينطبق على كل وصول في مكتب الاستقبال، بما في ذلك الضيوف بدون حجز والمجموعات والوصول المتأخر، في جميع الفنادق.',
                    'responsibilities' => 'موظف الاستقبال ينفذ التسجيل. مشرف مكتب الاستقبال يعالج الحالات الاستثنائية. مدير المناوبة يعتمد أي تغيير في السعر أو الغرفة.',
                    'tools' => 'نظام إدارة الفندق، جهاز ترميز المفاتيح، بطاقة التسجيل، جهاز الدفع، ماسح الهوية.',
                    'procedure' => array(
                        'رحّب بالضيف خلال عشر ثوانٍ من وصوله إلى المكتب، واقفاً، وأكد الاسم المدون في الحجز.',
                        'استخرج الحجز من النظام وأكد مع الضيف تاريخ المغادرة ونوع الغرفة والسعر وأي مشمولات في الباقة.',
                        'تحقق من هوية كل ضيف بالغ وسجل البيانات المطلوبة. أعد الوثيقة فوراً بعد المسح.',
                        'أكد بيانات الضيف: رقم الجوال والبريد الإلكتروني والجهة أو مصدر الحجز وأي تفضيل مذكور.',
                        'خذ تفويض الدفع لقيمة الغرفة ومبلغ احتياطي للمصاريف. اذكر المبلغ المحجوز بصوت مسموع قبل التفويض.',
                        'تأكد أن الغرفة المخصصة بحالة نظيفة ومفتشة قبل ترميز المفتاح. إن لم تكن كذلك، خصص بديلاً مساوياً أو أفضل.',
                        'رمّز المفتاح لتاريخ المغادرة الصحيح وسلّمه داخل ظرف مكتوب عليه رقم الغرفة، دون ذكره بصوت مسموع.',
                        'اشرح وقت الإفطار وموقعه وطريقة الدخول للشبكة والرقم المباشر للمكتب.',
                        'اعرض المساعدة في الأمتعة ووجّه الضيف إلى المصعد.',
                        'أكمل الوصول في النظام بحيث تظهر الغرفة مشغولة، واحفظ سجل التسجيل.',
                    ),
                    'checklist' => array('الترحيب بالضيف واقفاً', 'تأكيد الحجز بصوت مسموع', 'التحقق من الهوية وإعادتها',
                        'تسجيل بيانات التواصل', 'تفويض الدفع وذكر المبلغ', 'تأكيد نظافة الغرفة',
                        'ترميز المفتاح للتاريخ الصحيح', 'عدم ذكر رقم الغرفة بصوت مسموع', 'تقديم التعريف بالخدمات', 'إكمال الوصول في النظام'),
                    'safety' => 'لا تذكر رقم الغرفة على مسمع من ضيف آخر. لا تترك وثيقة هوية دون إشراف على المكتب.',
                    'quality' => 'إتمام التسجيل خلال أربع دقائق للوصول الفردي. سجل تسجيل مكتمل دون أي حقل إلزامي فارغ.',
                    'escalation' => 'صعّد إلى مدير المناوبة عند أي نزاع على السعر، أو عدم توفر نوع الغرفة عند الوصول، أو هوية يتعذر التحقق منها.',
                )),

            array('sop-fo-checkout', 'sop-front-office', 'FO', 1, 'organization',
                'Guest Check-out Procedure', 'إجراء تسجيل مغادرة الضيف',
                array(
                    'purpose' => 'To close a stay with a correct final bill, recover hotel property, and release the room to housekeeping without delay.',
                    'scope' => 'Applies to every departure, including express check-out and group departures.',
                    'responsibilities' => 'Front Office Associate processes the departure. Duty Manager approves any charge removal.',
                    'tools' => 'Property management system, card payment terminal, printer, minibar and late charge reports.',
                    'procedure' => array(
                        'Greet the guest and confirm the room number and name from their key folder, not by asking across the desk.',
                        'Check for outstanding charges posted after the last audit, including restaurant, minibar and telephone.',
                        'Present the folio and walk the guest through it line by line if the total is above the quoted rate.',
                        'Resolve any disputed line before taking payment. Removing a charge requires Duty Manager approval and a reason recorded in the PMS.',
                        'Settle the balance and release the incidental authorisation. Confirm the release to the guest.',
                        'Issue the invoice by email, and print only if the guest asks.',
                        'Recover the key card and any borrowed hotel property.',
                        'Ask whether the stay met expectations and record any comment in the guest profile.',
                        'Complete the departure in the PMS immediately so the room shows as vacant dirty.',
                        'Offer luggage storage or transport assistance before the guest leaves the desk.',
                    ),
                    'checklist' => array('Room and name confirmed discreetly', 'Late charges checked', 'Folio presented',
                        'Disputes resolved before payment', 'Balance settled', 'Authorisation released',
                        'Invoice sent', 'Key recovered', 'Feedback captured', 'Departure posted in PMS'),
                    'safety' => 'Never discuss a folio total within earshot of other guests. Card details are never written down.',
                    'quality' => 'Departure completed within three minutes. Room released to housekeeping within five minutes of the guest leaving.',
                    'escalation' => 'Escalate to the Duty Manager for any disputed charge, refund request or declined settlement.',
                ),
                array(
                    'purpose' => 'إنهاء الإقامة بفاتورة نهائية صحيحة، واسترجاع ممتلكات الفندق، وتحرير الغرفة للتدبير الفندقي دون تأخير.',
                    'scope' => 'ينطبق على كل مغادرة، بما في ذلك المغادرة السريعة ومغادرة المجموعات.',
                    'responsibilities' => 'موظف الاستقبال ينفذ المغادرة. مدير المناوبة يعتمد أي حذف لرسوم.',
                    'tools' => 'نظام إدارة الفندق، جهاز الدفع، الطابعة، تقارير الميني بار والرسوم المتأخرة.',
                    'procedure' => array(
                        'رحّب بالضيف وأكد رقم الغرفة والاسم من ظرف المفتاح، لا بالسؤال بصوت مسموع.',
                        'تحقق من الرسوم المرحّلة بعد آخر تدقيق، بما في ذلك المطعم والميني بار والهاتف.',
                        'اعرض الفاتورة واشرحها بنداً بنداً إذا تجاوز الإجمالي السعر المتفق عليه.',
                        'عالج أي بند معترض عليه قبل استلام الدفع. حذف أي رسم يتطلب موافقة مدير المناوبة وسبباً مسجلاً في النظام.',
                        'سدد الرصيد وحرر المبلغ الاحتياطي. أبلغ الضيف بالتحرير.',
                        'أرسل الفاتورة بالبريد الإلكتروني، واطبعها فقط عند طلب الضيف.',
                        'استرجع بطاقة المفتاح وأي ممتلكات مستعارة من الفندق.',
                        'اسأل إن كانت الإقامة قد لبت التوقعات وسجل أي ملاحظة في ملف الضيف.',
                        'أكمل المغادرة في النظام فوراً بحيث تظهر الغرفة شاغرة غير نظيفة.',
                        'اعرض حفظ الأمتعة أو المساعدة في المواصلات قبل مغادرة الضيف للمكتب.',
                    ),
                    'checklist' => array('تأكيد الغرفة والاسم بتحفظ', 'فحص الرسوم المتأخرة', 'عرض الفاتورة',
                        'حل الاعتراضات قبل الدفع', 'تسديد الرصيد', 'تحرير المبلغ الاحتياطي',
                        'إرسال الفاتورة', 'استرجاع المفتاح', 'تسجيل الملاحظات', 'ترحيل المغادرة في النظام'),
                    'safety' => 'لا تناقش إجمالي الفاتورة على مسمع من ضيوف آخرين. لا تُدوّن بيانات البطاقة إطلاقاً.',
                    'quality' => 'إتمام المغادرة خلال ثلاث دقائق. تحرير الغرفة للتدبير خلال خمس دقائق من مغادرة الضيف.',
                    'escalation' => 'صعّد إلى مدير المناوبة عند أي رسم معترض عليه أو طلب استرداد أو رفض للدفع.',
                )),

            array('sop-fo-complaint', 'sop-guest-experience', 'GR', 1, 'organization',
                'Guest Complaint Handling', 'إجراء معالجة شكاوى الضيوف',
                array(
                    'purpose' => 'To resolve a guest complaint at the first point of contact wherever possible, and to record it so the cause can be corrected.',
                    'scope' => 'Applies to every department and every channel: in person, telephone, in-stay message and post-stay review.',
                    'responsibilities' => 'Any employee receiving a complaint owns it until it is resolved or handed over by name. Department Manager approves compensation.',
                    'tools' => 'Guest feedback log, property management system profile notes, compensation authority matrix.',
                    'procedure' => array(
                        'Stop what you are doing and give the guest your full attention. Do not continue a task while listening.',
                        'Listen without interrupting until the guest has finished. Take a note of the facts, not your explanation.',
                        'Acknowledge the impact on the guest in your own words before offering anything.',
                        'Apologise for the experience without assigning blame to a colleague or a department.',
                        'Confirm your understanding back to the guest and ask what outcome they are looking for.',
                        'Resolve within your authority immediately. If it is outside your authority, say who will handle it and by when.',
                        'Agree the resolution with the guest explicitly before acting on it.',
                        'Carry out the resolution and confirm completion to the guest personally.',
                        'Record the complaint, the cause and the resolution in the feedback log the same shift.',
                        'Follow up before the guest departs to confirm the issue has not returned.',
                    ),
                    'checklist' => array('Full attention given', 'Listened without interrupting', 'Impact acknowledged',
                        'Apology given', 'Understanding confirmed', 'Outcome agreed with guest',
                        'Resolution delivered', 'Completion confirmed', 'Logged same shift', 'Follow-up before departure'),
                    'safety' => 'Withdraw and call security if a guest becomes abusive or threatening. Personal safety takes priority over resolution.',
                    'quality' => 'Acknowledged within five minutes. Resolved or ownership named within thirty minutes. Logged before end of shift.',
                    'escalation' => 'Escalate immediately for allegations of theft, injury, discrimination or food safety, and for any request for compensation above your authority.',
                ),
                array(
                    'purpose' => 'حل شكوى الضيف عند أول نقطة تواصل كلما أمكن، وتوثيقها بحيث يمكن تصحيح السبب.',
                    'scope' => 'ينطبق على كل قسم وكل قناة: شخصياً وهاتفياً ورسائل أثناء الإقامة وتقييمات ما بعد الإقامة.',
                    'responsibilities' => 'كل موظف يتلقى شكوى يتحمل مسؤوليتها حتى تُحل أو تُسلَّم لشخص محدد بالاسم. مدير القسم يعتمد التعويض.',
                    'tools' => 'سجل ملاحظات الضيوف، ملاحظات ملف الضيف في النظام، مصفوفة صلاحيات التعويض.',
                    'procedure' => array(
                        'توقف عما تفعله وامنح الضيف انتباهك الكامل. لا تكمل مهمة أثناء الاستماع.',
                        'استمع دون مقاطعة حتى ينتهي الضيف. دوّن الوقائع، لا تبريرك.',
                        'اعترف بأثر الأمر على الضيف بكلماتك قبل تقديم أي عرض.',
                        'اعتذر عن التجربة دون إلقاء اللوم على زميل أو قسم.',
                        'أعد صياغة فهمك للضيف واسأله عن النتيجة التي يريدها.',
                        'حل الأمر ضمن صلاحيتك فوراً. إن كان خارجها، اذكر من سيتولاه ومتى.',
                        'اتفق مع الضيف صراحةً على الحل قبل تنفيذه.',
                        'نفّذ الحل وأكد إتمامه للضيف شخصياً.',
                        'سجّل الشكوى وسببها وحلها في سجل الملاحظات خلال الوردية نفسها.',
                        'تابع قبل مغادرة الضيف للتأكد من عدم تكرار المشكلة.',
                    ),
                    'checklist' => array('منح الانتباه الكامل', 'الاستماع دون مقاطعة', 'الاعتراف بالأثر',
                        'تقديم الاعتذار', 'تأكيد الفهم', 'الاتفاق على النتيجة',
                        'تنفيذ الحل', 'تأكيد الإتمام', 'التوثيق في الوردية نفسها', 'المتابعة قبل المغادرة'),
                    'safety' => 'انسحب واتصل بالأمن إذا أصبح الضيف مسيئاً أو مهدداً. السلامة الشخصية تسبق حل المشكلة.',
                    'quality' => 'الإقرار خلال خمس دقائق. الحل أو تحديد المسؤول خلال ثلاثين دقيقة. التوثيق قبل نهاية الوردية.',
                    'escalation' => 'صعّد فوراً في حالات ادعاء السرقة أو الإصابة أو التمييز أو سلامة الغذاء، وأي طلب تعويض يتجاوز صلاحيتك.',
                )),

            array('sop-hk-room-cleaning', 'sop-housekeeping', 'HK', 1, 'organization',
                'Guest Room Cleaning', 'إجراء تنظيف غرفة الضيف',
                array(
                    'purpose' => 'To return a guest room to the published standard in a fixed sequence, so that any room can be inspected against the same expectation.',
                    'scope' => 'Applies to departure cleans and stayover service in all guest rooms and suites.',
                    'responsibilities' => 'Room Attendant performs the clean. Housekeeping Supervisor inspects and releases the room.',
                    'tools' => 'Cleaning trolley, colour coded cloths, approved chemicals, vacuum, linen stock, amenity stock, personal protective equipment.',
                    'procedure' => array(
                        'Knock three times, announce housekeeping, wait ten seconds, repeat, then enter and prop the door open.',
                        'Open curtains and windows where possible, and switch on all lights to identify failed bulbs.',
                        'Remove all rubbish and room service items, and report anything left behind to the supervisor.',
                        'Strip the bed and inspect linen for stains or damage. Withdraw anything below standard rather than returning it.',
                        'Apply bathroom chemicals and allow the stated dwell time while working on the bedroom.',
                        'Make the bed to the standard setup, then dust from the highest surface downwards.',
                        'Clean the bathroom in order: mirror, basin, bath or shower, toilet last, then floor.',
                        'Replenish amenities, linen, stationery and minibar to the published par level.',
                        'Vacuum from the far corner towards the door, and check under the bed and behind the curtains.',
                        'Do a final visual check from the doorway at guest eye level, then set the room status in the system.',
                    ),
                    'checklist' => array('Entry announced correctly', 'Lights and bulbs checked', 'Rubbish removed',
                        'Substandard linen withdrawn', 'Chemical dwell time observed', 'Bed to standard',
                        'Bathroom cleaned in order', 'Amenities at par', 'Vacuumed to the door', 'Final check from doorway'),
                    'safety' => 'Never mix chemicals. Wear gloves for all bathroom work. Place the wet floor sign before mopping. Never carry a used cloth between bathroom and bedroom.',
                    'quality' => 'Departure clean within forty minutes for a standard room. Room passes inspection without a re-clean.',
                    'escalation' => 'Report immediately: any suspected biohazard, a guest belonging found after departure, damage beyond fair wear, and any room that cannot be entered safely.',
                ),
                array(
                    'purpose' => 'إعادة غرفة الضيف إلى المعيار المعتمد بتسلسل ثابت، بحيث يمكن تفتيش أي غرفة وفق التوقع نفسه.',
                    'scope' => 'ينطبق على تنظيف غرف المغادرة وخدمة الإقامة المستمرة في جميع الغرف والأجنحة.',
                    'responsibilities' => 'عامل الغرف ينفذ التنظيف. مشرف التدبير الفندقي يفتش ويحرر الغرفة.',
                    'tools' => 'عربة التنظيف، مناشف بترميز لوني، المواد المعتمدة، المكنسة، المفروشات، المستلزمات، معدات الحماية الشخصية.',
                    'procedure' => array(
                        'اطرق ثلاث مرات، وأعلن عن التدبير الفندقي، وانتظر عشر ثوانٍ، وكرر، ثم ادخل وثبّت الباب مفتوحاً.',
                        'افتح الستائر والنوافذ حيثما أمكن، وشغّل جميع الأضواء لاكتشاف اللمبات التالفة.',
                        'أزل جميع النفايات وأدوات خدمة الغرف، وأبلغ المشرف عن أي شيء متروك.',
                        'انزع المفروشات وافحصها بحثاً عن البقع أو التلف. اسحب ما دون المعيار بدلاً من إعادته.',
                        'ضع مواد تنظيف دورة المياه واترك مدة التفاعل المحددة أثناء عملك في غرفة النوم.',
                        'رتب السرير وفق الإعداد القياسي، ثم نظف الغبار من أعلى سطح إلى أسفل.',
                        'نظف دورة المياه بالترتيب: المرآة، المغسلة، البانيو أو الدش، المرحاض أخيراً، ثم الأرضية.',
                        'أعد تعبئة المستلزمات والمفروشات والقرطاسية والميني بار إلى المستوى المعتمد.',
                        'كنس من الزاوية البعيدة باتجاه الباب، وافحص تحت السرير وخلف الستائر.',
                        'قم بفحص بصري نهائي من عند الباب على مستوى نظر الضيف، ثم حدّث حالة الغرفة في النظام.',
                    ),
                    'checklist' => array('الإعلان عند الدخول', 'فحص الأضواء واللمبات', 'إزالة النفايات',
                        'سحب المفروشات دون المعيار', 'مراعاة مدة تفاعل المواد', 'السرير وفق المعيار',
                        'تنظيف دورة المياه بالترتيب', 'المستلزمات بالمستوى المعتمد', 'الكنس حتى الباب', 'الفحص النهائي من الباب'),
                    'safety' => 'لا تخلط المواد الكيميائية إطلاقاً. ارتدِ القفازات في كل أعمال دورة المياه. ضع لافتة الأرضية المبللة قبل المسح. لا تنقل منشفة مستعملة بين دورة المياه وغرفة النوم.',
                    'quality' => 'تنظيف غرفة المغادرة خلال أربعين دقيقة للغرفة القياسية. اجتياز التفتيش دون إعادة تنظيف.',
                    'escalation' => 'أبلغ فوراً عن: أي اشتباه بخطر بيولوجي، أو متعلقات ضيف بعد المغادرة، أو تلف يتجاوز الاستخدام الطبيعي، أو غرفة يتعذر دخولها بأمان.',
                )),

            array('sop-hk-lost-found', 'sop-housekeeping', 'HK', 1, 'organization',
                'Lost and Found Handling', 'إجراء المفقودات والموجودات',
                array(
                    'purpose' => 'To protect guest property found on the premises and return it to its owner through a traceable, auditable process.',
                    'scope' => 'Applies to any item found anywhere on the property by any employee.',
                    'responsibilities' => 'The finder hands the item in unopened. Housekeeping holds the register. Security witnesses high value items.',
                    'tools' => 'Lost and found register, sealed storage bags, secure store, high value safe.',
                    'procedure' => array(
                        'Do not open, use, or take home any found item under any circumstance.',
                        'Hand the item to the Housekeeping office before the end of your shift.',
                        'Record in the register: date, time, exact location found, finder name, and a factual description.',
                        'Seal the item in a bag with the register number written on the outside.',
                        'Store valuables, documents and electronics in the high value safe, witnessed by Security.',
                        'Check the register against the room history and contact the guest within twenty four hours if the owner is identifiable.',
                        'Arrange return by courier at the guest cost, or hold for collection, and record which was agreed.',
                        'Obtain a signature or written confirmation on release, and record who released it.',
                        'Hold unclaimed general items for three months, documents for six months, and valuables for twelve months.',
                        'Dispose of unclaimed items only with written management approval, recorded against the register number.',
                    ),
                    'checklist' => array('Item not opened', 'Handed in same shift', 'Register entry complete',
                        'Item sealed and numbered', 'Valuables witnessed', 'Owner contacted within 24 hours',
                        'Return method agreed', 'Release signed', 'Retention period applied', 'Disposal approved in writing'),
                    'safety' => 'Do not handle a suspicious package. Do not handle medication, sharps or anything leaking. Call Security instead.',
                    'quality' => 'Every found item has a register entry within the same shift. No release without a recorded signature.',
                    'escalation' => 'Escalate to Security and the Duty Manager for cash, identification documents, weapons, controlled substances or anything suspicious.',
                ),
                array(
                    'purpose' => 'حماية ممتلكات الضيوف الموجودة في الفندق وإعادتها لأصحابها عبر إجراء موثق وقابل للتدقيق.',
                    'scope' => 'ينطبق على أي غرض يعثر عليه أي موظف في أي مكان داخل الفندق.',
                    'responsibilities' => 'من يجد الغرض يسلمه دون فتحه. التدبير الفندقي يحتفظ بالسجل. الأمن يشهد على الأغراض الثمينة.',
                    'tools' => 'سجل المفقودات، أكياس مختومة، مخزن آمن، خزنة الأغراض الثمينة.',
                    'procedure' => array(
                        'لا تفتح أو تستخدم أو تأخذ أي غرض موجود إلى المنزل تحت أي ظرف.',
                        'سلّم الغرض إلى مكتب التدبير الفندقي قبل نهاية ورديتك.',
                        'سجّل في السجل: التاريخ والوقت والموقع الدقيق واسم من وجده ووصفاً واقعياً.',
                        'اختم الغرض في كيس مكتوب عليه رقم السجل من الخارج.',
                        'خزّن الأغراض الثمينة والوثائق والإلكترونيات في خزنة الأغراض الثمينة بحضور الأمن.',
                        'طابق السجل مع سجل الغرفة وتواصل مع الضيف خلال أربع وعشرين ساعة إذا أمكن تحديد المالك.',
                        'رتب الإعادة عبر شركة شحن على حساب الضيف، أو الاحتفاظ للاستلام، وسجّل ما تم الاتفاق عليه.',
                        'احصل على توقيع أو تأكيد كتابي عند التسليم، وسجّل من قام بالتسليم.',
                        'احتفظ بالأغراض العامة غير المطالب بها ثلاثة أشهر، والوثائق ستة أشهر، والثمينة اثني عشر شهراً.',
                        'لا تتخلص من أي غرض إلا بموافقة إدارية مكتوبة، مسجلة أمام رقم السجل.',
                    ),
                    'checklist' => array('عدم فتح الغرض', 'التسليم في الوردية نفسها', 'اكتمال قيد السجل',
                        'ختم الغرض وترقيمه', 'الإشهاد على الأغراض الثمينة', 'التواصل مع المالك خلال ٢٤ ساعة',
                        'الاتفاق على طريقة الإعادة', 'توقيع التسليم', 'تطبيق مدة الاحتفاظ', 'موافقة مكتوبة على الإتلاف'),
                    'safety' => 'لا تتعامل مع طرد مشبوه. لا تتعامل مع أدوية أو أدوات حادة أو أي شيء يتسرب منه سائل. اتصل بالأمن.',
                    'quality' => 'كل غرض موجود له قيد في السجل خلال الوردية نفسها. لا تسليم دون توقيع مسجل.',
                    'escalation' => 'صعّد إلى الأمن ومدير المناوبة في حالات النقد ووثائق الهوية والأسلحة والمواد الخاضعة للرقابة وأي شيء مشبوه.',
                )),

            array('sop-kit-temperature', 'sop-kitchen', 'KIT', 1, 'organization',
                'Food Temperature Control', 'إجراء ضبط درجات حرارة الأغذية',
                array(
                    'purpose' => 'To keep food out of the temperature range in which bacteria multiply, and to hold a record that proves control was maintained.',
                    'scope' => 'Applies to receiving, storage, preparation, cooking, hot holding, cooling and reheating in every kitchen and pantry.',
                    'responsibilities' => 'Every chef records their own readings. Sous Chef verifies the log daily. Executive Chef reviews weekly.',
                    'tools' => 'Calibrated probe thermometer, probe wipes, temperature log sheet, fridge and freezer display thermometers.',
                    'procedure' => array(
                        'Calibrate the probe in iced water at the start of each shift and record the result.',
                        'Clean and sanitise the probe before and after every single use.',
                        'Check and record chilled storage at or below 5 degrees Celsius, twice per shift.',
                        'Check and record frozen storage at or below minus 18 degrees Celsius, twice per shift.',
                        'Probe the thickest part of cooked food and confirm 75 degrees Celsius or above before service.',
                        'Hold hot food at 63 degrees Celsius or above, and record the holding temperature every two hours.',
                        'Cool cooked food from 60 to 21 degrees Celsius within two hours, and to 5 degrees Celsius within a further four hours.',
                        'Reheat only once, to 75 degrees Celsius or above, and record it.',
                        'Record every reading on the log sheet at the time it is taken, never from memory at the end of a shift.',
                        'Act on any out of range reading immediately, record the corrective action taken, and tell the Sous Chef.',
                    ),
                    'checklist' => array('Probe calibrated this shift', 'Probe sanitised each use', 'Chilled storage logged twice',
                        'Frozen storage logged twice', 'Cooking temperature confirmed', 'Hot holding logged two hourly',
                        'Cooling times met', 'Reheat logged', 'Readings recorded at the time', 'Corrective action recorded'),
                    'safety' => 'Discard any food held between 5 and 63 degrees Celsius for more than four hours. Never taste food to judge whether it is safe.',
                    'quality' => 'A complete log for every shift with no blank cells. Every out of range reading has a recorded corrective action.',
                    'escalation' => 'Escalate to the Executive Chef immediately for any suspected temperature abuse of served food, and for any refrigeration failure.',
                ),
                array(
                    'purpose' => 'إبقاء الأغذية خارج نطاق الحرارة الذي تتكاثر فيه البكتيريا، والاحتفاظ بسجل يثبت استمرار التحكم.',
                    'scope' => 'ينطبق على الاستلام والتخزين والتحضير والطهي والحفظ الساخن والتبريد وإعادة التسخين في كل مطبخ ومخزن.',
                    'responsibilities' => 'كل طاهٍ يسجل قراءاته بنفسه. مساعد رئيس الطهاة يتحقق من السجل يومياً. رئيس الطهاة التنفيذي يراجع أسبوعياً.',
                    'tools' => 'مقياس حرارة معاير، مناديل تعقيم المجس، ورقة سجل الحرارة، موازين حرارة الثلاجات والمجمدات.',
                    'procedure' => array(
                        'عاير المجس في ماء مثلج في بداية كل وردية وسجّل النتيجة.',
                        'نظّف وعقّم المجس قبل وبعد كل استخدام دون استثناء.',
                        'افحص وسجّل التخزين المبرد عند ٥ درجات مئوية أو أقل، مرتين في الوردية.',
                        'افحص وسجّل التخزين المجمد عند ناقص ١٨ درجة مئوية أو أقل، مرتين في الوردية.',
                        'اقس أسمك جزء من الطعام المطهو وأكد ٧٥ درجة مئوية أو أعلى قبل التقديم.',
                        'احفظ الطعام الساخن عند ٦٣ درجة مئوية أو أعلى، وسجّل حرارة الحفظ كل ساعتين.',
                        'برّد الطعام المطهو من ٦٠ إلى ٢١ درجة مئوية خلال ساعتين، وإلى ٥ درجات خلال أربع ساعات إضافية.',
                        'أعد التسخين مرة واحدة فقط، إلى ٧٥ درجة مئوية أو أعلى، وسجّل ذلك.',
                        'سجّل كل قراءة في السجل وقت أخذها، لا من الذاكرة في نهاية الوردية.',
                        'تصرف فوراً عند أي قراءة خارج النطاق، وسجّل الإجراء التصحيحي، وأبلغ مساعد رئيس الطهاة.',
                    ),
                    'checklist' => array('معايرة المجس هذه الوردية', 'تعقيم المجس كل استخدام', 'تسجيل التبريد مرتين',
                        'تسجيل التجميد مرتين', 'تأكيد حرارة الطهي', 'تسجيل الحفظ الساخن كل ساعتين',
                        'الالتزام بأزمنة التبريد', 'تسجيل إعادة التسخين', 'تسجيل القراءات وقتها', 'تسجيل الإجراء التصحيحي'),
                    'safety' => 'تخلّص من أي طعام بقي بين ٥ و٦٣ درجة مئوية لأكثر من أربع ساعات. لا تتذوق الطعام للحكم على سلامته.',
                    'quality' => 'سجل مكتمل لكل وردية دون خانات فارغة. كل قراءة خارج النطاق لها إجراء تصحيحي مسجل.',
                    'escalation' => 'صعّد إلى رئيس الطهاة التنفيذي فوراً عند الاشتباه في سوء حفظ حراري لطعام قُدّم، وعند أي عطل في التبريد.',
                )),

            array('sop-eng-fire-panel', 'sop-safety', 'ENG', 1, 'organization',
                'Fire Alarm Response', 'إجراء الاستجابة لإنذار الحريق',
                array(
                    'purpose' => 'To respond to a fire alarm activation quickly and in a fixed order, so that a real fire is met immediately and a false alarm does not become an unnecessary evacuation.',
                    'scope' => 'Applies to every alarm activation at every property, at any hour.',
                    'responsibilities' => 'Duty Engineer investigates. Duty Manager decides on evacuation. Security controls the assembly point. Every employee has an evacuation role.',
                    'tools' => 'Fire alarm control panel, two way radio, master key, torch, floor plans, evacuation list.',
                    'procedure' => array(
                        'On activation, the Duty Engineer reads the panel and identifies the exact zone and device.',
                        'Announce the zone on the radio so all departments hear the same information.',
                        'Investigate the identified device within three minutes, taking the stairs, never the lift.',
                        'Confirm by sight whether there is fire, smoke, or a false activation cause such as steam or aerosol.',
                        'If it is a false activation, report the cause on the radio and silence the panel only with Duty Manager approval.',
                        'If fire or smoke is confirmed, raise the general alarm immediately and call the civil defence emergency number.',
                        'The Duty Manager orders evacuation of the affected floor, the floor above and the floor below first.',
                        'Employees sweep their assigned area, direct guests to the nearest protected stairwell, and never use a lift.',
                        'Security accounts for guests and employees at the assembly point using the in-house list.',
                        'Nobody re-enters the building until the civil defence officer in charge gives clearance.',
                    ),
                    'checklist' => array('Panel read and zone identified', 'Zone announced on radio', 'Investigated within 3 minutes',
                        'Cause confirmed by sight', 'Emergency services called if confirmed', 'Evacuation ordered by Duty Manager',
                        'Floors swept', 'Lifts not used', 'Assembly point roll call', 'Re-entry only on official clearance'),
                    'safety' => 'Never investigate a fire alone in a smoke filled area. Never use a lift during an alarm. Never reset the panel before the cause is confirmed.',
                    'quality' => 'Alarm investigated within three minutes of activation. A written incident record completed within one hour of the all clear.',
                    'escalation' => 'Any confirmed fire is escalated to the General Manager and civil defence immediately, with no intermediate step.',
                ),
                array(
                    'purpose' => 'الاستجابة لتفعيل إنذار الحريق بسرعة وبترتيب ثابت، بحيث يُواجه الحريق الحقيقي فوراً ولا يتحول الإنذار الكاذب إلى إخلاء غير ضروري.',
                    'scope' => 'ينطبق على كل تفعيل للإنذار في كل فندق وفي أي ساعة.',
                    'responsibilities' => 'مهندس المناوبة يتحقق. مدير المناوبة يقرر الإخلاء. الأمن يدير نقطة التجمع. لكل موظف دور في الإخلاء.',
                    'tools' => 'لوحة تحكم إنذار الحريق، جهاز اتصال لاسلكي، المفتاح الرئيسي، كشاف، مخططات الطوابق، قائمة الإخلاء.',
                    'procedure' => array(
                        'عند التفعيل، يقرأ مهندس المناوبة اللوحة ويحدد المنطقة والجهاز بدقة.',
                        'أعلن المنطقة عبر اللاسلكي بحيث تسمع جميع الأقسام المعلومة نفسها.',
                        'تحقق من الجهاز المحدد خلال ثلاث دقائق، باستخدام الدرج، لا المصعد إطلاقاً.',
                        'أكد بالنظر وجود حريق أو دخان أو سبب تفعيل كاذب مثل البخار أو البخاخات.',
                        'إن كان التفعيل كاذباً، أبلغ عن السبب عبر اللاسلكي ولا تُسكت اللوحة إلا بموافقة مدير المناوبة.',
                        'عند تأكيد الحريق أو الدخان، فعّل الإنذار العام فوراً واتصل برقم طوارئ الدفاع المدني.',
                        'يأمر مدير المناوبة بإخلاء الطابق المتأثر والطابق الذي فوقه والذي تحته أولاً.',
                        'يمشط الموظفون مناطقهم المحددة ويوجهون الضيوف إلى أقرب درج محمي، ولا يستخدمون المصعد.',
                        'يحصي الأمن الضيوف والموظفين عند نقطة التجمع باستخدام القائمة الداخلية.',
                        'لا يعود أحد إلى المبنى حتى يصرّح ضابط الدفاع المدني المسؤول بذلك.',
                    ),
                    'checklist' => array('قراءة اللوحة وتحديد المنطقة', 'إعلان المنطقة عبر اللاسلكي', 'التحقق خلال ٣ دقائق',
                        'تأكيد السبب بالنظر', 'الاتصال بالطوارئ عند التأكيد', 'أمر الإخلاء من مدير المناوبة',
                        'تمشيط الطوابق', 'عدم استخدام المصاعد', 'حصر الأشخاص في نقطة التجمع', 'العودة بتصريح رسمي فقط'),
                    'safety' => 'لا تتحقق من حريق بمفردك في منطقة مليئة بالدخان. لا تستخدم المصعد أثناء الإنذار. لا تُعد ضبط اللوحة قبل تأكيد السبب.',
                    'quality' => 'التحقق من الإنذار خلال ثلاث دقائق من التفعيل. تقرير حادث مكتوب خلال ساعة من انتهاء الحالة.',
                    'escalation' => 'أي حريق مؤكد يُصعّد إلى المدير العام والدفاع المدني فوراً دون أي خطوة وسيطة.',
                )),

            array('sop-sec-key-control', 'sop-security', 'SEC', 1, 'organization',
                'Master Key Control', 'إجراء التحكم بالمفاتيح الرئيسية',
                array(
                    'purpose' => 'To ensure every master key is accounted for at all times and that access to guest rooms is traceable to a named employee.',
                    'scope' => 'Applies to all master, section and floor keys at every property.',
                    'responsibilities' => 'Security holds the key register. Department heads authorise issue. Every holder signs personally.',
                    'tools' => 'Key register, key safe, key encoder audit report, employee identification.',
                    'procedure' => array(
                        'Issue a key only against the employee identification and a personal signature in the register.',
                        'Record the key number, holder name, department, date and time of issue.',
                        'Never pass a key to another employee. A key changes hands only through the key safe.',
                        'Keep the key attached to the person on a retractable cord, never left on a trolley or a desk.',
                        'Return the key to the key safe at the end of every shift and sign it back in.',
                        'Security reconciles the register against the physical keys at each shift change.',
                        'Report a lost key immediately to Security and the Duty Manager, not at the end of the shift.',
                        'On a reported loss, Security deactivates the key in the system before any search begins.',
                        'Review the encoder audit report weekly and investigate any access outside an assigned area.',
                        'Re-key the affected section when a master key is not recovered within twenty four hours.',
                    ),
                    'checklist' => array('Identification checked', 'Register signed personally', 'Issue details recorded',
                        'Key attached to person', 'No key passed between staff', 'Returned and signed in',
                        'Shift reconciliation done', 'Loss reported immediately', 'Key deactivated on loss', 'Audit report reviewed weekly'),
                    'safety' => 'A master key is never left unattended for any reason, including a short break. Never label a key with the property name.',
                    'quality' => 'Every key accounted for at every shift change. No unexplained gap in the register.',
                    'escalation' => 'Escalate any unrecovered master key to the General Manager within one hour.',
                ),
                array(
                    'purpose' => 'ضمان حصر جميع المفاتيح الرئيسية في كل وقت، وأن يكون الدخول إلى غرف الضيوف متتبعاً إلى موظف محدد بالاسم.',
                    'scope' => 'ينطبق على جميع المفاتيح الرئيسية ومفاتيح الأقسام والطوابق في كل فندق.',
                    'responsibilities' => 'الأمن يحتفظ بسجل المفاتيح. رؤساء الأقسام يعتمدون الصرف. كل حامل مفتاح يوقع شخصياً.',
                    'tools' => 'سجل المفاتيح، خزنة المفاتيح، تقرير تدقيق جهاز الترميز، بطاقة تعريف الموظف.',
                    'procedure' => array(
                        'لا تصرف مفتاحاً إلا مقابل بطاقة تعريف الموظف وتوقيع شخصي في السجل.',
                        'سجّل رقم المفتاح واسم الحامل والقسم وتاريخ ووقت الصرف.',
                        'لا تسلّم مفتاحاً لموظف آخر إطلاقاً. المفتاح ينتقل فقط عبر خزنة المفاتيح.',
                        'أبقِ المفتاح مثبتاً على الشخص بحبل قابل للسحب، ولا تتركه على عربة أو مكتب.',
                        'أعد المفتاح إلى الخزنة في نهاية كل وردية ووقّع على الإعادة.',
                        'يطابق الأمن السجل مع المفاتيح الفعلية عند كل تغيير وردية.',
                        'أبلغ عن فقدان مفتاح فوراً للأمن ومدير المناوبة، لا في نهاية الوردية.',
                        'عند الإبلاغ عن فقدان، يعطّل الأمن المفتاح في النظام قبل بدء أي بحث.',
                        'راجع تقرير تدقيق جهاز الترميز أسبوعياً وحقق في أي دخول خارج المنطقة المخصصة.',
                        'أعد ترميز القسم المتأثر إذا لم يُسترجع المفتاح الرئيسي خلال أربع وعشرين ساعة.',
                    ),
                    'checklist' => array('فحص بطاقة التعريف', 'التوقيع الشخصي في السجل', 'تسجيل بيانات الصرف',
                        'تثبيت المفتاح على الشخص', 'عدم تبادل المفاتيح بين الموظفين', 'الإعادة والتوقيع',
                        'المطابقة عند تغيير الوردية', 'الإبلاغ الفوري عن الفقدان', 'تعطيل المفتاح عند الفقدان', 'مراجعة تقرير التدقيق أسبوعياً'),
                    'safety' => 'لا يُترك المفتاح الرئيسي دون إشراف لأي سبب، بما في ذلك استراحة قصيرة. لا توسم المفتاح باسم الفندق.',
                    'quality' => 'حصر كل مفتاح عند كل تغيير وردية. لا فجوة غير مفسرة في السجل.',
                    'escalation' => 'صعّد أي مفتاح رئيسي غير مسترجع إلى المدير العام خلال ساعة واحدة.',
                )),

            array('sop-fb-service-sequence', 'sop-food-beverage', 'FB', 1, 'organization',
                'Restaurant Service Sequence', 'إجراء تسلسل خدمة المطعم',
                array(
                    'purpose' => 'To deliver a consistent restaurant service in a defined order so that every guest receives the same standard regardless of who serves them.',
                    'scope' => 'Applies to all à la carte restaurant service across every property outlet.',
                    'responsibilities' => 'Server delivers the sequence. Captain supervises the section. Restaurant Manager resolves guest issues.',
                    'tools' => 'Point of sale terminal, order pad, service tray, menus in both languages, allergen reference.',
                    'procedure' => array(
                        'Greet the guest at the table within one minute of seating and offer water.',
                        'Present menus open, in the guest preferred language, and state the two dishes the kitchen recommends today.',
                        'Ask about dietary requirements and allergies before taking the order, not after.',
                        'Take the order starting with the guest who is ready, and repeat it back before entering it.',
                        'Enter the order into the point of sale with the correct course timing and any modifier.',
                        'Serve from the right where the layout allows, and announce each dish as it is placed.',
                        'Check back within two minutes of the main course being served, using an open question.',
                        'Clear only when every guest at the table has finished, and clear from the right.',
                        'Offer dessert and hot beverages before presenting the bill, never together with it.',
                        'Present the bill face down within two minutes of it being requested, and settle at the table.',
                    ),
                    'checklist' => array('Greeted within 1 minute', 'Water offered', 'Menus in preferred language',
                        'Allergies asked before ordering', 'Order repeated back', 'Course timing entered',
                        'Dishes announced', 'Check back within 2 minutes', 'Table cleared together', 'Bill presented face down'),
                    'safety' => 'Never guess an allergen answer. Confirm with the kitchen. Carry hot plates with a cloth and warn the guest.',
                    'quality' => 'Greeting within one minute. Starter within twelve minutes of ordering. No table left uncleared for more than five minutes.',
                    'escalation' => 'Escalate to the Restaurant Manager for any allergy incident, any returned dish, and any guest who asks to speak to a manager.',
                ),
                array(
                    'purpose' => 'تقديم خدمة مطعم متسقة بترتيب محدد بحيث يحصل كل ضيف على المعيار نفسه بغض النظر عمن يخدمه.',
                    'scope' => 'ينطبق على خدمة المطاعم بنظام الطلب المفرد في جميع منافذ الفنادق.',
                    'responsibilities' => 'النادل ينفذ التسلسل. الكابتن يشرف على القسم. مدير المطعم يعالج مشكلات الضيوف.',
                    'tools' => 'جهاز نقاط البيع، دفتر الطلبات، صينية الخدمة، قوائم الطعام باللغتين، مرجع مسببات الحساسية.',
                    'procedure' => array(
                        'رحّب بالضيف على الطاولة خلال دقيقة من جلوسه واعرض الماء.',
                        'قدّم قوائم الطعام مفتوحة باللغة التي يفضلها الضيف، واذكر طبقين يوصي بهما المطبخ اليوم.',
                        'اسأل عن المتطلبات الغذائية والحساسية قبل أخذ الطلب، لا بعده.',
                        'ابدأ أخذ الطلب من الضيف الجاهز، وأعد قراءة الطلب قبل إدخاله.',
                        'أدخل الطلب في نقاط البيع بتوقيت الأطباق الصحيح وأي تعديل مطلوب.',
                        'قدّم من جهة اليمين حيثما يسمح الترتيب، واذكر اسم كل طبق عند وضعه.',
                        'تحقق من رضا الضيف خلال دقيقتين من تقديم الطبق الرئيسي بسؤال مفتوح.',
                        'ارفع الأطباق فقط بعد أن ينتهي جميع من على الطاولة، ومن جهة اليمين.',
                        'اعرض الحلويات والمشروبات الساخنة قبل تقديم الفاتورة، لا معها.',
                        'قدّم الفاتورة مقلوبة خلال دقيقتين من طلبها، وأتمم الدفع على الطاولة.',
                    ),
                    'checklist' => array('الترحيب خلال دقيقة', 'عرض الماء', 'القوائم باللغة المفضلة',
                        'السؤال عن الحساسية قبل الطلب', 'إعادة قراءة الطلب', 'إدخال توقيت الأطباق',
                        'ذكر أسماء الأطباق', 'التحقق خلال دقيقتين', 'رفع الأطباق معاً', 'تقديم الفاتورة مقلوبة'),
                    'safety' => 'لا تخمّن إجابة عن مسبب حساسية. تأكد من المطبخ. احمل الأطباق الساخنة بقطعة قماش ونبّه الضيف.',
                    'quality' => 'الترحيب خلال دقيقة. المقبلات خلال اثنتي عشرة دقيقة من الطلب. لا طاولة تبقى دون رفع أكثر من خمس دقائق.',
                    'escalation' => 'صعّد إلى مدير المطعم في أي حادثة حساسية، أو طبق مُعاد، أو ضيف يطلب التحدث إلى مدير.',
                )),

            array('sop-eng-ppm-guestroom', 'sop-maintenance', 'ENG', 0, 'organization',
                'Guest Room Preventive Maintenance', 'إجراء الصيانة الوقائية لغرف الضيوف',
                array(
                    'purpose' => 'To find and correct room faults before a guest does, on a scheduled cycle that covers every room.',
                    'scope' => 'Applies to every guest room and suite, on a rolling schedule set by the Chief Engineer.',
                    'responsibilities' => 'Maintenance Technician performs the round. Engineering Supervisor schedules and verifies. Housekeeping releases the room.',
                    'tools' => 'PPM checklist, tool kit, spare lamps and filters, work order system, moisture meter.',
                    'procedure' => array(
                        'Take the room out of inventory through the front office before starting, never work in a sellable room.',
                        'Test every light fitting, switch and socket, and replace any failed lamp with the correct type.',
                        'Run the air conditioning through its full range and check the supply temperature and the filter condition.',
                        'Run all taps and the shower, check the flow, the drainage speed and the seal condition.',
                        'Flush the toilet three times and check the fill, the seal and the fixing.',
                        'Test the television, the remote, the safe, the kettle, the telephone and the wifi connection.',
                        'Check the door closer, the lock, the viewer, the chain and the emergency plan on the back of the door.',
                        'Inspect grout, sealant, skirting and paintwork, and record anything below standard with a photograph.',
                        'Raise a work order for anything that cannot be corrected on the round, with a target date.',
                        'Sign off the checklist, return the room to housekeeping for cleaning, and only then release it for sale.',
                    ),
                    'checklist' => array('Room taken out of inventory', 'All lighting tested', 'Air conditioning tested',
                        'Water flow and drainage checked', 'Toilet checked', 'Room electronics tested',
                        'Door and lock checked', 'Finishes inspected and photographed', 'Work orders raised', 'Checklist signed off'),
                    'safety' => 'Isolate power before any electrical work. Never stand on furniture. Place a warning sign at the door while working.',
                    'quality' => 'Every room receives a full PPM at the scheduled interval, with a signed checklist retained for audit.',
                    'escalation' => 'Escalate to the Chief Engineer for any water ingress, electrical fault beyond a lamp change, or structural damage.',
                ),
                array(
                    'purpose' => 'اكتشاف أعطال الغرفة وتصحيحها قبل أن يلاحظها الضيف، ضمن دورة مجدولة تغطي كل غرفة.',
                    'scope' => 'ينطبق على كل غرفة وجناح، وفق جدول دوري يحدده كبير المهندسين.',
                    'responsibilities' => 'فني الصيانة ينفذ الجولة. مشرف الهندسة يجدول ويتحقق. التدبير الفندقي يحرر الغرفة.',
                    'tools' => 'قائمة الصيانة الوقائية، حقيبة الأدوات، لمبات وفلاتر احتياطية، نظام أوامر العمل، جهاز قياس الرطوبة.',
                    'procedure' => array(
                        'أخرج الغرفة من المخزون عبر مكتب الاستقبال قبل البدء، ولا تعمل في غرفة قابلة للبيع.',
                        'اختبر كل وحدة إنارة ومفتاح ومقبس، واستبدل أي لمبة تالفة بالنوع الصحيح.',
                        'شغّل التكييف على كامل نطاقه وافحص حرارة الهواء الخارج وحالة الفلتر.',
                        'شغّل جميع الصنابير والدش، وافحص التدفق وسرعة التصريف وحالة العوازل.',
                        'اشطف المرحاض ثلاث مرات وافحص التعبئة والعزل والتثبيت.',
                        'اختبر التلفاز وجهاز التحكم والخزنة والغلاية والهاتف واتصال الشبكة.',
                        'افحص مغلاق الباب والقفل والعين السحرية والسلسلة وخطة الطوارئ خلف الباب.',
                        'افحص الفواصل والسيليكون والوزرات والدهان، وسجّل ما دون المعيار بصورة فوتوغرافية.',
                        'أصدر أمر عمل لكل ما لا يمكن تصحيحه في الجولة، مع تاريخ مستهدف.',
                        'وقّع على القائمة، وأعد الغرفة للتدبير الفندقي للتنظيف، ثم حررها للبيع بعد ذلك فقط.',
                    ),
                    'checklist' => array('إخراج الغرفة من المخزون', 'اختبار كل الإنارة', 'اختبار التكييف',
                        'فحص التدفق والتصريف', 'فحص المرحاض', 'اختبار أجهزة الغرفة',
                        'فحص الباب والقفل', 'فحص التشطيبات وتصويرها', 'إصدار أوامر العمل', 'التوقيع على القائمة'),
                    'safety' => 'اعزل التيار قبل أي عمل كهربائي. لا تقف على الأثاث. ضع لافتة تحذير عند الباب أثناء العمل.',
                    'quality' => 'كل غرفة تتلقى صيانة وقائية كاملة في الفترة المجدولة، مع قائمة موقعة محفوظة للتدقيق.',
                    'escalation' => 'صعّد إلى كبير المهندسين عند أي تسرب مياه أو عطل كهربائي يتجاوز تغيير لمبة أو ضرر إنشائي.',
                )),

            array('sop-hr-onboarding', 'sop-hr', 'HR', 0, 'organization',
                'New Employee Onboarding', 'إجراء إدماج الموظف الجديد',
                array(
                    'purpose' => 'To bring a new employee to a safe, competent standard in their first weeks, with their mandatory training and SOP acknowledgements recorded.',
                    'scope' => 'Applies to every new hire, transfer and returning seasonal employee.',
                    'responsibilities' => 'HR owns the process. The line manager owns the department induction. The employee completes their assigned training.',
                    'tools' => 'Academy learner account, training assignment, SOP library, uniform and locker issue, identification and access card.',
                    'procedure' => array(
                        'Create the academy account before the first day, with department, property and job role set correctly.',
                        'Assign the mandatory safety training and the department SOP acknowledgements with a due date of day seven.',
                        'On day one, deliver the property induction: emergency exits, assembly point, reporting lines and working hours.',
                        'Issue uniform, locker, identification and system access against signature.',
                        'Introduce the employee to their team and name the person they should ask when unsure.',
                        'Walk the department with the line manager and show each area named in their SOPs.',
                        'Confirm on day three that the assigned training has been started, and remove any access barrier.',
                        'Review completion on day seven. Training not completed is a manager action, not an employee failure.',
                        'Hold a thirty day conversation covering what they can now do unaided and what still needs support.',
                        'Record the outcome in the employee skill profile and assign any follow-up training.',
                    ),
                    'checklist' => array('Account created before day one', 'Mandatory training assigned', 'Property induction delivered',
                        'Uniform and access issued', 'Team introduction done', 'Department walkthrough done',
                        'Day three check', 'Day seven completion review', 'Thirty day conversation', 'Skill profile updated'),
                    'safety' => 'An employee must not work unsupervised in a hazardous area before completing the mandatory safety training.',
                    'quality' => 'Mandatory training completed within seven days. Every department SOP acknowledged within fourteen days.',
                    'escalation' => 'Escalate to HR if training is not complete by day fourteen, or if the employee reports they were not given the induction.',
                ),
                array(
                    'purpose' => 'الوصول بالموظف الجديد إلى مستوى آمن وكفء في أسابيعه الأولى، مع توثيق تدريبه الإلزامي وإقراراته بالإجراءات.',
                    'scope' => 'ينطبق على كل موظف جديد ومنقول وموسمي عائد.',
                    'responsibilities' => 'الموارد البشرية تملك الإجراء. المدير المباشر يملك تعريف القسم. الموظف يكمل التدريب المسند إليه.',
                    'tools' => 'حساب متدرب في الأكاديمية، تكليف تدريبي، مكتبة الإجراءات، صرف الزي والخزانة، بطاقة التعريف والدخول.',
                    'procedure' => array(
                        'أنشئ حساب الأكاديمية قبل اليوم الأول، مع ضبط القسم والفندق والمسمى الوظيفي بشكل صحيح.',
                        'أسند تدريب السلامة الإلزامي وإقرارات إجراءات القسم بتاريخ استحقاق في اليوم السابع.',
                        'في اليوم الأول، قدّم تعريف الفندق: مخارج الطوارئ ونقطة التجمع وخطوط الإبلاغ وساعات العمل.',
                        'اصرف الزي والخزانة وبطاقة التعريف وصلاحيات الأنظمة مقابل توقيع.',
                        'عرّف الموظف بفريقه وحدد له الشخص الذي يسأله عند عدم التأكد.',
                        'تجوّل في القسم مع المدير المباشر واعرض كل منطقة مذكورة في إجراءاته.',
                        'تأكد في اليوم الثالث من بدء التدريب المسند، وأزل أي عائق للوصول.',
                        'راجع الإكمال في اليوم السابع. عدم إكمال التدريب مسؤولية المدير لا تقصير من الموظف.',
                        'أجرِ حواراً في اليوم الثلاثين حول ما يستطيع أداءه دون مساعدة وما يحتاج فيه دعماً.',
                        'سجّل النتيجة في ملف مهارات الموظف وأسند أي تدريب لاحق.',
                    ),
                    'checklist' => array('إنشاء الحساب قبل اليوم الأول', 'إسناد التدريب الإلزامي', 'تقديم تعريف الفندق',
                        'صرف الزي والصلاحيات', 'تعريف الفريق', 'جولة القسم',
                        'متابعة اليوم الثالث', 'مراجعة اليوم السابع', 'حوار اليوم الثلاثين', 'تحديث ملف المهارات'),
                    'safety' => 'لا يعمل الموظف دون إشراف في منطقة خطرة قبل إكمال تدريب السلامة الإلزامي.',
                    'quality' => 'إكمال التدريب الإلزامي خلال سبعة أيام. الإقرار بكل إجراءات القسم خلال أربعة عشر يوماً.',
                    'escalation' => 'صعّد إلى الموارد البشرية إذا لم يكتمل التدريب بحلول اليوم الرابع عشر، أو إذا أفاد الموظف بعدم حصوله على التعريف.',
                )),

            array('sop-fin-cash-handling', 'sop-finance', 'FIN', 1, 'private',
                'Front Desk Cash Handling', 'إجراء التعامل النقدي في الاستقبال',
                array(
                    'purpose' => 'To control cash at the front desk so that every movement is recorded and any difference is identified at the shift it occurred.',
                    'scope' => 'Applies to every cash float, cash payment and cash refund at the front desk and outlet cashier positions.',
                    'responsibilities' => 'The cashier on shift is personally accountable for their float. Finance performs surprise counts. Duty Manager witnesses drops.',
                    'tools' => 'Individual cash float, drop safe, count sheet, counterfeit detection pen, point of sale.',
                    'procedure' => array(
                        'Count your float in front of the outgoing cashier at handover and sign the count sheet.',
                        'Never share a float. One float, one named cashier, one shift.',
                        'Check every note above the set threshold with the detection pen before accepting it.',
                        'Count cash back to the guest aloud, and place the tendered note on the drawer edge until change is given.',
                        'Post every cash payment to the correct folio immediately, never at the end of the shift.',
                        'A refund in cash requires Duty Manager authorisation and a signed refund voucher before it is paid.',
                        'Drop excess cash into the safe whenever the float exceeds its limit, witnessed by the Duty Manager.',
                        'Count down at the end of shift, complete the count sheet, and record any difference honestly.',
                        'Report any difference at handover. A difference concealed is a disciplinary matter, a difference reported is an investigation.',
                        'Seal the drop envelope, record the serial number, and hand it to the safe in the presence of the witness.',
                    ),
                    'checklist' => array('Float counted at handover', 'Float not shared', 'Notes checked',
                        'Change counted aloud', 'Payments posted immediately', 'Refunds authorised in writing',
                        'Excess dropped and witnessed', 'End of shift count done', 'Difference reported', 'Drop envelope sealed and recorded'),
                    'safety' => 'Never count cash in view of the lobby. Never carry cash through a public area without a second employee.',
                    'quality' => 'Every shift has a completed and signed count sheet. Differences are reported the same shift, without exception.',
                    'escalation' => 'Escalate to Finance and the Duty Manager for any difference above the set threshold, any suspected counterfeit note, and any refund request without a folio.',
                ),
                array(
                    'purpose' => 'ضبط النقد في مكتب الاستقبال بحيث تُسجل كل حركة ويُحدد أي فرق في الوردية التي حدث فيها.',
                    'scope' => 'ينطبق على كل صندوق نقدي ودفعة نقدية واسترداد نقدي في الاستقبال ومراكز الكاشير.',
                    'responsibilities' => 'الكاشير في الوردية مسؤول شخصياً عن صندوقه. المالية تنفذ جرداً مفاجئاً. مدير المناوبة يشهد على الإيداعات.',
                    'tools' => 'صندوق نقدي فردي، خزنة الإيداع، ورقة الجرد، قلم كشف التزوير، نقاط البيع.',
                    'procedure' => array(
                        'اعدّ صندوقك أمام الكاشير المنصرف عند التسليم ووقّع على ورقة الجرد.',
                        'لا تشارك الصندوق إطلاقاً. صندوق واحد، كاشير واحد بالاسم، وردية واحدة.',
                        'افحص كل ورقة نقدية تتجاوز الحد المقرر بقلم الكشف قبل قبولها.',
                        'عدّ النقد المُعاد للضيف بصوت مسموع، وضع الورقة المستلمة على حافة الدرج حتى يُسلَّم الباقي.',
                        'رحّل كل دفعة نقدية إلى الفاتورة الصحيحة فوراً، لا في نهاية الوردية.',
                        'الاسترداد النقدي يتطلب تفويض مدير المناوبة وقسيمة استرداد موقعة قبل الصرف.',
                        'أودع الفائض النقدي في الخزنة كلما تجاوز الصندوق حده، بحضور مدير المناوبة كشاهد.',
                        'اعدّ الصندوق في نهاية الوردية، وأكمل ورقة الجرد، وسجّل أي فرق بصدق.',
                        'أبلغ عن أي فرق عند التسليم. إخفاء الفرق مسألة انضباطية، والإبلاغ عنه تحقيق.',
                        'اختم ظرف الإيداع، وسجّل رقمه التسلسلي، وسلّمه للخزنة بحضور الشاهد.',
                    ),
                    'checklist' => array('جرد الصندوق عند التسليم', 'عدم مشاركة الصندوق', 'فحص الأوراق النقدية',
                        'عد الباقي بصوت مسموع', 'ترحيل الدفعات فوراً', 'تفويض الاسترداد كتابياً',
                        'إيداع الفائض بحضور شاهد', 'جرد نهاية الوردية', 'الإبلاغ عن الفرق', 'ختم وتسجيل ظرف الإيداع'),
                    'safety' => 'لا تعدّ النقد على مرأى من اللوبي. لا تنقل النقد عبر منطقة عامة دون موظف ثانٍ.',
                    'quality' => 'لكل وردية ورقة جرد مكتملة وموقعة. تُبلّغ الفروقات في الوردية نفسها دون استثناء.',
                    'escalation' => 'صعّد إلى المالية ومدير المناوبة عند أي فرق يتجاوز الحد المقرر، أو ورقة نقدية مشتبه بتزويرها، أو طلب استرداد دون فاتورة.',
                )),

            array('sop-pre-opening-room-readiness', 'sop-pre-opening', 'HK', 0, 'organization',
                'Pre-opening Room Readiness', 'إجراء جاهزية الغرف قبل الافتتاح',
                array(
                    'purpose' => 'To confirm that a room is complete, functional and to specification before the property accepts its first booking.',
                    'scope' => 'Applies to every room during a pre-opening or post-renovation handover.',
                    'responsibilities' => 'Executive Housekeeper leads the inspection. Chief Engineer signs off systems. General Manager gives final release.',
                    'tools' => 'Room specification sheet, snag list, camera, PPM checklist, inventory list.',
                    'procedure' => array(
                        'Compare the room against the signed specification sheet item by item, including finishes and furniture.',
                        'Count and record the full room inventory: linen, amenities, stationery, hangers, glassware and electricals.',
                        'Test every system with the Engineering team and record the result against the PPM checklist.',
                        'Photograph every defect and enter it on the snag list with a responsible contractor and a date.',
                        'Verify the fire safety items: detector, emergency plan, door closer and the escape route signage.',
                        'Confirm the key encoding works for that room and that the lock audit records the test.',
                        'Deep clean the room after the last contractor has left, not before.',
                        'Re-inspect after the deep clean and close the snag list items that are complete.',
                        'Hold the room out of inventory until every safety item on the snag list is closed.',
                        'Obtain the General Manager release signature and only then load the room into the system for sale.',
                    ),
                    'checklist' => array('Specification compared item by item', 'Inventory counted', 'Systems tested with Engineering',
                        'Defects photographed and listed', 'Fire safety items verified', 'Key encoding tested',
                        'Deep clean after contractors', 'Re-inspection done', 'Safety snags closed', 'General Manager release signed'),
                    'safety' => 'No room is released for sale with an open fire safety, electrical or water safety snag, regardless of the opening date.',
                    'quality' => 'Every released room has a signed readiness record and a closed snag list retained for audit.',
                    'escalation' => 'Escalate to the General Manager any pressure to release a room with an open safety snag.',
                ),
                array(
                    'purpose' => 'التأكد من أن الغرفة مكتملة وتعمل ومطابقة للمواصفات قبل أن يقبل الفندق أول حجز.',
                    'scope' => 'ينطبق على كل غرفة أثناء التسليم قبل الافتتاح أو بعد التجديد.',
                    'responsibilities' => 'مدير التدبير الفندقي يقود التفتيش. كبير المهندسين يعتمد الأنظمة. المدير العام يمنح التحرير النهائي.',
                    'tools' => 'ورقة مواصفات الغرفة، قائمة الملاحظات، كاميرا، قائمة الصيانة الوقائية، قائمة الجرد.',
                    'procedure' => array(
                        'قارن الغرفة بورقة المواصفات المعتمدة بنداً بنداً، بما في ذلك التشطيبات والأثاث.',
                        'اعدّ وسجّل جرد الغرفة الكامل: المفروشات والمستلزمات والقرطاسية والعلاقات والزجاجيات والكهربائيات.',
                        'اختبر كل نظام مع فريق الهندسة وسجّل النتيجة في قائمة الصيانة الوقائية.',
                        'صوّر كل عيب وأدرجه في قائمة الملاحظات مع المقاول المسؤول وتاريخ الإنجاز.',
                        'تحقق من عناصر السلامة من الحريق: الكاشف وخطة الطوارئ ومغلاق الباب ولوحات مسار الهروب.',
                        'تأكد أن ترميز المفاتيح يعمل لتلك الغرفة وأن سجل تدقيق القفل يوثق الاختبار.',
                        'نفّذ التنظيف العميق بعد مغادرة آخر مقاول، لا قبل ذلك.',
                        'أعد التفتيش بعد التنظيف العميق وأغلق بنود قائمة الملاحظات المنجزة.',
                        'أبقِ الغرفة خارج المخزون حتى تُغلق كل بنود السلامة في قائمة الملاحظات.',
                        'احصل على توقيع تحرير المدير العام، ثم أدخل الغرفة في النظام للبيع بعد ذلك فقط.',
                    ),
                    'checklist' => array('مقارنة المواصفات بنداً بنداً', 'جرد المحتويات', 'اختبار الأنظمة مع الهندسة',
                        'تصوير العيوب وإدراجها', 'التحقق من عناصر السلامة', 'اختبار ترميز المفاتيح',
                        'التنظيف العميق بعد المقاولين', 'إعادة التفتيش', 'إغلاق ملاحظات السلامة', 'توقيع تحرير المدير العام'),
                    'safety' => 'لا تُحرَّر أي غرفة للبيع مع وجود ملاحظة مفتوحة تتعلق بسلامة الحريق أو الكهرباء أو المياه، مهما كان موعد الافتتاح.',
                    'quality' => 'لكل غرفة محررة سجل جاهزية موقع وقائمة ملاحظات مغلقة محفوظة للتدقيق.',
                    'escalation' => 'صعّد إلى المدير العام أي ضغط لتحرير غرفة مع ملاحظة سلامة مفتوحة.',
                )),

            array('sop-proc-receiving', 'sop-procurement', 'PROC', 0, 'organization',
                'Goods Receiving', 'إجراء استلام البضائع',
                array(
                    'purpose' => 'To accept only goods that match the purchase order in quantity, quality and condition, and to create the record the invoice will be paid against.',
                    'scope' => 'Applies to every delivery to every property, including food, beverage, operating supplies and contractor materials.',
                    'responsibilities' => 'Receiving Clerk checks and signs. The requesting department verifies quality. Finance matches the invoice.',
                    'tools' => 'Purchase order, calibrated scales, probe thermometer, goods received note, camera.',
                    'procedure' => array(
                        'Refuse any delivery that arrives without a purchase order reference.',
                        'Check the vehicle condition and cleanliness before unloading chilled or frozen goods.',
                        'Probe chilled goods on arrival and reject anything above 5 degrees Celsius.',
                        'Probe frozen goods and reject anything above minus 15 degrees Celsius or showing signs of thawing.',
                        'Weigh or count every line against the purchase order. Do not accept a rounded quantity.',
                        'Check expiry and production dates and reject anything with less than the agreed remaining shelf life.',
                        'Inspect packaging for damage, pest evidence or leakage, and photograph anything rejected.',
                        'Record partial deliveries and short quantities on the delivery note before signing it.',
                        'Sign only for what was actually received, never for the full order as a courtesy.',
                        'Move chilled and frozen goods to storage within fifteen minutes of acceptance.',
                    ),
                    'checklist' => array('Purchase order referenced', 'Vehicle checked', 'Chilled goods probed',
                        'Frozen goods probed', 'Quantities verified', 'Dates checked',
                        'Packaging inspected', 'Shortages recorded', 'Signed for actual receipt', 'Storage within 15 minutes'),
                    'safety' => 'Do not accept any food delivery from an unrefrigerated vehicle. Do not lift beyond the safe manual handling limit.',
                    'quality' => 'Every delivery has a goods received note matched to a purchase order. No invoice is paid without one.',
                    'escalation' => 'Escalate to Procurement and the Executive Chef for repeated quality failures from a supplier, and any rejected temperature delivery.',
                ),
                array(
                    'purpose' => 'قبول البضائع المطابقة لأمر الشراء كمية وجودة وحالة فقط، وإنشاء السجل الذي ستُدفع الفاتورة بناءً عليه.',
                    'scope' => 'ينطبق على كل توريد لكل فندق، بما في ذلك الأغذية والمشروبات ومستلزمات التشغيل ومواد المقاولين.',
                    'responsibilities' => 'موظف الاستلام يفحص ويوقع. القسم الطالب يتحقق من الجودة. المالية تطابق الفاتورة.',
                    'tools' => 'أمر الشراء، موازين معايرة، مقياس حرارة، مذكرة استلام البضائع، كاميرا.',
                    'procedure' => array(
                        'ارفض أي توريد يصل دون مرجع أمر شراء.',
                        'افحص حالة المركبة ونظافتها قبل تنزيل البضائع المبردة أو المجمدة.',
                        'اقس حرارة البضائع المبردة عند الوصول وارفض ما يتجاوز ٥ درجات مئوية.',
                        'اقس حرارة البضائع المجمدة وارفض ما يتجاوز ناقص ١٥ درجة مئوية أو يظهر عليه الذوبان.',
                        'زِن أو اعدّ كل بند مقابل أمر الشراء. لا تقبل كمية مقربة.',
                        'افحص تواريخ الإنتاج والانتهاء وارفض ما تبقى له أقل من مدة الصلاحية المتفق عليها.',
                        'افحص التغليف بحثاً عن التلف أو أثر الآفات أو التسرب، وصوّر كل مرفوض.',
                        'سجّل التوريدات الجزئية والنقص في مذكرة التسليم قبل التوقيع عليها.',
                        'وقّع على ما استُلم فعلاً فقط، لا على الطلب كاملاً مجاملةً.',
                        'انقل البضائع المبردة والمجمدة إلى التخزين خلال خمس عشرة دقيقة من القبول.',
                    ),
                    'checklist' => array('الإشارة لأمر الشراء', 'فحص المركبة', 'قياس حرارة المبرد',
                        'قياس حرارة المجمد', 'التحقق من الكميات', 'فحص التواريخ',
                        'فحص التغليف', 'تسجيل النقص', 'التوقيع على المستلم فعلاً', 'التخزين خلال ١٥ دقيقة'),
                    'safety' => 'لا تقبل أي توريد غذائي من مركبة غير مبردة. لا ترفع أوزاناً تتجاوز حد المناولة اليدوية الآمن.',
                    'quality' => 'لكل توريد مذكرة استلام مطابقة لأمر شراء. لا تُدفع فاتورة بدونها.',
                    'escalation' => 'صعّد إلى المشتريات ورئيس الطهاة التنفيذي عند تكرار إخفاق الجودة من مورد، وعند أي توريد مرفوض حرارياً.',
                )),
        );
    }

    public function run($db) {
        $this->boot($db);
        $written = 0;

        $org = $this->db->get_where('ha_organization', array('slug' => 'dyafa-hospitality-group'))->row_array();
        $org_id = $org ? (int) $org['id'] : null;

        $owner = $this->db->get_where('users', array('email' => 'academy.admin@hospitalityacademy.sa'))->row_array();
        $owner_id = $owner ? (int) $owner['id'] : null;
        $approver = $this->db->get_where('users', array('email' => 'org.admin@dyafagroup.sa'))->row_array();
        $approver_id = $approver ? (int) $approver['id'] : null;

        // Categories
        $category_ids = array();
        foreach (self::categories() as $i => $c) {
            list($code, $en, $ar) = $c;
            $category_ids[$code] = $this->upsert('ha_sop_category', array('code' => $code), array(
                'name_en'    => $en,
                'name_ar'    => $ar,
                'slug_en'    => str_replace('sop-', '', $code),
                'slug_ar'    => $this->slugify($ar),
                'sort_order' => $i,
                'status'     => 'active',
            ));
            $written++;
        }

        foreach (self::documents() as $doc) {
            list($code, $category, $dept, $mandatory, $visibility, $title_en, $title_ar, $en, $ar) = $doc;

            $sop_id = $this->upsert('ha_sop_document', array('code' => $code), array(
                'slug_en'                  => $code,
                'slug_ar'                  => $this->slugify($title_ar),
                'category_id'              => $category_ids[$category],
                'organization_id'          => $org_id,
                'department_code'          => $dept,
                'owner_user_id'            => $owner_id,
                'visibility'               => $visibility,
                'is_mandatory'             => $mandatory,
                'requires_acknowledgement' => 1,
                'review_interval_months'   => 12,
                'status'                   => 'published',
                'created_by'               => $owner_id,
            ));
            $written++;

            $version_id = $this->upsert('ha_sop_version',
                array('sop_id' => $sop_id, 'version_label' => '1.0'),
                array(
                    'version_major'    => 1,
                    'version_minor'    => 0,
                    'change_summary'   => 'First published version.',
                    'author_user_id'   => $owner_id,
                    'approver_user_id' => $approver_id,
                    'status'           => 'published',
                    'effective_date'   => date('Y-m-d'),
                    'review_date'      => date('Y-m-d', strtotime('+12 months')),
                    'approved_at'      => $this->now,
                    'published_at'     => $this->now,
                ));
            $written++;

            $this->db->where('id', $sop_id)->update('ha_sop_document', array('current_version_id' => $version_id));

            foreach (array('en' => $en, 'ar' => $ar) as $locale => $body) {
                $this->upsert('ha_sop_version_translation',
                    array('version_id' => $version_id, 'locale' => $locale),
                    array(
                        'title'             => $locale === 'en' ? $title_en : $title_ar,
                        'purpose'           => $body['purpose'],
                        'scope'             => $body['scope'],
                        'responsibilities'  => $body['responsibilities'],
                        'required_tools'    => $body['tools'],
                        'procedure'         => json_encode($body['procedure'], JSON_UNESCAPED_UNICODE),
                        'checklist'         => json_encode($body['checklist'], JSON_UNESCAPED_UNICODE),
                        'safety_notes'      => $body['safety'],
                        'quality_standard'  => $body['quality'],
                        'escalation'        => $body['escalation'],
                        'related_documents' => '',
                    ));
                $written++;
            }

            // Every SOP checklist becomes a runnable operational checklist.
            $checklist_id = $this->upsert('ha_checklist', array('code' => $code . '-checklist'), array(
                'title_en'        => $title_en . ' Checklist',
                'title_ar'        => 'قائمة تحقق: ' . $title_ar,
                'description_en'  => 'The verification points from ' . $title_en . ', as a checklist that can be run and signed.',
                'description_ar'  => 'نقاط التحقق من ' . $title_ar . ' كقائمة يمكن تنفيذها والتوقيع عليها.',
                'organization_id' => $org_id,
                'department_code' => $dept,
                'sop_id'          => $sop_id,
                'recurrence'      => 'per_shift',
                'status'          => 'published',
                'created_by'      => $owner_id,
            ));
            $written++;

            $this->db->where('checklist_id', $checklist_id)->delete('ha_checklist_item');
            foreach ($en['checklist'] as $i => $label) {
                $this->db->insert('ha_checklist_item', array(
                    'checklist_id' => $checklist_id,
                    'label_en'     => $label,
                    'label_ar'     => isset($ar['checklist'][$i]) ? $ar['checklist'][$i] : $label,
                    'is_mandatory' => 1,
                    'sort_order'   => $i,
                ));
                $written++;
            }
        }

        // Related documents, recorded as real links rather than free text.
        $links = array(
            array('sop-fo-checkin', 'sop-fo-checkout'),
            array('sop-fo-checkin', 'sop-sec-key-control'),
            array('sop-fo-checkout', 'sop-fin-cash-handling'),
            array('sop-hk-room-cleaning', 'sop-hk-lost-found'),
            array('sop-hk-room-cleaning', 'sop-eng-ppm-guestroom'),
            array('sop-kit-temperature', 'sop-proc-receiving'),
            array('sop-eng-fire-panel', 'sop-sec-key-control'),
            array('sop-fb-service-sequence', 'sop-kit-temperature'),
            array('sop-hr-onboarding', 'sop-eng-fire-panel'),
            array('sop-pre-opening-room-readiness', 'sop-eng-ppm-guestroom'),
        );
        $ids = array();
        foreach ($this->db->get('ha_sop_document')->result_array() as $row) {
            $ids[$row['code']] = (int) $row['id'];
        }
        foreach ($links as $pair) {
            if (isset($ids[$pair[0]], $ids[$pair[1]])) {
                $this->link('ha_sop_related', array('sop_id' => $ids[$pair[0]], 'related_sop_id' => $ids[$pair[1]]));
                $this->link('ha_sop_related', array('sop_id' => $ids[$pair[1]], 'related_sop_id' => $ids[$pair[0]]));
                $written += 2;
            }
        }

        return $written;
    }
}
