export type Role =
  "learner" | "supervisor" | "manager" | "instructor" | "admin";
export type ScreenKind =
  | "intro"
  | "auth"
  | "home"
  | "courses"
  | "course"
  | "lesson"
  | "quiz"
  | "result"
  | "knowledge"
  | "sop"
  | "assistant"
  | "progress"
  | "profile"
  | "settings"
  | "list"
  | "detail"
  | "form"
  | "dashboard"
  | "select"
  | "qr"
  | "state";
export interface ScreenSpec {
  id: string;
  title: string;
  ar: string;
  module: string;
  kind: ScreenKind;
  benefit: string;
  roles?: Role[];
  source?: string;
  next?: string;
}
const management: Role[] = ["supervisor", "manager", "admin"];
const admin: Role[] = ["instructor", "admin"];
export const screens: ScreenSpec[] = [
  {
    id: "splash",
    title: "People. Knowledge. Performance.",
    ar: "الأفراد. المعرفة. الأداء.",
    module: "Access",
    kind: "intro",
    benefit: "A confident, recognizable ALTUS arrival.",
    next: "welcome",
  },
  {
    id: "welcome",
    title: "Extraordinary service starts with you.",
    ar: "الخدمة الاستثنائية تبدأ بك.",
    module: "Access",
    kind: "intro",
    benefit: "Connect every employee to the purpose of hospitality.",
    next: "introduction",
  },
  {
    id: "introduction",
    title: "Knowledge that makes a difference.",
    ar: "معرفة تصنع الفرق.",
    module: "Access",
    kind: "intro",
    benefit: "Explain learning, application and measurable performance.",
    next: "language",
  },
  {
    id: "language",
    title: "Your language. Your experience.",
    ar: "لغتك. تجربتك.",
    module: "Access",
    kind: "select",
    benefit: "English and Arabic interfaces; expandable global locale catalog.",
    next: "sign-in",
  },
  {
    id: "sign-in",
    title: "Welcome back",
    ar: "مرحباً بعودتك",
    module: "Access",
    kind: "auth",
    benefit:
      "Securely connect a personal account or explicitly enter the demonstration.",
    next: "first-setup",
  },
  {
    id: "forgot-password",
    title: "Recover your account",
    ar: "استعادة حسابك",
    module: "Access",
    kind: "auth",
    benefit: "Use the existing secure web account recovery flow.",
  },
  {
    id: "reset-password",
    title: "Set a new password",
    ar: "تعيين كلمة مرور جديدة",
    module: "Access",
    kind: "auth",
    benefit: "Complete password recovery with the account provider.",
  },
  {
    id: "otp",
    title: "Verify your identity",
    ar: "تأكيد هويتك",
    module: "Access",
    kind: "auth",
    benefit: "Preserve the platform authenticator and recovery-code policy.",
  },
  {
    id: "first-setup",
    title: "Make it yours",
    ar: "اجعلها تجربتك",
    module: "Access",
    kind: "form",
    benefit: "Set a preferred name and region.",
    next: "organization",
  },
  {
    id: "organization",
    title: "Your hotel group",
    ar: "مجموعتك الفندقية",
    module: "Access",
    kind: "select",
    benefit: "Identify an authorized organization.",
    next: "property",
  },
  {
    id: "property",
    title: "Your property",
    ar: "منشأتك",
    module: "Access",
    kind: "select",
    benefit: "Keep property learning and SOPs in the correct context.",
    next: "role",
  },
  {
    id: "role",
    title: "Your workspace",
    ar: "مساحة عملك",
    module: "Access",
    kind: "select",
    benefit:
      "Confirm server-issued roles; demonstrate role-specific experiences.",
    next: "consent",
  },
  {
    id: "consent",
    title: "A foundation of trust",
    ar: "أساس من الثقة",
    module: "Access",
    kind: "select",
    benefit: "Review privacy and terms before accepting.",
    next: "notification-permission",
  },
  {
    id: "notification-permission",
    title: "Stay one step ahead",
    ar: "ابقَ متقدماً بخطوة",
    module: "Access",
    kind: "select",
    benefit: "Request notification permission at a meaningful moment.",
    next: "setup-success",
  },
  {
    id: "setup-success",
    title: "Your journey starts here",
    ar: "رحلتك تبدأ هنا",
    module: "Access",
    kind: "state",
    benefit: "Confirm setup and guide the employee to the next action.",
    next: "home",
  },
  {
    id: "home",
    title: "Your next step, made clear.",
    ar: "خطوتك التالية واضحة.",
    module: "Learner",
    kind: "home",
    benefit:
      "One prioritized next action, required learning and operational knowledge.",
  },
  {
    id: "learning",
    title: "A little learning. A lasting difference.",
    ar: "تعلّم اليوم. أثر يدوم.",
    module: "Learning",
    kind: "courses",
    benefit: "Search and filter an actionable learning plan.",
    source: "plan",
  },
  ...[
    ["mandatory", "Mandatory learning", "التعلّم الإلزامي"],
    ["assigned", "Assigned courses", "الدورات المعيّنة"],
    ["in-progress", "In progress", "قيد التقدم"],
    ["completed", "Completed learning", "التعلّم المكتمل"],
    ["overdue", "Upcoming & overdue", "القادم والمتأخر"],
    ["recommended", "Recommended for you", "موصى به لك"],
    ["paths", "Learning paths", "مسارات التعلّم"],
    ["programs", "Programs", "البرامج"],
    ["course-history", "Course history", "سجل الدورات"],
  ].map(([id, title, ar]): ScreenSpec => ({
    id,
    title,
    ar,
    module: "Learning",
    kind: "courses",
    benefit: "A focused view of the employee learning journey.",
    source: "plan",
  })),
  {
    id: "catalog",
    title: "Elevate your everyday.",
    ar: "ارتقِ بيومك.",
    module: "Learning",
    kind: "courses",
    benefit: "Discover hospitality learning across professional domains.",
    source: "courses",
  },
  {
    id: "categories",
    title: "Professional domains",
    ar: "المجالات المهنية",
    module: "Learning",
    kind: "list",
    benefit: "Explore every core hospitality discipline.",
  },
  {
    id: "course",
    title: "Course details",
    ar: "تفاصيل الدورة",
    module: "Learning",
    kind: "course",
    benefit:
      "Understand outcomes, competencies, lessons and certificate rules.",
    source: "course",
  },
  {
    id: "lesson",
    title: "Learn. Apply. Remember.",
    ar: "تعلّم. طبّق. تذكّر.",
    module: "Learning",
    kind: "lesson",
    benefit: "A focused native text/video player with progress and next steps.",
    source: "lesson",
  },
  {
    id: "transcript",
    title: "Lesson transcript",
    ar: "نص الدرس",
    module: "Learning",
    kind: "detail",
    benefit: "Read alongside the lesson for accessibility and comprehension.",
  },
  {
    id: "resources",
    title: "Learning resources",
    ar: "موارد التعلّم",
    module: "Learning",
    kind: "list",
    benefit: "Bring practical reference material into the workflow.",
  },
  {
    id: "quiz",
    title: "Put your knowledge to work.",
    ar: "وظّف معرفتك.",
    module: "Assessment",
    kind: "quiz",
    benefit:
      "Scenario and knowledge questions with pass rules and clear feedback.",
  },
  {
    id: "quiz-result",
    title: "Your assessment result",
    ar: "نتيجة تقييمك",
    module: "Assessment",
    kind: "result",
    benefit: "Understand the score, explanations and permitted next step.",
  },
  {
    id: "assessment-history",
    title: "Assessment history",
    ar: "سجل التقييمات",
    module: "Assessment",
    kind: "list",
    benefit: "Review past attempts and improvement.",
  },
  {
    id: "knowledge",
    title: "Confidence, at your fingertips.",
    ar: "الثقة بين يديك.",
    module: "Knowledge",
    kind: "knowledge",
    benefit: "Find current approved SOPs, policies, standards and checklists.",
    source: "knowledge",
  },
  ...[
    ["policies", "Policies & standards", "السياسات والمعايير"],
    ["checklists", "Operational checklists", "قوائم التحقق التشغيلية"],
    ["articles", "Articles & best practices", "المقالات وأفضل الممارسات"],
    ["forms", "Forms & templates", "النماذج والقوالب"],
    ["department-resources", "Department resources", "موارد الأقسام"],
  ].map(([id, title, ar]): ScreenSpec => ({
    id,
    title,
    ar,
    module: "Knowledge",
    kind: "knowledge",
    benefit: "Find operational guidance in the right content category.",
    source: "knowledge",
  })),
  {
    id: "sop",
    title: "The standard behind great service.",
    ar: "المعيار وراء الخدمة المتميزة.",
    module: "Knowledge",
    kind: "sop",
    benefit:
      "Read versioned procedures, safety notes and confirm understanding.",
    source: "sop",
  },
  {
    id: "search",
    title: "What would you like to know?",
    ar: "ماذا تود أن تعرف؟",
    module: "Knowledge",
    kind: "knowledge",
    benefit: "Search courses and authorized operational sources together.",
    source: "search",
  },
  {
    id: "favorites",
    title: "Saved for the moment you need it.",
    ar: "محفوظة للحظة التي تحتاجها.",
    module: "Knowledge",
    kind: "knowledge",
    benefit: "Keep useful courses and guidance close at hand.",
  },
  {
    id: "recent",
    title: "Recently viewed",
    ar: "المشاهدة مؤخراً",
    module: "Knowledge",
    kind: "knowledge",
    benefit: "Return quickly to useful operational content.",
  },
  {
    id: "saved-searches",
    title: "Saved searches",
    ar: "عمليات البحث المحفوظة",
    module: "Knowledge",
    kind: "list",
    benefit: "Repeat useful queries without retyping.",
  },
  {
    id: "acknowledgments",
    title: "Read & confirmed",
    ar: "تمت القراءة والتأكيد",
    module: "Knowledge",
    kind: "list",
    benefit: "Record acknowledgment against the current approved version.",
  },
  {
    id: "assistant",
    title: "Good questions. Trusted answers.",
    ar: "أسئلة جيدة. إجابات موثوقة.",
    module: "Assistant",
    kind: "assistant",
    benefit:
      "Retrieve approved guidance with citations and honest coverage limits.",
    source: "assistant",
  },
  {
    id: "conversation-history",
    title: "Your conversations",
    ar: "محادثاتك",
    module: "Assistant",
    kind: "list",
    benefit: "Return to previous questions and sources.",
  },
  {
    id: "progress",
    title: "See how far you have come.",
    ar: "شاهد مدى تقدمك.",
    module: "Performance",
    kind: "progress",
    benefit: "Track learning, readiness, activity and evidence.",
    source: "plan",
  },
  {
    id: "competencies",
    title: "Turn knowledge into capability.",
    ar: "حوّل المعرفة إلى كفاءة.",
    module: "Performance",
    kind: "dashboard",
    benefit: "Understand strengths, gaps and recommended next learning.",
    source: "competencies",
  },
  {
    id: "readiness",
    title: "Ready, with evidence.",
    ar: "جاهزية مدعومة بالأدلة.",
    module: "Performance",
    kind: "dashboard",
    benefit: "Explain readiness using actual policy checks.",
    source: "readiness",
  },
  {
    id: "actions",
    title: "Your improvement plan",
    ar: "خطة تحسينك",
    module: "Performance",
    kind: "list",
    benefit: "Make identified gaps actionable.",
    source: "actions",
  },
  {
    id: "action-detail",
    title: "Improvement action",
    ar: "إجراء التحسين",
    module: "Performance",
    kind: "detail",
    benefit: "Review deadlines, evidence and review status.",
  },
  {
    id: "certificates",
    title: "Achievement, recognized.",
    ar: "إنجاز يستحق التقدير.",
    module: "Performance",
    kind: "list",
    benefit: "Find issued credentials and expiry details.",
    source: "certificates",
  },
  {
    id: "certificate",
    title: "Your achievement",
    ar: "إنجازك",
    module: "Performance",
    kind: "detail",
    benefit: "Review and share an issued certificate.",
  },
  {
    id: "certificate-verify",
    title: "Verify a credential",
    ar: "تحقق من الشهادة",
    module: "Performance",
    kind: "qr",
    benefit: "Check a certificate using the trusted verification service.",
  },
  {
    id: "notifications",
    title: "Your updates",
    ar: "تحديثاتك",
    module: "Personal",
    kind: "list",
    benefit: "Read assignment reminders, revisions and announcements.",
    source: "notifications",
  },
  {
    id: "notification-detail",
    title: "Update details",
    ar: "تفاصيل التحديث",
    module: "Personal",
    kind: "detail",
    benefit: "Understand a notification and open the relevant destination.",
  },
  {
    id: "announcements",
    title: "From your property",
    ar: "من منشأتك",
    module: "Personal",
    kind: "list",
    benefit: "Keep employees aligned on important operational updates.",
  },
  {
    id: "calendar",
    title: "Make time for growth.",
    ar: "خصص وقتاً للنمو.",
    module: "Personal",
    kind: "list",
    benefit: "See training sessions and upcoming deadlines.",
  },
  {
    id: "event",
    title: "Training session",
    ar: "جلسة تدريبية",
    module: "Personal",
    kind: "detail",
    benefit: "Review the session, location and attendance action.",
  },
  {
    id: "qr-attendance",
    title: "Check in to learning",
    ar: "سجّل حضورك للتعلّم",
    module: "Personal",
    kind: "qr",
    benefit: "Scan an attendance or authorized learning link.",
  },
  {
    id: "downloads",
    title: "Knowledge that travels with you.",
    ar: "معرفة ترافقك.",
    module: "Personal",
    kind: "list",
    benefit: "Review saved offline reading and remove local downloads.",
  },
  {
    id: "download-detail",
    title: "Offline content",
    ar: "المحتوى دون اتصال",
    module: "Personal",
    kind: "detail",
    benefit: "Read locally saved content and see its version.",
  },
  {
    id: "discussion",
    title: "Better, together.",
    ar: "أفضل معاً.",
    module: "Collaboration",
    kind: "list",
    benefit: "Read and contribute to learning conversations.",
  },
  {
    id: "discussion-detail",
    title: "Learning conversation",
    ar: "محادثة التعلّم",
    module: "Collaboration",
    kind: "detail",
    benefit: "Review instructor and colleague contributions.",
  },
  {
    id: "new-discussion",
    title: "Ask your team",
    ar: "اسأل فريقك",
    module: "Collaboration",
    kind: "form",
    benefit: "Post a focused learning question.",
  },
  {
    id: "profile",
    title: "Your space to grow.",
    ar: "مساحتك للنمو.",
    module: "Personal",
    kind: "profile",
    benefit: "Find account details, preferences and every personal tool.",
  },
  {
    id: "edit-profile",
    title: "Your profile",
    ar: "ملفك الشخصي",
    module: "Personal",
    kind: "form",
    benefit: "Maintain personal display details.",
  },
  {
    id: "settings",
    title: "Make it work for you.",
    ar: "اجعلها تناسبك.",
    module: "Personal",
    kind: "settings",
    benefit: "Change language, theme and accessibility without signing out.",
  },
  {
    id: "notification-settings",
    title: "Notification preferences",
    ar: "تفضيلات الإشعارات",
    module: "Personal",
    kind: "settings",
    benefit: "Choose useful reminder categories.",
  },
  {
    id: "security",
    title: "Account security",
    ar: "أمان الحساب",
    module: "Personal",
    kind: "auth",
    benefit:
      "Manage credentials, password and MFA using the existing identity system.",
  },
  {
    id: "privacy",
    title: "Privacy",
    ar: "الخصوصية",
    module: "Personal",
    kind: "detail",
    benefit:
      "Understand how workplace account and learning information is used.",
  },
  {
    id: "terms",
    title: "Terms of use",
    ar: "شروط الاستخدام",
    module: "Personal",
    kind: "detail",
    benefit: "Review the platform terms.",
  },
  {
    id: "about",
    title: "People. Knowledge. Performance.",
    ar: "الأفراد. المعرفة. الأداء.",
    module: "Personal",
    kind: "detail",
    benefit: "Explain ALTUS positioning and the app version.",
  },
  {
    id: "delete-account",
    title: "Account deletion request",
    ar: "طلب حذف الحساب",
    module: "Personal",
    kind: "form",
    benefit: "Request account deletion with employer retention considerations.",
  },
  {
    id: "management",
    title: "Great teams. Measurable progress.",
    ar: "فرق متميزة. تقدم قابل للقياس.",
    module: "Management",
    kind: "dashboard",
    benefit: "See who needs attention and act on training and readiness.",
    roles: management,
    source: "people",
  },
  {
    id: "team",
    title: "The people behind the experience.",
    ar: "الأفراد وراء التجربة.",
    module: "Management",
    kind: "list",
    benefit: "Find authorized employees and their readiness.",
    roles: management,
    source: "people",
  },
  {
    id: "learner-detail",
    title: "Employee development",
    ar: "تطوير الموظف",
    module: "Management",
    kind: "detail",
    benefit: "Review the employee learning and competency record.",
    roles: management,
  },
  {
    id: "assign",
    title: "Give growth a direction.",
    ar: "امنح النمو اتجاهاً.",
    module: "Management",
    kind: "form",
    benefit: "Assign a course to authorized people with a deadline.",
    roles: management,
  },
  {
    id: "reports",
    title: "From insight to improvement.",
    ar: "من الرؤية إلى التحسين.",
    module: "Management",
    kind: "dashboard",
    benefit: "Review capability gaps and property performance.",
    roles: management,
    source: "kpis",
  },
  {
    id: "gaps",
    title: "Where to focus next",
    ar: "أين نركز تالياً",
    module: "Management",
    kind: "list",
    benefit: "Prioritize open competency gaps.",
    roles: management,
    source: "gaps",
  },
  {
    id: "assessor-queue",
    title: "Practical assessment queue",
    ar: "قائمة التقييم العملي",
    module: "Management",
    kind: "list",
    benefit: "Find employees ready for practical evaluation.",
    roles: management,
  },
  {
    id: "practical",
    title: "Observe. Assess. Develop.",
    ar: "لاحظ. قيّم. طوّر.",
    module: "Management",
    kind: "form",
    benefit: "Record criterion-based observed evidence.",
    roles: management,
  },
  {
    id: "branding",
    title: "Your brand. ALTUS capability.",
    ar: "علامتك. كفاءة ألتوس.",
    module: "Management",
    kind: "form",
    benefit: "Preview property identity using centralized design tokens.",
    roles: management,
  },
  {
    id: "admin",
    title: "A portfolio of potential.",
    ar: "محفظة من الإمكانات.",
    module: "Administration",
    kind: "dashboard",
    benefit: "Reach central content, governance, property and system tools.",
    roles: admin,
  },
  ...[
    ["clients", "Client organizations", "العملاء والمؤسسات"],
    ["properties", "Properties", "المنشآت"],
    ["users", "Users & access", "المستخدمون والصلاحيات"],
    ["roles", "Roles & permissions", "الأدوار والصلاحيات"],
    ["content", "Content library", "مكتبة المحتوى"],
    ["versions", "Versions & approvals", "الإصدارات والموافقات"],
    ["portfolio", "Cross-property analytics", "تحليلات المنشآت"],
    ["audit", "Audit activity", "نشاط التدقيق"],
  ].map(([id, title, ar]): ScreenSpec => ({
    id,
    title,
    ar,
    module: "Administration",
    kind: id === "portfolio" ? "dashboard" : "list",
    benefit: "Review governed platform operations in the authorized scope.",
    roles: admin,
  })),
  {
    id: "course-editor",
    title: "Shape the learning experience.",
    ar: "صمّم تجربة التعلّم.",
    module: "Administration",
    kind: "form",
    benefit: "Prepare a course draft without overwriting published content.",
    roles: admin,
  },
  {
    id: "version-detail",
    title: "Review with confidence.",
    ar: "راجع بثقة.",
    module: "Administration",
    kind: "detail",
    benefit: "Review revision metadata and approval separation.",
    roles: admin,
  },
  {
    id: "support",
    title: "We are here to help.",
    ar: "نحن هنا لمساعدتك.",
    module: "Support",
    kind: "list",
    benefit: "Find FAQs, issue reporting and support requests.",
  },
  {
    id: "faq",
    title: "A little clarity",
    ar: "مزيد من الوضوح",
    module: "Support",
    kind: "list",
    benefit: "Resolve common learning and account questions.",
  },
  {
    id: "tickets",
    title: "Your support requests",
    ar: "طلبات الدعم",
    module: "Support",
    kind: "list",
    benefit: "Track the status of submitted support requests.",
  },
  {
    id: "new-ticket",
    title: "Let us help you move forward.",
    ar: "دعنا نساعدك على التقدم.",
    module: "Support",
    kind: "form",
    benefit: "Describe an issue and attach a file.",
  },
  {
    id: "ticket-detail",
    title: "Support request",
    ar: "طلب الدعم",
    module: "Support",
    kind: "detail",
    benefit: "Read a submitted issue and its status.",
  },
  {
    id: "report-issue",
    title: "Report an issue",
    ar: "الإبلاغ عن مشكلة",
    module: "Support",
    kind: "form",
    benefit: "Report a technical or content issue with context.",
  },
  ...[
    ["offline", "You are offline", "أنت غير متصل"],
    ["session-expired", "Please sign in again", "يرجى تسجيل الدخول مجدداً"],
    [
      "maintenance",
      "A little care, behind the scenes.",
      "نعمل على تحسين التجربة.",
    ],
    ["update-required", "A better experience awaits.", "تجربة أفضل بانتظارك."],
    ["permission-denied", "Access is restricted", "الوصول مقيّد"],
    ["error", "Let us try that again.", "لنحاول مرة أخرى."],
    ["not-found", "This page is unavailable", "هذه الصفحة غير متاحة"],
  ].map(([id, title, ar]): ScreenSpec => ({
    id,
    title,
    ar,
    module: "System",
    kind: "state",
    benefit: "A clear, recoverable system state.",
  })),
];
export const byId = Object.fromEntries(screens.map((s) => [s.id, s])) as Record<
  string,
  ScreenSpec
>;
export const publicScreens = new Set(
  screens
    .filter(
      (s) =>
        s.module === "Access" ||
        ["privacy", "terms", "about", "not-found"].includes(s.id),
    )
    .map((s) => s.id),
);
