<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
| -------------------------------------------------------------------------
| AI provider registry (ha_ai_providers)
| -------------------------------------------------------------------------
| Researched: 2026-09-24, against official provider documentation pages
| (URLs are given per entry in 'sources' / 'available_regions').
|
| RULES
|  1. The live models endpoint (models_path) is the SOURCE OF TRUTH for
|     model IDs. 'default_models' is only an offline fallback / UI hint and
|     WILL go stale. Always prefer GET base_url . models_path when non-null.
|  2. Full request URL = base_url . path (chat_path, models_path, tts.path,
|     video.create_path ...). Paths starting with 'https://' are absolute.
|     Placeholders in {braces} must be substituted by the caller.
|  3. Anything that could not be confirmed on an official page is null, or
|     is listed in the entry's 'unverified' array with an explanation in
|     'note'. hq_country is general company knowledge (not stated in API
|     docs) and is therefore listed as unverified everywhere.
|  4. auth: send header  <auth.header>: <auth.prefix><credential>
|     plus every entry of auth.extra_headers. 'flow' describes non-static
|     credentials (OAuth / IAM exchanges).
|
| api_style values: openai | anthropic | gemini | cohere | bedrock |
|                   azure_openai | custom
| capabilities values: chat, vision, tts, stt, image, video, embeddings
| -------------------------------------------------------------------------
*/

$config['ha_ai_providers'] = array(

	/* =====================================================================
	 * GLOBAL / WESTERN LLM PROVIDERS
	 * ===================================================================*/

	'anthropic' => array(
		'name'        => 'Claude API',
		'company'     => 'Anthropic',
		'hq_country'  => 'US',
		'docs_url'    => 'https://platform.claude.com/docs/en/api/overview',
		'api_style'   => 'anthropic',
		'base_url'    => 'https://api.anthropic.com',
		'regional_base_urls' => array(),
		'openai_compatible' => array(
			'base_url' => 'https://api.anthropic.com/v1',
			'note'     => 'Docs: not a long-term/production-ready solution; ignores response_format, strict, audio, prompt caching.',
		),
		'auth' => array(
			'header' => 'x-api-key',
			'prefix' => '',
			'alt'    => 'Authorization: Bearer <key> is also accepted',
			'extra_headers' => array(
				'anthropic-version' => '2023-06-01',
				'content-type'      => 'application/json',
			),
			'optional_headers' => array('anthropic-workspace-id' => 'required only with multi-workspace API keys'),
		),
		'chat_path'   => '/v1/messages',
		'models_path' => '/v1/models',
		'capabilities' => array('chat', 'vision'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array(
			'text'   => 'About 150 listed countries incl. SA, AE, EG, JO, KW, QA, OM, BH, EU, UK, US, IN. China, Russia, Iran are not listed. Ukraine excludes Crimea/Donetsk/Luhansk. Data residency via request body inference_geo = "global" (default) or "us" (1.1x price).',
			'source' => 'https://platform.claude.com/docs/en/api/supported-regions',
		),
		'default_models' => array('claude-opus-5-5', 'claude-sonnet-5', 'claude-haiku-4-5'),
		'key_url'  => 'https://platform.claude.com/settings/keys',
		'unverified' => array('hq_country'),
		'note' => 'Models list uses after_id/before_id pagination.',
	),

	'openai' => array(
		'name'        => 'OpenAI API',
		'company'     => 'OpenAI',
		'hq_country'  => 'US',
		'docs_url'    => 'https://developers.openai.com/api/docs',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.openai.com/v1',
		'regional_base_urls' => array(
			'United States'            => 'https://us.api.openai.com/v1',
			'Europe (EEA+Switzerland)' => 'https://eu.api.openai.com/v1',
			'Australia'                => 'https://au.api.openai.com/v1',
			'Canada'                   => 'https://ca.api.openai.com/v1',
			'Japan'                    => 'https://jp.api.openai.com/v1',
			'India'                    => 'https://in.api.openai.com/v1',
			'Singapore'                => 'https://sg.api.openai.com/v1',
			'South Korea'              => 'https://kr.api.openai.com/v1',
			'United Kingdom'           => 'https://gb.api.openai.com/v1',
			'United Arab Emirates'     => 'https://ae.api.openai.com/v1',
		),
		'auth' => array(
			'header' => 'Authorization',
			'prefix' => 'Bearer ',
			'extra_headers' => array(),
			'optional_headers' => array('OpenAI-Organization' => '', 'OpenAI-Project' => ''),
		),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'tts', 'stt', 'image', 'embeddings'),
		'tts' => array(
			'path'        => '/audio/speech',
			'method'      => 'POST',
			'format'      => 'JSON {model, input, voice, instructions?, response_format?: mp3|opus|aac|flac|wav|pcm}. Returns binary audio. instructions not supported by tts-1/tts-1-hd.',
			'voices_path' => null,
			'voices'      => array('alloy', 'ash', 'ballad', 'coral', 'echo', 'fable', 'nova', 'onyx', 'sage', 'shimmer', 'verse', 'marin', 'cedar'),
			'models'      => array('gpt-4o-mini-tts', 'tts-1', 'tts-1-hd'),
		),
		'video' => null,
		'available_regions' => array(
			'text'   => '190+ supported countries incl. SA, AE. China, Russia, Iran, North Korea, Syria, Cuba not supported. Regional hosts need data residency enabled on the project; UAE needs extra approval; only US/EU do regional processing (others storage only).',
			'source' => 'https://developers.openai.com/api/docs/supported-countries',
		),
		'default_models' => array('gpt-6-astra', 'gpt-6-sol', 'gpt-6-luna'),
		'key_url'  => 'https://platform.openai.com/settings/organization/api-keys',
		'unverified' => array('hq_country'),
		'note' => 'Sora 2 models and the Videos API (/v1/videos) were shut down on 2026-09-24 (source: https://developers.openai.com/api/docs/guides/video-generation), so video is null. Responses API (/responses) is the recommended primitive; /chat/completions still supported.',
	),

	'gemini' => array(
		'name'        => 'Gemini API (Google AI Studio)',
		'company'     => 'Google',
		'hq_country'  => 'US',
		'docs_url'    => 'https://ai.google.dev/gemini-api/docs',
		'api_style'   => 'gemini',
		'base_url'    => 'https://generativelanguage.googleapis.com/v1beta',
		'regional_base_urls' => array(),
		'openai_compatible' => array(
			'base_url' => 'https://generativelanguage.googleapis.com/v1beta/openai',
			'auth'     => 'Authorization: Bearer <GEMINI_API_KEY>',
			'paths'    => array('/chat/completions', '/models', '/embeddings', '/images/generations', '/videos'),
		),
		'auth' => array(
			'header' => 'x-goog-api-key',
			'prefix' => '',
			'extra_headers' => array(),
		),
		'chat_path'   => '/models/{model}:generateContent',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'tts', 'image', 'video', 'embeddings'),
		'tts' => array(
			'path'        => '/interactions',
			'method'      => 'POST',
			'format'      => 'JSON {model, input:[{type:"user_input",content:[{type:"text",text}]}], response_format:{type:"audio"}, generation_config:{speech_config:[{voice:"Kore"}]}}. Returns WAV 24kHz mono 16-bit by default; streaming = raw audio/l16.',
			'voices_path' => '/voices',
			'voices'      => array('Zephyr', 'Puck', 'Charon', 'Kore', 'Fenrir', 'Leda', 'Orus', 'Aoede'),
			'models'      => array('gemini-3.8-flash-tts', 'gemini-3.8-flash-lite-tts'),
		),
		'video' => array(
			'create_path' => '/models/{model}:predictLongRunning',
			'status_path' => '/{operation_name}',
			'format'      => 'JSON {instances:[{prompt}], parameters:{aspectRatio 16:9|9:16, resolution 720p|1080p|4k, durationSeconds 4|6|8}}. Poll operation until done, then download video URI with the API key header.',
			'models'      => array('veo-3.1-generate-preview', 'veo-3.1-fast-generate-preview', 'veo-3.1-lite-generate-preview'),
			'notes'       => 'Docs recommend gemini-omni-1.1-flash (Interactions API) for general video; Veo for extension/frame control. personGeneration limited to allow_adult in EU/UK/CH/MENA.',
		),
		'available_regions' => array(
			'text'   => '190+ countries incl. EU, UK, SA, AE. China, Russia, Iran, North Korea, Syria not listed. Users must be 18+. Unsupported regions can use Vertex AI / Gemini Enterprise Agent Platform.',
			'source' => 'https://ai.google.dev/gemini-api/docs/available-regions',
		),
		'default_models' => array('gemini-3.8-flash', 'gemini-3.1-pro-preview', 'gemini-3.5-flash-lite'),
		'key_url'  => 'https://aistudio.google.com/apikey',
		'unverified' => array('hq_country'),
		'note' => 'TTS is documented only through the Interactions API (not generateContent) as of this date.',
	),

	'vertex_ai' => array(
		'name'        => 'Gemini Enterprise Agent Platform (formerly Vertex AI)',
		'company'     => 'Google Cloud',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.cloud.google.com/gemini-enterprise-agent-platform/overview',
		'api_style'   => 'gemini',
		'base_url'    => 'https://aiplatform.googleapis.com/v1/projects/{project}/locations/global',
		'regional_base_urls' => array(
			'global'                => 'https://aiplatform.googleapis.com/v1/projects/{project}/locations/global',
			'regional (e.g. us-central1)' => 'https://{region}-aiplatform.googleapis.com/v1/projects/{project}/locations/{region}',
			'US multi-region'       => 'https://aiplatform.us.rep.googleapis.com/v1/projects/{project}/locations/us',
			'EU multi-region'       => 'https://aiplatform.eu.rep.googleapis.com/v1/projects/{project}/locations/eu',
		),
		'openai_compatible' => array(
			'base_url' => 'https://{region}-aiplatform.googleapis.com/v1/projects/{project}/locations/{region}/endpoints/openapi',
			'paths'    => array('/chat/completions'),
			'note'     => 'model IDs take the form google/gemini-...',
		),
		'auth' => array(
			'header' => 'Authorization',
			'prefix' => 'Bearer ',
			'flow'   => 'OAuth2 access token from ADC / service account (e.g. gcloud auth print-access-token), scope https://www.googleapis.com/auth/cloud-platform.',
			'extra_headers' => array(),
		),
		'chat_path'   => '/publishers/google/models/{model}:generateContent',
		'models_path' => null,
		'capabilities' => array('chat', 'vision', 'image', 'video', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array(
			'text'   => 'Per Google Cloud region; see locations page.',
			'source' => 'https://docs.cloud.google.com/gemini-enterprise-agent-platform/resources/locations',
		),
		'default_models' => array('gemini-3.8-flash'),
		'key_url'  => 'https://console.cloud.google.com/iam-admin/serviceaccounts',
		'unverified' => array('hq_country', 'models_path', 'tts', 'video', 'available_regions', 'key_url'),
		'note' => 'Renamed from Vertex AI (hostname unchanged). Publisher model list endpoint, TTS and Veo paths on this platform, and region list were not confirmed on an official page (set null); likely parity with Gemini API. Claude is available via Model Garden.',
	),

	'azure_openai' => array(
		'name'        => 'Azure OpenAI in Microsoft Foundry Models',
		'company'     => 'Microsoft',
		'hq_country'  => 'US',
		'docs_url'    => 'https://learn.microsoft.com/en-us/azure/foundry/openai/api-version-lifecycle',
		'api_style'   => 'azure_openai',
		'base_url'    => 'https://{resource}.openai.azure.com/openai/v1',
		'regional_base_urls' => array(
			'Foundry resource host' => 'https://{resource}.services.ai.azure.com/openai/v1',
		),
		'auth' => array(
			'header' => 'api-key',
			'prefix' => '',
			'alt'    => 'Authorization: Bearer <Entra ID token>, scope https://ai.azure.com/.default',
			'extra_headers' => array(),
		),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'tts', 'stt', 'image', 'video', 'embeddings'),
		'tts' => array(
			'path'        => '/audio/speech?api-version=preview',
			'method'      => 'POST',
			'format'      => 'OpenAI-style JSON {model (deployment), input (max 4096 chars), voice, response_format, speed 0.25-4, instructions, stream_format sse|audio}.',
			'voices_path' => null,
			'voices'      => array('alloy', 'ash', 'ballad', 'coral', 'echo', 'sage', 'shimmer', 'verse', 'marin', 'cedar'),
			'models'      => array('gpt-4o-mini-tts'),
		),
		'video' => array(
			'create_path' => '/video/generations/jobs?api-version=preview',
			'status_path' => '/video/generations/jobs/{job_id}?api-version=preview',
			'content_path'=> '/video/generations/{generation_id}/content/video?api-version=preview',
			'models'      => array('sora-2'),
			'notes'       => 'Preview; sora-2 version 2025-12-08 retires 2026-10-15. Whether sora-2 uses this path or /videos was not confirmed.',
		),
		'available_regions' => array(
			'text'   => 'Region chosen per resource. Deployment types: Global, Data Zone (US/EU/Asia Pacific), Regional. Per-model region tables at source.',
			'source' => 'https://learn.microsoft.com/en-us/azure/foundry/foundry-models/concepts/models-sold-directly-by-azure-region-availability',
		),
		'default_models' => array('gpt-6-astra', 'gpt-5.5'),
		'key_url'  => 'https://portal.azure.com',
		'unverified' => array('hq_country', 'models_path', 'video'),
		'note' => 'v1 API needs no api-version (except preview features). "model" = your deployment name. Key is under resource > Keys and Endpoint. GET /openai/v1/models not quoted on fetched pages.',
	),

	'bedrock' => array(
		'name'        => 'Amazon Bedrock',
		'company'     => 'Amazon Web Services',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.aws.amazon.com/bedrock/latest/userguide/',
		'api_style'   => 'bedrock',
		'base_url'    => 'https://bedrock-runtime.{region}.amazonaws.com',
		'regional_base_urls' => array(
			'bedrock-runtime (per AWS region)' => 'https://bedrock-runtime.{region}.amazonaws.com',
			'bedrock-mantle (compatibility)'   => 'https://bedrock-mantle.{region}.api.aws/v1',
		),
		'openai_compatible' => array(
			'base_url' => 'https://bedrock-runtime.{region}.amazonaws.com/openai/v1',
			'paths'    => array('/chat/completions', '/responses'),
			'note'     => 'bedrock-runtime does NOT implement GET /models; bedrock-mantle (https://bedrock-mantle.{region}.api.aws/v1) does.',
		),
		'auth' => array(
			'header' => 'Authorization',
			'prefix' => 'Bearer ',
			'flow'   => 'Amazon Bedrock API key (env AWS_BEARER_TOKEN_BEDROCK) as Bearer, or AWS SigV4 signing with IAM credentials.',
			'extra_headers' => array(),
		),
		'chat_path'   => '/model/{modelId}/converse',
		'models_path' => null,
		'capabilities' => array('chat', 'vision', 'video', 'embeddings'),
		'tts'   => null,
		'video' => array(
			'create_path' => '/async-invoke',
			'status_path' => '/async-invoke/{invocationArn}',
			'models'      => array('amazon.nova-reel-v1:1'),
			'notes'       => 'StartAsyncInvoke; output written to an S3 bucket.',
		),
		'available_regions' => array(
			'text'   => 'Model availability varies by AWS region; cross-region inference profiles US, EU, JP, AU, global.',
			'source' => 'https://docs.aws.amazon.com/bedrock/latest/userguide/endpoints.html',
		),
		'default_models' => array('anthropic.claude-opus-5-5', 'openai.gpt-oss-120b-1:0'),
		'key_url'  => 'https://console.aws.amazon.com/bedrock',
		'unverified' => array('hq_country', 'video'),
		'note' => 'List models via control-plane ListFoundationModels (https://bedrock.{region}.amazonaws.com/foundation-models) or GET /models on bedrock-mantle. Nova Reel async-invoke paths from search snippet only. Amazon Polly (TTS) is a separate service, not covered.',
	),

	'mistral' => array(
		'name'        => 'Mistral AI API (Studio)',
		'company'     => 'Mistral AI',
		'hq_country'  => 'FR',
		'docs_url'    => 'https://docs.mistral.ai/api/',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.mistral.ai/v1',
		'regional_base_urls' => array(
			'EU' => 'https://api.eu.mistral.ai/v1',
			'US' => 'https://api.us.mistral.ai/v1',
		),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'tts', 'stt', 'embeddings'),
		'tts' => array(
			'path'        => '/audio/speech',
			'method'      => 'POST',
			'format'      => 'JSON {input, model, voice_id | ref_audio (base64 clip for zero-shot cloning), response_format pcm|wav|mp3|flac|opus, stream}. Returns JSON {audio_data: base64} or SSE.',
			'voices_path' => '/audio/voices',
			'models'      => array('voxtral-mini-tts-2603'),
		),
		'video' => null,
		'available_regions' => array(
			'text'   => 'Global endpoint has no fixed inference location; EU/US regional endpoints cost 1.1x, serve only regionally hosted models, and lack Agents/Batch/Files. No supported-countries page found.',
			'source' => 'https://docs.mistral.ai/inference/regional-inference',
		),
		'default_models' => array('mistral-medium-3-5', 'mistral-large-2512', 'mistral-small-4-0-26-03'),
		'key_url'  => 'https://console.mistral.ai',
		'unverified' => array('hq_country'),
		'note' => 'STT: /audio/transcriptions with voxtral-mini-transcribe-26-02. Regional base path suffix /v1 assumed by analogy with global host.',
	),

	'cohere' => array(
		'name'        => 'Cohere API',
		'company'     => 'Cohere',
		'hq_country'  => 'CA',
		'docs_url'    => 'https://docs.cohere.com',
		'api_style'   => 'cohere',
		'base_url'    => 'https://api.cohere.com',
		'regional_base_urls' => array(),
		'openai_compatible' => array(
			'base_url' => 'https://api.cohere.ai/compatibility/v1',
			'paths'    => array('/chat/completions', '/embeddings', '/audio/transcriptions'),
		),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/v2/chat',
		'models_path' => '/v1/models',
		'capabilities' => array('chat', 'vision', 'stt', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('command-a-plus-05-2026', 'command-a-03-2025', 'command-a-reasoning-08-2025'),
		'key_url'  => 'https://dashboard.cohere.com/api-keys',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'No supported-countries page found (unverified). Embeddings embed-v4.0; rerank rerank-v4.0-pro; STT cohere-transcribe-03-2026.',
	),

	'xai' => array(
		'name'        => 'xAI API (Grok)',
		'company'     => 'xAI',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.x.ai',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.x.ai/v1',
		'regional_base_urls' => array(
			'US (US processing guaranteed; limited models)' => 'https://us.api.x.ai/v1',
		),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'tts', 'stt', 'image', 'video'),
		'tts' => array(
			'path'        => '/tts',
			'method'      => 'POST',
			'format'      => 'JSON {text (<=60k chars), language (BCP-47 or "auto"), voice_id (default "eve"), output_format {codec mp3|wav|pcm|mulaw|alaw, sample_rate, bit_rate}, speed 0.7-1.5}. Returns raw audio bytes. WebSocket streaming wss://api.x.ai/v1/tts.',
			'voices_path' => '/tts/voices',
		),
		'video' => array(
			'create_path' => '/videos/generations',
			'status_path' => '/videos/{request_id}',
			'format'      => 'JSON {prompt, model, duration 1-15, aspect_ratio, resolution 480p|720p|1080p, image?, generate_audio?}. Status pending|done|expired|failed.',
			'models'      => array('grok-imagine-video-1.5', 'grok-imagine-video'),
		),
		'available_regions' => array(
			'text'   => 'No country restrictions stated on regions page. Regional endpoint alone is not a full data-residency guarantee.',
			'source' => 'https://docs.x.ai/docs/key-information/regions',
		),
		'default_models' => array('grok-4.7', 'grok-4.20-0309-reasoning', 'grok-4.20-0309-non-reasoning'),
		'key_url'  => 'https://console.x.ai/team/default/api-keys',
		'unverified' => array('hq_country'),
		'note' => '/chat/completions is labelled legacy; /responses recommended. Image: POST /images/generations (grok-imagine-image-2.0). An eu-west-1 host appeared only in a search snippet and is omitted.',
	),

	'groq' => array(
		'name'        => 'GroqCloud',
		'company'     => 'Groq, Inc.',
		'hq_country'  => 'US',
		'docs_url'    => 'https://console.groq.com/docs',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.groq.com/openai/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'tts', 'stt'),
		'tts' => array(
			'path'        => '/audio/speech',
			'method'      => 'POST',
			'format'      => 'OpenAI-style JSON {model, input (<=200 chars), voice, response_format wav}. WAV only.',
			'voices_path' => null,
			'voices'      => array('autumn', 'diana', 'hannah', 'austin', 'daniel', 'troy'),
			'models'      => array('canopylabs/orpheus-v1-english', 'canopylabs/orpheus-arabic-saudi'),
		),
		'video' => null,
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('openai/gpt-oss-120b', 'llama-3.3-70b-versatile', 'llama-3.1-8b-instant'),
		'key_url'  => 'https://console.groq.com/keys',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'No country list found. Regional pinning is Enterprise-only (community FAQ). Arabic Orpheus voices: abdullah, fahad, sultan, lulwa, noura, aisha. STT models whisper-large-v3, whisper-large-v3-turbo.',
	),

	'cerebras' => array(
		'name'        => 'Cerebras Inference',
		'company'     => 'Cerebras Systems',
		'hq_country'  => 'US',
		'docs_url'    => 'https://inference-docs.cerebras.ai',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.cerebras.ai/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('gpt-oss-120b', 'qwen-3.8-27b'),
		'key_url'  => 'https://cloud.cerebras.ai',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'Vision accepts base64 data URIs only.',
	),

	'deepseek' => array(
		'name'        => 'DeepSeek API',
		'company'     => 'DeepSeek',
		'hq_country'  => 'CN',
		'docs_url'    => 'https://api-docs.deepseek.com/',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.deepseek.com',
		'regional_base_urls' => array(),
		'anthropic_compatible' => array('base_url' => 'https://api.deepseek.com/anthropic'),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('deepseek-flash', 'deepseek-v4-pro'),
		'key_url'  => 'https://platform.deepseek.com/api_keys',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'Legacy name deepseek-v4-flash still accepted, served by V4.1-Flash.',
	),

	'together' => array(
		'name'        => 'Together AI',
		'company'     => 'Together AI',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.together.ai',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.together.ai/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'tts', 'stt', 'image', 'video', 'embeddings'),
		'tts' => array(
			'path'        => '/audio/speech',
			'method'      => 'POST',
			'format'      => 'OpenAI-style JSON {model, input, voice, response_format mp3|wav|raw|mulaw, sample_rate, language}.',
			'voices_path' => '/voices?model={model}',
			'models'      => array('hexgrad/Kokoro-82M'),
		),
		'video' => array(
			'create_path' => 'https://api.together.ai/v2/videos',
			'status_path' => 'https://api.together.ai/v2/videos/{id}',
			'format'      => 'Async job; status queued|in_progress|completed|failed|cancelled.',
			'models'      => array('openai/sora-2'),
		),
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('MiniMaxAI/MiniMax-M3', 'deepseek-ai/DeepSeek-V4-Pro-0813', 'meta-llama/Llama-3.3-70B-Instruct-Turbo'),
		'key_url'  => 'https://api.together.ai/',
		'unverified' => array('hq_country', 'models_path', 'available_regions', 'video'),
		'note' => 'Video status path inferred from SDK videos.retrieve. openai/sora-2 example may be affected by OpenAI Sora shutdown on 2026-09-24.',
	),

	'fireworks' => array(
		'name'        => 'Fireworks AI',
		'company'     => 'Fireworks AI',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.fireworks.ai',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.fireworks.ai/inference/v1',
		'regional_base_urls' => array(),
		'anthropic_compatible' => array('base_url' => 'https://api.fireworks.ai/inference'),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => 'https://api.fireworks.ai/v1/accounts/{account_id}/models',
		'capabilities' => array('chat', 'vision', 'stt', 'image', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array(
			'text'   => 'Serverless has no regional endpoint; dedicated deployments can pin GLOBAL/US/EUROPE/APAC or single regions.',
			'source' => 'https://docs.fireworks.ai/deployments/regions',
		),
		'default_models' => array('accounts/fireworks/models/kimi-k3', 'accounts/fireworks/models/glm-5p3-flash', 'accounts/fireworks/models/deepseek-v3p1'),
		'key_url'  => 'https://app.fireworks.ai/settings/users/api-keys',
		'unverified' => array('hq_country'),
		'note' => 'Only the native account-scoped models list is documented (not OpenAI /models). Use account_id "fireworks" for public models.',
	),

	'openrouter' => array(
		'name'        => 'OpenRouter',
		'company'     => 'OpenRouter, Inc.',
		'hq_country'  => 'US',
		'docs_url'    => 'https://openrouter.ai/docs',
		'api_style'   => 'openai',
		'base_url'    => 'https://openrouter.ai/api/v1',
		'regional_base_urls' => array(
			'EU (Business/Enterprise only)' => 'https://eu.openrouter.ai/api/v1',
			'US (Business/Enterprise only)' => 'https://us.openrouter.ai/api/v1',
		),
		'auth' => array(
			'header' => 'Authorization',
			'prefix' => 'Bearer ',
			'extra_headers' => array(),
			'optional_headers' => array('HTTP-Referer' => 'site URL', 'X-OpenRouter-Title' => 'site name'),
		),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'tts', 'stt', 'image', 'video', 'embeddings'),
		'tts' => array(
			'path'        => '/audio/speech',
			'method'      => 'POST',
			'format'      => 'OpenAI-style JSON {model, input, voice (provider-specific), response_format mp3|pcm, speed}. Returns raw bytes.',
			'voices_path' => null,
			'models_filter' => '/models?output_modalities=speech',
		),
		'video' => array(
			'create_path'  => '/videos',
			'status_path'  => '/videos/{jobId}',
			'content_path' => '/videos/{jobId}/content?index=0',
			'models_path'  => '/videos/models',
			'models'       => array('google/veo-3.1'),
		),
		'available_regions' => array(
			'text'   => 'Global; in-region routing (fails closed) only on Business/Enterprise plans.',
			'source' => 'https://openrouter.ai/docs/guides/features/in-region-routing.md',
		),
		'default_models' => array('openrouter/auto'),
		'key_url'  => 'https://openrouter.ai/keys',
		'unverified' => array('hq_country', 'default_models', 'key_url'),
		'note' => 'Image: POST /images. Use live /models; any provider/model slug works.',
	),

	'perplexity' => array(
		'name'        => 'Perplexity API (Sonar)',
		'company'     => 'Perplexity AI',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.perplexity.ai',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.perplexity.ai',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/router/v1/models',
		'capabilities' => array('chat', 'vision', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('sonar-pro', 'sonar', 'sonar-reasoning-pro'),
		'key_url'  => 'https://console.perplexity.ai/project/keys',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'Docs: "Sonar Chat Completions is now Agent API. Sonar will be supported until September 27, 2026." Migrate to Agent API (https://api.perplexity.ai/v1/agent) or OpenAI-compatible Router (https://api.perplexity.ai/router/v1). models_path covers Router models only.',
	),

	'nvidia_nim' => array(
		'name'        => 'NVIDIA NIM (API Catalog)',
		'company'     => 'NVIDIA',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.api.nvidia.com/nim/reference/llm-apis',
		'api_style'   => 'openai',
		'base_url'    => 'https://integrate.api.nvidia.com/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('nvidia/nemotron-3-ultra-550b-a55b', 'deepseek-ai/deepseek-v4-pro', 'openai/gpt-oss-120b'),
		'key_url'  => 'https://build.nvidia.com',
		'unverified' => array('hq_country', 'models_path', 'available_regions'),
		'note' => 'Keys start with nvapi-. Visual/retrieval models use other hosts (not verified).',
	),

	'huggingface' => array(
		'name'        => 'Hugging Face Inference Providers',
		'company'     => 'Hugging Face',
		'hq_country'  => 'US',
		'docs_url'    => 'https://huggingface.co/docs/inference-providers',
		'api_style'   => 'openai',
		'base_url'    => 'https://router.huggingface.co/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'stt', 'image', 'video', 'embeddings'),
		'tts'   => null,
		'video' => array(
			'create_path' => null,
			'notes'       => 'text-to-video task via providers (fal-ai, replicate, novita, together, wavespeed) through HF inference clients; raw REST path not verified.',
		),
		'available_regions' => array('text' => 'None stated.', 'source' => 'https://huggingface.co/docs/inference-providers/index'),
		'default_models' => array('openai/gpt-oss-120b', 'deepseek-ai/DeepSeek-R1'),
		'key_url'  => 'https://huggingface.co/settings/tokens',
		'unverified' => array('hq_country'),
		'note' => 'Token must be fine-grained with "Make calls to Inference Providers". Model suffixes :fastest (default), :cheapest, :preferred, or :<provider>.',
	),

	'watsonx' => array(
		'name'        => 'IBM watsonx.ai',
		'company'     => 'IBM',
		'hq_country'  => 'US',
		'docs_url'    => 'https://cloud.ibm.com/apidocs/watsonx-ai',
		'api_style'   => 'custom',
		'base_url'    => 'https://us-south.ml.cloud.ibm.com',
		'regional_base_urls' => array(
			'us-south (Dallas)'    => 'https://us-south.ml.cloud.ibm.com',
			'eu-de (Frankfurt)'    => 'https://eu-de.ml.cloud.ibm.com',
			'eu-gb (London)'       => 'https://eu-gb.ml.cloud.ibm.com',
			'jp-tok (Tokyo)'       => 'https://jp-tok.ml.cloud.ibm.com',
			'au-syd (Sydney)'      => 'https://au-syd.ml.cloud.ibm.com',
			'ca-tor (Toronto)'     => 'https://ca-tor.ml.cloud.ibm.com',
			'ap-south-1 (Mumbai)'  => 'https://ap-south-1.aws.wxai.ibm.com',
		),
		'auth' => array(
			'header' => 'Authorization',
			'prefix' => 'Bearer ',
			'flow'   => 'Exchange IBM Cloud API key at POST https://iam.cloud.ibm.com/identity/token (grant_type=urn:ibm:params:oauth:grant-type:apikey) for an IAM access token.',
			'extra_headers' => array(),
			'required_params' => 'query version=YYYY-MM-DD on every call; body project_id or space_id.',
		),
		'chat_path'   => '/ml/v1/text/chat?version={version}',
		'models_path' => '/ml/v1/foundation_model_specs?version={version}',
		'capabilities' => array('chat', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array(
			'text'   => 'Model availability varies by data center.',
			'source' => 'https://www.ibm.com/docs/en/watsonx/saas?topic=solutions-supported-foundation-models',
		),
		'default_models' => array('ibm/granite-4-h-small', 'meta-llama/llama-4-maverick-17b-128e-instruct-fp8', 'mistralai/mistral-large-2512'),
		'key_url'  => 'https://cloud.ibm.com/iam/apikeys',
		'unverified' => array('hq_country', 'key_url'),
		'note' => 'Embeddings: POST /ml/v1/text/embeddings. Vision support not verified. Watson TTS is a separate service (not covered).',
	),

	'ai21' => array(
		'name'        => 'AI21 Studio',
		'company'     => 'AI21 Labs',
		'hq_country'  => 'IL',
		'docs_url'    => 'https://docs.ai21.com',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.ai21.com/studio/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => null,
		'capabilities' => array('chat'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('jamba-large', 'jamba-mini'),
		'key_url'  => 'https://studio.ai21.com',
		'unverified' => array('hq_country', 'api_style', 'available_regions'),
		'note' => 'Uses chat/completions schema but no official OpenAI-compatibility statement; no list-models endpoint documented.',
	),

	'reka' => array(
		'name'        => 'Reka API',
		'company'     => 'Reka AI',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.reka.ai',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.reka.ai/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'X-Api-Key', 'prefix' => '', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('reka-flash', 'reka-edge'),
		'key_url'  => 'https://platform.reka.ai/',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'REST examples use X-Api-Key; Bearer via OpenAI SDK implied but unverified. Video/audio are understanding inputs only.',
	),

	/* =====================================================================
	 * CHINA
	 * ===================================================================*/

	'dashscope' => array(
		'name'        => 'Alibaba Cloud Model Studio (DashScope / Qwen)',
		'company'     => 'Alibaba Cloud',
		'hq_country'  => 'CN',
		'docs_url'    => 'https://www.alibabacloud.com/help/en/model-studio/',
		'api_style'   => 'openai',
		'base_url'    => 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
		'regional_base_urls' => array(
			'International (Singapore)'   => 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
			'China mainland (Beijing)'    => 'https://dashscope.aliyuncs.com/compatible-mode/v1',
			'China (Hong Kong)'           => 'https://cn-hongkong.dashscope.aliyuncs.com/compatible-mode/v1',
			'US (Virginia)'               => 'https://dashscope-us.aliyuncs.com/compatible-mode/v1',
			'Germany (Frankfurt, workspace host)' => 'https://{WorkspaceId}.eu-central-1.maas.aliyuncs.com/compatible-mode/v1',
			'Japan (Tokyo, workspace host)'       => 'https://{WorkspaceId}.ap-northeast-1.maas.aliyuncs.com/compatible-mode/v1',
		),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => null,
		'capabilities' => array('chat', 'vision', 'tts', 'image', 'video', 'embeddings'),
		'tts' => array(
			'path'        => 'https://dashscope-intl.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation',
			'method'      => 'POST',
			'format'      => 'Native DashScope JSON {model:"qwen3-tts-flash", input:{text, voice:"Cherry", language_type:"English"}}.',
			'voices_path' => null,
			'models'      => array('qwen3-tts-flash', 'qwen3-tts-instruct-flash'),
		),
		'video' => array(
			'create_path' => '/api/v1/services/aigc/video-generation/video-synthesis',
			'status_path' => '/api/v1/tasks/{task_id}',
			'required_headers' => array('X-DashScope-Async' => 'enable'),
			'format'      => 'Async; relative to regional native host (e.g. https://dashscope-intl.aliyuncs.com or https://{WorkspaceId}.{region}.maas.aliyuncs.com). Task IDs and URLs expire after 24h.',
			'models'      => array('wan2.7-t2v'),
		),
		'available_regions' => array(
			'text'   => 'Each region has its own endpoint, API keys and model list; not usable across regions. US region has no IPv6.',
			'source' => 'https://www.alibabacloud.com/help/en/model-studio/regions',
		),
		'default_models' => array('qwen3.8-max', 'qwen3.7-plus', 'qwen3.8-flash'),
		'key_url'  => 'https://modelstudio.console.alibabacloud.com/ap-southeast-1/settings/api-key',
		'unverified' => array('hq_country', 'models_path', 'video'),
		'note' => 'Docs now recommend workspace hosts https://{WorkspaceId}.{region}.maas.aliyuncs.com. /models list not found in docs. Video paths are relative to the native (non compatible-mode) regional host. China real-name rules not stated on fetched pages. Beijing TTS host unverified.',
	),

	'moonshot' => array(
		'name'        => 'Kimi API (Moonshot AI)',
		'company'     => 'Moonshot AI',
		'hq_country'  => 'CN',
		'docs_url'    => 'https://platform.kimi.ai/docs',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.moonshot.ai/v1',
		'regional_base_urls' => array(
			'International'  => 'https://api.moonshot.ai/v1',
			'China mainland' => 'https://api.moonshot.cn/v1',
		),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array(
			'text'   => 'Separate international (platform.kimi.ai) and China (platform.kimi.com) platforms; keys are NOT interchangeable.',
			'source' => 'https://platform.kimi.ai/docs/api/list-models',
		),
		'default_models' => array('kimi-k3', 'kimi-k2.6'),
		'key_url'  => 'https://platform.kimi.ai/console/api-keys',
		'unverified' => array('hq_country'),
		'note' => 'China console key page path unverified.',
	),

	'zhipu' => array(
		'name'        => 'Z.ai / Zhipu BigModel (GLM)',
		'company'     => 'Zhipu AI (Z.ai)',
		'hq_country'  => 'CN',
		'docs_url'    => 'https://docs.z.ai',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.z.ai/api/paas/v4',
		'regional_base_urls' => array(
			'International (Z.ai)'   => 'https://api.z.ai/api/paas/v4',
			'China mainland (BigModel)' => 'https://open.bigmodel.cn/api/paas/v4',
		),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => null,
		'capabilities' => array('chat', 'vision', 'tts', 'stt', 'image', 'video'),
		'tts' => array(
			'path'        => 'https://open.bigmodel.cn/api/paas/v4/audio/speech',
			'method'      => 'POST',
			'format'      => 'CHINA ENDPOINT ONLY. JSON {model:"glm-tts", input, voice, speed, volume, response_format wav|pcm, stream, encode_format base64}.',
			'voices_path' => null,
			'models'      => array('glm-tts'),
		),
		'video' => array(
			'create_path' => '/videos/generations',
			'status_path' => '/async-result/{id}',
			'format'      => 'Async; returns id + task_status PROCESSING|SUCCESS|FAIL.',
			'models'      => array('cogvideox-3'),
		),
		'available_regions' => array(
			'text'   => 'Separate international (z.ai) and China (bigmodel.cn) consoles. No explicit country restriction found.',
			'source' => 'https://docs.z.ai/guides/overview/quick-start',
		),
		'default_models' => array('glm-5.3', 'GLM-5.3-FLASH'),
		'key_url'  => 'https://z.ai/manage-apikey/apikey-list',
		'unverified' => array('hq_country'),
		'note' => 'China key URL: https://bigmodel.cn/usercenter/proj-mgmt/apikeys. No list-models endpoint documented. Video status path on open.bigmodel.cn unverified. STT model GLM-ASR-2512.',
	),

	'minimax' => array(
		'name'        => 'MiniMax API',
		'company'     => 'MiniMax',
		'hq_country'  => 'CN',
		'docs_url'    => 'https://platform.minimax.io/docs',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.minimax.io/v1',
		'regional_base_urls' => array(
			'International'  => 'https://api.minimax.io/v1',
			'China mainland' => 'https://api.minimax.cn/v1',
		),
		'anthropic_compatible' => array('base_url' => 'https://api.minimax.io/anthropic'),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => null,
		'capabilities' => array('chat', 'tts', 'video'),
		'tts' => array(
			'path'        => '/t2a_v2',
			'method'      => 'POST',
			'format'      => 'Custom JSON {model, text (<10000 chars), voice_setting:{voice_id e.g. "English_Graceful_Lady"}, audio_setting}.',
			'voices_path' => '/get_voice',
			'voices_note' => 'POST with {"voice_type":"system"|"voice_cloning"|"voice_generation"|"all"}',
			'models'      => array('speech-2.8-hd', 'speech-2.8-turbo'),
		),
		'video' => array(
			'create_path' => '/video_generation',
			'status_path' => '/query/video_generation?task_id={task_id}',
			'format'      => 'Async; status returns file_id, then download via file retrieve API.',
			'models'      => array('MiniMax-Hailuo-2.3', 'MiniMax-Hailuo-02'),
		),
		'available_regions' => array(
			'text'   => 'Separate international (.io) and China (.cn) platforms.',
			'source' => 'https://platform.minimax.io/docs/guides/quickstart',
		),
		'default_models' => array('MiniMax-M3', 'MiniMax-M2.7'),
		'key_url'  => 'https://platform.minimax.io/user-center/basic-information/interface-key',
		'unverified' => array('hq_country', 'models_path'),
		'note' => 'File retrieve path likely /files/retrieve (unverified). CN video host unverified. Pay-as-you-go and subscription keys are separate.',
	),

	'qianfan' => array(
		'name'        => 'Baidu Qianfan (ERNIE)',
		'company'     => 'Baidu',
		'hq_country'  => 'CN',
		'docs_url'    => 'https://cloud.baidu.com/doc/qianfan/s/rmh4stn9m',
		'api_style'   => 'openai',
		'base_url'    => 'https://qianfan.baidubce.com/v2',
		'regional_base_urls' => array(),
		'auth' => array(
			'header' => 'Authorization',
			'prefix' => 'Bearer ',
			'extra_headers' => array(),
			'optional_headers' => array('appid' => 'app-xxxxxx'),
		),
		'chat_path'   => '/chat/completions',
		'models_path' => null,
		'capabilities' => array('chat'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array(
			'text'   => 'China cloud (console.bce.baidu.com); no international endpoint found.',
			'source' => 'https://cloud.baidu.com/doc/qianfan/s/rmh4stn9m',
		),
		'default_models' => array('ernie-4.0-turbo-8k', 'ernie-3.5-8k'),
		'key_url'  => 'https://console.bce.baidu.com/iam/#/iam/apikey/list',
		'unverified' => array('hq_country', 'models_path', 'default_models'),
		'note' => 'Keys look like bce-v3/ALTAK-... default_models are doc examples; current ERNIE flagship IDs not verified - fetch live. Vision/embeddings/image not verified.',
	),

	'volcengine_ark' => array(
		'name'        => 'Volcengine Ark (Doubao) / BytePlus ModelArk',
		'company'     => 'ByteDance',
		'hq_country'  => 'CN',
		'docs_url'    => 'https://docs.volcengine.com/docs/82379',
		'api_style'   => 'openai',
		'base_url'    => 'https://ark.cn-beijing.volces.com/api/v3',
		'regional_base_urls' => array(
			'China (Beijing) - Volcengine'            => 'https://ark.cn-beijing.volces.com/api/v3',
			'International (Johor) - BytePlus ModelArk' => 'https://ark.ap-southeast.bytepluses.com/api/v3',
		),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => null,
		'capabilities' => array('chat', 'vision', 'image', 'video', 'embeddings'),
		'tts'   => null,
		'video' => array(
			'create_path' => '/contents/generations/tasks',
			'status_path' => '/contents/generations/tasks/{id}',
			'format'      => 'JSON {model, content[] text/image/video/audio, resolution, ratio, duration, generate_audio}. Poll until status "succeeded" (or webhook); result video_url.',
			'models'      => array('doubao-seedance-2-5-260628', 'doubao-seedance-2-0-260128'),
		),
		'available_regions' => array(
			'text'   => 'Volcengine = China (cn-beijing); BytePlus = international. Model service must be activated in console first.',
			'source' => 'https://docs.volcengine.com/docs/82379/1399008?lang=zh',
		),
		'default_models' => array('doubao-seed-2-1-pro-260628'),
		'key_url'  => 'https://ark.volcengine.com/region:cn-beijing/apiKey',
		'unverified' => array('hq_country', 'models_path'),
		'note' => 'BytePlus base URL from official-domain search snippet (page did not render); BytePlus key URL (console.byteplus.com) and model IDs unverified. Doubao speech is a separate product.',
	),

	'hunyuan' => array(
		'name'        => 'Tencent Hunyuan',
		'company'     => 'Tencent Cloud',
		'hq_country'  => 'CN',
		'docs_url'    => 'https://cloud.tencent.com/document/product/1729/111007',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.hunyuan.cloud.tencent.com/v1',
		'regional_base_urls' => array(
			'China' => 'https://api.hunyuan.cloud.tencent.com/v1',
		),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => null,
		'capabilities' => array('chat', 'vision', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array(
			'text'   => 'China (Tencent Cloud). Default concurrency 5 shared across main/sub accounts.',
			'source' => 'https://cloud.tencent.com/document/product/1729/111007',
		),
		'default_models' => array('hunyuan-turbos-latest', 'hunyuan-vision'),
		'key_url'  => 'https://console.cloud.tencent.com/hunyuan/start',
		'unverified' => array('hq_country'),
		'note' => 'Only /chat/completions and /embeddings documented. International TokenHub hosts (tokenhub-intl.tencentcloudmaas.com) seen only in a non-API page; omitted.',
	),

	/* =====================================================================
	 * RUSSIA / KOREA / INDIA / MIDDLE EAST
	 * ===================================================================*/

	'yandex' => array(
		'name'        => 'Yandex AI Studio (YandexGPT / Alice AI)',
		'company'     => 'Yandex',
		'hq_country'  => 'RU',
		'docs_url'    => 'https://aistudio.yandex.ru/docs/en/ai-studio/',
		'api_style'   => 'openai',
		'base_url'    => 'https://ai.api.cloud.yandex.net/v1',
		'regional_base_urls' => array(
			'legacy host (tutorials)' => 'https://llm.api.cloud.yandex.net/v1',
		),
		'auth' => array(
			'header' => 'Authorization',
			'prefix' => 'Api-Key ',
			'alt'    => 'IAM token: Authorization: Bearer <IAM_TOKEN>',
			'extra_headers' => array('OpenAI-Project' => '{folder_id}'),
		),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'tts', 'stt', 'image', 'embeddings'),
		'tts' => array(
			'path'        => 'https://tts.api.cloud.yandex.net/tts/v3/utteranceSynthesis',
			'method'      => 'POST',
			'format'      => 'SpeechKit v3 REST JSON {text, hints:[{voice:"marina"},{role:"friendly"}]}; header x-folder-id required; streamed JSON with base64 in result.audioChunk.data. v1 alt: https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize (form-urlencoded).',
			'voices_path' => null,
		),
		'video' => null,
		'available_regions' => array(
			'text'   => 'Yandex Cloud Russia region (Kazakhstan region exists, org owners only). Active billing account required.',
			'source' => 'https://aistudio.yandex.ru/docs/en/ai-studio/quickstart/',
		),
		'default_models' => array('gpt://{folder_id}/aliceai-llm', 'gpt://{folder_id}/yandexgpt-5.1', 'gpt://{folder_id}/yandexgpt-5-lite'),
		'key_url'  => 'https://aistudio.yandex.ru',
		'unverified' => array('hq_country'),
		'note' => 'Model string embeds folder ID. Kazakhstan endpoint unverified. Legal-entity/residency rules not found. Vision unverified.',
	),

	'gigachat' => array(
		'name'        => 'GigaChat API',
		'company'     => 'Sber',
		'hq_country'  => 'RU',
		'docs_url'    => 'https://developers.sber.ru/docs/ru/gigachat/',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.giga.chat/v1',
		'regional_base_urls' => array(
			'legacy (being phased out)' => 'https://gigachat.devices.sberbank.ru/api/v1',
		),
		'auth' => array(
			'header' => 'Authorization',
			'prefix' => 'Bearer ',
			'flow'   => 'POST https://ngw.devices.sberbank.ru:9443/api/v2/oauth with headers Authorization: Basic <authorization_key>, RqUID: <uuid4>, Content-Type: application/x-www-form-urlencoded; body scope=GIGACHAT_API_PERS | GIGACHAT_API_B2B | GIGACHAT_API_CORP. Access token valid 30 min.',
			'extra_headers' => array(),
			'tls_note' => 'Requires Russian Trusted Root CA (Mintsifry) in the trust store.',
		),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'image', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array(
			'text'   => 'Individuals, sole proprietors and legal entities in Russia; Russian root CA required.',
			'source' => 'https://developers.sber.ru/docs/ru/gigachat/api/reference/rest/gigachat-api',
		),
		'default_models' => array('GigaChat-2-Max', 'GigaChat-2-Pro', 'GigaChat-2-Lite'),
		'key_url'  => 'https://developers.sber.ru/studio',
		'unverified' => array('hq_country'),
		'note' => 'Docs call OpenAI compatibility partial. api.giga.chat primary since 2026-07-17. Image generation via chat. SaluteSpeech (TTS) is a separate product, not covered.',
	),

	'naver_clova' => array(
		'name'        => 'NAVER CLOVA Studio (HyperCLOVA X)',
		'company'     => 'NAVER Cloud',
		'hq_country'  => 'KR',
		'docs_url'    => 'https://api.ncloud-docs.com/docs/en/clovastudio-openaicompatibility',
		'api_style'   => 'openai',
		'base_url'    => 'https://clovastudio.stream.ntruss.com/v1/openai',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'tts', 'embeddings'),
		'tts' => array(
			'path'        => 'https://naveropenapi.apigw.ntruss.com/tts-premium/v1/tts',
			'method'      => 'POST',
			'format'      => 'CLOVA Voice Premium (separate product). Headers x-ncp-apigw-api-key-id, x-ncp-apigw-api-key. Form-urlencoded {speaker, text, format, volume, speed, pitch, emotion}.',
			'voices_path' => null,
		),
		'video' => null,
		'available_regions' => array(
			'text'   => 'NAVER Cloud Platform regions KR, US West, SG, JP, DE. Korea-only restriction not stated.',
			'source' => 'https://guide.ncloud-docs.com/docs/en/clovastudio-overview',
		),
		'default_models' => array('HCX-007', 'HCX-005', 'HCX-DASH-002'),
		'key_url'  => 'https://clovastudio.ncloud.com',
		'unverified' => array('hq_country'),
		'note' => 'Compatibility layer requires snake_case fields, n=1, no frequency_penalty/logprobs. Native API: POST https://clovastudio.stream.ntruss.com/v3/chat-completions/{modelName}. TTS /tts path suffix unverified.',
	),

	'upstage' => array(
		'name'        => 'Upstage Console (Solar)',
		'company'     => 'Upstage',
		'hq_country'  => 'KR',
		'docs_url'    => 'https://console.upstage.ai/docs/getting-started',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.upstage.ai/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => null,
		'capabilities' => array('chat', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('solar-pro4', 'solar-pro3', 'solar-mini4'),
		'key_url'  => 'https://console.upstage.ai/api-keys',
		'unverified' => array('hq_country', 'models_path', 'available_regions'),
		'note' => 'Docs render client-side; list-models endpoint and region restrictions not confirmed.',
	),

	'sarvam' => array(
		'name'        => 'Sarvam AI API',
		'company'     => 'Sarvam AI',
		'hq_country'  => 'IN',
		'docs_url'    => 'https://docs.sarvam.ai/api-reference-docs/introduction',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.sarvam.ai/v1',
		'regional_base_urls' => array(),
		'auth' => array(
			'header' => 'api-subscription-key',
			'prefix' => '',
			'alt'    => 'Authorization: Bearer <key> (for OpenAI-compatible tooling)',
			'extra_headers' => array(),
		),
		'chat_path'   => '/chat/completions',
		'models_path' => null,
		'capabilities' => array('chat', 'tts', 'stt'),
		'tts' => array(
			'path'        => 'https://api.sarvam.ai/text-to-speech',
			'method'      => 'POST',
			'format'      => 'JSON {text (<=2500 chars v3), language_code (e.g. hi-IN), speaker (default "shubh"), model "bulbul:v3"|"bulbul:v2", pace, temperature, output_audio_codec, speech_sample_rate}. Returns {audios:[base64]}.',
			'voices_path' => null,
			'models'      => array('bulbul:v3', 'bulbul:v2'),
		),
		'video' => null,
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('sarvam-105b', 'sarvam-105b-conversations'),
		'key_url'  => 'https://dashboard.sarvam.ai',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'STT: POST https://api.sarvam.ai/speech-to-text multipart {file, model saaras:v3|saaras:v4, language_code, mode}; <30s clips (longer via Batch API).',
	),

	'core42' => array(
		'name'        => 'Core42 Compass',
		'company'     => 'Core42 (G42)',
		'hq_country'  => 'AE',
		'docs_url'    => 'https://www.core42.ai/compass/documentation',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.core42.ai/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'api-key', 'prefix' => '', 'extra_headers' => array()),
		'chat_path'   => '/chat/completions',
		'models_path' => null,
		'capabilities' => array('chat', 'tts', 'stt', 'image', 'embeddings'),
		'tts' => array(
			'path'        => '/audio/speech?api-version=2025-03-01-preview',
			'method'      => 'POST',
			'format'      => 'Azure/OpenAI-style JSON {model:"gpt-4o-mini-tts", input, voice (alloy, echo, coral, marin, cedar ...)}.',
			'voices_path' => null,
			'models'      => array('gpt-4o-mini-tts'),
		),
		'video' => null,
		'available_regions' => array(
			'text'   => 'Per-model hosting region (UAE, Sweden Central, Global, USA). Requires active subscription activated by Compass team (sales-gated).',
			'source' => 'https://www.core42.ai/compass/documentation/compass-api-faqs',
		),
		'default_models' => array('k2-horizon-375b', 'gpt-5.5'),
		'key_url'  => null,
		'unverified' => array('hq_country', 'models_path', 'key_url'),
		'note' => 'Jais is NOT in the current Compass model list (Jais 2 is open-weight on Hugging Face, inception42); no Jais API verified. Arabic model: G42-INCEPTION-GPT41-MSA. Key from Compass account > API Keys (URL not shown).',
	),

	'humain_allam' => array(
		'name'        => 'HUMAIN (ALLaM)',
		'company'     => 'HUMAIN (PIF) / SDAIA',
		'hq_country'  => 'SA',
		'docs_url'    => 'https://api-allam.humain.ai/',
		'api_style'   => null,
		'base_url'    => null,
		'regional_base_urls' => array(),
		'auth' => null,
		'chat_path'   => null,
		'models_path' => null,
		'capabilities' => array('chat'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array(
			'text'   => 'ALLaM 34B / HUMAIN Chat launched first in Saudi Arabia (2025-08-25).',
			'source' => 'https://www.spa.gov.sa/en/N2385004',
		),
		'default_models' => array(),
		'key_url'  => null,
		'alternatives' => array(
			'azure_foundry' => 'ALLaM-2-7b-instruct (SDAIA) GA in Microsoft Foundry catalog as serverless API: https://ai.azure.com/catalog/models/ALLaM-2-7b-instruct',
			'watsonx'       => 'allam-1-13b-instruct listed but DEPRECATED (IBM watsonx.ai v2.4 announcement).',
		),
		'unverified' => array('hq_country', 'api_style', 'base_url', 'auth', 'chat_path', 'models_path', 'default_models', 'key_url'),
		'note' => 'UNVERIFIED: no public API documentation could be read (developer portal renders client-side; humain.com platform page 403; marketplace requires sign-up). Use Azure Foundry ALLaM-2-7b-instruct for a documented path.',
	),

	/* =====================================================================
	 * LOCAL (OpenAI-compatible localhost)
	 * ===================================================================*/

	'ollama' => array(
		'name'        => 'Ollama (local)',
		'company'     => 'Ollama',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.ollama.com/api/openai-compatibility',
		'api_style'   => 'openai',
		'base_url'    => 'http://localhost:11434/v1',
		'regional_base_urls' => array(
			'Ollama Cloud' => 'https://ollama.com/v1',
		),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array(), 'note' => 'Local: key required by SDKs but ignored (any value). Cloud: OLLAMA_API_KEY.'),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'vision', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array('text' => 'Runs locally; no restrictions.', 'source' => 'https://docs.ollama.com/api/openai-compatibility'),
		'default_models' => array(),
		'key_url'  => 'https://ollama.com',
		'unverified' => array('hq_country'),
		'note' => 'Models are whatever the user has pulled; always use /models. Vision: base64 images only. Cloud Bearer format unverified.',
	),

	'lmstudio' => array(
		'name'        => 'LM Studio (local)',
		'company'     => 'Element Labs (LM Studio)',
		'hq_country'  => 'US',
		'docs_url'    => 'https://lmstudio.ai/docs/developer/openai-compat',
		'api_style'   => 'openai',
		'base_url'    => 'http://localhost:1234/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array(), 'note' => 'No auth by default; if enabled in Server Settings use Bearer $LM_API_TOKEN.'),
		'chat_path'   => '/chat/completions',
		'models_path' => '/models',
		'capabilities' => array('chat', 'embeddings'),
		'tts'   => null,
		'video' => null,
		'available_regions' => array('text' => 'Runs locally; no restrictions.', 'source' => 'https://lmstudio.ai/docs/developer/openai-compat'),
		'default_models' => array(),
		'key_url'  => null,
		'unverified' => array('hq_country'),
		'note' => 'Anthropic-compatible Messages endpoint also supported. Vision depends on loaded model.',
	),

	/* =====================================================================
	 * MEDIA-ONLY PROVIDERS (TTS / avatar video / video generation)
	 * ===================================================================*/

	'elevenlabs' => array(
		'name'        => 'ElevenLabs API',
		'company'     => 'ElevenLabs',
		'hq_country'  => 'US',
		'docs_url'    => 'https://elevenlabs.io/docs',
		'api_style'   => 'custom',
		'base_url'    => 'https://api.elevenlabs.io',
		'regional_base_urls' => array(
			'EU residency (Enterprise)'        => 'https://api.eu.residency.elevenlabs.io',
			'India residency (Enterprise)'     => 'https://api.in.residency.elevenlabs.io',
			'Singapore residency (Enterprise)' => 'https://api.sg.residency.elevenlabs.io',
		),
		'auth' => array('header' => 'xi-api-key', 'prefix' => '', 'extra_headers' => array()),
		'chat_path'   => null,
		'models_path' => '/v1/models',
		'capabilities' => array('tts', 'stt'),
		'tts' => array(
			'path'        => '/v1/text-to-speech/{voice_id}?output_format=mp3_44100_128',
			'method'      => 'POST',
			'format'      => 'JSON {text, model_id (default eleven_multilingual_v2), voice_settings {stability, similarity_boost, style, use_speaker_boost, speed}}. Returns binary audio.',
			'voices_path' => '/v2/voices',
			'models'      => array('eleven_multilingual_v2', 'eleven_v3', 'eleven_flash_v2_5'),
		),
		'video' => null,
		'available_regions' => array(
			'text'   => 'Global; data residency hosts are Enterprise-only.',
			'source' => 'https://elevenlabs.io/docs/product-guides/administration/data-residency',
		),
		'default_models' => array('eleven_multilingual_v2', 'eleven_v3', 'eleven_flash_v2_5'),
		'key_url'  => 'https://elevenlabs.io/app/settings/api-keys',
		'unverified' => array('hq_country', 'key_url'),
		'note' => 'STT: POST /v1/speech-to-text multipart, model_id scribe_v2.',
	),

	'azure_speech' => array(
		'name'        => 'Azure AI Speech (Text to speech)',
		'company'     => 'Microsoft',
		'hq_country'  => 'US',
		'docs_url'    => 'https://learn.microsoft.com/en-us/azure/ai-services/speech-service/rest-text-to-speech',
		'api_style'   => 'custom',
		'base_url'    => 'https://{region}.tts.speech.microsoft.com',
		'regional_base_urls' => array(
			'resource endpoint' => 'https://{resource}.cognitiveservices.azure.com',
			'eastus'       => 'https://eastus.tts.speech.microsoft.com',
			'westeurope'   => 'https://westeurope.tts.speech.microsoft.com',
			'uaenorth'     => 'https://uaenorth.tts.speech.microsoft.com',
			'qatarcentral' => 'https://qatarcentral.tts.speech.microsoft.com',
			'centralindia' => 'https://centralindia.tts.speech.microsoft.com',
			'US Gov'       => 'https://{region}.tts.speech.azure.us',
		),
		'auth' => array(
			'header' => 'Ocp-Apim-Subscription-Key',
			'prefix' => '',
			'alt'    => 'Authorization: Bearer <token> from POST https://{region}.api.cognitive.microsoft.com/sts/v1.0/issueToken (10 min)',
			'extra_headers' => array(
				'Content-Type'             => 'application/ssml+xml',
				'X-Microsoft-OutputFormat' => 'audio-24khz-48kbitrate-mono-mp3',
				'User-Agent'               => '{app_name}',
			),
		),
		'chat_path'   => null,
		'models_path' => null,
		'capabilities' => array('tts', 'stt'),
		'tts' => array(
			'path'        => '/cognitiveservices/v1',
			'method'      => 'POST',
			'format'      => 'SSML body, e.g. <speak version="1.0" xml:lang="en-US"><voice name="en-US-JennyNeural">...</voice></speak>. Audio max 10 min.',
			'voices_path' => '/cognitiveservices/voices/list',
		),
		'video' => null,
		'available_regions' => array(
			'text'   => 'Keys are region-scoped; ~33 public regions (incl. uaenorth, qatarcentral, centralindia). HD/preview voices only in subset of regions.',
			'source' => 'https://learn.microsoft.com/en-us/azure/ai-services/speech-service/regions',
		),
		'default_models' => array('en-US-JennyNeural', 'en-US-ChristopherNeural', 'en-US-JennyMultilingualNeural'),
		'key_url'  => 'https://portal.azure.com',
		'unverified' => array('hq_country'),
		'note' => 'default_models are voice ShortNames. Voices list verified on resource endpoint as /tts/cognitiveservices/voices/list; regional-host form unverified. TTS avatar video exists but was not researched.',
	),

	'google_tts' => array(
		'name'        => 'Google Cloud Text-to-Speech',
		'company'     => 'Google Cloud',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.cloud.google.com/text-to-speech/docs',
		'api_style'   => 'custom',
		'base_url'    => 'https://texttospeech.googleapis.com',
		'regional_base_urls' => array(
			'eu'          => 'https://eu-texttospeech.googleapis.com',
			'us'          => 'https://us-texttospeech.googleapis.com',
			'us-central1' => 'https://us-central1-texttospeech.googleapis.com',
		),
		'auth' => array(
			'header' => 'Authorization',
			'prefix' => 'Bearer ',
			'flow'   => 'OAuth2 access token, scope https://www.googleapis.com/auth/cloud-platform.',
			'extra_headers' => array(),
			'optional_headers' => array('x-goog-user-project' => '{project_id}'),
		),
		'chat_path'   => null,
		'models_path' => null,
		'capabilities' => array('tts'),
		'tts' => array(
			'path'        => '/v1/text:synthesize',
			'method'      => 'POST',
			'format'      => 'JSON {input:{text|ssml}, voice:{languageCode, name, modelName?}, audioConfig:{audioEncoding}}. Returns {audioContent: base64}.',
			'voices_path' => '/v1/voices?languageCode={lang}',
			'models'      => array('gemini-2.5-flash-tts', 'gemini-2.5-pro-tts'),
		),
		'video' => null,
		'available_regions' => array(
			'text'   => 'Global plus EU/US regional endpoints for data locality.',
			'source' => 'https://docs.cloud.google.com/text-to-speech/docs/endpoints',
		),
		'default_models' => array('gemini-2.5-flash-tts', 'gemini-2.5-pro-tts'),
		'key_url'  => 'https://console.cloud.google.com/apis/credentials',
		'unverified' => array('hq_country', 'key_url'),
		'note' => 'API-key auth (x-goog-api-key) not confirmed for TTS; OAuth is the documented path.',
	),

	'google_veo' => array(
		'name'        => 'Google Veo (via Gemini API)',
		'company'     => 'Google',
		'hq_country'  => 'US',
		'docs_url'    => 'https://ai.google.dev/gemini-api/docs/veo',
		'api_style'   => 'gemini',
		'base_url'    => 'https://generativelanguage.googleapis.com/v1beta',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'x-goog-api-key', 'prefix' => '', 'extra_headers' => array()),
		'chat_path'   => null,
		'models_path' => '/models',
		'capabilities' => array('video'),
		'tts'   => null,
		'video' => array(
			'create_path' => '/models/{model}:predictLongRunning',
			'status_path' => '/{operation_name}',
			'format'      => 'JSON {instances:[{prompt}], parameters:{aspectRatio, resolution, durationSeconds}}. Poll GET until done:true; download response video URI with API key.',
			'models'      => array('veo-3.1-generate-preview', 'veo-3.1-fast-generate-preview', 'veo-3.1-lite-generate-preview'),
		),
		'available_regions' => array(
			'text'   => 'Same as Gemini API; personGeneration restricted to allow_adult in EU/UK/CH/MENA.',
			'source' => 'https://ai.google.dev/gemini-api/docs/available-regions',
		),
		'default_models' => array('veo-3.1-generate-preview'),
		'key_url'  => 'https://aistudio.google.com/apikey',
		'unverified' => array('hq_country'),
		'note' => 'Same key as the gemini entry.',
	),

	'openai_sora' => array(
		'name'        => 'OpenAI Videos API (Sora)',
		'company'     => 'OpenAI',
		'hq_country'  => 'US',
		'docs_url'    => 'https://developers.openai.com/api/docs/guides/video-generation',
		'api_style'   => 'openai',
		'base_url'    => 'https://api.openai.com/v1',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => null,
		'models_path' => null,
		'capabilities' => array(),
		'tts'   => null,
		'video' => null,
		'available_regions' => array(
			'text'   => 'DISCONTINUED: "The Sora 2 models and Videos API were shut down on September 24, 2026". No replacement API.',
			'source' => 'https://developers.openai.com/api/docs/guides/video-generation',
		),
		'default_models' => array(),
		'key_url'  => null,
		'deprecated' => true,
		'unverified' => array('hq_country'),
		'note' => 'Kept for reference only. Former endpoints: POST /videos, GET /videos/{id}, GET /videos/{id}/content. Do not use.',
	),

	'heygen' => array(
		'name'        => 'HeyGen API',
		'company'     => 'HeyGen Inc.',
		'hq_country'  => 'US',
		'docs_url'    => 'https://developers.heygen.com',
		'api_style'   => 'custom',
		'base_url'    => 'https://api.heygen.com',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'X-Api-Key', 'prefix' => '', 'extra_headers' => array()),
		'chat_path'   => null,
		'models_path' => null,
		'capabilities' => array('video'),
		'tts'   => null,
		'video' => array(
			'create_path'  => '/v3/videos',
			'status_path'  => '/v3/videos/{video_id}',
			'avatars_path' => '/v3/avatars/looks',
			'voices_path'  => '/v3/voices',
			'format'       => 'JSON discriminated by type: "avatar" {avatar_id, script + voice_id | audio_url | audio_asset_id}, "image", "cinematic_avatar", "studio" {scenes}. Returns data.video_id; status pending|processing|completed|failed with presigned video_url.',
		),
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array(),
		'key_url'  => 'https://app.heygen.com/developers/api',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'v2 /v2/video/generate docs now 404; v3 is current. Engine enum values (Avatar III/IV/V) unverified. Account check: GET /v3/users/me.',
	),

	'synthesia' => array(
		'name'        => 'Synthesia API',
		'company'     => 'Synthesia Ltd',
		'hq_country'  => 'GB',
		'docs_url'    => 'https://docs.synthesia.io',
		'api_style'   => 'custom',
		'base_url'    => 'https://api.synthesia.io/v2',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => '', 'extra_headers' => array()),
		'chat_path'   => null,
		'models_path' => null,
		'capabilities' => array('video'),
		'tts'   => null,
		'video' => array(
			'create_path'  => '/videos',
			'status_path'  => '/videos/{video_id}',
			'avatars_path' => null,
			'voices_path'  => null,
			'format'       => 'JSON {input:[{scriptText, avatar, background}], test:bool, title}. Status in_progress|complete|error|rejected; "download" is a time-limited URL. test:true is free & watermarked.',
		),
		'available_regions' => array(
			'text'   => 'API requires Creator plan or higher. No regional info documented.',
			'source' => 'https://docs.synthesia.io/reference/video-api-introduction',
		),
		'default_models' => array(),
		'key_url'  => null,
		'unverified' => array('hq_country'),
		'note' => 'Raw API key in Authorization (no Bearer). Avatars/voices are static tables in docs (UUIDs), no list endpoint. Key: Synthesia Studio > Developers > API keys.',
	),

	'd_id' => array(
		'name'        => 'D-ID API',
		'company'     => 'D-ID Ltd',
		'hq_country'  => 'IL',
		'docs_url'    => 'https://docs.d-id.com',
		'api_style'   => 'custom',
		'base_url'    => 'https://api.d-id.com',
		'regional_base_urls' => array(),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Basic ', 'extra_headers' => array()),
		'chat_path'   => null,
		'models_path' => null,
		'capabilities' => array('video'),
		'tts'   => null,
		'video' => array(
			'create_path'  => '/talks',
			'status_path'  => '/talks/{id}',
			'alt_create'   => '/clips',
			'alt_status'   => '/clips/{id}',
			'avatars_path' => '/clips/presenters',
			'voices_path'  => '/tts/voices?provider={provider}',
			'format'       => 'talks: JSON {source_url, script:{type:"text", input, provider:{type:"microsoft", voice_id:"en-US-JennyNeural"}}}; clips: {presenter_id, script}. Poll until status done; result_url.',
		),
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array(),
		'key_url'  => 'https://studio.d-id.com/account-settings',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'Basic credential is the key string from Studio (API_USERNAME:API_PASSWORD); whether to base64-encode is not stated. Newer POST /expressives (V4 avatars) exists.',
	),

	'runway' => array(
		'name'        => 'Runway API',
		'company'     => 'Runway AI, Inc.',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.dev.runwayml.com',
		'api_style'   => 'custom',
		'base_url'    => 'https://api.dev.runwayml.com',
		'regional_base_urls' => array(),
		'auth' => array(
			'header' => 'Authorization',
			'prefix' => 'Bearer ',
			'extra_headers' => array('X-Runway-Version' => '2024-11-06'),
		),
		'chat_path'   => null,
		'models_path' => null,
		'capabilities' => array('video', 'image', 'tts'),
		'tts' => array(
			'path'        => '/v1/text_to_speech',
			'method'      => 'POST',
			'format'      => 'JSON {model, promptText, voice:{type, presetId}}.',
			'voices_path' => null,
			'models'      => array('eleven_multilingual_v2', 'eleven_v3'),
		),
		'video' => array(
			'create_path' => '/v1/image_to_video',
			'alt_create'  => '/v1/text_to_video',
			'status_path' => '/v1/tasks/{id}',
			'format'      => 'image_to_video JSON {model, promptImage, promptText (<=1000), ratio e.g. 1280:720, duration 2-10}. Returns {id}; status PENDING|THROTTLED|RUNNING|SUCCEEDED|FAILED|CANCELLED.',
			'models'      => array('gen4.5', 'gen4_turbo'),
		),
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('gen4.5', 'gen4_turbo', 'gen4_image'),
		'key_url'  => 'https://dev.runway.com',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'Model IDs retire (gen3a_turbo, gen4_aleph removed); check https://docs.dev.runwayml.com/guides/models.md. Voice presetId list unverified.',
	),

	'luma' => array(
		'name'        => 'Luma Dream Machine API',
		'company'     => 'Luma AI, Inc.',
		'hq_country'  => 'US',
		'docs_url'    => 'https://docs.lumalabs.ai/docs/api',
		'api_style'   => 'custom',
		'base_url'    => 'https://api.lumalabs.ai/dream-machine/v1',
		'regional_base_urls' => array(
			'Luma Agents API (newer)' => 'https://agents.lumalabs.ai/v1',
		),
		'auth' => array('header' => 'Authorization', 'prefix' => 'Bearer ', 'extra_headers' => array()),
		'chat_path'   => null,
		'models_path' => null,
		'capabilities' => array('video', 'image'),
		'tts'   => null,
		'video' => array(
			'create_path' => '/generations',
			'status_path' => '/generations/{id}',
			'format'      => 'JSON {prompt, model, aspect_ratio "16:9", resolution 540p|720p|1080p|4k, duration "5s", keyframes?, callback_url?}. State queued|dreaming|completed|failed; assets.video is the URL.',
			'models'      => array('ray-2', 'ray-flash-2'),
		),
		'available_regions' => array('text' => null, 'source' => null),
		'default_models' => array('ray-2', 'ray-flash-2'),
		'key_url'  => 'https://platform.lumalabs.ai/',
		'unverified' => array('hq_country', 'available_regions'),
		'note' => 'Images: POST /generations/image (photon-1). Luma calls the Agents API (model ray-3.2) the current documentation; no deprecation notice for dream-machine/v1 found.',
	),
);
