"""
Self-hosts the Altus Gulf brand typefaces and writes assets/academy/altus-fonts.css.

    python tools/fetch_fonts.py

Brand typography (font-identity sheet) names Canela, Neue Haas Grotesk, Inter and
IBM Plex Mono. Canela and Neue Haas Grotesk are commercial faces with no webfont
licence on file, so open-licence faces stand in for them (the stacks in
academy.css still list the brand faces first, so licensed files dropped in later
win automatically):

    Canela            -> Fraunces (display serif, SIL OFL)
    Neue Haas Grotesk -> Inter Tight (headings, SIL OFL)
    Inter             -> Inter (body, SIL OFL)
    IBM Plex Mono     -> IBM Plex Mono (data, SIL OFL)
    Arabic            -> IBM Plex Sans Arabic (SIL OFL), the Plex family's Arabic

One @font-face per unicode subset, so a Latin page never downloads Arabic glyphs.
"""
import pathlib
import re
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = ROOT / 'assets' / 'academy' / 'fonts'
CSS = ROOT / 'assets' / 'academy' / 'altus-fonts.css'
UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'

# family, css2 axis spec, local file prefix, subsets kept
FACES = [
    ('Fraunces', 'ital,wght@0,400;0,600;1,400', 'fraunces', {'latin', 'latin-ext'}),
    ('Inter Tight', 'wght@500;600;700', 'inter-tight', {'latin', 'latin-ext'}),
    ('Inter', 'wght@400;500;600', 'inter', {'latin', 'latin-ext'}),
    ('IBM Plex Mono', 'wght@400;500', 'ibm-plex-mono', {'latin'}),
    ('IBM Plex Sans Arabic', 'wght@400;500;600;700', 'ibm-plex-sans-arabic', {'arabic'}),
]

HEADER = '''/*
 * ALTUS GULF typefaces, self-hosted.
 *
 * GENERATED by tools/fetch_fonts.py -- do not edit by hand.
 *
 * Font-identity sheet: Canela (display), Neue Haas Grotesk (headings), Inter
 * (reading), IBM Plex Mono (data). Canela and Neue Haas Grotesk are licensed
 * commercial faces, so Fraunces and Inter Tight stand in until webfont files
 * are licensed; the stacks in academy.css name the brand faces first.
 *
 * Licences -- all SIL Open Font License 1.1, permitting self-hosting and
 * commercial use: Fraunces, Inter Tight, Inter, IBM Plex Mono, IBM Plex Sans Arabic.
 */
'''


# Metric-matched local fallbacks: text paints at once in a face that occupies the
# same space, so the swap to the webfont does not shift the layout.
FALLBACKS = '''
@font-face {
    font-family: 'Inter Fallback';
    src: local('Arial'), local('Helvetica Neue'), local('Liberation Sans');
    size-adjust: 107.1%;
    ascent-override: 90.4%;
    descent-override: 22.5%;
    line-gap-override: 0%;
}

@font-face {
    font-family: 'Fraunces Fallback';
    src: local('Georgia'), local('Times New Roman'), local('Liberation Serif');
    size-adjust: 104%;
    ascent-override: 94%;
    descent-override: 24.5%;
    line-gap-override: 0%;
}
'''


def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': UA}), timeout=60).read()


def main():
    FONTS.mkdir(parents=True, exist_ok=True)
    out = [HEADER]
    for family, axes, prefix, keep in FACES:
        css = get('https://fonts.googleapis.com/css2?family=' + family.replace(' ', '+') + ':' + axes + '&display=swap').decode()
        for subset, block in re.findall(r'/\* ([\w-]+) \*/\s*(@font-face \{.*?\})', css, re.S):
            if subset not in keep:
                continue
            style = re.search(r'font-style: (\w+)', block).group(1)
            weight = re.search(r'font-weight: (\d+)', block).group(1)
            src = re.search(r'url\((https://[^)]+\.woff2)\)', block).group(1)
            rng = re.search(r'unicode-range: ([^;]+);', block).group(1)
            name = f'{prefix}-{weight}{"-italic" if style == "italic" else ""}-{subset}.woff2'
            (FONTS / name).write_bytes(get(src))
            out.append(f"""
@font-face {{
    font-family: '{family}';
    font-style: {style};
    font-weight: {weight};
    font-display: swap;
    src: url('fonts/{name}') format('woff2');
    unicode-range: {rng};
}}
""")
            print(name)
    out.append(FALLBACKS)
    CSS.write_text(''.join(out), encoding='utf-8')
    print('wrote', CSS)


if __name__ == '__main__':
    main()
