/* Render standalone printable guides, role chapter links and the actual mobile route inventory. */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ROOT=path.resolve(__dirname,'..'),OUT=path.join(ROOT,'docs/guides'),APP=path.join(ROOT,'mobile app/altus-mobile');
const ts=require(path.join(APP,'node_modules/typescript'));
const result={exports:{}};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(APP,'src/domain/screens.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:result.exports,module:result});
const routeCode=fs.readFileSync(path.join(APP,'src/app/[route].tsx'),'utf8');
const supported=new Set([...routeCode.match(/const liveSupported = new Set\(\[([\s\S]*?)\]\)/)[1].matchAll(/"([^"]+)"/g)].map(match=>match[1]));
const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const style=`:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#f7f5f1;color:#1c2227;font:16px/1.7 'Segoe UI',Tahoma,Arial,sans-serif}header{background:#1c2227;color:white;padding:28px max(24px,calc((100% - 1080px)/2));border-bottom:4px solid #c45b2f}header a{color:#f3c5a8}main{max-width:1080px;margin:auto;padding:28px 24px 70px}h1,h2,h3{line-height:1.25}h2{margin-top:36px}a{color:#944527}pre{padding:18px;background:#e9e5df;border-radius:10px;overflow:auto}code{font-size:.9em}table{border-collapse:collapse;width:100%;background:white;font-size:14px}td,th{padding:10px;border:1px solid #ddd;text-align:start;vertical-align:top}.card{background:white;border:1px solid #ded8cf;border-radius:14px;padding:22px;margin-bottom:20px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px}video{display:block;width:100%;max-height:640px;background:#111}.chapters{max-height:300px;overflow:auto;display:flex;flex-wrap:wrap;gap:8px;padding:10px 0}button,.button{border:1px solid #c45b2f;border-radius:8px;background:white;color:#71371e;padding:9px 12px;cursor:pointer;text-decoration:none;font:inherit}p{margin:12px 0}.muted{color:#646a6d}img{max-width:100%}@media(max-width:600px){main{padding:20px 15px}table{display:block;overflow:auto}header{padding:22px 15px}}@media print{header,nav,.no-print{display:none}body{background:white;font-size:12px}main{padding:0;max-width:none}h2{break-after:avoid}pre,table{break-inside:avoid}a{color:inherit}}`;
function inline(value){return escape(value).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/!\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>`<img alt="${label}" src="${escape(url)}" loading="lazy">`).replace(/\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>{const [file,anchor]=url.split('#');return `<a href="${escape(file.endsWith('.md')?path.basename(file,'.md')+'.html'+(anchor?'#'+anchor:''):url)}">${label}</a>`;});}
function markdown(source){const lines=source.split(/\r?\n/),html=[];let fence=false,list=false,table=false;
 for(let i=0;i<lines.length;i++){const line=lines[i];if(line.startsWith('```')){if(list){html.push('</ul>');list=false;}html.push(fence?'</code></pre>':'<pre><code>');fence=!fence;continue;}if(fence){html.push(escape(line)+'\n');continue;}if(/^\|/.test(line)){if(/^[|\s:-]+$/.test(line))continue;if(!table){html.push('<table>');table=true;}const first=/^[|\s:-]+$/.test(lines[i+1]||'');html.push('<tr>'+line.split('|').slice(1,-1).map(cell=>`<${first?'th':'td'}>${inline(cell.trim())}</${first?'th':'td'}>`).join('')+'</tr>');continue;}if(table){html.push('</table>');table=false;}if(/^[-*] |^\d+\. /.test(line)){if(!list){html.push('<ul>');list=true;}html.push('<li>'+inline(line.replace(/^[-*] |^\d+\. /,''))+'</li>');continue;}if(list){html.push('</ul>');list=false;}const heading=/^(#{1,6}) (.+)/.exec(line);if(heading){html.push(`<h${heading[1].length} dir="auto">${inline(heading[2])}</h${heading[1].length}>`);}else if(line.trim())html.push('<p dir="auto">'+inline(line)+'</p>');}
 if(list)html.push('</ul>');if(table)html.push('</table>');return html.join('\n');}
const page=(title,body)=>`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>${style}</style><header><strong>ALTUS KNOWLEDGE &amp; PERFORMANCE</strong><br><a href="index.html">User guides and recordings</a></header><main>${body}</main></html>`;
const names=['ADMIN_USER_GUIDE','STUDENT_USER_GUIDE','INSTRUCTOR_USER_GUIDE','MOBILE_INSTALLATION','VERIFICATION'];
for(const name of names){const src=fs.readFileSync(path.join(OUT,name+'.md'),'utf8');fs.writeFileSync(path.join(OUT,name+'.html'),page(name.replace(/_/g,' '),`<nav class="no-print"><button onclick="window.print()">Print / Save PDF</button></nav>`+markdown(src)));}
for(const name of ['ADMIN_INSTALL','ADMIN_GUIDE','ADMIN_FEATURES','ADMIN_BASELINE','MCP_GATEWAY_RUNBOOK','MCP_ADMIN_WORKFLOWS','PUBLISHER_API','MOBILE_APP']){const src=fs.readFileSync(path.join(ROOT,'docs',name+'.md'),'utf8').replace(/\]\(screenshots\//g,'](../screenshots/');fs.writeFileSync(path.join(OUT,name+'.html'),page(name.replace(/_/g,' '),markdown(src)));}
for(const name of ['ALTUS_AI_PUBLISHER_ACCEPTANCE_REPORT','README','DEPLOYMENT','gap','IMPLEMENTATION_STATUS']){
 let src=fs.readFileSync(path.join(ROOT,name+'.md'),'utf8').replace(/\]\(docs\/screenshots\//g,'](../screenshots/');
 // Public training copies omit local fixture passwords. The developer's original README is preserved.
 src=src.replace(/## 1\. Sign-in accounts[\s\S]*?(?=## 2\.)/,'## Sign in\n\nUse your own existing account. Ask the administrator to provision access; local fixture credentials are omitted from this public training copy.\n\n').replace(/Academy#2026|admin123/g,'[local credentials omitted]');
 src=src.replace(/\]\(docs\/guides\//g,'](').replace(/\]\(mobile%20app\/client-deliverables\/android\/ALTUS-1\.0\.1-release\.apk\)/g,'](../../mobile%20app/client-deliverables/android/ALTUS-1.0.1-release.apk)');
 fs.writeFileSync(path.join(OUT,name+'.html'),page(name.replace(/_/g,' '),markdown(src)));
}
const inventory=result.exports.screens.map(screen=>({...screen,live:supported.has(screen.id)||result.exports.publicScreens.has(screen.id),roles:screen.roles||['all']}));
fs.writeFileSync(path.join(OUT,'mobile-screen-inventory.json'),JSON.stringify(inventory,null,2));
let inventoryHtml='<h1>Every registered mobile option</h1><p>Actual source inventory. A live-supported route may still require credentials, a role, a configured provider or a record identifier. Demonstration-only routes display an explicit unavailable state for live accounts; this is not a claim that every registered screen has live CRUD.</p><table><tr><th>Option / route</th><th>Purpose</th><th>Access</th><th>Live status</th></tr>';
for(const screen of inventory)inventoryHtml+=`<tr><td><strong>${escape(screen.title)}</strong><br><code>/${escape(screen.id)}</code><br><span lang="ar" dir="rtl">${escape(screen.ar)}</span></td><td>${escape(screen.benefit)}</td><td>${escape(screen.roles.join(', '))}</td><td>${screen.live?'Connected/shared route':'Demonstration only; use the supported website flow'}${screen.source?'<br>Native source: <code>'+escape(screen.source)+'</code>':''}</td></tr>`;
fs.writeFileSync(path.join(OUT,'MOBILE_OPTIONS.html'),page('Mobile screen inventory',inventoryHtml+'</table>'));
const roles=[['admin','Administrator','ADMIN_USER_GUIDE'],['learner','Student','STUDENT_USER_GUIDE'],['instructor','Instructor','INSTRUCTOR_USER_GUIDE']];
let cards='',videoData=[];
for(const [role,label,guide] of roles){const file=path.join(OUT,role+'-chapters.json'),manifest=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):null;const chapters=manifest?.chapters.map(chapter=>({title:chapter.title,text:chapter.text,start:chapter.start,end:chapter.end}))||[];
 videoData.push({role,label,chapters});
 cards+=`<section class="card"><h2>${label} walkthrough</h2><p><a class="button" href="${guide}.html">Read ${label.toLowerCase()} guide / الدليل</a> <a class="button" href="${guide}.pdf" download>Download PDF</a></p><video id="video-${role}" controls preload="metadata" src="ALTUS-${label==='Administrator'?'Admin':label}-Guide.mp4"><track kind="captions" label="English" srclang="en" src="${role}-chapters.vtt"></video><p class="muted">Actual local screen recording · English synthetic narration · isolated sample accounts · ${chapters.length} chapters</p><div class="chapters" id="chapters-${role}"></div><p><a href="${role}-MENU_REFERENCE.html">Every recorded menu option and visible control</a> · <a href="ALTUS-${label==='Administrator'?'Admin':label}-Guide.mp4" download>Download video</a></p></section>`;
 if(manifest){let body=`<h1>${label}: every recorded menu option</h1><p>Captured from the isolated local role on ${escape(manifest.created)}. Permissions can change the visible menu. Controls are listed as seen; empty fixtures are not completed real-world transactions.</p>`;
 for(const chapter of manifest.chapters){body+=`<section class="card"><h2>${escape(chapter.title)}</h2><p>${escape(chapter.text)}</p><p><code>${escape(new URL(chapter.url).pathname)}</code></p><p><strong>Page controls:</strong> ${escape(chapter.controls.join(' · ')||'See the field labels and actions shown in this video chapter and the role guide.')}</p></section>`;}fs.writeFileSync(path.join(OUT,role+'-MENU_REFERENCE.html'),page(label+' menu reference',body));}
}
const intro=`<h1>Learn to use ALTUS</h1><p>Administrator, student and instructor guides, actual narrated recordings and a complete source-based mobile option inventory. Choose a chapter to jump directly to a tool.</p><div class="grid"><section class="card"><h2>Install and connect</h2><p><a href="MOBILE_INSTALLATION.html">Mobile URL, keys, APK and connection testing</a></p><p><a href="ADMIN_INSTALL.html">Backend migrations, OCR/AI worker, backup and rollback</a></p></section><section class="card"><h2>MCP and feature reference</h2><p><a href="MCP_GATEWAY_RUNBOOK.html">Gateway / OAuth installation</a></p><p><a href="MCP_ADMIN_WORKFLOWS.html">Connect, approve, revoke and test MCP</a></p><p><a href="ADMIN_FEATURES.html">Native admin features</a> · <a href="MOBILE_OPTIONS.html">Every mobile option</a></p></section></div>`;
const script=`<script>const guides=${JSON.stringify(videoData).replace(/</g,'\\u003c')};for(const guide of guides){const holder=document.getElementById('chapters-'+guide.role);for(const chapter of guide.chapters){const button=document.createElement('button');button.textContent=Math.floor(chapter.start/60)+':'+String(Math.floor(chapter.start%60)).padStart(2,'0')+' '+chapter.title;button.onclick=()=>{const video=document.getElementById('video-'+guide.role);video.currentTime=chapter.start;video.play();};holder.append(button);}}</script>`;
const mobileFile=path.join(OUT,'mobile-chapters.json');
let mobileCard='';
if(fs.existsSync(mobileFile)){const mobile=JSON.parse(fs.readFileSync(mobileFile,'utf8'));mobileCard=`<section class="card"><h2>Mobile setup: actual app and connection check</h2><video controls preload="metadata" src="ALTUS-Mobile-Guide.mp4"><track kind="captions" label="English" srclang="en" src="mobile-chapters.vtt"></video><p><a href="ALTUS-Mobile-Guide.mp4" download>Download mobile setup video</a> · <a href="MOBILE_INSTALLATION.html">URL and key instructions</a></p><p class="muted">${mobile.chapters.length} steps · real working local configuration endpoint · no personal credentials recorded.</p></section>`;}
fs.writeFileSync(path.join(OUT,'index.html'),page('ALTUS user guides and videos',intro+mobileCard+cards+script));
console.log(`Rendered role guides, chapter player and ${inventory.length} mobile options.`);
